### ISSUE TITLE
change gui plz 

### ISSUE THREAD

**Issue by erfan132** [ravibpatel/AutoUpdater.NET#100]
change it bro 
using materialskin

**Comment by serdam55** [comment]
@erfan132 I have suggest to him in the past MaterialDesignInXaml, but I guess will be a very nice feature give to our user the possibility to customize the AutoUpdater interface easily

**Comment by ravibpatel** [comment]
@erfan132 @serdam55  You can provide your own UI using CheckForUpdateEvent. I want to change UI to WPF but it won't happen soon.

**Comment by KoruNL** [comment]
@erfan132 @serdam55 @ravibpatel In issue #89 I have asked a question about the use of MVVM in AutoUpdater.Net. Moving to MVVM would make it a lot easier to switch the UI to WPF, Xamarin or whatever may come along in the future. As stated by @ravibpatel MVVM (and WPF) would be a nice addition for version 2.0 of AutoUpdater.Net. I have offered help moving AutoUpdater.Net to MVVM.

**Comment by serdam55** [comment]
@KoruNL could I ask you some question about mvvm logic? you can shot me an email at marioserdama@gmail.com

**Comment by ravibpatel** [comment]
This can be solved by developing non UI version. See #282.
