### ISSUE TITLE
How do I update silently?

### ISSUE THREAD

**Issue by xbhuang1994** [ravibpatel/AutoUpdater.NET#101]
I do not want users to click the Update button, but when the update is detected automatically update?

**Comment by ravibpatel** [comment]
@xbhuang1994 You can use CheckForUpdateEvent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). Just remove the message box asking for permission and it will update it automatically without asking.

**Comment by EKanadily** [comment]
but in this case it will force program exit, no?

**Comment by ravibpatel** [comment]
v1.5 have this feature.
