### ISSUE TITLE
Update packages for different versions

### ISSUE THREAD

**Issue by shimon166** [ravibpatel/AutoUpdater.NET#102]
Hi, thanks for the maintenance and refactoring this package.
As i remember this package has the ability for several updates (items) in the same XML but i see now in code that it is not possible. How can i handle different update packages for same main version (like application with 32 and 64 bit)? and what about updates for differnent main versions? there is any workaround?
Thanks in advance

**Comment by ravibpatel** [comment]
@shimon166  You can check for if the process is 32 bit or 64 bit and then you can use the XML URL according to it.

**Comment by shimon166** [comment]
Thanks, what about update for different main versions? create differnt XML for each version?

**Comment by ravibpatel** [comment]
How you define different main versions?

**Comment by ravibpatel** [comment]
@shimon166 @AluminiumTech Only way to handle that right now is creating different XML files.

**Comment by shimon166** [comment]
Thanks, thats actually what i did.

**Comment by PeterRock** [comment]
> @shimon166 @AluminiumTech Only way to handle that right now is creating different XML files.

Thanks！Great idea!
