### ISSUE TITLE
Add a GUI less version for .NET Core/Framework Console Applications.

### ISSUE THREAD

**Issue by AluminiumTech** [ravibpatel/AutoUpdater.NET#103]
Hi,
I'd like to suggest the addition of a GUI less version for .NET Core/.NET Framework console apps.

The interaction/starting updating would be through a console based UI instead of through the GUI.

With the improvements it still wouldn't be compatible with .NET Core but in the future it could be if other changes were also made which I'll detail elsewhere.

**Comment by AluminiumTech** [comment]
@ravibpatel It's 2018 and frankly anybody using .NET 4.0 should be on a newer version as Microsoft has discontinued support for it. 4.5.2 or newer is supported and frankly I don't think older apps should be holding this project back. Same for .NET 2.0 .

Dropping .NET 4.0 and .NET 2.0 would be a first step in the right direction.

**Comment by ravibpatel** [comment]
@AluminiumTech I agree with you and I would love to separate GUI and back-end code but let's discuss this after I write To-do.
