### ISSUE TITLE
Migrate to .NET Standard 2.0 to allow usage in .NET Core apps

### ISSUE THREAD

**Issue by AluminiumTech** [ravibpatel/AutoUpdater.NET#104]
I'd like to suggest migrating the library to .NET Standard 2.0 .

This migration would mean that the GUI components would need to be separated from the code/programming logic so that the code could be used by .NET Core apps and the GUI library would reference the code responsible.

**Comment by ravibpatel** [comment]
@AluminiumTech Great suggestion. Let me add this to version 2.0 milestone.

**Comment by AluminiumTech** [comment]
@ravibpatel Are you ok with moving away from using the Windows Registry to a settings saving solution which is cross-platform?

Because it's a lot of effort (if even possible at all) to make .NET Standard 2.0 work with the Windows Registry.

The code just needs not to be platform specific (or we could try to do Registry stuff for Windows and other stuff for Other OSes).

**Comment by KoruNL** [comment]
@ravibpatel Migration to .NET Standard 2.0 means targeting at least .NET 4.6.1. What about your "I prefer sticking to 4.0." comment in issue #89 from just a fortnight ago?

**Comment by ravibpatel** [comment]
@KoruNL I still prefer sticking to .net 4.0 but we are just in brainstorming stage and open to ideas. Providing .NET Standard support means portability so we can create separate implementations for it.

**Comment by KoruNL** [comment]
@ravibpatel If I may put in my two cents, then I would prefer migration of AutoUpdater.NET to .NET Standard 2.0 over .net 4.0 support. Especially in the light of moving AutoUpdater.NET itself to it's next version.

**Comment by AluminiumTech** [comment]
I've started working on a new .NET Standard 2.0 Library Project inside the Solution in my fork of AutoUpdater.

I'm going to try to migrate stuff over but there are inherently some things we cannot include support for in the .NET Standard version.

For example, developers of applications would be responsible for getting user permission to start updating apps, developers would also be responsible for creating their own interface or GUI to interact with the library.

And developers would also be responsible for the code managing the remind later functionality.

**Comment by AluminiumTech** [comment]
Okay, so I'm probably going to start over my attempt at porting to .NET Standard 2.0 .

I now have a plan on how I'd like to tackle this
1. Fork ZipExtractor and migrate it to a .NET Core console app to allow being run on Windows, Mac, or Linux. On Windows it will still be an exe file and function identically to how it does now.
2. Create a new .NET Standard library in my fork of the project and call it AutoUpdater.NET.Official.Standard and try to migrate as much code as can be migrated and potentially re-write some bits.
3. I'd like to try to also migrate the Translations to a format which would be easier for .NET Standard and usage in environments without a GUI.
4. When all the core functionality from v1 works in the v2 code, I'd like to do some tests and it might be a good idea to release 1 or more previews to iron out any issues.
5. Write new documentation for v2.0 
6. Once it's stable then 2.0 can be released

@ravibpatel  Could you create a v2.0 branch? This'll allow you to continue to work on v1 whilst letting us make changes and allow you to merge pull requests for 2.0

If you have any questions then please let me know. I'll post in this issue as progress is made so please keep it open.

Thanks :)

**Comment by PoLaKoSz** [comment]
Hi @AluminiumTech !

> developers would also be responsible for creating their own interface or GUI to interact with the library

I think the .NET Standard 2.0 should at least contains a WPF UI to have an example implementation and of course don't forget about people out there who want a fast solution and don't want to mess with the UI too and satisfied with the built-in.  :smile:

*(Sorry for my bad English)*

**Comment by AluminiumTech** [comment]
> I think the .NET Standard 2.0 should at least contains a WPF UI to have an example implementation and of course don't forget about people out there who want a fast solution and don't want to mess with the UI too and satisfied with the built-in. 😄

Yeah, we can definitely have a GUI example using the .NET Standard version working with WPF and also a WinForms version. But I think also having a .NET Core console app example would also be good.

I'm starting from scratch so as soon as I have stuff I'll be sure to submit a pull request when we have a v2.0 branch.

**Comment by AluminiumTech** [comment]
By the way, @ravibpatel  Why does the ZipExtractor project contain the ZipStorer.cs file? Can't we just reference it from Nuget and make it easier to manage from there?

Can we migrate to the Nuget package?

**Comment by AluminiumTech** [comment]
@ravibpatel  As a dependency it's easier to manage imho. 

Anyhow, I started work on ZipExtractorCore and I'll provide more details when it's completed. I think it won't take too long to get done.

**Comment by AluminiumTech** [comment]
@PoLaKoSz  Here's what I've done so far on ZipExtractorCore -> https://github.com/CSMarkBenchmark/ZipExtractorCore/

If you want me to make some binaries for it and upload them on the releases page of that then I can.

**Comment by lrosemberg** [comment]
any news on the migration?

**Comment by ravibpatel** [comment]
I'm gonna start on it soon. I will start it in another branch. So everyone can contribute to it.

**Comment by gedclack** [comment]
Hi @ravibpatel , I love how easy to use AutoUpdater.NET in my existing winforms apps.
And It will be great to see it grows to support .NET core 3.1 which relates to the ability to deploy `Single exe` or `Self-contained`

**Comment by AxxiD** [comment]
Is this still being actively being worked on? What is missing? I'd really like seeing this being completed.

**Comment by ravibpatel** [comment]
.NET Core 3.1 and .NET 5.0 is supported in the latest version.

**Comment by AluminiumTech** [comment]
> 
> 
> .NET Core 3.1 and .NET 5.0 is supported in the latest version.

Only in .NET Core 3.1 and .NET 5 WPF and Winforms apps. Console .Net Core and .Net 5 apps wouldn't work with this because it's still tied to Winforms and WPF GUI which doesn't exist on macOS or Linux and will even trigger an exception if called from Windows on a Console .NET 5 app.

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find t
he file specified.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at AutoUpdaterDotNET.AutoUpdater.Start(String appCast, Assembly myAssembly)
   at EnviousSoftwareCLI.Program.Main(String[] args) in [Redacted Project Directory]\Program.cs:line 16
`
