### ISSUE TITLE
Which version is used for comparison?

### ISSUE THREAD

**Issue by jwillmer** [ravibpatel/AutoUpdater.NET#114]
Do I need to set the `AssemblyVersion` in order for the updater to compare to the latest version?

**Comment by jwillmer** [comment]
https://github.com/ravibpatel/AutoUpdater.NET/blob/aaf192ceeb639e4837d3c2dd023571ec18783065/AutoUpdater.NET/AutoUpdater.cs#L295

**Comment by jwillmer** [comment]
Maybe add this into the readme along with how to zip the update file (no sub folders)?

**Comment by ravibpatel** [comment]
@jwillmer It will extract everything into the folder where your application executable resides. So you need to zip files according to that.
