### ISSUE TITLE
Logging system update

### ISSUE THREAD

**Issue by jwillmer** [ravibpatel/AutoUpdater.NET#116]
I like to send a log message to my server when someone has updated his system. Which would be the preferred way to recognize this? Is it safe to amuse that if the `AutoUpdater.ApplicationExitEvent` is triggered that a new version is about to be installed?

Can I get current / latest version to post a message like: `user X has updated from version 1.0 to version 3.5`?

In your documentation it looks like I need to use `Application.Exit();` if I use the `AutoUpdater.ApplicationExitEvent` in order to close the app - is this the case?

**Comment by ravibpatel** [comment]
@jwillmer  Currently it doesn't pass version information in ApplicationExitEvent but it is a good idea to add it. I will implement it soon.

**Comment by jwillmer** [comment]
I looked at your code and I found that you use the registry to store the update information. To solve this issue it would be great to implement an event that triggers as soon as an update was made.

You could store the information of starting an update in the registry and look on each start if on the last exit a update was processed. You could also add a update result flag like `sucessfull`, `error while downloading zip`, `etc`

**Comment by jwillmer** [comment]
Something like this function - returns `true` on first installation as well as on updated versions

```
private bool IsNewAppVersion()
{
    bool isNewAppVersion = false;
    var registryLocation = $@"Software\...\Version";
    var currentVersion = Assembly.GetExecutingAssembly().GetName().Version;
    using (RegistryKey updateKey = Registry.CurrentUser.OpenSubKey(registryLocation))
    {
        if (updateKey != null)
        {
            var applicationVersion = new Version(updateKey.GetValue("version") as string);
            if (applicationVersion < currentVersion)
            {
                updateKey.SetValue("version", currentVersion.ToString());
                isNewAppVersion = true;
            }
        }
        else
        {
            using (RegistryKey updateKeyWrite = Registry.CurrentUser.CreateSubKey(registryLocation))
            {
                updateKeyWrite.SetValue("version", currentVersion.ToString());
                isNewAppVersion = true;
            }
        }
    }

    return isNewAppVersion;
}
```

**Comment by ravibpatel** [comment]
@jwillmer  This is more custom functionality and not everyone would be interested in it so I think it is better to leave this up to the user.
