### ISSUE TITLE
Application exit event behaviour

### ISSUE THREAD

**Issue by jwillmer** [ravibpatel/AutoUpdater.NET#117]
https://github.com/ravibpatel/AutoUpdater.NET/blob/aaf192ceeb639e4837d3c2dd023571ec18783065/AutoUpdater.NET/AutoUpdater.cs#L502

I think it is unusual that using the `AutoUpdater.ApplicationExitEvent` prevents the application from exit. WPF has a similar event that you can use to get notified about the exit of the application but it does not prevent closing the app - you can however prevent the closing inside the event.

**Comment by ravibpatel** [comment]
@jwillmer I provided this event in case if someone has problems with exiting application they can do it them self-using this event. This way users can exit the application by themselves.
