### ISSUE TITLE
Start arguments

### ISSUE THREAD

**Issue by liver** [ravibpatel/AutoUpdater.NET#12]
Add to the method DownloadUpdate(string[] args) to start updated application with arguments.

**Comment by ravibpatel** [comment]
I am thinking of adding an XML tag for arguments that will be used with the installer.

**Comment by tip2tail** [comment]
Hi

I have submitted PR #60  for this.

Thanks,
Mark

**Comment by tip2tail** [comment]
Hi,

Thanks for merging #60. When do you plan to do a new release via nuget?

Mark

**Comment by ravibpatel** [comment]
@tip2tail Not soon I will refine this feature before Nuget release.

**Comment by ravibpatel** [comment]
Released new version 1.4.5 with this feature.

**Comment by AAN3AC** [comment]
It sounds like specifying command line arguments for the installer EXE was implemented in 2017, but I can not find how to do it?

How can this be done?

**Comment by ravibpatel** [comment]
@AAN3AC You can specify command line arguments in the XML file. Use args tag.
