### ISSUE TITLE
Open the zip file but don't extract the files

### ISSUE THREAD

**Issue by HelderPinto79** [ravibpatel/AutoUpdater.NET#120]
Hello,
I added the project AutoUpdater.NET to my soluction, and used the line autoupdater.Start(...) to update my application... the update starts, find that there is a new version, closes my application, download the zip file (my zip file contains only my updated dlls) and then it opens the zip file and show the dlls BUT it doesn't extract them to my application folder... just finish like that, with no errors... but don't extract the files...
am i missing something?!
can someone help me please?

**Comment by ravibpatel** [comment]
@HelderPinto79  This should not be happening which version of AutoUpdater.NET are you using?

**Comment by HaTram** [comment]
Me to. Latest Version: 1.4.7

**Comment by HelderPinto79** [comment]
I'm using the latest version... 1.4.7

**Comment by ravibpatel** [comment]
@HelderPinto79 @HaTram Can you give me your XML file url? I think it is a issue with file name. It can’t get correct extension from download url. If you can’t give it here you can also send it on [https://rbsoft.uservoice.com](https://rbsoft.uservoice.com).

**Comment by HaTram** [comment]
![image](https://user-images.githubusercontent.com/37732915/37885937-2c7678ba-30e2-11e8-8875-075b8bde6953.png)

**Comment by ravibpatel** [comment]
@HaTram  I can't debug using the image. Please provide real download URL. If you don't want to post it here and you can provide it [here](https://rbsoft.uservoice.com/).

**Comment by HelderPinto79** [comment]
Sure... you can use my xml file here : 
http://www.dojocampos.com/app_update/versao.xml

`<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>1.0.1.0</version>
    <url>http://www.dojocampos.com/app_update/update.zip</url>
    <changelog>http://www.dojocampos.com/app_update/changelog.html</changelog>
    <mandatory>true</mandatory>
</item>`

**Comment by HelderPinto79** [comment]
Now i see i was using an older version from Codeplex...
Download now the solution from Github...
But i can't compile the solution... i've got these errors : 

`Metadata file 'C:\Outros\AutoUpdater.NET-master\AutoUpdater.NET\bin\Debug\net20\AutoUpdater.NET.dll' could not be found	AutoUpdaterTest
	
Metadata file 'C:\Outros\AutoUpdater.NET-master\AutoUpdater.NET\bin\Debug\net20\AutoUpdater.NET.dll' could not be found	AutoUpdaterTestWPF	

Error signing output with public key from file 'ZipExtractor.snk' -- Invalid public key.	ZipExtractor	

Error signing output with public key from file 'AutoUpdater.NET.snk' -- Invalid public key.	AutoUpdater.NET	`

**Comment by ravibpatel** [comment]
Uncheck "Sign the assembly" from signing tab in project's properties for both ZipExtractor and AutoUpdater.NET project.

**Comment by ravibpatel** [comment]
@HelderPinto79  I tested it with your XML and it worked fine.

**Comment by HelderPinto79** [comment]
@ravibpatel It's working fine now... many thanks... sorry, i'm a little nooby...

**Comment by HelderPinto79** [comment]
Issue closed. Thanks for the help.

**Comment by ravibpatel** [comment]
@HelderPinto79 You are welcome.
