### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by Jafesu** [ravibpatel/AutoUpdater.NET#121]
Can you Expose Current Version?

**Comment by ravibpatel** [comment]
@Jafesu Why you need it to be public? You can get current version easily from your application like [this](https://stackoverflow.com/questions/36351866/how-to-get-application-version). Also, it will be not be assigned any value until Start method runs.

**Comment by Jafesu** [comment]
@ravibpatel my end goal, is when my application first starts it run the check, if the user chooses to skip I have a label that flashes reminding of an update, I want to be able to compare my application version with what autoupdater gets from the xml, I just don't want to have to setup full xnl parsing since auto updater already does that

**Comment by ravibpatel** [comment]
@Jafesu You can handle CheckForUpdateEvent and get all info you need. You can do it as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).
