### ISSUE TITLE
Download From FTP

### ISSUE THREAD

**Issue by stardance** [ravibpatel/AutoUpdater.NET#124]
It seems the xml file and the update file are download from public network.
Can there be a way of downoad file  from FTP?

**Comment by ravibpatel** [comment]
@stardance You can handle [CheckForUpdateEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) and download the update using following code.

[https://stackoverflow.com/questions/12519290/downloading-files-using-ftpwebrequest](https://stackoverflow.com/questions/12519290/downloading-files-using-ftpwebrequest)

**Comment by stardance** [comment]
@ravibpatel Roger that : )Thanks for you reply!
