### ISSUE TITLE
Can i wait for the application to check the version ?

### ISSUE THREAD

**Issue by SoulsReborn** [ravibpatel/AutoUpdater.NET#125]
For example an if statement, if there is no new version then just open the application.
else If there is a new version, then stop opening the application and stay on the window i desire it to stay.

i added the code and everything works fine . but the application fully starts up and then it opens the window of  'hey there's a new update' if there is an update i want to tell the application to not load the next window.

**Comment by SoulsReborn** [comment]
Nevermind found the answer .. just had to use the custom AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args) event

**Comment by AresEkb** [comment]
How did you implemented it? I use a custom CheckForUpdateEvent handler. But the application starts anyway in background.

**Comment by DjordjeMandic** [comment]
@AresEkb Make a variable bool pauseStartup = true and then if there is no new update just set it to false. And add while(pauseStartup) Thread.sleep(100); before application.run. (Im not sure if this will work.)

**Comment by AresEkb** [comment]
I've got it. One should remove application startup logic from `Main()` method. This method must invoke only updater. And CheckForUpdateEvent handler must explicitly run main application logic.

**Comment by DjordjeMandic** [comment]
@AresEkb its not good idea to run main application method inside event. what if multiple events occur?

**Comment by ravibpatel** [comment]
@AresEkb Network request can take unknown amount of time so application can take longer to startup if I provide non-async version of Start method. That's why I decided against it.

**Comment by AresEkb** [comment]
Thank you for answers! It seems I have a very specific update scenario. I develop a corporate application, which must be auto updated at startup. This update must be forced. There should not be any confirmation dialogs. So, it's easer to implement it from scratch.
