### ISSUE TITLE
Require forced update

### ISSUE THREAD

**Issue by glorytak** [ravibpatel/AutoUpdater.NET#127]
Require forced update option, please

**Comment by bakx** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>0.0.5.0</version>
    <url>some url</url>
    <changelog>some log location</changelog>
    <mandatory>false</mandatory>
</item>

Doesn't it already have that? With the mandatory flag?

**Comment by fritz-net** [comment]
just add an callback to `AutoUpdater.CheckForUpdateEvent`

there you check if there is a new update `args.IsUpdateAvailable`

if there is a new update call `AutoUpdater.DownloadUpdate()`

if this returns `true` kill your app

all silent
