### ISSUE TITLE
Add AutoCheck for Update based on Time interval

### ISSUE THREAD

**Issue by delfuria** [ravibpatel/AutoUpdater.NET#13]
Hi,
i think that could be great to implement a way for check for the updates every (n) seconds(or minutes) and not only when the app start.

**Comment by ravibpatel** [comment]
Nice idea. Looking forward to implementing it in the future.

**Comment by stebla27** [comment]
Would be a very helpful feature.

**Comment by ravibpatel** [comment]
You can do this as shown in following.

[https://github.com/ravibpatel/AutoUpdater.NET#check-updates-frequently](https://github.com/ravibpatel/AutoUpdater.NET#check-updates-frequently)
