### ISSUE TITLE
How to disable change log page's js script error?

### ISSUE THREAD

**Issue by xucongli1989** [ravibpatel/AutoUpdater.NET#131]
When I run updater window,and the change log window is show.But have some js error.So I want to disabled that errors to show users. 
Set the change log window's browser control like this : new WebBrowser().ScriptErrorsSuppressed = true;

![20180423111500](https://user-images.githubusercontent.com/9961428/39105417-5420327c-46e8-11e8-95f1-f43153ceb1e6.jpg)

Thanks a lot.

**Comment by ravibpatel** [comment]
@xucongli1989 Which windows version are you using?

**Comment by xucongli1989** [comment]
If use WebBrowser contorl in winform ,the IE version is 'IE7' whatever installed other version.So you can stop  the browser error via 'ScriptErrorsSuppressed'. You can try it.

**Comment by ravibpatel** [comment]
@xucongli1989 I will add that change.

**Comment by xucongli1989** [comment]
OK，thx a lot.
