### ISSUE TITLE
Can you make these languages folders tidy?

### ISSUE THREAD

**Issue by xucongli1989** [ravibpatel/AutoUpdater.NET#132]
Can I set the language by myself,and remove the needless folders automatically when after build?
![20180423134958](https://user-images.githubusercontent.com/9961428/39109020-a311bfda-46fd-11e8-9d9e-101d5f664973.jpg)

**Comment by ravibpatel** [comment]
@xucongli1989 If you use .NET 4.0 or above they are tidy.

**Comment by xucongli1989** [comment]
Are you sure that are not empty folder?I hope just only one if I assign language.

**Comment by ravibpatel** [comment]
@xucongli1989 There are no folders if you use .NET 4.0 or above. Resource assemblies are embedded.

**Comment by xucongli1989** [comment]
OK,thx a lot.
