### ISSUE TITLE
not able to install MSI

### ISSUE THREAD

**Issue by soeyen** [ravibpatel/AutoUpdater.NET#137]
When I specify an MSI in the XML config file, the updater throws an exception:

"no application is associated with the specified file for this operation"

Is see the code is using "UseShellExecute = true", so it should work.

Then I tried changing the code in \AutoUpdater.NET\DownloadUpdateDialog.cs like this:

`if (extension.ToLower().EndsWith(".msi")) {
	processStartInfo = new ProcessStartInfo
	{
		FileName = "msiexec",		
		Arguments = "/i " + tempPath
	};
}`
This runs the MSI succesfully, but the app itself isn't started afterwards.
Can this be caused by the MSI file? (I tried multiple)

**Comment by ravibpatel** [comment]
@soeyen If MSI started successfully after your changes then you need to handle launching of the application from MSI. AutoUpdater.NET closes after it launches an installer so it can't control it.

**Comment by soeyen** [comment]
Hi @ravibpatel ,
that makes sense.
How about the msi installation? I'm I doing something wrong that the direct execution, using shellExecute, does not work for me?

**Comment by ravibpatel** [comment]
@soeyen I will test it with other .msi files and see if they behave same.

**Comment by ghost1face** [comment]
I've just run into the same problem with my .msi file and resolved the issue the same way.  I agree the application can be restarted through the installer.  

I can submit a pull request if this makes things easier.
