### ISSUE TITLE
Needs Info

### ISSUE THREAD

**Issue by sajjadjaved01** [ravibpatel/AutoUpdater.NET#139]
![image](https://user-images.githubusercontent.com/10374846/39352607-b632367a-4a1e-11e8-9322-5a08328f2a7a.png)

**Comment by ravibpatel** [comment]
@sajjadjaved01  Can you share me your XML file URL?

**Comment by sajjadjaved01** [comment]
http://sajjadjaved.ml/update.xml

**Comment by ravibpatel** [comment]
@sajjadjaved01 You are using .7z file as download URL. Please use .zip files. 7z files are not supported.

**Comment by sajjadjaved01** [comment]
Okay

**Comment by sajjadjaved01** [comment]
Okay ✔
