### ISSUE TITLE
The Chinese file name is downloaded after downloading the random code

### ISSUE THREAD

**Issue by gaoconggit** [ravibpatel/AutoUpdater.NET#140]
![image](https://user-images.githubusercontent.com/10905068/39509138-b40f2b30-4e17-11e8-9777-29220ab15227.png)

**Comment by ravibpatel** [comment]
@gaoconggit after downloading the random code what you mean by that. Can you elaborate?

**Comment by gaoconggit** [comment]
My zip compression package contains files of Chinese file names.

**Comment by gaoconggit** [comment]
After the update is completed, a wrong file name is out

**Comment by ravibpatel** [comment]
Can you provide me url of XML file you are using?

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/39516561-dba7c432-4e2f-11e8-9a5f-252ea4435e58.png)

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/39516610-fdd8d71c-4e2f-11e8-8d41-42c84f5977fb.png)

**Comment by gaoconggit** [comment]
Like this can solve the Chinese file name disorderly

**Comment by gaoconggit** [comment]
this is my xml file
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>5.0</version>
    <url>http://haoidea.wang/test.zip</url>
    <mandatory>false</mandatory>
</item>

**Comment by gaoconggit** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>5.0</version>
    <url>http://haoidea.wang/test.zip</url>
    <mandatory>false</mandatory>
</item>

**Comment by gaoconggit** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>5.0</version>
    <url>http://haoidea.wang/test.zip</url>
    <mandatory>false</mandatory>
</item>

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/39560182-798a4654-4ece-11e8-9bf6-c1d9f5940e75.png)

**Comment by gaoconggit** [comment]
http://haoidea.wang/test.zip

**Comment by ravibpatel** [comment]
@gaoconggit Tried setting different encodings but no luck. 7zip shows names correctly. I will keep digging into it.

**Comment by nolongerhesitate** [comment]
Excuse me, but the problem is not solved.

**Comment by nolongerhesitate** [comment]
> http://haoidea.wang/test.zip

我使用好压打包，解决了这个问题

**Comment by gaoconggit** [comment]
@nolongerhesitate 
估计好压压缩的编码，正好兼容 437这个编码

**Comment by zzl4883a** [comment]
> > http://haoidea.wang/test.zip
> 
> 我使用好压打包，解决了这个问题

看到了你的回答，解决了我的问题，谢谢~

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1. It may fix your issue if you are using .net 4.5 or above.
