### ISSUE TITLE
on windows xp,Decompression error

### ISSUE THREAD

**Issue by gaoconggit** [ravibpatel/AutoUpdater.NET#143]
![image](https://user-images.githubusercontent.com/10905068/39619725-6a6f5b58-4fbb-11e8-8fa9-2040e4042177.png)

**Comment by gaoconggit** [comment]
![image](https://user-images.githubusercontent.com/10905068/39619790-93966bc0-4fbb-11e8-9e4c-20cd4a66a68c.png)

**Comment by ravibpatel** [comment]
@gaoconggit Also I don't have XP PC to reproduce this issue.

**Comment by stardance** [comment]
.NET 2.0 is Required!
