### ISSUE TITLE
Multiple items to check in one xml file

### ISSUE THREAD

**Issue by sekulicb** [ravibpatel/AutoUpdater.NET#144]
Hi. Thanks for this amazing library. I have a case where my app is hosting a number of dlls, where each dll is behaving like add-in (extending host app). What I mean by that is that every dlls has its own UI, viewModel and set of dependencies. It would be pretty cool for me if I could just check in bulk each version of installed apps, and only update those that have new version available or leave it up to the user to choose. I wanted to write xml file as: 

<item>
     app 1
</item>
<item>
     app 2
</item>
.
.
.    app 10

I know that you cannot have multiple item tags but is there any workaround ?

Thanks,

Bane

**Comment by ravibpatel** [comment]
@sekulicb The best approach for this currently is using multiple XML files.

**Comment by sekulicb** [comment]
Thanks for quick response. One more question. How can I change InstalledVersion property before actual comparison of versions ? I need assembly version of add-in, not version of mainAssembly ? 

All the best,
Bane

**Comment by ravibpatel** [comment]
@sekulicb You can provide your assembly in Start method. This way your assembly will be used for app title and version information.

**Comment by sekulicb** [comment]
Great. Thanks!
