### ISSUE TITLE
throwing error when updating using msi file

### ISSUE THREAD

**Issue by hashirsoft** [ravibpatel/AutoUpdater.NET#147]
I am trying to update using msi file. but it is thrwoing the following exception

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at AutoUpdaterDotNET.DownloadUpdateDialog.WebClientOnDownloadFileCompleted(Object sender, AsyncCompletedEventArgs asyncCompletedEventArgs)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.DownloadFileOperationCompleted(Object arg)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SetupDemo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/NTG/Setup1/SetupDemo.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.4.9.0
    Win32 Version: 1.4.9.0
    CodeBase: file:///C:/Program%20Files%20(x86)/NTG/Setup1/AutoUpdater.NET.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ravibpatel** [comment]
@hashirsoft Please try following the latest version of the library from [here](https://ci.appveyor.com/api/buildjobs/o83yrb3i6u0hwewm/artifacts/AutoUpdater.NET-1.4.9.zip).

**Comment by hashirsoft** [comment]
@ravibpatel dear can you please help me in this regard?

**Comment by ravibpatel** [comment]
@hashirsoft Does MSI installer work when executed normally?

**Comment by hashirsoft** [comment]
yes, when I am double clicking on downloaded msi then it is working fine

**Comment by hashirsoft** [comment]
only issue from application. also issue is coming mostly when updating from application and when debugging then it is working fine.

**Comment by ravibpatel** [comment]
@hashirsoft Please try the latest version of the application from [here](https://ci.appveyor.com/api/buildjobs/secddu10txkh8746/artifacts/AutoUpdater.NET-1.4.9.zip). It should fix the problem you are having.

**Comment by ravibpatel** [comment]
@hashirsoft If you are using installer then you should handle that logic in an installer. The zip file is for simple updates and installer is for advance updates.

**Comment by hashirsoft** [comment]
@ravibpatel but the issue is when is set this <mandatory>true</mandatory> then it just hide skip and cancel button. I believe it should also hide cross button on top right of popup. becasue in current implementation user can still skip update even the mandatory flag is on.

**Comment by ravibpatel** [comment]
@hashirsoft User will get prompt every time they open the application if you are using it in Form constructor or load event when the mandatory flag is set. I didn't want to force users to update so I kept it that way. Many users don't like being forced to update.

**Comment by hashirsoft** [comment]
ok right, actually in my opinion it will be good addition like we have financial application and we have a requirement if we have critical update related to finance then user must update before moving forward. I can fix this by changing code at my end but in this way I will not be able to get future updates on this. Can you please add new flag to handle this scenario so that if someone want to use this feature then he/she can turn on that flag.

Best Regards

**Comment by ravibpatel** [comment]
@hashirsoft Can you please raise another issue for this?

**Comment by hashirsoft** [comment]
@ravibpatel yes sure
