### ISSUE TITLE
user must update application before moving forward

### ISSUE THREAD

**Issue by hashirsoft** [ravibpatel/AutoUpdater.NET#148]
Hello Ravi,

Currently user can skip update by clicking top right x button even mandatory flag is on. We have a requirement in some scenarios user must update before moving forward. Can you please hide top right x button when mandatory flag is on or you can add another property like critical and when this critical property is on then user cannot move forward without updating application.

Best Regards,
Mansoor

**Comment by AluminiumTech** [comment]
@ravibpatel  might be worth changing the milestone to v2.0
