### ISSUE TITLE
Force an update?

### ISSUE THREAD

**Issue by anthonyjr2** [ravibpatel/AutoUpdater.NET#15]
Is there a way to force updates on the application? As in, remove the remind me later button and make it so they cannot use the program unless they update. At this point if I happen to accidentally click remind me later or skip there is no way to get the update until I send a newer version out.

**Comment by ravibpatel** [comment]
You can handle the update logic yourself and if there is update it will download it automatically. You can do it by using following code.

```csharp
private void FormMain_Load(object sender, EventArgs e)
{
    //First you need to subscribe to CheckForUpdateEvent before calling Start method of AutoUpdater.
    AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;

    AutoUpdater.Start("Put your XML file URL here.");
}

private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
{
    if (args != null)
    {
        if (args.IsUpdateAvailable)
        {
                try
                {
                    //You can use Download Update dialog used by AutoUpdater.NET to download the update.

                    AutoUpdater.DownloadUpdate();
                }
                catch (Exception exception)
                {
                    MessageBox.Show(exception.Message, exception.GetType().ToString(), MessageBoxButtons.OK,
                        MessageBoxIcon.Error);
                }
        }
        else
        {
            MessageBox.Show(@"There is no update available please try again later.", @"No update available",
                MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
    }
    else
    {
        MessageBox.Show(
                @"There is a problem reaching update server please check your internet connection and try again later.",
                @"Update check failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
}
```

**Comment by anthonyjr2** [comment]
Ah, I saw that code on the main page but I ran into a small problem with it. Using that as-is makes a "No update available" box pop up every time I start the program. I only want that to pop up when I click the "Check for updates" button. I'm sure I can figure out a workaround.

But is there any way to also add a feature to AutoUpdater that just lets you disable the remind button? Just like the skip button can be disabled.

**Comment by anthonyjr2** [comment]
I just threw a bool check for first run in there and it works fine. But I would still like to request a disable option like the skip button.

**Comment by ravibpatel** [comment]
If you don't want to check for update on startup of an application then just move following line into Button click event. I will provide an option to disable remind later button soon.

`AutoUpdater.Start("Put your XML file URL here.");`

**Comment by anthonyjr2** [comment]
I see the commit for the remind later button, thanks!
