### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by batarian71** [ravibpatel/AutoUpdater.NET#150]
Hi,

I want to make a contribution. Do you want me to design a logo for this repo?

**Comment by ravibpatel** [comment]
@batarian71 Can you show me example logo?

**Comment by batarian71** [comment]
![1](https://user-images.githubusercontent.com/36008612/40886583-5dd31d0e-6743-11e8-8484-d0af1a1a9da9.jpg)

also if there is anything you want please say me.

**Comment by ravibpatel** [comment]
@batarian71 Great. Can you make it small? Just strip above part consisting of 5 logos and change "Auto updater" to "AutoUpdater.NET" and it will look great.

**Comment by batarian71** [comment]
I edited the logo. How is it? I will send a pr soon.

![autoupdater](https://user-images.githubusercontent.com/36008612/41061247-abb398f2-69da-11e8-8daf-4573dbd8c07e.jpg)
