### ISSUE TITLE
GitHub Download SSL/TLS Error 

### ISSUE THREAD

**Issue by irs-sesc1** [ravibpatel/AutoUpdater.NET#153]
Starting a few weeks ago I received the following error when downloading an update file from a public GitHub release.
```
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
```
Therefore I switched to S3 storage and it worked fine again. 

I was using version 1.4.7. Now I updated to version 1.4.10 but the problem still exists.

**Comment by ravibpatel** [comment]
@irs-sesc1 You can try fix suggested in issue #25.
