### ISSUE TITLE
Dont Work AutoUpdater.NET

### ISSUE THREAD

**Issue by seguis** [ravibpatel/AutoUpdater.NET#155]
Good day
It does not work for me in any way to update, for more than I try, it does not show a message of any kind, this is my code, I do not know what I'm doing wrong.
Try allowing everything in the Load event of the form and even then it does not show anything, it does not show a message of any kind, it's as if AutoUpdater.NET was not installed
![updater](https://user-images.githubusercontent.com/33499071/41440174-99001542-6ffb-11e8-8594-429ce1f4334c.jpg)

**Comment by seguis** [comment]
If friend, but still does not show any message, I think that it should show that the application is already updated, but it does not show that kind of message either

**Comment by ravibpatel** [comment]
@seguis Can you give me URL of your XML file?

**Comment by seguis** [comment]
yes -> https://travianbotff.com.ve/actualizacion.xml

**Comment by seguis** [comment]
Friend I think it is problems with the server where I had the XML file, at this time my website is down due to problems with web hosting, so while the hosting is repaired, I decided to try LOCALHOST, the XML file on localhost, that is -> http://127.0.0.1/actualization.xml

And it worked 100%, now I have 2 possible problems "The antivirus blocked my connection to the web server OR the VB NET program was connected and could read the XML file, but even so it did not show any alert for any problem of the server where I had hosted the XML file "

**Comment by ravibpatel** [comment]
@seguis If you use the following line before calling Start method then it will show you an error.

````vb
AutoUpdater.ReportErrors = True
````
