### ISSUE TITLE
Extractor fail to extract/replace all or some file

### ISSUE THREAD

**Issue by tasossavva** [ravibpatel/AutoUpdater.NET#158]
I face an issue lately (I believe this is happening after the latest Windows update), where in some cases the extractor fails to extract/replace some or all of the files.

```
private void SoftwareUpdate()
{
        AutoUpdater.AppTitle = "PayrollPlus";
        AutoUpdater.LetUserSelectRemindLater = false;
        AutoUpdater.RunUpdateAsAdmin = true;
        AutoUpdater.ShowSkipButton = true;
        AutoUpdater.Start(@"https://www.codeworks.com.cy/cw!Downloads/PayrollPlus/ver-10.1/updater/updater.xml");
}
```

This happens both with version 1.4.10 & 1.4.9.

```
<item>
       <version>10.1.28.0</version>
       <url>https://www.codeworks.com.cy/cw!Downloads/PayrollPlus/ver-10.1/updater/updater.zip</url>
       <changelog>https://www.codeworks.com.cy/cw!Downloads/PayrollPlus/ver-10.1/updater/index.html</changelog>
       <mandatory>true</mandatory>
</item>

```

I do not know why this is happening. The extract path is 
_C:\Program Files (x86)\Codeworks Ltd\PayrollPlus_

**Comment by tasossavva** [comment]
Working link below
`https://www.codeworks.com.cy/cw!Downloads/PayrollPlus/ver-2.13/updater/updater.xml`

I am using WinRAR 5.50 (64-bit) for creating the zip file.

**Comment by tasossavva** [comment]
I am running the same version too. Unfortunately this is happening on some computers and I could not specify when. Could you also try for the link below? The difference is that the file size is bigger and in that case the problem was raising more often.

`https://www.codeworks.com.cy/cw!Downloads/PayrollPlus/ver-2.11/updater/updater.xml`

I do not know if it has to do with the time the software is re-executed. Maybe the program is called before the extraction is completed!!!

Actually I have no idea what causes it. I am just trying to feature it out.

**Comment by ravibpatel** [comment]
@tasossavva This link worked perfectly for me too. You can try handling application exit logic manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually). It may happen if your application isn't exiting properly. You can also try running your application as admin if it works that way then it is certain that you have file permissions problem.

**Comment by tasossavva** [comment]
Ok, I think I found the issue. The application was calling a method after the update and probably this was taking longer to close the app. So this might have been the issue, I will test it and revise here.

**Comment by tasossavva** [comment]
I believe that the issue raises because I call **AutoUpdater **in** SoftwareUpdate()** called by the **Form_Load** method. As result, the source code entire code in **Form_Load** is executed, even that after  **AutoUpdater**.

I believe that this could be solved if there was a property letting know if **AutoUpdater** execution finished, or if there was a delay (in milliseconds i.e.) for executing **AutoUpdater extraction**.

**Comment by ravibpatel** [comment]
@tasossavva [ApplicationExitEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually) exist for same reason. It will run when AutoUpdater finishes the execution and needs to close the application to start the extraction.

**Comment by chpiter** [comment]
@tasossavva I get the same issue ,how can i fix it ,thanks

**Comment by tasossavva** [comment]
@chpiter I believe that the issue raises because some other functions are still running and the software has not closed before the extractions has started.

To solve that you either have to make sure that nothing else will run after the update process, or follow what @ravibpatel suggested, using [ApplicationExitEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually).

**Comment by tasossavva** [comment]
@ravibpatel thank you. I will give it a try.

**Comment by ravibpatel** [comment]
@tasossavva Updated NuGet package with the fix.

**Comment by AluminiumTech** [comment]
I'm still having this issue with AutoUpdater.NET 1.4.11

**Comment by mfansari82** [comment]
> @tasossavva It works fine for me. I think it may be a file permissions issue. Make sure your files aren't read-only. I have Windows 10 April 2018.

how to gave full control permission

**Comment by tasossavva** [comment]
@mfansari82 Could you clarify please? I do not understand the question.
