### ISSUE TITLE
System.Net.WebException

### ISSUE THREAD

**Issue by xdKagami** [ravibpatel/AutoUpdater.NET#159]
When I click update I get an error:
An exception occured during a WebClient Request
https://i.imgur.com/pRGeuMH.png

**Comment by ravibpatel** [comment]
@xdKagami Can you give me URL of your XML file?

**Comment by ravibpatel** [comment]
@kiran1384 Can you give me URL of update file?

**Comment by kiran1384** [comment]
here is the link Ravi
http://************/AutoUpdater/Installation/HIRF_Setup.msi

**Comment by ravibpatel** [comment]
@kiran1384 Can you provide me accessible link? I can't find out what is wrong with dummy link. If you can't provide it here, you can provide it on https://rbsoft.uservoice.com

**Comment by kiran1384** [comment]
Ravi, it's an intranet link and not accessible outside the company network.
When clicked on the link, the .msi file download will prompt to save or run
the file.

Kiran N
Bangalore.

**Comment by ravibpatel** [comment]
@kiran1384 In that case you can try debugging the AutoUpdater.NET project by adding it to your solution.

**Comment by kiran1384** [comment]
Thanks @ravibpatel,  will try to figure out by adding the project to my soulution.
