### ISSUE TITLE
Feature request: Make ShowUpdateForm() public

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/AutoUpdater.NET#161]
I did make workaround with AutoUpdaterOnCheckForUpdateEvent but now i dont get changelog window. I just want my app to check for updates on startup and if there are none dont inform user. 

Maybe change this:

```
if (ReportErrors)
{
    MessageBox.Show(Resources.UpdateUnavailableMessage, Resources.UpdateUnavailableCaption,
                                        MessageBoxButtons.OK, MessageBoxIcon.Information);
}
```

To this:

```
if (ReportErrors && ShowNoUpdateMessageBox)
{
    MessageBox.Show(Resources.UpdateUnavailableMessage, Resources.UpdateUnavailableCaption,
                                        MessageBoxButtons.OK, MessageBoxIcon.Information);
}
```

**Comment by DjordjeMandic** [comment]
@ravibpatel Then how i can show show update form? I can do DownloadUpdate but i cant use ShowUpdateForm beacuse its private.

**Comment by ravibpatel** [comment]
@DjordjeMandic There is no need to use event if you want to show update form. Can you tell me the reason for using this event?

**Comment by DjordjeMandic** [comment]
I want to have multiple updater xml files and if one does not have update then i want to check another and only way is to do it via event. As far as I know. Also i want to implement logger via event.
