### ISSUE TITLE
Update changed files only

### ISSUE THREAD

**Issue by MarianoTerzolo** [ravibpatel/AutoUpdater.NET#162]
I'm a newbie with autoupdater and I find the program very useful!
I need to know how to avoid replacing the .config file and, if possible, update only the changed files.

Thanks a lot!

**Comment by chpiter** [comment]
+1

**Comment by ravibpatel** [comment]
@chpiter @MarianoTerzolo You need to zip the updated files with the same directory structure as your application directory structure. That way only updated files will be replaced. After that, you need to upload that zip on your server and provide the URL between url tag as shown [here]https://github.com/ravibpatel/AutoUpdater.NET#xml-file).
