### ISSUE TITLE
System.IO.IOException - Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by AluminiumTech** [ravibpatel/AutoUpdater.NET#164]
So, I set up AutoUpdater.NET in one of my WPF apps using the examples shown and I just tried updating an older version on a production PC.

It gave me an error showing this: 

![image](https://user-images.githubusercontent.com/14107316/42451703-f0fe2a94-837f-11e8-9a09-e3ce3643f428.png)

I'm not sure what's wrong. I followed the example and the app doesn't close when the update is getting installed.

**Comment by AluminiumTech** [comment]
So, I think I've fixed that issue.  But after the update is downloaded, it's not installed properly and doesn't overwrite the existing app version.

**Comment by AluminiumTech** [comment]
@ravibpatel  Is it normal for the updater to create a new folder with the update and not overwrite the existing app files?

**Comment by ravibpatel** [comment]
@AluminiumTech This is not normal behavior. I will investigate it further and let you know what causes it.

**Comment by AluminiumTech** [comment]
Any luck with finding what was causing it?

**Comment by ravibpatel** [comment]
@ravibpatel Sorry, I am busy with another project. As soon as I get some free time from it I will look into this.

**Comment by PoPoWanObi** [comment]
Also have this issue ~

**Comment by hepter** [comment]
> Also have this issue ~

+1

**Comment by ravibpatel** [comment]
@hepter Does it crashed every time or sometimes?

**Comment by hepter** [comment]
Yes I have tried differents ways  but I got the same error every time

**Comment by kerajel** [comment]
+1 have the same error

**Comment by ravibpatel** [comment]
If someone can reference the project and provide me a stack trace I can pinpoint the problem. I can't reproduce this issue on my PC so it is hard to pinpoint the cause of this issue.

**Comment by kerajel** [comment]
After switching from Microsoft Visual Studio Installer Projects to Advanced Installer the problem has gone.

**Comment by wvdvegt** [comment]
It was fixed (for me) the moment i referenced the ZipExtractor project in my main application.

**Comment by ravibpatel** [comment]
@wvdvegt Can you tell me which line was giving that error?

**Comment by wvdvegt** [comment]
I'll try but i will be early next week before i have time. I will integrate your updater into another application.
