### ISSUE TITLE
Can not make ZipExtractor.exe

### ISSUE THREAD

**Issue by jinsla** [ravibpatel/AutoUpdater.NET#166]
Unhandleed exception has occurred
Access to the path "d://ZipExtractor.exe"is denied.
Because security tool, i want dont make ZipExtractor.exe and always ready that exe file on there.
By setting AutoUpdater.DownloadPath.

But i cant make new AutoUpdater.NET.dll file
(DownloadUpdateDialog.cs
//File.WriteAllBytes(installerPath.Resources.ZipExtractor)
)

Can you make new AutoUpdater.NET.dll file for me?

**Comment by DjordjeMandic** [comment]
If you comment `File.WriteAllBytes(installerPath.Resources.ZipExtractor)` out that then you must add file missing check beacuse if zipextractor is missing updater will likely crash.

**Comment by ravibpatel** [comment]
@jinsla if you want to rebuild project locally then you must go into project properties and disable signing.

**Comment by jinsla** [comment]
@ravibpatel Thank you for help~!

**Comment by SuryaWalker** [comment]
> @jinsla if you want to rebuild project locally then you must go into project properties and disable signing

In my opinion that info  should be included  in the readme on the start page of the autoupdater.net, since usually you would expect a solution to compile after downloading it from working github repo...

**Comment by ravibpatel** [comment]
@SuryaWalker It is included in the README.md [here](https://github.com/ravibpatel/AutoUpdater.NET#steps-to-build-it-for-further-development).

**Comment by SuryaWalker** [comment]
> @SuryaWalker It is included in the README.md [here](https://github.com/ravibpatel/AutoUpdater.NET#steps-to-build-it-for-further-development).

Thanks for the link and very quick reply! Now I got it compiled, nevertheless, it took me almost 1 hour. Since the test projects are already set to net462, so why not setting it as default target for all other projects as well, just to make a fully working solution locally without any adjustments required?

**Comment by ravibpatel** [comment]
@SuryaWalker It is used for deployment. It automatically builds NuGet package for all versions. If I target a single framework, then it won't work.
