### ISSUE TITLE
Update installation, reboot, OLD version still here

### ISSUE THREAD

**Issue by nicolharico** [ravibpatel/AutoUpdater.NET#167]
Hi ladies & gentlemen,

First, thanks for this nice lib !

Secondly, I'm having an issue trying to implement the auto update feature at the moment. 

Everything looks "normal", the distant new version is detected, the ZIP (containing the installer/publishing folder of the app new version) is downloaded, extracted and the prompts goes  thru the "installing updates" progress bar. When it ends, the app restarts and... this is still the old version, and the prompt for a new version come back etc.

The xml parts looks OK as the newer version is detected on the Start method, the URL looks OK as it downloads the archive. (I obviously replaced some parts of the URL with ### ;)

`<?xml version="1.0" encoding="utf-8"?>
<item>
  <version>1.0.1.11</version>
  <url>http://####.me:####/nicolas/apps/######/update.zip</url>
  <mandatory>false</mandatory>
</item>`

I may be concerned with the ZIP archive content. I placed the Publish output folder (containing the setup.exe, .application file, autorun.inf and Application files folder) in a simple zip archive. It looks the updated is being installed as the progress bar of the "installing updates" specify the version number of the newer version. 

Did I miss something ? Am I doing something wrong here ?

Thanks in advance for your support 👍 
![publishziparchive](https://user-images.githubusercontent.com/38257864/42571392-441cf6b8-8517-11e8-9baf-17be7cef414d.PNG)

**Comment by ravibpatel** [comment]
@nicolharico Are you using same file structure as your application file structure? Also, is your zip file contain the main executable with assembly version mentioned in the XML file?

**Comment by tiransa** [comment]
i also have this issue

my text.xml file
`<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>1.3.0.0</version>
    <url>http://192.168.5.253:8081/server/update.zip</url>
</item>`

my button action
`AutoUpdater.Start("http://192.168.5.253:8081/server/test.xml");
            AutoUpdater.ReportErrors = true;
            AutoUpdater.RunUpdateAsAdmin = false;
            AutoUpdater.DownloadPath = Environment.CurrentDirectory;`

updater show download process and also install process then restart old software again. assembly version is same as XML file.

**Comment by ravibpatel** [comment]
@nicolharico Can you share your application? Please also share your update zip file. It will help me to troubleshoot your problem.

**Comment by ravibpatel** [comment]
@tiransa @nicolharico Updated NuGet package with the fix. Please, can you check it?
