### ISSUE TITLE
Wait for update to finish

### ISSUE THREAD

**Issue by Karbust** [ravibpatel/AutoUpdater.NET#168]
Hello,

I have my Auto Patcher for the game, and I pretend to use this package to update the Auto Patcher (C#) when I need to release some update.

I have this on Program.cs (Yes, on Program.cs)
```
                    AutoUpdater.ShowRemindLaterButton = false;
                    AutoUpdater.ShowSkipButton = false;
                    AutoUpdater.Mandatory = true;
                    AutoUpdater.OpenDownloadPage = false;
                    AutoUpdater.Start("http://xxx.xxx/update.xml");

                    Application.EnableVisualStyles();
                    Application.SetCompatibleTextRenderingDefault(false);
                    Application.Run(new pForm());
```

As soon as the pForm() is loaded it starts the files updates right away, but I pretend to use the AutoUpdater and only after is finishes successfully it loads the form. How can I do that?

Thank you all

**Comment by ravibpatel** [comment]
@Karbust You need to handle updates manually for that to work. You can do that as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).
