### ISSUE TITLE
Access Update Path via Authentication

### ISSUE THREAD

**Issue by LuciaVeldera** [ravibpatel/AutoUpdater.NET#169]
Are there any way to pass username and password as parameters if application update path require authentication to access?

**Comment by ravibpatel** [comment]
You can try setting [web request credentials](https://msdn.microsoft.com/en-us/library/system.net.webrequest.credentials(v=vs.110).aspx) for that. You should do it after the following line.

https://github.com/ravibpatel/AutoUpdater.NET/blob/2175cedd823f1a5989f51a2b1120a3e9e163d634/AutoUpdater.NET/AutoUpdater.cs#L297

**Comment by LuciaVeldera** [comment]
I can't edit the source code because I install it via NuGet PM. Do you have any advice?

**Comment by ravibpatel** [comment]
@LuciaVeldera 

You can download the project and add a reference to your project to edit source code. Usually, it is a not a good idea to include Authentication information in C# code. You need to use some kind of obfuscation to hide the credentials.
