### ISSUE TITLE
Request to specify base directory path for unzip

### ISSUE THREAD

**Issue by i8out** [ravibpatel/AutoUpdater.NET#17]
Can we specify the start directory path for extracting the saved directory path in my zip file when AutoUpdater starts extract?

**Comment by ravibpatel** [comment]
No, AutoUpdater.NET uses currently executing application path to determine the directory to extract. If you want to customize this behaviour you can download the project and customize the code according to your needs. I suggest you should use installer as update file for more complex update process.
