### ISSUE TITLE
Source not Found Using .dll file

### ISSUE THREAD

**Issue by whoami213** [ravibpatel/AutoUpdater.NET#170]
unable to get update

![image](https://user-images.githubusercontent.com/18107626/42927967-997e6de2-8b68-11e8-8dee-3850fdc49860.png)

**Comment by ravibpatel** [comment]
@whoami213 Can you try using NuGet file?

**Comment by whoami213** [comment]
i solve the problem... Error Occurred if the url in the xml is null or path doesn't exist.
please catch the error and display to user.
thank you!
