### ISSUE TITLE
ZipExtractor logging

### ISSUE THREAD

**Issue by mashles** [ravibpatel/AutoUpdater.NET#171]
I am having real trouble identifying why ZipExtractor is bombing out half way through the extract, leaving only half the files replaced. Is there any way you can add some logging or even throw up a message as part of ZipExtractor when it fails to fully extract the zip.

What should the command line arguments be for ZipExtractor if I want to test it out separate from the library?

**Comment by ravibpatel** [comment]
@mashles Zip Extractor needs 2 arguments 1st one is the path of the update zip file and the second one is the current executable file.

https://github.com/ravibpatel/AutoUpdater.NET/blob/2175cedd823f1a5989f51a2b1120a3e9e163d634/AutoUpdater.NET/DownloadUpdateDialog.cs#L154

**Comment by IRHAMidIR** [comment]
> I am having real trouble identifying why ZipExtractor is bombing out half way through the extract, leaving only half the files replaced. Is there any way you can add some logging or even throw up a message as part of ZipExtractor when it fails to fully extract the zip.
> 
> What should the command line arguments be for ZipExtractor if I want to test it out separate from the library?

Hi There,I have the same problem , ZipExtractor Dosent Replace correctly , Pls Help

**Comment by ravibpatel** [comment]
@IRHAMidIR Can you tell me URL of your XML file?
