### ISSUE TITLE
Does AutoUpdater.NET support running exe file self-replacing?

### ISSUE THREAD

**Issue by tangtao-xp1** [ravibpatel/AutoUpdater.NET#175]
I wonder if the running process(main.exe) could download new version exe file and replace itself ?
I tried to do that, but the main.exe rejected me because the exe is running

Thank you!

**Comment by ravibpatel** [comment]
@tangtao-xp1 Yeah, Just zip it and provide zip file URL in your XML file. It will replace currently running exe.

**Comment by tangtao-xp1** [comment]
@ravibpatel It works, thank you!

**Comment by DjordjeMandic** [comment]
@ravibpatel it works only if zipped file is same name of current running executable. can you make zip extractor to extract file and replace it with the executable that has to be updated if filename is different? example if user renames my app from test.exe to test2.exe and runs an update updater will just extract file from archive in same directory and now i have test.exe(new version) and test2.exe(old version). Can zipextractor replace renamed test2.exe(old one) to new test.exe from archive?
