### ISSUE TITLE
Zip file is not extracted

### ISSUE THREAD

**Issue by frost4869** [ravibpatel/AutoUpdater.NET#18]
After finished download the zip file, it just opens the zip file without extracting.
I am using AutoUpdater from Nuget for a WPF application. Am I missing something ?

**Comment by ravibpatel** [comment]
can you give me URL of your XML file?

**Comment by frost4869** [comment]
here: 

`<item>
	<version>6.21.17</version>
	<url>
		https://github.com/frost4869/uploadfiles/raw/master/PC%20Installer.rar
	</url>
	<changelog>
		https://github.com/frost4869/PCs/releases
	</changelog>
	<mandatory>false</mandatory>
</item>`

I know this issue has been asked before, but I didn't quite understand the problem, thank you for responsed

**Comment by ravibpatel** [comment]
AutoUpdater.NET only supports .zip files and installer files in url field. You used .rar file as a download URL. Compress it as a zip file and try again it will work.

**Comment by frost4869** [comment]
oh man I feel so dumn right now, thank you, everything works fine now !
