### ISSUE TITLE
Unable to update the application after new version downloaded

### ISSUE THREAD

**Issue by kiran1384** [ravibpatel/AutoUpdater.NET#181]
I am getting an error message - This installation package could not be opened. Verify that the package exists and that you can access it, contact the application vendor to verify that this is a valid Windows Installer package.
I can see the newer version downloaded in the download path, when i try to manually install by clicking that file i see an error message saying - Unable to install because a newer version of this product is already installed. I see that the old version and new version of the application are different but do not understand this message. Please help.

**Comment by ravibpatel** [comment]
@kiran1384 This is the error from installer. What kind of installer are you using?

**Comment by kiran1384** [comment]
@ravibpatel it's a .msi installer

**Comment by ravibpatel** [comment]
@kiran1384 Is there a reason why you need to use installer? If your update only requires changing some files then you should use Zip for simpler updates cause AutoUpdater.NET doesn't have any control over installer. You can try fix mentioned [here](https://support.pix4d.com/hc/en-us/articles/202650009-Error-This-installation-package-could-not-be-opened-Contact-the-application-vendor-to-verify-that-this-is-a-valid-Windows-Installer-package-).

**Comment by kiran1384** [comment]
@ravibpatel I will give a try with your suggestion, thank you.
