### ISSUE TITLE
Use native Windows Zip extraction

### ISSUE THREAD

**Issue by djcarter-dv** [ravibpatel/AutoUpdater.NET#182]
Hi there, wondering if there's any reason we cannot use Windows native C# zip extraction for Windows 7 and higher? Has anyone tried this? 

https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive?view=netframework-4.7.2

This separate ZipExtractor.exe prompts UAC, hanging the update, which is causing me a lot of problems with overseas users and headless servers.

Thanks,
DJ

**Comment by djcarter-dv** [comment]
I've downloaded the code and I see you are using System.IO.Compression. It looks like I'm missing the keys for signing the binaries. Should I just generate my own?

**Comment by ravibpatel** [comment]
You can turn of UAC promt as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#run-update-process-without-administrator-privileges).  Also I didn't use ZipArchive cause AutoUpdate.NET was made for .NET framework 2.0 and above.

**Comment by AluminiumTech** [comment]
@djcarter-dv  I will try to look into this for the .NET Core version of ZipExtractor I'm working on since the documentation says it should work in .NET Core.

**Comment by NewITCorp** [comment]
may I vote for this feature, sometimes my clients have a security policy that always prompt for a admin privilege during autoupdate everytime which is annoying. if we can use some other unzip tool without running extenal exe will be great.

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1 with this feature.

**Comment by prj** [comment]
> 
> 
> Updated the NuGet package to v1.6.1 with this feature.

How to actually use it?
I do not see anything in the documentation about it.

**Comment by ravibpatel** [comment]
@prj When you use zip file as an update file, it will automatically use native windows zip extraction in new version.

**Comment by prj** [comment]
I was using v1.6.4, and now I am using v1.7.0.
I use a XML file on the server to configure the updater, which points to a Zip file.

ZipExtractor is still always used.

I am on .NET Core 3.1.

**Comment by ravibpatel** [comment]
@prj ZipExtractor uses native Zip functionality available in .NET Framework 4.5 or above. Before that, it was using ZipStorer library, so in this case native means using function already available in framework rather than using third part library.

**Comment by ravibpatel** [comment]
@prj You can download the source code, add your signing certificate and recompile it.

**Comment by prj** [comment]
> @prj You can download the source code, add your signing certificate and recompile it.

Two years later, and this is still probably the biggest issue with the tool. The UAC popup with unknown publisher is really getting old.

Do you feel like elaborating on the "add your signing certificate and recompile it" part?

So far:
1. Cloned the Git.
2. Set the project type to .net version I am using
3. Removed the strong name signing (.net 5+ does not care about this anyway).
4. Added a post-build step to ZipExtractor to sign the ZipExtractor.exe in resources with my code signing certificate
5. Built release and used "Pack" option to create a nuget package
6. Added local build folder as nuget source and installed the package from there

Result:
ZipExtractor is now signed, however the actual update does not work. Everything is fine in the app, however ZipExtractor.exe fails to run.
All I see in event viewer is this:
Description: A .NET application failed.
Application: ZipExtractor.exe
Path: C:\Users\err_g\AppData\Local\Temp\ZipExtractor.exe
Message: The application to execute does not exist: 'C:\Users\err_g\AppData\Local\Temp\ZipExtractor.dll'.

And yes, inded, the .dll is not there.

Is there yet another magic handshake or secret hoop that I missed to build the project?

**Comment by prj** [comment]
Solution for .net5/.net6 and VS2022, because zipextractor is not possible to build as a single exe with them currently:
1. Download latest AutoUpdater.NET release.
2. Extract the "zipextractor" resource using ilspy (naming it ZipExtractor.exe).
3. Copy it to the AutoUpdater.NET/Resources folder.
4. Sign the ZipExtractor.exe with your cert.
5. Unload the ZipExtractor project, because otherwise it will just overwrite it.
6. Build the AutoUpdater.NET project
