### ISSUE TITLE
Managing a stable and a beta update channels

### ISSUE THREAD

**Issue by NeomMob** [ravibpatel/AutoUpdater.NET#184]
How can we manage 2 different update channels (one for stable release, one for beta ones) and allow the user to move from one to the other?

**Comment by ravibpatel** [comment]
@NeomMob You can use separate call to Start method for both beta and stable channel.

**Comment by NeomMob** [comment]
@ravibpatel Thanks for your answer. Imagien my stable version is 1.2 and my beta 1.3. If I want to move from beta (already installed) to stable, how can I force the updater to "downgrade" from 1.3 to 1.2 ?

**Comment by PoLaKoSz** [comment]
@NeomMob I recommend to follow [semantic versioning](https://semver.org).

**Comment by NeomMob** [comment]
@PoLaKoSz Thanks for the suggestion. How can semver can solve the question of moving from a stabble channel to a beta one and the opposite?

**Comment by NeomMob** [comment]
@PoLaKoSz Thanks for these pointers!
