### ISSUE TITLE
Includign AutoUpdater.NET package broke Type.GetType

### ISSUE THREAD

**Issue by snechaev** [ravibpatel/AutoUpdater.NET#185]
In out code we have the operation like this 
`var result = Type.GetType("ArrayOfint, http://schemas.microsoft.com/2003/10/Serialization/Arrays");
`(the argument is actually calculated). The expected result will be null (type not found). 

But after adding AutoUpdater.NET 1.4.11.0 and referencing one of static field of AutoUpdater class, the code above throws FileLoadException instead returning null.

Full test code. Create Console application (.net 4.5) and replace Program.cs with the following snippet,
```
using System;
using AutoUpdaterDotNET;
namespace Crash
{
    class Program
    {
        static void Main(string[] args)
        {
            AutoUpdater.ShowSkipButton = false;//commenting this will fix the issue
            var result = Type.GetType("ArrayOfint, http://schemas.microsoft.com/2003/10/Serialization/Arrays");
        }
    }
}
```
I make some research and found, that if I recompile AutoUpdater.NET without Resource.Embedder package (and additionally manually remove corresponding build targets from .csproj file), and use this rebuilded package instead of nuget package, the issue stop reproducing.
So, looks like the issue is caused by the bug in the Resource.Embedder package.

My environment is Win7 (with all updates) and VS2017 (15.8.4)

**Comment by MarcStan** [comment]
My knowledge of type internals is a bit rusty, but is "ArrayOfint, http://schemas.microsoft.com/2003/10/Serialization/Arrays" valid?

Checking the [Type.GetType](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.7.2#System_Type_GetType_System_String_) and [type names](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names?view=netframework-4.7.2) documentations I can't find any reference to schema based type loading and as far as my knowledge goes it should only be "TypeName, AssemblyName"

If it is valid, could you point me to the documentation? (personal interest)

Further if I do this in a clean console app project (the true means "throw on error"):
> Type.GetType("ArrayOfint, http://schemas.microsoft.com/2003/10/Serialization/Arrays", true)

I get "System.IO.FileNotFoundException: 'Could not load file or assembly 'http:\/\/schemas.microsoft.com\/2003\/10\/Serialization\/Arrays' or one of its dependencies. The system cannot find the file specified.'"

So I think your dynamic computation of the type name is a bit off.

Regarding the crash: It happens in resource embedder as described [here](https://github.com/MarcStan/Resource.Embedder/issues/7) and I can fix it via user input validation.
