### ISSUE TITLE
Make the DialogBox optional. Enabled by default.

### ISSUE THREAD

**Issue by UBGEdev** [ravibpatel/AutoUpdater.NET#186]
The thing is, this module work as a charm. it would be great if it could update silently. so there's no need to connect to the vps and update.

**Comment by snechaev** [comment]
@UBGEdev, but there is already CheckForUpdateEvent here. With this event you can easily start downloading of the new version without any dialog boxes. The example is present in the [readme file](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).

**Comment by UBGEdev** [comment]
Untesrtood.
