### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by cobra23** [ravibpatel/AutoUpdater.NET#187]
thank you for the helpfull project, is it possible to use google drive as webserver?
because i can't do it, would you help me please

**Comment by AluminiumTech** [comment]
What issue(s) are you having and what specifically are you doing?

**Comment by cobra23** [comment]
i want to use google drive as server so autoupdater.start(googledrivexmllink);
where googledrivexmllink is the link provided by google drive when i upload the xml file in it, in my case the link is:
https://drive.google.com/file/d/1rcnBrIpMZiqq2sh65YgMuEAJMXBxTfeO/view?usp=drivesdk
I think that is a problem of subdomain, because i try it with two other subdomain and it dose not work also, unles it woks,  is there any solotion for this please.

**Comment by AluminiumTech** [comment]
@cobra23  The issue might be that the XML file points to localhost.

**Comment by cobra23** [comment]
@Aluminium Tech
no i don't think so, cause I changed the link of the zip file, but the main problem is that there is no dialog box apeared to show me that there is a new version, but when i change the server of the fml link to anther domain name(not subdomain) it works perfectly, thank you in advance

**Comment by ravibpatel** [comment]
@cobra23 Link you provide for the XML file should provide raw XML data nothing else. In the case of Google Drive links that is not the case. I suggest using GitHub repo to provide XML file as it provides raw linking to files inside the repo.

**Comment by cobra23** [comment]
@ravibpatel thank you for the response sir, but i don't have any pb with servers using domain names, my pb is when i upload the xml in servers using subdomains like drive.google.com, please is there a solution to avoid it?

**Comment by JanWidm** [comment]
You could set up your github.io page and upload everything there!

**Comment by cobra23** [comment]
@JanWidm thank you

**Comment by JanWidm** [comment]
The problem is that Google Drive does not provide a direct file link (with the .xml at the end) so this would be kinda tricky to do. You would have to get the content of your google link somehow and feed it to the AutoUpdater.

**Comment by cobra23** [comment]
@JanWidm this is not the pb cause i used another url (http:/technocid-dz.hebergratuit.net/upd/test.xml)
and it was the same pb, the application dont show me the udate dialog box, so i think that this library don't support subdomains names. otherwise (domain names works with me!)

**Comment by JanWidm** [comment]
@cobra23 subdomains is not a problem. Are you sure you increased the version in the XML and did not skip the update? Try to change the version in the XML to version 2.0.0.1 (just to test) and update your application.

**Comment by cobra23** [comment]
@JanWidm thank, but i used the same xml in a domain name and it works perfectly
for the version nuber ichanged to other version and it also dosn't work, i created a github page and also same
https://cobra23.github.io/updatebs.github.io/test.xml

**Comment by JanWidm** [comment]
@cobra23 also you should enable `AutoUpdater.ReportErrors = true;` so you get a message if there is no newer update avaiable.

In your Google Drive XML you use version `2.0.0.0` and in your website version u used `1.0.0.1`

**Comment by JanWidm** [comment]
@cobra23 I just pasted your github.io XML into my application and it worked. I assume that your installed version (.exe) has a higher productversion that the version in the xml. Could you check that?

**Comment by cobra23** [comment]
@JanWidm thank you for the efforts, the version of my exe is 1.0.0.0,(lower to the xml), but when i wrote autoupdater.reporterrors=true;
it shows to me an error message: that there is a problem with the update server

**Comment by JanWidm** [comment]
@cobra23 so there is a problem with connecting to the github.io server. I just tested it for my project. I'll take a look at the code to find out the problem. @ravibpatel

**Comment by JanWidm** [comment]
@cobra23 is it possible that you added the Autoupdater.NET.Official just as a dll Reference?

`<Reference Include="AutoUpdater.NET">
      <HintPath>..\..\teset\packages\Autoupdater.NET.Official.1.4.11\lib\net40\AutoUpdater.NET.dll</HintPath></Reference>`

Could you create a new Project with the NuGet Package instead of the direct dll?

**Comment by cobra23** [comment]
@JanWidm thank you sir, your project works fine, but when i create another project using the nuget lib, i have the same pb

**Comment by JanWidm** [comment]
@cobra23 possible problem with your Visual Studio version? I saw that you are not using the newest right.

**Comment by cobra23** [comment]
@JanWidm yes i am using sharpdevelop 5 with is equivalent to visual studio 2010 express

**Comment by JanWidm** [comment]
@cobra23 you might have found the problem haha 😄 I don't know if there are any bugs with creating projects with sharpdevelop. I think it would be great to test the visual studio community edition (free) to avoid this kind of bugs. You probably should test it and decide what you should use. For now I think you can close this issue since it's not a general problem.

**Comment by cobra23** [comment]
@JanWidm thank you very much :+1:
