### ISSUE TITLE
Doesn't seem to work with proxy

### ISSUE THREAD

**Issue by zedle** [ravibpatel/AutoUpdater.NET#189]
I have a proxy enabled on the system and it doesn't seem to retrieve the XML file. I can access the URL through the proxy without issue. Tried manually setting the proxy details as per the readme and it didn't change the result. ReportErrors = true seems to do nothing (looking for some insight into why it doesn't trigger an update with the proxy enabled).

**Comment by ravibpatel** [comment]
@zedle Did you try adding the project as source and debugging it? I never tested proxy feature extensively. If you can provide me your proxy detail and file URL it will help me test it. You can do it here https://rbsoft.uservoice.com.
