### ISSUE TITLE
ZipExtractor UI hangs while extracting the update

### ISSUE THREAD

**Issue by prchanda** [ravibpatel/AutoUpdater.NET#190]
I have followed this : https://github.com/ravibpatel/AutoUpdater.NET#adding-one-line-to-make-it-work and my code looks like this:

public frmDashboard()
        {
            AutoUpdater.RunUpdateAsAdmin = false;
            AutoUpdater.DownloadPath = Environment.CurrentDirectory;
            AutoUpdater.Start("https://xyz.com/release/updates.xml");
            InitializeComponent();
            InitializeControls();
        }

So when I ran my application, updates got downloaded but ZipExtractor UI gets in hang state as shown below, although it does it's job, taking a long time.

![image](https://user-images.githubusercontent.com/35064849/46242256-2a091c00-c3e4-11e8-803f-668cd7024896.png)

ZipExtractor UI takes 2 minutes to extract a very small file 781KB, which is something not expected. Secondly it seems like extraction logic is implemented in the UI thread of ZipExtractor causing it to hang.

Can you please fix this issue ?

**Comment by prchanda** [comment]
> @prchanda I think it is caused by Prcoess.WaitForExit() call in ZipExtractor. Thanks for reporting this I will fix it asap.
> Also, Please try to use AutoUpdater.Start after InitializeComponent call.

Thanks a lot for quick reply ! 

I will try it right away and let you know, how it goes.

**Comment by prchanda** [comment]
Unfortunately calling AutoUpdater.Start after InitializeComponent call, didn't help. Is it fixed yet ?

**Comment by ravibpatel** [comment]
@prchanda Sorry, I am working on another project so I can't fix it right now. This usually happens if your application is taking a long time to close. I close this issue when I fix it.

**Comment by prchanda** [comment]
> @prchanda Sorry, I am working on another project so I can't fix it right now. This usually happens if your application is taking a long time to close. I close this issue when I fix it.

No problem @ravibpatel. Can you provide any ETA for the fix ?

I really liked this utility, so don't want to switch to any other options.. :)

**Comment by ravibpatel** [comment]
@prchanda I can't promise but I will try to do it before the end of next week.

**Comment by Shamanovski** [comment]
And one more thing, how to suppress "There is no update available. Please try again later." dialog when versions match? It is meaningless for this case

**Comment by ravibpatel** [comment]
@Shamanovski Make sure [error reporting](https://github.com/ravibpatel/AutoUpdater.NET#enable-error-reporting) is disabled. If you use installer file instead of zip file as download file AutoUpdater will try to execute it.

**Comment by Shamanovski** [comment]
> @Shamanovski Make sure [error reporting](https://github.com/ravibpatel/AutoUpdater.NET#enable-error-reporting) is disabled. If you use installer file instead of zip file as download file AutoUpdater will try to execute it.

thank you!
