### ISSUE TITLE
Webrequest.Create incorrect URL

### ISSUE THREAD

**Issue by JanWidm** [ravibpatel/AutoUpdater.NET#193]
Is it possible to add some errorhandling for your `Webrequest.Create()` logic?

In the `AutoUpdater.cs` line `297` is following code: `var webRequest = WebRequest.Create(AppCastURL);`
If you provide a incorrect or empty URL the app just crashes with a not so pretty error message. (sorry can't really post it because it's in german for me)

https://github.com/ravibpatel/AutoUpdater.NET/blob/f184795dc7c0c02e6470785b0a22b44d6f5e9f5b/AutoUpdater.NET/AutoUpdater.cs#L297

**Comment by ravibpatel** [comment]
@JanWidm Yeah, I think it is necessary. I will do it asap.

**Comment by ravibpatel** [comment]
@JanWidm I think it will be a bad idea to suppress this error cause it is a fatal error. Without correct URL it can't work. The developer must see this error to know if he did something wrong.
