### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by PoPoWanObi** [ravibpatel/AutoUpdater.NET#195]
Hello, I am using the latest version embedded into my application.

I am receiving the error "Update Check Failed | There is a problem reaching update server. Please check your internet connection and try again later." The message displays immediately with ReportErrors enabled.

The update URL is set properly and it is able to open in a browser just fine.

Using the default URL works fine however.

XML, and .zip are located correctly on the server.

**Comment by ravibpatel** [comment]
@PoPoWanObi Can you give me URL of your XML file?

**Comment by PoPoWanObi** [comment]
Sure. https://vanguardservers.tk/downloads/launcher.xml

**Comment by PoPoWanObi** [comment]
@cobra23 Hello I am using Visual Studio 2017.

Building in Net framework 4.5.

**Comment by cobra23** [comment]
@PoPoWanObi here is a project created with 2017 last update and framework 4.6.1 by @JanWidm and modified by me in VS2013 to use your URL, it works fine, you have to try it
so the problem is in the framework : using  4.6.1 or higher works else No
the URL of the project using your xml URL
https://cobra23.github.io/essaiAuto2.zip

**Comment by JanWidm** [comment]
@cobra23 @PoPoWanObi @ravibpatel Yeah this is actually a strage behaviour. The AutoUpdate.NET uses WebRequest -> https://github.com/ravibpatel/AutoUpdater.NET/blob/f184795dc7c0c02e6470785b0a22b44d6f5e9f5b/AutoUpdater.NET/AutoUpdater.cs#L297
Webrequest is a obsolete API and probably should be updated to [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?redirectedfrom=MSDN&view=netframework-4.7.2) by @ravibpatel 

here is the msdn site about [WebRequest](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.-ctor?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_HttpWebRequest__ctor) saying that it is obsolete

**Comment by JanWidm** [comment]
Okay, so working with .NET Framework 4.6 works fine, everything below says I am not able to connect to the server. @ravibpatel

**Comment by ravibpatel** [comment]
@PoPoWanObi @JanWidm You need to switch Security Protocol. Switching to TLS 1.2 should work. See #25. I will add this to docs.

Use the following statement before using the Start method.

```csharp
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12
```

**Comment by PoPoWanObi** [comment]
@cobra23 , @ravibpatel , @JanWidm 

Thanks guys.
