### ISSUE TITLE
Force check update

### ISSUE THREAD

**Issue by JanWidm** [ravibpatel/AutoUpdater.NET#196]
Is it possible to force the check for a update? If not this would be a great improvement imo.

**Example:**
In my application, I check for updates on App-Startup, if I choose to skip the update or do it by mistake, I won't be able to update the app. It would be great to have a bool to "force" the update.

**Comment by ravibpatel** [comment]
@JanWidm Just set Mandatory to true in XML and user will get prompt until they update the application. There is no way to skip the update.

**Comment by JanWidm** [comment]
Yeah, but thats not really the point. I'd like to have a normal update and if the user skips it by mistake or just would like to update later, he won't be able to do that. Is there no way to say "I'd like to check again" or just ignore the skip I set earlyer? The info is saved in the registry right?

**Comment by ravibpatel** [comment]
@JanWidm If you set it to true then previous values of Skip and Remind Later will be ignored. I usually do it like this. First I check for update at the start of the application with Mandatory flag off. But I also provide an option to check for the update manually and it has the Mandatory flag on like [this](https://github.com/ravibpatel/AutoUpdater.NET#ignore-previous-remind-later-or-skip-settings). So even if they skipped it they can check for the update manually.

**Comment by JanWidm** [comment]
@ravibpatel that was what I was looking for 👍 Thanks. I thought you were talking about the Mandatory flag in the XML.
