### ISSUE TITLE
Possible issue with Italian Translations - Translators wanted

### ISSUE THREAD

**Issue by AluminiumTech** [ravibpatel/AutoUpdater.NET#197]
Hi, 
I noticed that there's an issue with the Italian Translations for AutoUpdater.

The first phrase in the translation file hasn't been translated but the rest have been.

![image](https://user-images.githubusercontent.com/14107316/46757333-c2937c00-ccc1-11e8-82b2-9e34111df3fe.png)

**Comment by ravibpatel** [comment]
@AluminiumTech Hi, Most of the translations are user submitted. So I don't know anything about it maybe it was better untranslated.

**Comment by AluminiumTech** [comment]
Okay. It's probably a good idea to keep this issue open until it is fixed.

**Comment by volkcloud** [comment]
Hello.
I was writing an issue when readed this post. This sentence
"{0} {1} è ora disponibile. Hai {2} installata versione. Volete scaricare ora?"
can be wel formed as "{0} {1} è ora disponibile. Hai la versione {2} installata. Vuoi scaricare ora?"

(I am italian)

**Comment by bacca87** [comment]
the translation was fixed with my last pull request, this ticket can be closed.
