### ISSUE TITLE
Old application stays in control panel

### ISSUE THREAD

**Issue by heensdave** [ravibpatel/AutoUpdater.NET#199]
I am using the latest version 1.4.11.0 I am able to update the application (from version 1.0.0 to 2.0.0) but if I check in the control panel I can see the old version (1.0.0) there too.

**Comment by ravibpatel** [comment]
@heensdave Are you using Zip file to update the application?

**Comment by heensdave** [comment]
I am using .MSI installer

**Comment by ravibpatel** [comment]
@heensdave AutoUpdater.NET just executes your installer so if it changes the version if you manually upgrade then it should change version when you update it using AutoUpdater.NET.

**Comment by heensdave** [comment]
It does changes the version on existing application. Only issue is it left over the entry of old version of application in control panel

**Comment by ravibpatel** [comment]
@heensdave You need to create an installer in a way it can detect existing installation and upgrade it.  Seems like your installer installs it like a fresh installation and that's why it is leaving old entry behind.

**Comment by ravibpatel** [comment]
@heensdave Yeah, That was my point. AutoUpdater.NET just downloads and executes the installer. It doesn't influence actions taken by the installer.

**Comment by heensdave** [comment]
Recreating installer with handling previous version works. Thanks for the prompt response.
