### ISSUE TITLE
Feature request | appSettings on AppCast

### ISSUE THREAD

**Issue by mossandlichens** [ravibpatel/AutoUpdater.NET#2]
Would it be possible to extend the appcast xml to support a section like appSettings?

**Comment by ravibpatel** [comment]
Can you give me a scenario where this feature can be useful?

**Comment by mossandlichens** [comment]
App A is delivered and used by clients P, Q and R.
Each client enters an API key to use App A.
Based on this API key App A remotely configures each instance of App A.

A key value pair such as appSettings in AutoUpdater.NET AppCast xml will help in implementing this remote config, which otherwise will have to implemented separately.

**Comment by ravibpatel** [comment]
I think it is possible to do this. But I am thinking of solution where you can add any additional tags to app cast XML and AutoUpdater.NET will fetch those and make them available to you in a CheckForUpdateEvent.

**Comment by mossandlichens** [comment]
That will be great! Is there any way I can support you?

**Comment by ravibpatel** [comment]
I will contact you if I need help. Thanks for offering.
