### ISSUE TITLE
Uses of webResponse.ResponseUri after webResponse is closed

### ISSUE THREAD

**Issue by taylorzs** [ravibpatel/AutoUpdater.NET#20]
Please check following commit 89e05799896bdfee7e439fc4025a8035a982ba63on June 16.

AutoUpdater.cs   

![image](https://user-images.githubusercontent.com/29901996/27842721-d43ad966-610c-11e7-8cc9-f45e1cedc6ec.png)

It will cause System.ObjectDisposedException.

**Comment by ravibpatel** [comment]
Thanks for reporting the issue. I totally missed that one. I will fix it asap.
