### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by DrJaymz** [ravibpatel/AutoUpdater.NET#202]
I think I can get away with just updating files from a zip file.  It works if I ran my application originally as administrator, however, if I run normally then it cannot download the files because it hasn't got permission to write to the folder.

Supposedly, I could run an MSI which would of course require UAC to ask if this is ok and then it should work.

The only other solution I was thinking was to create a windows service that does have the right permissions and it can do whatever it like then.

How is everyone else running this? Have they all got UAC turned off or something?

**Comment by GusGiann** [comment]
Same problem here. I want to update application on Pc's that have User Privileges without the need of an Administrator present when update is done. Program Files Folders are protected.
It would be so so nice if we could download the update in the same folder as application and replace some files (even .exe).
But as I have already mentioned Program Files folder is not accepting any changes without Admin Rights.

Most Applications are installed to Program Files Folder. 
Any suggestions how to overcome this problem ??

**Comment by ravibpatel** [comment]
@GusGiann You need to run updater as admin as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#run-update-process-without-administrator-privileges).

**Comment by GusGiann** [comment]
Yes I Know but I want to bypass all these procedure because update is going to be executed (automaticly in mandatory mode) from simple users accounts. Is there a way to pass admin values directly to updater?
Thank you very much in advance for your help.!!

**Comment by steveskalski** [comment]
Same issue here.  I have admin set to true in Autoupdater and I get a directory write error due to permissions.

**Comment by ravibpatel** [comment]
@GusGiann I don't think UAC can work that way. So you can't pass admin values directly. To avoid this problem you can force the user to install application where standard user has permission to write.

**Comment by steveskalski** [comment]
@ravibpatel  I am using the updater to run an installer.  The installer is writing to the program files (x86) folder.

**Comment by ravibpatel** [comment]
@ravibpatel RunUpdateAsAdmin option only works if you provide Zip file as an update file. If you provide installer then it is installer's responsibility to elevate the installer process. This library only downloads and executes the installer.

**Comment by yasirrose** [comment]
@DrJaymz facing same issue. Did you have any workaround for it? Actually, i want to update windows service which is not possible without updating it from service.

**Comment by FlameadoDeMoe** [comment]
Any news about this issue?

Thanks in advance.

**Comment by GusGiann** [comment]
> 
> 
> Any news about this issue?
> 
> Thanks in advance.

No my friend. AutoUpdater.Net is great but any update file  must be executed with Administrator Privilages in user PC !
