### ISSUE TITLE
version not changing 

### ISSUE THREAD

**Issue by GoatMemes** [ravibpatel/AutoUpdater.NET#204]
I have everything set up and the updates work but when I install an update it doesn't update my applications version, But it does install the update. So how do I make it so it changes application version along with the update?

**Comment by ravibpatel** [comment]
@GoatMemes Are you using a zip file for the updates?

**Comment by GoatMemes** [comment]
@ravibpatel Yes

**Comment by ravibpatel** [comment]
@GoatMemes Where you didn't see the application version after update. Zip file updates just overwrite app folder data with the new update. If you want full control over updates then you should use the installer

**Comment by GoatMemes** [comment]
@ravibpatel When I click the "Check for updates" button it opens the menu saying there is an update so then I go ahead and update it but then if I click the button after the update it still says the application version is still the same how do I get it to change the app version with the update

**Comment by AAN3AC** [comment]
The version number inside your exe file is in your visual studio project properties.  Manifest

**Comment by GoatMemes** [comment]
@AAN3AC Still when I try to update it says my current version is "1.0.0.0" but in the manifest is says "1.0.0.2".

**Comment by GoatMemes** [comment]
I figured it out thanks for helping!!!  👍

**Comment by AAN3AC** [comment]
I meant "assembly information" the "assembly version"
