### ISSUE TITLE
Can I download XML from Google Drive by my own and transfer the content to AutoUpdater.Start ?

### ISSUE THREAD

**Issue by thelemontree10** [ravibpatel/AutoUpdater.NET#205]
Dear ravibpatel,

I copy your code inside (webresponse) AutoUpdater.Start to download XML from my google drive. The test shows that the code inside yor dll can download XML from google drive.

But when I copy the link to use directly from AutoUpdater.Start, it always shows error like problem about connectivity.

So can I have a turn around way to transfer the XML data I have already downloaded, load that into AutoUpdater.Start ?

Thank a lot.

P/S:

Here is my google drive link for you to try. I make it public so that it can be downloaded without authorizing through Google API.

https://drive.google.com/uc?export=download&id=1gEaZOYbW3QJWpY1IyDung9XLhzixLPWJ

Best Regards,

**Comment by ravibpatel** [comment]
@thelemontree10 Your XML is wrong. You must provide url and version fields in XML. Also, make sure version you specify in XML must be higher than your assembly version.

**Comment by thelemontree10** [comment]
I have identified the problem. The XML you have seen is the revision.

The problem here is that if you have the word "id" in the tag <url>, your code can not parse xml and throw error. 

In addition, in stead of throwing a general error. You should throw error description thrown by VS. So that people can know what is wrong. Your error description make me misunderstand all...

**Comment by thelemontree10** [comment]
For those who see this post,

If you still want to use google drive, instead of using XML, you use JSON as a AppCast as described in the readme of AutoUpdater.
