### ISSUE TITLE
Distribute library with resx files

### ISSUE THREAD

**Issue by Primabase** [ravibpatel/AutoUpdater.NET#206]
I've added a reference to AutoUpdate.NET library in a Windows Form application. The setup project (MSI) install correctly but when I open the UpdateForm the language is always English. If I debug from V.S. in my laptop the language is correct.
After various tests I've discovered that if i copy language folders in application folder of the client UpdateForm run with correct language. I've to include language folders of the library in the distribution project?

Thank you

**Comment by ravibpatel** [comment]
@Primabase Which .NET Framework are you using?

**Comment by Primabase** [comment]
.NET Framework 4

Thank you

**Comment by ravibpatel** [comment]
@Primabase .NET Framework 4 version has embedded resource assembly so it should work without problems. Are you using the NuGet package?
