### ISSUE TITLE
Problem with AutoUpdater.Start method

### ISSUE THREAD

**Issue by wizengamot** [ravibpatel/AutoUpdater.NET#207]
Confirmed this on multiple occasions with code on my side.  When I store the URL in AppSettings and then either directly use code such as AutoUpdater.Start(ConfigurationManager.AppSetting["UpdateURL"]); the UpdateInfoEventArgs value in the AutoUpdaterOnCheckForUpdateEvent is null.  When I pass the url as string like this:  AutoUpdater.Start("https://www.google.com/update.xml"); then the UpdateInfoEventArgs has a value when the event is fired.

I even tried creating a string variable url; first, filling it with the contents of the AppSetting and then passing the string variable to the AutoUpdater.Start and it still did not work.  The only working scenario is when the value is an actual string.  I have confirmed via copy/paste that the value in AppSetting and the value passed in the quotes to the Start method are exactly the same.

Here are the conditions that I have noted so far.
1.4.7 Framework 4.5.2, 4.6 & 4.61 - works only if I pass the Start method an actual string in quotes.
1.4.11 Framework 4.5.2, 4.6, & 4.6.1 - works only if I pass the Start method an actual string in quotes.
I have also checked to ensure that the update.xml file is UTF-8 encoded so it matches

If anyone knows what I am doing wrong, I would be very thankful as I believe this was working correctly back when I started using the software a year ago and it does not appear that anyone else is having this trouble so I am thinking its some sort of environment thing.

The text of my update.xml follows: {I have changed the URL to one that does not work.. }
```
<?xml version="1.0" encoding="UTF-8"?>
<item>
<version>2.0.0.0</version>
<url>https://autoupdate.blob.core.windows.net/marcam/v2.zip</url>
<changelog></changelog>
<mandatory>true</mandatory>
</item> 
```

**Comment by ravibpatel** [comment]
@wizengamot Make sure ConfigurationManager.AppSetting["UpdateURL"] gives the correct URL. It can happen if it adds something to the value and that makes URL malformed.
