### ISSUE TITLE
Download xml from a server share location (Windows share SMB)

### ISSUE THREAD

**Issue by blind0wl** [ravibpatel/AutoUpdater.NET#208]
I have a few clients who are fairly locked down in terms of outside internet access and I don't have much access to a web server within their network.  Is there anyway I can have the updater use a windows share to check the xml?  Im struggling to find a solution for them without the required internet access.  Other users with no restrictions have no problems.  This group of users cannot use a proxy either.  Shot in the dark, but thought I would ask.

**Comment by ravibpatel** [comment]
@blind0wl It is not likely to work if Windows share uses a username and password which is always the case with the newer version of Windows.

**Comment by chuckv2014** [comment]
Hello,

I am attempting the same thing... however, users have permissions... I can browse the .XML by using:
"file://///TCHWhiteCloud/WhiteCloud/Update/AutoUpdaterTest.xml" using ctrl-click inside the VS2017 IDE... so, the path and security are satisfied... yet still doesn't display the dialog... is there some fix for this? This is an outstanding tool, very easy to use... would be great to be able to utilize if for a local network folder location.

Please advise (Thank you)
Chuck

**Comment by ravibpatel** [comment]
@chuckv2014 There is temp workaround for the issue. You need to host serve XML file through the server. You can do that by installing WAMP or configuring IIS.

**Comment by chuckv2014** [comment]
Thank you for your reply... I got it to load the XML and update w/o WAMP nor IIS... but it is throwing a File I/O Exception - not being able to fine the Assembly (I uploaded a new question earlier) nI can click "continue" and it loads the updated .exe. Can you direct me to a solution?

**Comment by they-we** [comment]
we seems to have the same issue. I have managed to host the xml using iis but the AutoUpdater.start doesn't seem to get the xml to work
