### ISSUE TITLE
Add option to update .net framework also

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/AutoUpdater.NET#211]
Can you add option so that we can specify minimum .net framework version: 
![image](https://user-images.githubusercontent.com/6750655/49245582-10e81000-f413-11e8-92ad-b65e7713ce5d.png) this. My app doesn't work like it should on framework version under 4.7. I would like to be able to specify minimum supported runtime version tag in updater.xml and let the updater check for framework update too. The problem is that people who are running my app on windows 7 cant update because there is TLS connection error. I fixed it in new version but they need to update manually. Also updating framework on clients machine would be another solution but i dont want to overcomplicate stuff. I just want to be covered if i make any changes in future. So for example if my app v3.3 works normally on .net v4.5 but new update v3.4 cant work without v4.7 i would like that updater could update framework too or download it and run installation and let user finish it. I know about <supportedRuntime> element but im not sure that users will get prompt to update framework by default.

**Comment by ravibpatel** [comment]
@DjordjeMandic This falls into a complex update scenario. So I think it would be better if you use the installer as an update file that way you will have total control over the update process.
