### ISSUE TITLE
Feature request - change IE web browser control to edge,firefox or chrome

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/AutoUpdater.NET#212]
Some web pages wont load or they show big popup over whole window about not supporting IE.

**Comment by davwheat** [comment]
Making a library bigger isn't always bad as long as it improves it. Using CEF could be a great thing to do.

#257 is a reason that exactly shows why IE is bad and shouldn't be used anymore.

**Comment by Wonderdch** [comment]
+1 😪

**Comment by ravibpatel** [comment]
Added support for WebView2 since v1.7.1.
