### ISSUE TITLE
AutoUpdater.NET does not replace files after updating the application.

### ISSUE THREAD

**Issue by H0neyCake** [ravibpatel/AutoUpdater.NET#213]
I tried different ways of updating from the easiest to the most specific. In all cases the same thing happens. The application with the new version only opens after the update. But the application itself remains the same version. However, if I change the name, for example, not "Application", but "Application1" - it places it in the same folder as the main application. Also, i tried add to .xml param <checksum>, but it's not helping me.
My Update Method: 
```c#
private void SoftwareUpdate()
{
        AutoUpdater.AppTitle = "AppUpdate";
        AutoUpdater.LetUserSelectRemindLater = false;
        AutoUpdater.RunUpdateAsAdmin = true;
        AutoUpdater.ShowSkipButton = true;
        AutoUpdater.DownloadPath = Environment.CurrentDirectory;
        AutoUpdater.Start("my-xml-link");
}
```

**Comment by DjordjeMandic** [comment]
Read #160 
I think that you're having same problem.

**Comment by mattiegames** [comment]
I found it runs best from Program.cs, Just 2 lines added and works every time for me.  Try this way.

`
using AutoUpdaterDotNET;

namespace Update
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            AutoUpdater.Start("http://localhost/updates/AutoUpdater.xml");
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
}
`

**Comment by H0neyCake** [comment]
> I found it runs best from Program.cs, Just 2 lines added and works every time for me. Try this way.
> 
> `
> using AutoUpdaterDotNET;
> 
> namespace Update
> {
> static class Program
> {
> ///
> 
> 
> /// The main entry point for the application.
> ///
> 
> [STAThread]
> static void Main()
> {
> AutoUpdater.Start("http://localhost/updates/AutoUpdater.xml");
> Application.EnableVisualStyles();
> Application.SetCompatibleTextRenderingDefault(false);
> Application.Run(new MainForm());
> }
> }
> }
> `

No, sorry, its doesn't work. Same problem.

**Comment by ravibpatel** [comment]
@H0neyCake If you are using Zip file then it is required that Application executable name should stay the same otherwise it won't work. If update involves removing some files or doing any other things it is a good idea to use an installer as an update file.

**Comment by H0neyCake** [comment]
> @H0neyCake If you are using Zip file then it is required that Application executable name should stay the same otherwise it won't work. If update involves removing some files or doing any other things it is a good idea to use an installer as an update file.

No, i don't use Zip file, just .exe file. But he doesn't replace. Look, update happens and new application opened, but application doesn't replace in root directory,

**Comment by ravibpatel** [comment]
@H0neyCake You can't use application executable as an update file. If you want to only replace old executable with the new one then zip it and provide its URL as an update file.

**Comment by JvB94** [comment]
bump - same issue here. I'm using ZIP Files but the name of the Application is correct. 
It's not a generell problem just some user have issues. Is there a solution for that issue?

**Comment by ravibpatel** [comment]
@JvB94 Can you tell me the percentage of your userbase hit by this issue? This can be the permissions problem. In that case, you can try running the [update process as Admin](https://github.com/ravibpatel/AutoUpdater.NET#run-update-process-without-administrator-privileges). 

Another reason this can happen is due to corrupted download. In that case, you can try [adding checksum](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) of the update file and it will give an error if the file got corrupted while downloading.

**Comment by anuragdmon** [comment]
u might not have paid attention but the downloaded .exe file has different filesize which shouldnt happen and neither does it replaces the olderversion.exe to newerversion.exe even with same file name

**Comment by ozplc83** [comment]
Greetings have, 
I have this same problem in two desktop applications (WPF).

The update message is triggered, everything runs perfect, the zip is downloaded, updates the files, according to the log they are all replaced but as the executable is not replaced and runs the old one staying in a loop and asks to update again.
`
public MainWindow()
        {
            AutoUpdate();
            InitializeComponent();
            LoadPrinters();
        }
private void AutoUpdate()
        {
            AutoUpdater.AppTitle = "Print UPC From FNSKU (aka Anti-GTA) - UPDATE";
            AutoUpdater.Mandatory = true;
            AutoUpdater.UpdateMode = Mode.Forced;
            AutoUpdater.RunUpdateAsAdmin = true;        
            AutoUpdater.ReportErrors = true;


            AutoUpdater.Start("url-Update.xml");
        }
`
[ZipExtractor.log](https://github.com/ravibpatel/AutoUpdater.NET/files/5144286/ZipExtractor.log)
Attach the extractor log. 

thank you in advance.

**Comment by ravibpatel** [comment]
@ozplc83 I think you are zipping your application wrong way. I see it includes the Release folder. You should zip all files directly inside the Release folder and make sure your file structure matches the file structure of the update zip file. For example, If my installed version has my executable in the root folder but for some reason, I decide to move it into the "bin" folder in update zip then it won't work.

**Comment by ozplc83** [comment]
> @ozplc83 I think you are zipping your application wrong way. I see it includes the Release folder. You should zip all files directly inside the Release folder and make sure your file structure matches the file structure of the update zip file. For example, If my installed version has my executable in the root folder but for some reason, I decide to move it into the "bin" folder in update zip then it won't work.

Thank you very much for your help, 

Everything works 100% Ok.

The zip file was made of all the files in the release, as recommended, without placing them inside a folder.
I hope it will help others who present this problem.

**Comment by neonleo** [comment]
> I found it runs best from Program.cs, Just 2 lines added and works every time for me. Try this way.
> 
> `
> using AutoUpdaterDotNET;
> 
> namespace Update
> {
> static class Program
> {
> ///
> 
> 
> /// The main entry point for the application.
> ///
> 
> [STAThread]
> static void Main()
> {
> AutoUpdater.Start("http://localhost/updates/AutoUpdater.xml");
> Application.EnableVisualStyles();
> Application.SetCompatibleTextRenderingDefault(false);
> Application.Run(new MainForm());
> }
> }
> }
> `

Not Actually, Place and the WinForm constructor or Form_Load event still work good to me, but I thought it is very depend how the form is pre-load or post-load.
