### ISSUE TITLE
Feature request | Custom path for updated files.

### ISSUE THREAD

**Issue by FloranTheHunter** [ravibpatel/AutoUpdater.NET#215]
Currently, AutoUpdater is only made to update itself. But sometimes you need to perfrorm update on external program (if you have launcher for smth, for example). 
But this problem can be fixed with new variable, that represents custom update folder path.

**Comment by merihdursun** [comment]
Is there any news about that? I have external zip file and i should extract it to another location.

**Comment by ravibpatel** [comment]
@merihdursun This feature is still not available.
