### ISSUE TITLE
Ability to ignore mandatory updates by having the 'close window X' enabled

### ISSUE THREAD

**Issue by frankhommers** [ravibpatel/AutoUpdater.NET#216]
If I mark my update as mandatory, I still can skip it by clicking the close window X.
Also the applicationexit event doesn't get fired.

![image](https://user-images.githubusercontent.com/7355878/49995115-8ca59900-ff8b-11e8-89c9-21c690f59e07.png)

**Comment by ravibpatel** [comment]
@frankhommers It is intended behavior so users are not forced to update. The mandatory feature is designed so developers can provide a way to check updates after user pressed Skip or Remind Later buttons. But I see lots of devs are asking for this feature so it will be available in the new version.
