### ISSUE TITLE
Undo Update Error

### ISSUE THREAD

**Issue by fredmartinssilva** [ravibpatel/AutoUpdater.NET#220]
Good afternoon, i like would know if is possible to undo a update with error?

**Comment by ravibpatel** [comment]
@fredmartinssilva Hi, It is not possible to undo the update unless you are using the installer to update the app instead of a Zip file. Even if you use the installer your installer must support rollbacks.

**Comment by fredmartinssilva** [comment]
I understand. In this case I'll need develop in my app. Right?

**Comment by ravibpatel** [comment]
@fredmartinssilva For complex update procedure, it is required to use an installer as an update file. Auto

**Comment by fredmartinssilva** [comment]
@ravibpatel thanks! I will do.

**Comment by fredmartinssilva** [comment]
@ravibpatel thanks! I will do.
