### ISSUE TITLE
How to update zip.exe in AutoUpdater Project

### ISSUE THREAD

**Issue by mansoorulhaq324** [ravibpatel/AutoUpdater.NET#222]
Hi Ravi,

I made some changes in zip extractor project. But I cannot test those changes. because AutoUpdater.NET reading zip extractor from resource file. Can you please help me to fine stepts to create new .exe for extractor and then update resource file. Because when i opened .exe folder it contains 3 file one is text file second is reloc and third one is rsrc folder.

Best Regards,
Mansoor

**Comment by ravibpatel** [comment]
@mansoorulhaq324 Do you have your repo on Github? If it is the case please provide its URL so I can look how you implemented it.

**Comment by mansoorulhaq324** [comment]
it was my mistake. closing issue
