### ISSUE TITLE
Possible to Synchronously detect New version and Update

### ISSUE THREAD

**Issue by steveskalski** [ravibpatel/AutoUpdater.NET#223]
Is there a way to synchronously check for an update and then if found update?  Basically I am wondering if there is a way around the event.

**Comment by ravibpatel** [comment]
@steveskalski You can [handle update manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) but it will still run on another thread. Best you can do is move code you want to execute after the update check into the method handling the event.

**Comment by ravibpatel** [comment]
It is possible now to do it as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#check-for-updates-synchronously).
