### ISSUE TITLE
AutoUpdate.Proxy should be of type IWebProxy

### ISSUE THREAD

**Issue by psy4fun** [ravibpatel/AutoUpdater.NET#224]
Currently, AutoUpdate.Proxy is of type WebProxy.

WebProxy is just one of the possible implementations of an IWebProxy.

By restricting yourself to WebProxy, one cannot pass any other IWebProxy implementation. 

A simple scenario happens when retrieving the System WebProxy by means of WebRequest.GetSystemWebProxy() or WebRequest.DefaultWebProxy. What they return is a WebProxyWrapperOpaque, which is another implementation of an IWebProxy. An attempt to cast WebProxyWrapperOpaque to WebProxy is going to fail.

**Comment by ravibpatel** [comment]
@psy4fun Can you open a pull request with this change?
