### ISSUE TITLE
Minimum and Maximum window size

### ISSUE THREAD

**Issue by oleg-varlamov** [ravibpatel/AutoUpdater.NET#226]
It would be convenient to specify the maximum or minimum size of the notification window. On some monitors with a resolution of 800x600, no buttons are visible.

**Comment by ravibpatel** [comment]
@oleg-varlamov You can ignore changelog in the XML file and it will fit in 800x600. Lowering the size from current size will provide negative user experience cause WebBrowser control becomes very small.

**Comment by oleg-varlamov** [comment]
We have about 600 users with 800x600 monitor resolutions (It's sad but true). Most of them wants to know what was changed in new version. I think ignoring changelog is not the best solution in this case.

**Comment by ravibpatel** [comment]
@oleg-varlamov In that case, you can provide your own dialog by handling update manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). This way you will have total control of the layout.

**Comment by oleg-varlamov** [comment]
@ravibpatel Yes, thanks, I'm aware of this option! However, in this case, I need to copy the implementation of the three forms just to change the size of one of them. 
I propose to add the ability to change the size of the update form (something like AutoUpdater.UpdateFormSize = new Size(800,600)). And if someone needs such functionality, he will use this setting, if not, then the default form size will be used.

**Comment by ravibpatel** [comment]
@oleg-varlamov I will see what I can do about it.

**Comment by oleg-varlamov** [comment]
Thank you! I tried to make a pull request, but Git does not allow me to do this.

**Comment by ravibpatel** [comment]
You have to fork it to your account then you can create a branch with your changes. After that, you will be able to open a pull request.

**Comment by oleg-varlamov** [comment]
@ravibpatel Thank you! I sent a pull request with the discussed change.
