### ISSUE TITLE
How to deal with the CheckForUpdateEvent event if FTP has a username and password?

### ISSUE THREAD

**Issue by xgq07** [ravibpatel/AutoUpdater.NET#231]
How to deal with the CheckForUpdateEvent event if FTP has a username and password?

**Comment by ravibpatel** [comment]
@xgq07 How are you using it? Can you post an example code?

**Comment by xgq07** [comment]
@ravibpatel Thank you. 
`AutoUpdater.Start("ftp://localhost/UpdateFile/SocketServer.xml");`
If the FTP connection requires a username and password, the UpdateInfoEventArgs parameter in the CheckForUpdateEvent is null after the Start method. How should I add the username and password?

**Comment by ravibpatel** [comment]
@xgq07 It is not designed to work with FTP that's why it doesn't work. You have to modify the source code for that.

**Comment by xgq07** [comment]
@ravibpatel 
okay, thank you
