### ISSUE TITLE
ZipExtractor.exe

### ISSUE THREAD

**Issue by wangxiaofang1819** [ravibpatel/AutoUpdater.NET#232]
`System.IO.IOException:“The process cannot access the file 'D:\MES\master\src\MES\bin\Exe\Debug\MESClient\ZipExtractor.exe' because it is being used by another process.”`

` public CheckUpdateViewModel(RPCClient client)
        {
            _client = client;

            CurrentVersion = assembly.GetName().Version.ToString();
            Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("en");
            AutoUpdater.LetUserSelectRemindLater = true;
            AutoUpdater.ShowSkipButton = false;
            AutoUpdater.RemindLaterTimeSpan = RemindLaterFormat.Minutes;
            AutoUpdater.RemindLaterAt = 1;
            AutoUpdater.ReportErrors = true;
            DispatcherTimer timer = new DispatcherTimer { Interval = TimeSpan.FromMinutes(2) };
            timer.Tick += delegate { AutoUpdater.Start("D:\\MESClientWeb\\MESClient.xml"); };
            timer.Start();
        }
        public void Check()
        {
            try
            {
                AutoUpdater.OpenDownloadPage = false;
                AutoUpdater.DownloadPath = Environment.CurrentDirectory;
                AutoUpdater.Start("D:\\MESClientWeb\\MESClient.xml", assembly);

            }
            catch (Exception ex)
            {
                DXMessageBox.Show(ex.Message);
            }

        }`

I have this Problem , Why?

**Comment by wangxiaofang1819** [comment]
`<item>
<version>2.0.0.1</version>
<url>http://localhost:9910/MESClient.zip</url>
<changelog>
</changelog>
<mandatory>true</mandatory>
</item>`


when Press the button 'Update' ,it can download the zip file ,but still update failed

**Comment by ravibpatel** [comment]
@wangxiaofang1819 This can happen due to any other app (Antivirus software) is using the app while your app is trying to overwrite it in temp.

**Comment by wangxiaofang1819** [comment]
> @wangxiaofang1819 This can happen due to any other app (Antivirus software) is using the app while your app is trying to overwrite it in temp.
When first update, it can update Successfully .  When updated successfully ,the directory has 'ZipExtractor.exe', when open the Client again, the 'ZipExtractor.exe' is  being used by another process(MESClient),how to solve this problem?

**Comment by wangxiaofang1819** [comment]
> > @wangxiaofang1819 This can happen due to any other app (Antivirus software) is using the app while your app is trying to overwrite it in temp.
> > When first update, it can update Successfully .  When updated successfully ,the directory has 'ZipExtractor.exe', when open the Client again, the 'ZipExtractor.exe' is  being used by another process(MESClient),how to solve this problem?

Why  not delete 'ZipExtractor.exe'  when AutoUpdater update succussfully?  Doesn't other users have this problem?

**Comment by wangxiaofang1819** [comment]
> @wangxiaofang1819 This can happen due to any other app (Antivirus software) is using the app while your app is trying to overwrite it in temp.
if I want delete  'ZipExtractor.exe'  after ZipExtractor Unzip the file，before auto Process the MESClient.exe , how can I do?

**Comment by ravibpatel** [comment]
@wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.

**Comment by wangxiaofang1819** [comment]
> Main problem with this is ZipExtractor can't remove itself while it is running.
So can it remove after it runs , after ZipExtractor Unzip the file, before auto to start the MESClient.exe

**Comment by wangxiaofang1819** [comment]
> @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.

if iHow can I solve this problem ,

**Comment by wangxiaofang1819** [comment]
> > @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.
> 
> if iHow can I solve this problem ,AutoUpdater



> @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.



> @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.



> @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.

`
                string installerPath = Path.Combine(Path.GetDirectoryName(tempPath), "ZipExtractor.exe");
                File.WriteAllBytes(installerPath, Resources.ZipExtractor);
                StringBuilder arguments =
                    new StringBuilder($"\"{tempPath}\" \"{Process.GetCurrentProcess().MainModule.FileName}\"");
                string[] args = Environment.GetCommandLineArgs();  `
再File.WriteAllBytes 之前判断一下是否已经存在ZipExtractor

**Comment by wangxiaofang1819** [comment]
> > > @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.
> > 
> > 
> > if iHow can I solve this problem ,AutoUpdater
> 
> > @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.
> 
> > @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.
> 
> > @wangxiaofang1819 Main problem with this is ZipExtractor can't remove itself while it is running.
> 
> `string installerPath = Path.Combine(Path.GetDirectoryName(tempPath), "ZipExtractor.exe"); File.WriteAllBytes(installerPath, Resources.ZipExtractor); StringBuilder arguments = new StringBuilder($"\"{tempPath}\" \"{Process.GetCurrentProcess().MainModule.FileName}\""); string[] args = Environment.GetCommandLineArgs(); `
> before File.WriteAllBytes ,check wether ZipExtractor exist or not

` string installerPath = Path.Combine(Path.GetDirectoryName(tempPath), "ZipExtractor.exe");
                if(!File.Exists(installerPath))
                {
                    File.WriteAllBytes(installerPath, Resources.ZipExtractor);
                }`

**Comment by ravibpatel** [comment]
@wangxiaofang1819 I will add that thanks for the suggestion.

**Comment by wangxiaofang1819** [comment]
> @wangxiaofang1819 I will add that thanks for the suggestion.

Thanks for your reply .

**Comment by ravibpatel** [comment]
I think about this and I think executing the ZipExtractor while it is being used is not a good idea. If an update is bigger user can mistakenly try to open the app and if the update logic is at the start of the application it will make 2 instances of ZipExtractor which can cause many problems. I added the exception check instead. Now it will raise error dialog instead of crash.
