### ISSUE TITLE
Extraction file name problem (encoding)

### ISSUE THREAD

**Issue by jescampos** [ravibpatel/AutoUpdater.NET#233]
When the files are extracted, the file Gestão.exe is extracted like Gest╞o.exe making a app update loop!

I tested compressing the file with 7-zip (deflate encondig) and native windows 10.

**Comment by ravibpatel** [comment]
Can you provide me example zip file?

**Comment by jescampos** [comment]
Hi, of course: https://filebin.ca/4WdWSygj57hr/gestao_hst.zip

**Comment by jescampos** [comment]
@ravibpatel  I'm doing something wrong?

**Comment by ravibpatel** [comment]
@jescampos Hi, I didn't get the time to look at the issue. Any Zip related problems take time as I am using [ZipStorer](https://github.com/jaime-olivares/zipstorer) class to extract zip files. I'm thinking of moving to ZipArchive class provided by the framework in the future to avoid such problems.

**Comment by jescampos** [comment]
If you need help, just ask.
