### ISSUE TITLE
Store on server who updated?

### ISSUE THREAD

**Issue by AAN3AC** [ravibpatel/AutoUpdater.NET#236]
I am just wondering if my DotNet application can pass a string identifying the user's computer to AutoUpdater.NET (I can get the unique windows ID from the registry), and then on the server computer it adds a line to a text file so I can see which users have updated the software? 

The string provided by my Application will probably be the Date and the Windows Unique ID.

Later I would manually look at the text file to see who has updated.  I'd figure out who has not updated in a long while, and is using a really old version of my application, and maybe manually send those users an email reminder.

BTW, your AutoUpdater.NET works great.
This is just an idea.

**Comment by ravibpatel** [comment]
@AAN3AC Although your idea is great. Most devs won't use it and you can already implement your custom logic through events.
