### ISSUE TITLE
OpenDownloadPage=false does not working.

### ISSUE THREAD

**Issue by mertbekci** [ravibpatel/AutoUpdater.NET#237]
if "UpdateMode" is "Mode.ForcedDownload" "OpenDownloadPage = false;" the parameter does not work.

**Comment by ravibpatel** [comment]
It is intended behavior. If you want to force updates then it doesn't make sense to set OpenDownloadPage to true.

**Comment by mertbekci** [comment]
i dont want to show download form. How can i do it?

**Comment by ravibpatel** [comment]
You can handle update manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).

**Comment by mertbekci** [comment]
I don't want to see the screen in the picture
![image](https://user-images.githubusercontent.com/43381707/53096935-53604b00-3531-11e9-99e5-af17bfe38495.png)

**Comment by ravibpatel** [comment]
You can remove the following line and add your own code to handle the download.

```csharp
if (AutoUpdater.DownloadUpdate())
{
    Application.Exit();
}
```

**Comment by mertbekci** [comment]
how do I update when I delete lines?

**Comment by ravibpatel** [comment]
@mertbekci You need to handle the download using WebClient.

**Comment by mertbekci** [comment]
I think it must be parametric, thanks.
