### ISSUE TITLE
How can i use this if my webhost requires a web browser to see files?

### ISSUE THREAD

**Issue by SirDragonKnight** [ravibpatel/AutoUpdater.NET#239]
Hi there

I can get the program to work if I use local files
but if I host the files on my hosting site, it does not work and I believe this is because the hosting site requires a web browse to properly view/use the files.

is there a workaround for this?

**Comment by ravibpatel** [comment]
@SirDragonKnight You will need a server that can allow direct access to URL. If you are using Basic Authentication then you can provide credentials for that.

**Comment by SirDragonKnight** [comment]
Yeah i found a different Host site and it works very nicely. I still wonder how we can bypass that type of check though. The site that gave me trouble was www.epizy.com if you want to check it out. I was just using the free side of it which is where they limited it to browser only.

**Comment by ravibpatel** [comment]
@SirDragonKnight You can modify the code and try to add UserAgent to web request to see if it works.

**Comment by ravibpatel** [comment]
It is possible to set User Agent now as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-user-agent-for-http-web-requests).
