### ISSUE TITLE
Download crashes, 

### ISSUE THREAD

**Issue by datelligence** [ravibpatel/AutoUpdater.NET#24]
Hi Ravi,  after correctly configuring according to your documentation,  when user clicks to update my app,  The download progress bar appears to be downloading but at 75% it crashes the app.

What can be done or how can I fix what is wrondone in my code.  
I've already set method ReportErrors as true.  .NET framework ver 4.5.2.

Thanks,

**Comment by ravibpatel** [comment]
@datelligence Can you provide me with the URL of your XML file?

**Comment by datelligence** [comment]
Ok thanks Ravi,  https://www.datelligent.com/apps/psv/dsk/upd/psvDskSaManifest.xml

**Comment by ravibpatel** [comment]
@datelligence  File downloads completely fine for me without any crashes.

**Comment by datelligence** [comment]
Hi Ravi,  after 2 weeks working on other project,  I return.  The fact is that when autoupdater progress bar is about 75% it always crashes.  The event register gives me the info on the screen I attach. 
![screenshot from 2017-07-23 19-18-45](https://user-images.githubusercontent.com/8643845/28504427-838c4b60-6fdc-11e7-9708-4a10c1eba8d0.png)

**Comment by ravibpatel** [comment]
There is no mention of AutoUpdater.NET code in a stack trace. Also, AutoUpdater code is running without it, You can't reach the download dialog. So it seems that assembly .NET version is correct too. Can you try following solutions?

[https://stackoverflow.com/questions/26672062/wpf-application-crashed-with-xamlparseexception-and-system-io-filenotfoundexcept](https://stackoverflow.com/questions/26672062/wpf-application-crashed-with-xamlparseexception-and-system-io-filenotfoundexcept)

[https://stackoverflow.com/questions/22774135/how-to-resolve-this-system-io-filenotfoundexception](https://stackoverflow.com/questions/22774135/how-to-resolve-this-system-io-filenotfoundexception)

[https://stackoverflow.com/questions/42707672/after-fresh-install-of-visual-studio-2017-project-throws-system-io-filenotfound](
https://stackoverflow.com/questions/42707672/after-fresh-install-of-visual-studio-2017-project-throws-system-io-filenotfound)

**Comment by datelligence** [comment]
Thanks Ravi,  however,  when blocking the executiion of AutoUpdater.NET,  the app does not crashes.  So I agree that AutoUpdater.NET is working fine and the crash is caused by a missing dependency on my app,  I know this dependecy is related to AutoUpdater,NET,  which I' love to know what is.

**Comment by ravibpatel** [comment]
AutoUpdate.NET doesn't use any third party libraries except ZipStorer class which is not referenced but directly integrated into the project. Can you try downloading the latest version of the library from release section and try referencing the AutoUpdater.NET.dll for older .NET version.

[https://github.com/ravibpatel/AutoUpdater.NET/releases](https://github.com/ravibpatel/AutoUpdater.NET/releases)
