### ISSUE TITLE
Unable to change target framework

### ISSUE THREAD

**Issue by mansoorulhaq324** [ravibpatel/AutoUpdater.NET#240]
Hi Ravi,

I downloaded this source code and trying to change target framework from 2.0 to 4.5.1. But it is not allwoing to change me framework. When I am changing framework then it is asking to restart and after restart it always reverts back to 2.0.

**Comment by ravibpatel** [comment]
You may have to change the framework version directly by editing .csproj file as I defined different framework for each build types.

https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.NET.csproj#L41

**Comment by mansoorulhaq324** [comment]
Now I am able to change framework but now getting this error.

![capture](https://user-images.githubusercontent.com/42800922/53548021-558a6100-3b52-11e9-8eba-50efd9f2ce7f.PNG)

**Comment by ravibpatel** [comment]
You have to restore NuGet packages.

**Comment by mansoorulhaq324** [comment]
I tried to restore nugget package. even i reinstalled that package but nothing is working. I have published my project on github. Can you please review my code from here:
"https://github.com/mansoorulhaq324/AutoUpdater.NET.git"

I will be thankful.

**Comment by chao1986** [comment]
same Q
