### ISSUE TITLE
System.NotSupportedException: The requested security protocol is not supported

### ISSUE THREAD

**Issue by oleg-varlamov** [ravibpatel/AutoUpdater.NET#241]
When I run current version (build from master branch) I have following exception:

System.NotSupportedException: The requested security protocol is not supported.
   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at AutoUpdaterDotNET.AutoUpdater.Start(String appCast, Assembly myAssembly)

**Comment by DjordjeMandic** [comment]
Try adding `ServicePointManager.SecurityProtocol = (SecurityProtocolType)48 | (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;` somewhere in `Program.cs` **before** creation of the Form and also **before** using `AutoUpdaterDotNET`.

Note: `ServicePointManager.SecurityProtocol` setter seems to use configuration part of the program so if your configuration(user.config and/or app.config) is broken then this will throw `System.Configuration.ConfigurationErrorsException`

**Comment by oleg-varlamov** [comment]
Thank you!
I will try the solution you proposed. If it helps, I will close the issue.
