### ISSUE TITLE
Is it possible to run a script after update?

### ISSUE THREAD

**Issue by NewITCorp** [ravibpatel/AutoUpdater.NET#246]
Hi, 
I need to run a script after update, it is ngen.exe to precompile my dlls into image as described [here](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-2.0/6t9t5wcf(v=vs.80))

Is it possible to attach a script after update is completed?

thanks

**Comment by ravibpatel** [comment]
You need to use installer as update file for that.

**Comment by NewITCorp** [comment]
ok, thanks
