### ISSUE TITLE
Not working with TLS 1.2 Download Source .Net 4.0

### ISSUE THREAD

**Issue by bluebits88** [ravibpatel/AutoUpdater.NET#25]
Hello,

your Package seems currently not be able to connect to a HTTPS TLS 1.2 Source when used in .Net Framework 4.0.

I had to include the following lines of code to make it work:

       public const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
        public const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;
ServicePointManager.SecurityProtocol = Tls12;

I don't think i can place this code outside of DLL into my main Application, can I?

**Comment by ravibpatel** [comment]
@bluebits88 UI of the AutoUpdater.NET runs on another thread. If ServicePointManager.SecurityProtocol persists across threads it should work. The only way to know is by trying it.

**Comment by TechnikEmpire** [comment]
`// Enforce good/proper protocols
            ServicePointManager.SecurityProtocol = (ServicePointManager.SecurityProtocol & ~SecurityProtocolType.Ssl3) | (SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12);`

**Comment by jenokizm** [comment]
I have a website on https letsencrypt and everything works
