### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by anaether** [ravibpatel/AutoUpdater.NET#254]
Hey, 
Can your lib also be used under .net core?

**Comment by ravibpatel** [comment]
You can see v2.0 branch it contains code for .NET standard. But it is currently in works and it will take time.

**Comment by cdesch** [comment]
Anything we can do to help? Looking to get a version for .Net Core 3.1

**Comment by ravibpatel** [comment]
@cdesch I may need help with testing. I am also planning to separate the .NET Standard repo from this repo. Recently committed the ZipExtractor for .NET Core to the v2.0 branch.

**Comment by cdesch** [comment]
This [one](https://github.com/ravibpatel/AutoUpdater.NET/tree/v2.0/AutoUpdater.NETStandard)?

Do you want test cases for it?

**Comment by ravibpatel** [comment]
@cdesch Yes, That one. You can find example implementation of it from [here](https://github.com/ravibpatel/AutoUpdater.NET/tree/v2.0/AutoUpdater.NET.WPF). Also if you can do unit tests for [ZipExtractor.NETCore](https://github.com/ravibpatel/AutoUpdater.NET/tree/v2.0/ZipExtractor.NETCore) it will help.

**Comment by ravibpatel** [comment]
Added support for .NET Core 3.1 and .NET 5.0 in latest version.
