### ISSUE TITLE
zipextractor.log file write deny for normal users (v.1.5.1)

### ISSUE THREAD

**Issue by Gregorusp** [ravibpatel/AutoUpdater.NET#255]
Hi!

There is an issue when normal windows user runs application and it tries to update. It says " Exception. Access to path c:\windows\system32\zipextractor.log is denied". Can You change the folder for saving ZIPExtractor log file or make the parameter for it?
Thanks,
Greg

**Comment by ravibpatel** [comment]
It is weird that it is righting the log file to the system32 folder. DId you have DownloadPath set? If you didn't set it then it should write it in a temporary folder.

**Comment by dendism** [comment]
Hi!
i have the same issue. I don't have AutoUpdater.DownloadPath set to any path, but sometimes i get exactly the same exception and i wonder, why it tries to write to system32 folder.

**Comment by ravibpatel** [comment]
As you can see from code [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L163) it creates the log file in current dir where ZipExtractor resides. It is temp folder if you don't set the DownloadPath.

**Comment by ravibpatel** [comment]
Can you try the updated version from [here](https://ci.appveyor.com/api/buildjobs/mpj2tkxwag16uhnr/artifacts/AutoUpdater.NET-1.5.3.zip)? It should fix the issue.
