### ISSUE TITLE
Browser warning (GitHub no longer supports Internet Explorer)

### ISSUE THREAD

**Issue by SuperJMN** [ravibpatel/AutoUpdater.NET#257]
Hello! First of all, this library is golden and I love it. But I found a very annoying problem that makes my updates look totally unprofessional.

![image](https://user-images.githubusercontent.com/3109851/55884289-1bc46580-5ba8-11e9-86db-a562d084722b.png)

Moreover, the Spanish localization makes the "Remind me later" text wrap and clip inside the buttons.

I hope you could fix that soon.  

Thank you!

**Comment by DjordjeMandic** [comment]
#212
