### ISSUE TITLE
%path% used in AppCast is not working as expected

### ISSUE THREAD

**Issue by kegunathilaka** [ravibpatel/AutoUpdater.NET#259]
%path% string is not getting replaced properly by the DownloadUpdateDialog as expected. Even though following lines set the ProcessStartInfo.Arguments replacing the %path% correctly,

https://github.com/ravibpatel/AutoUpdater.NET/blob/43369a123b547bbc421dca3b1055e3f569d7efce/AutoUpdater.NET/DownloadUpdateDialog.cs#L166-L167

with a msi installer ProcessStartInfo.Arguments property is again set with unmodified %path% string in following line https://github.com/ravibpatel/AutoUpdater.NET/blob/43369a123b547bbc421dca3b1055e3f569d7efce/AutoUpdater.NET/DownloadUpdateDialog.cs#L217

**Comment by ravibpatel** [comment]
Thanks for pointing it out. I will fix it asap.
