### ISSUE TITLE
When update is NOT mandatory, CheckForUpdateEvent is not triggerred

### ISSUE THREAD

**Issue by AAN3AC** [ravibpatel/AutoUpdater.NET#262]
This is my XML file:
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>1.0.0.32</version>
    <url>http://www.howardz.com/Apps/TheModemsetup.exe</url>
    <args>/VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL /CLOSEAPPLICATIONS /FORCECLOSEAPPLICATIONS</args>
    <changelog>http://www.howardz.com/Apps/TheModemChangeLog.html</changelog>
    <mandatory>true</mandatory>
</item>

In my C# code
AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;

If I change the XML file to mandatory false, then
Global.Update.autoupdater(); 
then the event is never called.

So, in my configuration, I can not use mandatory False.
Is this correct operation?

**Comment by ravibpatel** [comment]
If you used Remind Later or Skip option before subscribing to the event then this can happen.

**Comment by oleg-varlamov** [comment]
> If you used Remind Later or Skip option before subscribing to the event then this can happen.

It might be convenient to add the ability to force an update request. For example, now I have several organizations that have an auto-update application installed. Regular users when there is a dialogue about the availability of an update choose to skip the update or postpone for several days. At the same time, when the system administrator comes and wants to update the application, the update dialog no longer appears. 

I would like to be able to force the update check without taking into account the values ​​stored in the registry.

**Comment by ravibpatel** [comment]
You can add a button and force the update via setting Mandatory to true from code as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#ignore-previous-remind-later-or-skip-settings).

**Comment by oleg-varlamov** [comment]
> You can add a button and force the update via setting Mandatory to true from code as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#ignore-previous-remind-later-or-skip-settings).

Thank! This option suits me!
