### ISSUE TITLE
What is JSON content equivalent for <mandatory mode="2">true</mandatory> in XML file ?

### ISSUE THREAD

**Issue by thelemontree10** [ravibpatel/AutoUpdater.NET#265]
Dear ravibpatel,

What is JSON content for < mandatory mode="2" >true < /mandatory > in XML file ?

Thank you a lot.

Best Regards,

**Comment by DjordjeMandic** [comment]
Take a look at: https://github.com/DjordjeMandic/LeagueFPSBoost/blob/master/AutoUpdater/updater.json
https://github.com/DjordjeMandic/LeagueFPSBoost/blob/master/LeagueFPSBoostGUI/Updater/UpdaterData.cs

You have to implement it yourself.

**Comment by thelemontree10** [comment]
I see no where in your link mentioning about the "mode=2"...

**Comment by ravibpatel** [comment]
You can format the JSON anyway you like. You just need to handle the parsing logic as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-parsing-logic-manually).
