### ISSUE TITLE
Windows 10 App Whitelisting

### ISSUE THREAD

**Issue by zabeloliver** [ravibpatel/AutoUpdater.NET#266]
Hi, we use application whitelisting. My App is Signed with my trusted developer key -  but what about the ZipExtractor? Has anyone experience with that kind of setup? Do i need to sign the .dll as well?
Thanks and best thanks for the great package! 👍

**Comment by ravibpatel** [comment]
If you have the trusted developer key then you should sign ZipExtractor too. I don't think you need to sign the .dll with your dev key if you are signing your app with it but ZipExtractor is a separate app so you should sign it.

**Comment by zabeloliver** [comment]
Hi, thanks! I'll sign the ZipExtractor as well and i'll report results here, in case anyone needs this information in future :)

**Comment by zabeloliver** [comment]
Hi, 
i tried it and the whitelisting throws an error if the ZipExtractor is not signed. I cloned the project, removed the build dependency between Lib and ZipExtractor and signed the .exe after it was build. Then i build the .dll and added it to my project. Now, i can updated my App on all whitelisted computers. :)

Thanks for your great project!
