### ISSUE TITLE
Service cannot be started

### ISSUE THREAD

**Issue by boburan** [ravibpatel/AutoUpdater.NET#267]
Hi, after succesful update ( via ZIP file) , service won't start itself and throws an error Event :

Service cannot be started. The service process could not connect to the service controller

nothing more.
It's run with:
AutoUpdates.AutoUpdates.IsWinService = true;
AutoUpdates.AutoUpdates.RunUpdateAsAdmin = true;     
thank you

**Comment by ravibpatel** [comment]
Look like an issue with your updated version rather than AutoUpdater.NET or your update installer or zip file is missing some referenced libraries.
