### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by engle2192** [ravibpatel/AutoUpdater.NET#268]
So I'm trying to test out this project but I'm running into some issues. I added AutoUpdater.Net to my winforms solution via the nuget package manager. added the `using AutoUpdaterDotNET;` and`AutoUpdater.Start("Path to XML");` to my form. Created the XML and placed it on my server share along with the msi installer for my project. Referenced the msi file in the URL portion of the XML(tried 2 diff formats `file://Servername/share/setup.msi` and `\\Servername\share\setup.msi` )

Where I'm running into issues is when the "A new version of is available!" form loads. After I click the update button I get the below error. Any help would be great!

Thanks in advance.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoUpdaterDotNET.DownloadUpdateDialog.DownloadUpdateDialogLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AutoUpdate
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Program%20Files/Test/AutoUpdateInstall/AutoUpdate.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.5.2.0
    Win32 Version: 1.5.2.0
    CodeBase: file:///C:/Program%20Files/Test/AutoUpdateInstall/AutoUpdater.NET.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by gchen001** [comment]
Exact same problem with yours. 

I'm waiting for the solution -_-

**Comment by ysildur** [comment]
Running to the same issue with version 1.5.2
I reverted back to version 1.5.1

**Comment by ravibpatel** [comment]
Are you guys using local download file URL?

**Comment by ravibpatel** [comment]
I fixed the issue in the latest version. You can download it from [here](https://ci.appveyor.com/api/buildjobs/j4i7arbvveoh4afu/artifacts/AutoUpdater.NET-1.5.3.zip). Can you check it out?

**Comment by gchen001** [comment]
> Are you guys using local download file URL?

Yes, url address in the local network. It worked when I came back to version 1.5.1 @ysldur

**Comment by ravibpatel** [comment]
@gchen001 Can you check out new version from [here](https://ci.appveyor.com/api/buildjobs/j4i7arbvveoh4afu/artifacts/AutoUpdater.NET-1.5.3.zip)? If it works fine I can release the NuGet package.

**Comment by engle2192** [comment]
@ravibpatel I can confirm that that fixes the issue! Thank you!

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.5.3 including the fix.

**Comment by gchen001** [comment]
@ravibpatel  Yes, I checked the dll you released just now, it could also work for my case.

**Comment by ysildur** [comment]
@ravibpatel I confirm that version 1.5.3 is working! Thanks for the quick action!
