### ISSUE TITLE
ZipExtractor doesn't load

### ISSUE THREAD

**Issue by Hendrik-Koelbel** [ravibpatel/AutoUpdater.NET#271]
The ZipExtrator does not load and this error message appears again and again.
Is it not possible to delete the ZipExtrator and the downloaded file after the update?

![Anmerkung 2019-06-07 140438](https://user-images.githubusercontent.com/31684940/59102719-378c8380-892d-11e9-916d-df9afa936f78.jpg)

![log](https://user-images.githubusercontent.com/31684940/59102896-b4b7f880-892d-11e9-9c61-c4b37b9257fa.jpg)

**Comment by ravibpatel** [comment]
Which application are you using to Zip the files?

**Comment by Hendrik-Koelbel** [comment]
Right click with the mouse on the exe and then -> "send to" -> compresses (zipped) folder
Can this happen because I use "Fody" to embed all .dll's into the .exe?

**Comment by ravibpatel** [comment]
Can you try zipping with application like 7Zip or WinRAR? It shouldn't matter if you are embedding it with Fody cause log file shows ZipExtractor is working but it just can't uncompress the Zip file.

**Comment by Hendrik-Koelbel** [comment]
I tried and it worked with WinRAR.
Would you give me permission to take some code snippets to develop my own version or improve it? 
Best Regards:)

**Comment by ravibpatel** [comment]
@Hendrik-Koelbel AutoUpdater.NET uses MIT license so you can modify as you see fit. There is no restriction.

**Comment by Hendrik-Koelbel** [comment]
Hey Ravi,

Could you possibly implement the CefSharp WebBrowser in the AutoUpdater? GitHub doesn't support Internet Explorer anymore but you will get an error message when you want to show GitHub releases.

Best Regards
Henni :)

**Comment by ravibpatel** [comment]
@Hendrik-Koelbel In 2.0 I will add CefSharp or [edge webbroswer control](https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/).
