### ISSUE TITLE
Include picture of the dialogs

### ISSUE THREAD

**Issue by haavamoa** [ravibpatel/AutoUpdater.NET#272]
Hi, this package looks awesome! Nice work, I will try it out!

You mention a dialog in the readme. Could you include a picture of a gif of what we can expect?

**Comment by ravibpatel** [comment]
Hi, You can see dialogs from the following link.

[https://archive.codeplex.com/?p=autoupdaterdotnet](https://archive.codeplex.com/?p=autoupdaterdotnet)
