### ISSUE TITLE
TryToFindFileName leaves semi-colon in fileName

### ISSUE THREAD

**Issue by ZantacPrime** [ravibpatel/AutoUpdater.NET#274]
I am attempting to run AutoUpdater.NET with a zip file downloaded from a TeamCity install (v. 2017.1.4). The content-disposition header has this value: `attachment; filename*=UTF-8''config_dev.zip;`. When `TryToFindFileName` is run, the returning value is `config_dev.zip;`, which causes Path.GetExtension to return `.zip;`. This results in the zip extension check to return false, skipping over the zip extraction. This ultimately results in a Win32Exception (No application is associated with the specified file for this operation). 

I added a line to strip out the semi-colon so I could work around this issue, but I'm sure there's a better solution.

**Comment by ravibpatel** [comment]
@ZantacPrime Can you change the content disposition header format from the server? This looks like an invalid content disposition header string. That semicolon shouldn't be there.
