### ISSUE TITLE
System gives exception while Cancel the Downloading how to manage

### ISSUE THREAD

**Issue by mfansari82** [ravibpatel/AutoUpdater.NET#275]
System gives exception while Cancel the Downloading manually.
How to manage exception ?
Please help me for this.

**Comment by ravibpatel** [comment]
Can you post the screenshot of exception dialog or stack trace?

**Comment by mfansari82** [comment]
> Can you post the screenshot of exception dialog or stack trace?

ok, here i attached the link of exception i got,
https://www.screencast.com/t/DRbRHEt0LVq9

**Comment by mfansari82** [comment]
at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)

i got above exception in stack trace

**Comment by ravibpatel** [comment]
Do you get exception dialog when it crashes?
