### ISSUE TITLE
Download never starts after clicking Update when HTTPS protocol is used.

### ISSUE THREAD

**Issue by viveksinghnegi7** [ravibpatel/AutoUpdater.NET#278]
I am downloading the update from the server with secure HTTP or HTTPS (to be able to use TLS 1.2). I guess AutoUpdater.NET doesn't support this yet. I would like to request this feature as everyone is moving towards TLS 1.2 now.

**Comment by viveksinghnegi7** [comment]
I get he following error.
There is a problem reaching update server. Please check your internet connection and try again.

**Comment by viveksinghnegi7** [comment]
the underlying connection was closed could not establish trust relationship for the ssl/tls channel

**Comment by ravibpatel** [comment]
AutoUpdater.NET does use TLS 1.2 when it is available. You can check out the code [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L241). Error you are experiencing can happen if your Server is not using an unknown SSL certificate. You can bypass it using the code shown [here](https://stackoverflow.com/a/6613434/1273550).

**Comment by viveksinghnegi7** [comment]
Thank you @ravibpatel. I will close this issue.
