### ISSUE TITLE
Extract .zip file have some trouble.

### ISSUE THREAD

**Issue by zzl4883a** [ravibpatel/AutoUpdater.NET#280]
I use the WinRAR to compress file.  
Chinese .exe file will generate gibberish when I update the software.

**Comment by zzl4883a** [comment]
I solved my problem yesterday,I used another decompression tool called "好压" to compress file.

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1. It may fix your issue if you are using .net 4.5 or above.
