### ISSUE TITLE
Only show the update form when the tool form loads

### ISSUE THREAD

**Issue by ktownmods** [ravibpatel/AutoUpdater.NET#29]
hey is there a way t o load autoupdater from Form_Load without the regular form from the c# project?

i mean when i start my priojekt the regular form comes and the autoupdater form is behind them you know?

sry for my bad english

**Comment by ravibpatel** [comment]
You can call Start method in Form_Shown method. That way it should be on top of the main form. Make sure your main form's Top Most property is false.

**Comment by ktownmods** [comment]
u add the start option in Form_Shown and make the main form top most to false but the mainform is still on the top and the updateform in the back

**Comment by ktownmods** [comment]
btw is there an way that when an update available that the update form only there without the mainform and when no update available the main form opens?

**Comment by ravibpatel** [comment]
You can do it by handling the update logic yourself. Like shown in the following documentation.

[Handling Updates Manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually)

**Comment by ktownmods** [comment]
Closed

**Comment by ktownmods** [comment]
this work but only with that 
![screenshot_76](https://user-images.githubusercontent.com/17227224/29753523-b1d8282e-8b73-11e7-84c7-155cad8d9788.png)
but i will that 
![screenshot_77](https://user-images.githubusercontent.com/17227224/29753544-f1ebae86-8b73-11e7-854a-e7591c21051f.png)

with the changelog

**Comment by ravibpatel** [comment]
@ktownmods You can make the update form yourself with the change log and show it when args.IsUpdateAvailable is true. You can use args.ChangelogURL to get the changelog URL.
