### ISSUE TITLE
Keep user's settings after updating

### ISSUE THREAD

**Issue by Ares-87** [ravibpatel/AutoUpdater.NET#291]
Hello, 
at every update, my application lose the saved settings, how I keep user.config's settings after updating?
And is possible update also if I have renamed the file.exe? The updater enter in loop mode.
Thank you

**Comment by ravibpatel** [comment]
Do you include user.config in the update zip file? If yes, then it will overwrite the file on the user's PC. 

No, If you are using ZIP file then it is necessary to keep the same filename otherwise it won't work. You can create an installer for an update if you like to change the exe name.

**Comment by dannythegreat** [comment]
I don't include user.config in the zip.

**Comment by ravibpatel** [comment]
You may need to upgrade it as suggested in [this](https://stackoverflow.com/a/534335/1273550) answer.

**Comment by AshotN** [comment]
Would it be possible to integrate that into the package?

**Comment by ravibpatel** [comment]
@AshotN It will be better to call it when your application starts.
