### ISSUE TITLE
CheckForUpdateEvent not fired

### ISSUE THREAD

**Issue by NeilMJohnson** [ravibpatel/AutoUpdater.NET#292]
Hi, my application uses AutoUpdater in two ways - one is a check for an update when the application starts, and the second is when the user chooses CheckForUpdates from a menu.  The first method seems to work fine when there is a new version.  The second method does not fire the event when there is not a new version or the ''currentVersion' is less than the current application version.  When checking the code, I suspect the following line needs this change:
               using (RegistryKey updateKey = Registry.CurrentUser.OpenSubKey(RegistryLocation))
                {
                    if (updateKey != null)
                    {
                        object skip = updateKey.GetValue("skip");
                        object applicationVersion = updateKey.GetValue("version");
                        if (skip != null && applicationVersion != null)
                        {
                            string skipValue = skip.ToString();
                            var skipVersion = new Version(applicationVersion.ToString());
                            if (skipValue.Equals("1") && CurrentVersion <= skipVersion) **{
                                 e.Cancel = false;
                                return;
                             }**

Otherwise the BackgroundWorkerOnRunWorkerCompleted event simply checks for cancel and exits before firing the event.  I am not sure what skip is actually doing at this point or if it is something I need to set?

**Comment by ravibpatel** [comment]
You should set Mandatory to true for a menu option as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#ignore-previous-remind-later-or-skip-settings). This way if the user previously skipped the update it will still show the dialog.

**Comment by NeilMJohnson** [comment]
Hi Ravi, I am not trying to force a mandatory update.  I have provided a menu option that allows the user to manually check for updates.  The problem is, if there is no new update, I need the Event to fire so that I can display the notification that there are no new updates to the user.  And the event does not fire if the web xml file shows a version that is less than or equal to the users installed version.  And that is because that check does not reset the Cancelled flag, so the post-processing code simply exits without firing the event.

 

BTW, I think your coding of this functionality is brilliant.  I had looked at writing this myself and felt that your implementation was better than anything I could come up with quickly. Very well thought-out.

 

Neil

**Comment by ravibpatel** [comment]
You can check this line [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L288). If you are hooked to the event it won't matter if an update is available or not it will fire unless if user skipped the update in the past or set it to remind later in standard dialog. That's why you need to use Mandatory flag to true so it can fire the event and ignore any remind later or skip settings previously set by the user.

**Comment by NeilMJohnson** [comment]
Hi Ravi, thanks for the quick response.  Please see the code below.  I have hooked to the event and it does not fire if the installed application version is greater than or equal to the web version.  If this is being run from the menu, the registerUpdateEvent flag gets set when this is called. The AutoUpdaterCheckForUpdateEvent never gets called.  The method is called the first time when the application starts and I don’t show any messages to the user unless the code detects a newer version.  In this case your code works great.  However, when the user wants to check for an update, I want to display a message indicating that there is nothing newer I expect for the event handler to be called and drop down to the last line to let the user know there is nothing newer.

 

As you can see, the event code is basically your C# code translated to VB.

 

Neil

 

 

    Private Sub CheckForUpdate(registerUpdateevent As Boolean)

        Try

            Dim updateEnbled As Boolean = ApplicationValuesManager.GetValue(Of Boolean)("UpdateCheckEnabled")

            If updateEnbled Then

                Dim updateUrlPath As String = ApplicationValuesManager.GetValue(Of String)("UpdateInfoPath")

                My.Application.Log.WriteEntry("Checking for Updates at " & updateUrlPath)

                If registerUpdateevent Then

                    AddHandler AutoUpdater.CheckForUpdateEvent, AddressOf AutoUpdaterCheckForUpdateEvent

                    AutoUpdater.ReportErrors = True

                End If

                If Me.InvokeRequired Then

                    Me.BeginInvoke(Sub()

                                       AutoUpdater.Start(updateUrlPath)

                                   End Sub)

                Else

                    AutoUpdater.Start(updateUrlPath)

                End If

            End If

        Catch ex As Exception

            WriteDetailedExceptionInfo("mdiFormMain", "CheckForUpdates", ex)

        End Try

    End Sub

    Private Sub AutoUpdaterCheckForUpdateEvent(args As UpdateInfoEventArgs)

        If Me.InvokeRequired Then

            Me.BeginInvoke(Sub() AutoUpdaterCheckForUpdateEvent(args))

            Return

        End If

        Me.Cursor = Cursors.Default

        Dim rslt As DialogResult

        If args Is Nothing Then

            MessageBox.Show(Me, "Unable to check for updates at this time - the update directory or website may be unavailable.", MsgBoxStyle.Exclamation, "Update Check Failed")

        Else

            If args.IsUpdateAvailable Then

                If args.Mandatory Then

                    rslt = MessageBox.Show(Me, String.Format("There is a new version {0} available, you are using version {1}. " & vbCrLf & _

                                                             "This is a required update. Press Ok to begin updating the application.", _

                                           args.CurrentVersion, args.InstalledVersion), MsgBoxStyle.OkOnly, "Update Available")

                Else

                    rslt = MessageBox.Show(Me, String.Format("There is a new version {0} available, you are using version {1}. " & vbCrLf & _

                                                             "Do you want to update the application now?", _

                                           args.CurrentVersion, args.InstalledVersion), MsgBoxStyle.YesNo, "Update Available")

                End If

                If rslt = Windows.Forms.DialogResult.OK OrElse rslt = Windows.Forms.DialogResult.Yes Then

                    Try

                        Me.Cursor = Cursors.WaitCursor

                        If AutoUpdater.DownloadUpdate Then

                            Application.Exit()

                        End If

                    Catch ex As Exception

                        DisplayErrorMessage(Me.Text, "AutoUpdaterCheckForUpdateEvent", ex)

                    Finally

                        Me.Cursor = Cursors.Default

                    End Try

                End If

            Else

                DisplayMessageBox(String.Format("You are running the most current version: ", args.CurrentVersion), MsgBoxStyle.Information, "No Update Available")

            End If

        End If

    End Sub

**Comment by ravibpatel** [comment]
I tried it in the test app and it works completely fine for me even if there is no update available event fired.

**Comment by NeilMJohnson** [comment]
Hi Ravi, could you try setting the version number in the xml file to be less than the version installed?  That is what is happening in my case, and when I step through the code it drops out at the point indicated with the e.Cancel event still set to true.  When the BackgroundWorkerOnRunWorkerCompleted runs the first thing it does is check for the cancelled flag.
 
            if (!runWorkerCompletedEventArgs.Cancelled)
 
At the point I indicated in the BackgroundWorker code, it exits and the flag is still set to true.  This means the event does not fire as the BackgroundWorkerOnRunWorkerCompleted code simply skips everything.
 
                           if (skipValue.Equals("1") && CurrentVersion <= skipVersion)
                                return;
 
When this return happens – e.Cancel is still set to true. I am not sure what the skip value is for, but it is set to “1”  for my application. So it simply exits.
 
I have downloaded the latest NuGet version prior to doing this as well as the most recent GIT version.
 
Neil

**Comment by ravibpatel** [comment]
I tried setting the version to lower than the current one but It still worked. The line where it stops indicates that you used skip button in the past and it set skipValue to 1 and skipVersion to the version you have in XML. That's why you need to set Mandatory to true it is designed for this kind of situation.

**Comment by NeilMJohnson** [comment]
Hi Ravi, I did set the Mandatory to true as you suggested and the event now fires.  The one problem now, is that if the actual new release is discretionary, setting this flag now forces it to be a mandatory update which the user now has to install whether they want to or not.  I would like it to have the same behaviour as the startup check – if the release is optional, the user should be able to defer it or choose to install it.

 

Could we have a flag that says ignore the skip flag, but then use the xml file to determine if the release is optional or mandatory?

 

Thanks, Neil

**Comment by ravibpatel** [comment]
You can achieve the behavior you want by setting the mandatory flag to true when registerUpdateevent is true. So if you use the following code right before the  `If registerUpdateevent Then ` statement then it will give you desired behavior. The update won't be mandatory when it is checked on startup but it will be mandatory when executed by a menu option.

````csharp
AutoUpdater.Mandatory = registerUpdateevent
````

**Comment by NeilMJohnson** [comment]
Yes, but the problem is I don’t want it to be mandatory when checked by the menu option.  I just want them to be able to find out if there is a newer update available with out having to install it, unless it really is Mandatory (e.g. as set in the XML file).

 

Neil

**Comment by ravibpatel** [comment]
The mandatory update doesn't mean it will force the user to do the update unless you set UpdatedMode to forced as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#forced-updates). User can still decide to do the update or not. Also in your case, you are doing it using event so it will be completely up to you to force it or not. In the case of a menu option, it is necessary to set Mandatory to true cause the user may have used skip or remind later in the past.
