### ISSUE TITLE
Language resource files appear when using PackageReference

### ISSUE THREAD

**Issue by FisherTsai** [ravibpatel/AutoUpdater.NET#293]
Recently I migrated one of my projects from packages.config to PackageReference (https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference). After migration, I found the language resource files (AutoUpdater.NET.resources.dll) appear in output folder even if the target framework is set to .NET 4.0 or higher version. This should be fixed after commit 279a3add1b9dc4c5209bf264f79a1e9d7b231b06. Does anyone know what's going on?

**Comment by timcoolman** [comment]
I'm having the same problem and would like to get rid of all the extra output. Found a post (unrelated to AutoUpdate.NET) suggesting to add the line below to the project file to prevent unwanted localization resources, but it hasn't made a difference.
<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
@FisherTsai, did you ever find a solution?

**Comment by Fma965** [comment]
+1 to this issue

**Comment by kdm6596** [comment]
+ 1

**Comment by ravibpatel** [comment]
Prior to version 1.9.2 it was using Resource.Embedder to embed the satellite assemblies for .NET Framework, but it breaks the strong name validation. You can use Resource.Embedder directly or remove the satellite assemblies if you don't require additional languages.

If you are using .NET core or above, you can just publish the single file assembly as shown [here](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli), and it will embed all satellite assemblies inside the output.
