### ISSUE TITLE
InstalledVersion provided in ParseUpdateInfoEvent handler is not passed to CheckForUpdateEvent

### ISSUE THREAD

**Issue by grzechj** [ravibpatel/AutoUpdater.NET#295]

**Comment by grzechj** [comment]
Sometimes it is useful to get currently installed version from other place than AssemblyVersion however this value is always overwritten by main executing assembly version.

**Comment by ravibpatel** [comment]
Thanks for the suggestion. Can you tell me a scenario where this can be useful?

**Comment by grzechj** [comment]
E.g. when you have complex software containing multiple binary files by the official versioning scheme is different than assembly/file versioning. In such case you store actual software package version somewhere in you installation folder or registry etc...
