### ISSUE TITLE
First installation

### ISSUE THREAD

**Issue by isatahiri** [ravibpatel/AutoUpdater.NET#300]
Hello,

I just discover AutoUpdater.NET and I would like to know how to manage the first installation. 

Currently, i understant how the updates work, but in the documentation it not clear for me how the first installation is done.

Can you help please ? 

Many thanks 
ISA

**Comment by ravibpatel** [comment]
It will work no matter which type of installer you use. Even if you copy the application files or use zip file to distribute your app, it will still work.

I personally use [NSIS](https://nsis.sourceforge.io/Main_Page) installer. You can use wizard mode of [HM NIS Edit](http://hmne.sourceforge.net/) to create installer easily if you are not familiar with NSIS scripting language. You can also check the .NET version installed on user's PC using [NsisDotNetChecker](NsisDotNetChecker) plugin.
