### ISSUE TITLE
System.IO.FileLoadException: 未能加载文件或程序集“AutoUpdater.NET, Version=1.5.5

### ISSUE THREAD

**Issue by rrzhaobaojun** [ravibpatel/AutoUpdater.NET#301]
System.IO.FileLoadException: 未能加载文件或程序集“AutoUpdater.NET, Version=1.5.5.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。

When the project name is AutoUpdaterTest ,This problem will not arise.
This problem arises when the project name is something else.

**Comment by ravibpatel** [comment]
Are you using a NuGet package?
