### ISSUE TITLE
Using Updated Files Stored in Github

### ISSUE THREAD

**Issue by sharathsridhar** [ravibpatel/AutoUpdater.NET#305]
Hello,

My question is regarding files/c# apps that are pushed to github. I develop new features and push the entire solution to github. I can use Octokit to download the the entire git repo/file to a local directory. In this case how can I use AutoUpdater.Start(), since this accepts only Url's?

Is there another method that points to a local directory and copies and replaces those files dll files from within the app and restarts the app?

**Comment by ravibpatel** [comment]
It is not possible to do it as you described but you can give it a zip file URL of your repo and it should work whenever you update.

**Comment by sharathsridhar** [comment]
Thank You @ravibpatel . I can download the files from Git to a local directory, then is it possible to comapre the xml and replace the exe and dll's from within the app and have it restart using your tool?

**Comment by ravibpatel** [comment]
No, It isn't possible.
