### ISSUE TITLE
Not controled exception "System.Net.WebException: Remote server error: (500) Syntax error, command not recognized."

### ISSUE THREAD

**Issue by rfrieir80** [ravibpatel/AutoUpdater.NET#306]
Hi,

sometimes, caused by problems with ftp server the application have an not controled exception:

System.Net.WebException: Remote server error: (500) Syntax error, command not recognized.
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   en System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   en System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Abort(Exception e)
   en System.Net.CommandStream.CheckContinuePipeline()
   en System.Net.FtpWebRequest.DataStreamClosed(CloseExState closeState)
   en System.Net.FtpDataStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   en System.Net.FtpDataStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.Net.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   en System.Xml.XmlTextReaderImpl.ReadData()
   en System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   en System.Xml.XmlTextReaderImpl.Read()
   en System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   en System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   en System.Xml.XmlDocument.Load(XmlReader reader)
   en System.Xml.XmlDocument.Load(Stream inStream)
   en AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerDoWork(Object sender, DoWorkEventArgs e)
   en System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   en System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

In the AutoUpdater.cs line 534 only catch "XmlException", maybe this cause the not controled exception.

**Comment by ravibpatel** [comment]
I fixed it. You can download the updated library from [here](https://ci.appveyor.com/api/buildjobs/4xhiewejb26pcayj/artifacts/AutoUpdater.NET-1.5.6.zip).

**Comment by rfrieir80** [comment]
Thanks!!

________________________________


[http://firmas.autronic.net/content/firmas-solution30-logo_18012019.jpg]

RICARDO FRIEIRO RODRIGUEZ
INGENIERO DE SOFTWARE
Mobile: +34 698 123 535
Phone: +34 986 467 090

[http://firmas.autronic.net/content/_firmas-solution30-asacert_29032019.png]


________________________________



ESPAÑA

 FRANCIA

 ITALIA

 ALEMANIA

 BENELUX


Le informamos que su dirección de correo electrónico, así como el resto de los datos de carácter personal que nos ha facilitado, serán objeto de tratamiento en nuestros registros de actividades con la finalidad de gestionar el contenido de esta comunicación, así como el de toda la documentación anexa, la agenda de contactos y las relaciones mercantiles con nuestros clientes y proveedores. Usted tiene derecho a obtener confirmación sobre si en VITGO COMUNICACIONES, S.L.U. estamos tratando sus datos personales y por tanto tiene derecho a ejercer sus derechos de acceso, rectificación, limitación del tratamiento, portabilidad, oposición al tratamiento y supresión de sus datos mediante escrito dirigido a la dirección postal VIGO(PONTEVEDRA), C.P. 36315, POLÍGONO PTL VALLADARES CALLE C NAVE A-2 o electrónica solutions30.spain@solutions30.com adjuntado copia del DNI en ambos casos, así como el derecho a presentar una reclamación ante la Autoridad de Control (aepd.es<https://www.aepd.es/>) La información incluida en este correo electrónico es confidencial y va dirigida únicamente al destinatario del mismo. En el supuesto de que usted no fuera el destinatario, le solicitamos que nos lo indique y no comunique su contenido a terceros, procediendo a su destrucción. Le informamos que está totalmente prohibida cualquier utilización, divulgación, distribución y/o reproducción de esta comunicación sin autorización expresa en virtud de la Legislación vigente. Gracias.

Política de calidad<http://firmas.autronic.net/Content/POLÍTICA%20CORPORATIVA%202019_Solutions30%20Vitgo.pdf>
De: Ravi Patel <notifications@github.com>
Enviado el: miércoles, 28 de agosto de 2019 13:09
Para: ravibpatel/AutoUpdater.NET <AutoUpdater.NET@noreply.github.com>
CC: Ricardo Frieiro Rodriguez <ricardo.frieiro@solutions30.com>; Author <author@noreply.github.com>
Asunto: Re: [ravibpatel/AutoUpdater.NET] Not controled exception "System.Net.WebException: Remote server error: (500) Syntax error, command not recognized." (#306)


I fixed it. You can download the updated library from here<https://ci.appveyor.com/api/buildjobs/4xhiewejb26pcayj/artifacts/AutoUpdater.NET-1.5.6.zip>.
