### ISSUE TITLE
Filter the Update receiving client

### ISSUE THREAD

**Issue by AdarshRise** [ravibpatel/AutoUpdater.NET#309]
Can I filter Client with some condition, so that only those who have fulfilled the condition will get a certain update.

**Comment by ravibpatel** [comment]
You can apply the filter by handling it manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).

**Comment by AdarshRise** [comment]
I mean any special parameter { like special updates for some } those who will have this boolean value True will get only those Updates where the this special parameter is true. Otherwise, they will get normal updates.
E.g. { 2 people, a and b ) 
a) 1.1 --> 1.2 --> 1.5(special condition fulfilled) -->1.6(special update)--> 1.7(special update)
b)1.1 --> 1.2 --> 1.5(special condition not fulfilled) -->1.6(regular update)--> 1.7(regular update)

**Comment by AdarshRise** [comment]
I would be having two different updates after (1.5v) and those who have fulfilled the special update requirement will get only special updates, and those who didn't will get my other { regular update}.
The application would still be the same but some difference would be there as per the condition they chose.

**Comment by ravibpatel** [comment]
There is no feature for this but I think you can do this by using 2 different XML files.

**Comment by AdarshRise** [comment]
Yeah, I think that would work, but if you could make it official { like mandatory parameter in 2.0} that would be nice. Closing this issue. Thanks.
