### ISSUE TITLE
ZipExtractor waiting for application exit

### ISSUE THREAD

**Issue by ktownmods** [ravibpatel/AutoUpdater.NET#31]
This doesnt work look at screenshot

![screenshot_73](https://user-images.githubusercontent.com/17227224/29486583-f2266354-84e9-11e7-9209-1c9d5ea5d75a.png)

**Comment by ktownmods** [comment]
That only happens when i use MetroFramework.Forms.MetroForm

**Comment by ravibpatel** [comment]
It means that something is preventing your application from closing. I tried using MetroForm and it works fine for me. If you can post the sample project about the issue it can help me identify the issue.

**Comment by solutionsville** [comment]
I am seeing the same issue. I noted the issue with the AutoUpdaterTest Forms application.

If I use the Button event, it fires correctly and does not error out. Using the options in the Form_Load event if I use any option other than the;;

AutoUpdater.Start("xmlfilelocation");

the AutoUpdaterTest application will not close and then results in an error message that there was a problem in reaching the server.

Digging into the AutoUpdater.dll to see where it occurs.

**Comment by ravibpatel** [comment]
@snnshn96 @solutionsville If you can provide sample application with the problem. It will be more helpful. I am unable to reproduce the issue on my end.

**Comment by solutionsville** [comment]
The Example is YOUR AutoUpdaterTest app in the AutoUpdater.NET-Master download.

Brian S. Cook
BNSF Railway | Consulting Systems Engineering I |
2400 Western Center Blvd, Fort Worth, TX, 76131
tel:8175930495 Office | tel:8176927662 Cellular | email:brian.cook@bnsf.com<sip:brian.cook@bnsf.com> Email
[2015SignatureLine]

**Comment by ravibpatel** [comment]
@solutionsville AutoUpdaterTest app works fine for me. I can't reproduce the issue on my PC.

**Comment by solutionsville** [comment]
Ok, Ravi, 
Steps to reproduce.
Start with a  clean copy of the AutoUpdater.NET-master file.
Open Solution in VS 2017
View Code for FormMain.cs in the AutoUpdaterTest project.
Uncomment lines 51, 55 and 57.
In my case I changed the http location, and then did a Rebuild all.
Select AutoUpdaterTest Startup Project and Click Start.
It prompts you that the program is out of date and asks if you want to update. Select Yes, then the ZipExtractor runs, and you get the Waiting for application to Exit... (See attached picture). The Application does not close nor does the application get updated. If you manually close the application, you never get the AutoUpdater.NET UpdateForm to display and you get the Update Unavailable MessageBox to display (See second picture).

Now, if I recommend Line 51, and 55 it will run correctly. If I set it to run with the timer, as coded, it does not work it gives you an error "a local or parameter named 'sender' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter, which is true because sender is defined in the Form_Load event.

I will make it work and update you in a  bit.
![autoupdatertestcapture](https://user-images.githubusercontent.com/15106217/29612979-7eb9d7f6-87c9-11e7-8c5e-8fd6f877e844.PNG)
![autoupdatertestupdatenotavailablecapture](https://user-images.githubusercontent.com/15106217/29613090-f5a56556-87c9-11e7-948f-a0a5241be838.PNG)

**Comment by ravibpatel** [comment]
@solutionsville Sorry, for not testing thoroughly. You are right there is a problem when developer handles the update logic and uses the DownloadUpdate method provided by AutoUpdater.NET.

Also, timer mistake is there too. I will fix it asap.

**Comment by solutionsville** [comment]
Now, to get the Timer event to work correctly, this is what I did;

``
using AutoUpdaterDotNET;
using AutoUpdaterTest.Properties;
using System;
using System.Reflection;
using System.Timers;
using System.Windows.Forms;

namespace AutoUpdaterTest
{
    public partial class FormMain : Form
    {
        private System.Timers.Timer timer;
        public FormMain()
        {
            timer = new System.Timers.Timer
            {
                AutoReset = true
            };
            timer.Elapsed += new ElapsedEventHandler(timer_Elapsed);
            timer.Interval = 2 * 60 * 1000;
            timer.Enabled = true;
            timer.Start();
            InitializeComponent();
            labelVersion.Text = string.Format(Resources.CurrentVersion, Assembly.GetEntryAssembly().GetName().Version);
        }

        private void FormMain_Load(object sender, EventArgs e)
        {
            //Uncomment below line to see russian version

            //AutoUpdater.CurrentCulture = CultureInfo.CreateSpecificCulture("ru");

            //If you want to open download page when user click on download button uncomment below line.

            //AutoUpdater.OpenDownloadPage = true;

            //Don't want user to select remind later time in AutoUpdater notification window then uncomment 3 lines below so default remind later time will be set to 2 days.

            //AutoUpdater.LetUserSelectRemindLater = false;
            //AutoUpdater.RemindLaterTimeSpan = RemindLaterFormat.Minutes;
            //AutoUpdater.RemindLaterAt = 1;

            //Don't want to show Skip button then uncomment below line.

            //AutoUpdater.ShowSkipButton = false;

            //Don't want to show Remind Later button then uncomment below line.

            //AutoUpdater.ShowRemindLaterButton = false;

            //Want to show custom application title then uncomment below line.

            //AutoUpdater.AppTitle = "My Custom Application Title";

            //Want to show errors then uncomment below line.

            //AutoUpdater.ReportErrors = true;

            //Want to handle update logic yourself then uncomment below line.

            //AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;

            //AutoUpdater.Start("http://nococg-util1.prod.trnctl.bnsf.com/AutoUpdaterTest.xml");

            //Want to check for updates frequently then uncomment following lines.
            //System.Timers.Timer timer = new System.Timers.Timer { Interval = 2 * 60 * 1000 };
            //timer.Elapsed += delegate (object sender, ElapsedEventArgs args)
            //{
            //    AutoUpdater.Start("http://MyHttpLinkAddress/AutoUpdaterTest.xml");
            //};
            //timer.Start();
        }

        private void timer_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
            AutoUpdater.Start("http://MyHttpLinkAddress/AutoUpdaterTest.xml");
            timer.Interval = 1000;
        }

        private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
        {
            if (args != null)
            {
                if (args.IsUpdateAvailable)
                {
                    var dialogResult =
                        MessageBox.Show(
                            $@"There is new version {args.CurrentVersion} available. You are using version {args.InstalledVersion}. Do you want to update the application now?", @"Update Available",
                            MessageBoxButtons.YesNo,
                            MessageBoxIcon.Information);

                    if (dialogResult.Equals(DialogResult.Yes))
                    {
                        try
                        {
                            //You can use Download Update dialog used by AutoUpdater.NET to download the update.

                            AutoUpdater.DownloadUpdate();
                        }
                        catch (Exception exception)
                        {
                            MessageBox.Show(exception.Message, exception.GetType().ToString(), MessageBoxButtons.OK,
                                MessageBoxIcon.Error);
                        }
                    }
                }
                else
                {
                    MessageBox.Show(@"There is no update available. Please try again later.", @"Update Unavailable",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            else
            {
                MessageBox.Show(
                       @"There is a problem reaching update server. Please check your internet connection and try again later.",
                       @"Update Check Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void ButtonCheckForUpdate_Click(object sender, EventArgs e)
        {
            AutoUpdater.Start("http://MyHttpLinkAddress/AutoUpdaterTest.xml");
        }
    }
}


Thanks,

**Comment by solutionsville** [comment]
One correction to the above;

Remove the timer.Interval = from the Form_Load event.

**Comment by solutionsville** [comment]
Additionally, if the user intends to Embed the AutoUpdate.NET.dll into the application, move this code to the Form_Load event. Leaving it in the Form_Main will result in a FileNotFound error when you launch it.

Obviously follow the practice for Embedding a dll as referenced in other articles. I can provide an example if you like.

Thanks,

**Comment by solutionsville** [comment]
Ravi, here is the example of the code if the user wants to embed the AutoUpdate.NET.dll into the AutoUpdateTest.exe or their own application;

``
using AutoUpdaterDotNET;
using AutoUpdaterTest.Properties;
using System;
using System.Reflection;
using System.Resources;
using System.Timers;
using System.Windows.Forms;

namespace AutoUpdaterTest
{
    public partial class FormMain : Form
    {
        private System.Timers.Timer timer;
        public FormMain()
        {
            AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve);
            InitializeComponent();
            labelVersion.Text = string.Format(Resources.CurrentVersion, Assembly.GetEntryAssembly().GetName().Version);
        }

        Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            // This is so you can embed the DLL resouces and not have to include them with the Executable.
            string dllName = args.Name.Contains(",") ? args.Name.Substring(0, args.Name.IndexOf(',')) : args.Name.Replace(".dll", "");
            dllName = dllName.Replace(".", "_");
            if (dllName.EndsWith("_resources")) return null;
            ResourceManager rm = new ResourceManager(GetType().Namespace + ".Properties.Resources", Assembly.GetExecutingAssembly());
            byte[] bytes = (byte[])rm.GetObject(dllName);
            return Assembly.Load(bytes);
        }

        private void FormMain_Load(object sender, EventArgs e)
        {
            timer = new System.Timers.Timer
            {
                AutoReset = true
            };
            timer.Elapsed += new ElapsedEventHandler(Timer_Elapsed);
            //timer.Interval = 2 * 60 * 1000;
            timer.Enabled = true;
            timer.Start();
            //AutoUpdater.CurrentCulture = CultureInfo.CreateSpecificCulture("ru");
            //AutoUpdater.OpenDownloadPage = true;
            //AutoUpdater.LetUserSelectRemindLater = false;
            //AutoUpdater.RemindLaterTimeSpan = RemindLaterFormat.Minutes;
            //AutoUpdater.RemindLaterAt = 1;
            //AutoUpdater.ShowSkipButton = false;
            //AutoUpdater.ShowRemindLaterButton = false;
            //AutoUpdater.AppTitle = "My Custom Application Title";
            //AutoUpdater.ReportErrors = true;
            //AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;
            // If you want the application to check at Startup each time, uncomment next line only.
            //AutoUpdater.Start("http://nococg-util1.prod.trnctl.bnsf.com/AutoUpdaterTest.xml");
            //System.Timers.Timer timer = new System.Timers.Timer { Interval = 2 * 60 * 1000 };
            //timer.Elapsed += delegate (object sender, ElapsedEventArgs args)
            //{
            //    AutoUpdater.Start("http://MyHttpLinkAddress/AutoUpdaterTest.xml");
            //}; clos
            //timer.Start();
        }

        private void Timer_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
            AutoUpdater.Start("http://nococg-util1.prod.trnctl.bnsf.com/AutoUpdaterTest.xml");
            // timer.Interval = 2 * 60 * 1000 is the default value. Set to 1000 for testing purposes.
            timer.Interval = 2 * 60 * 1000;
        }

        private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
        {
            if (args != null)
            {
                if (args.IsUpdateAvailable)
                {
                    var dialogResult =
                        MessageBox.Show(
                            $@"There is new version {args.CurrentVersion} available. You are using version {args.InstalledVersion}. Do you want to update the application now?", @"Update Available",
                            MessageBoxButtons.YesNo,
                            MessageBoxIcon.Information);

                    if (dialogResult.Equals(DialogResult.Yes))
                    {
                        try
                        {
                            //You can use Download Update dialog used by AutoUpdater.NET to download the update.

                            AutoUpdater.DownloadUpdate();
                        }
                        catch (Exception exception)
                        {
                            MessageBox.Show(exception.Message, exception.GetType().ToString(), MessageBoxButtons.OK,
                                MessageBoxIcon.Error);
                        }
                    }
                }
                else
                {
                    MessageBox.Show(@"There is no update available. Please try again later.", @"Update Unavailable",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            else
            {
                MessageBox.Show(
                       @"There is a problem reaching update server. Please check your internet connection and try again later.",
                       @"Update Check Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void ButtonCheckForUpdate_Click(object sender, EventArgs e)
        {
            // This is to manually check to see if the Application has an update
            AutoUpdater.Start("http://MyHttpLinkAddress/AutoUpdaterTest.xml");
        }
    }
}

Thanks,

**Comment by ravibpatel** [comment]
@solutionsville I updated the sample project with fixes. Check it out. There was nothing problematic with AutoUpdater.NET. dll itself. Just the wrong implementation.

**Comment by solutionsville** [comment]
Yes Sir, Agreed. not a problem with the .dll itself.

Great project! Thank you for creating it.

**Comment by solutionsville** [comment]
Looks and works good. Thanks for listening.

**Comment by snnshn96** [comment]
Hi guys I tried the new way up updating and it closes the application but when it opens the updated version it changes the color scheme of the application. Not sure why this is happening.

**Comment by snnshn96** [comment]
Sorry. I think I figured out why Windows Color Scheme changes. I think its because the program restarts as admin. I think this because when I right click on my application and run it as admin it changes the color scheme. I'm not sure why this is happening. If any one has an idea or how to stop it lmk.

**Comment by solutionsville** [comment]
Can you post your code?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ravibpatel** [comment]
@snnshn96 What type (WPF or Winforms) of application are you building?

**Comment by snnshn96** [comment]
Its a Winforms application. And its a pretty big project that im working on at my internship.

**Comment by ravibpatel** [comment]
@snnshn96 If you can provide screenshots of both original and changed color scheme it will be useful.

**Comment by ktownmods** [comment]
Closed
