### ISSUE TITLE
winform 更新 程序集的AssemblyTitle如果是中文可能会存在问题

### ISSUE THREAD

**Issue by Shinupy** [ravibpatel/AutoUpdater.NET#310]
更新时，AppTitle会取程序集的AssemblyTitle的值，如果 AssemblyTitle是中文，有一部分中文可能存在问题。如：老、布
代码中此语句，会导致错误。在BackgroundWorkerDoWork 方法下，（AutoUpdater.cs 中 426 行）
 httpWebRequest.UserAgent = GetUserAgent();
GetUserAgent() 方法会获取 AssemblyTitle 的值
原因可能是 UserAgent 要求字符的 低字节为 01111111 被留作控制字节，而有一部分汉字的低字节01111111，导致的错误。
结果是无法发起请求，错误报告显示连接服务器有问题

**Comment by ravibpatel** [comment]
You can work around the problem by setting up a custom User-Agent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-user-agent-for-http-web-requests). I will see what I can do about it.

**Comment by Shinupy** [comment]
OK，Thanks

**Comment by ravibpatel** [comment]
Does workaround resolve your issue?
