### ISSUE TITLE
show that connect webapi server failed but I can confirm the server is working well

### ISSUE THREAD

**Issue by Chencp2** [ravibpatel/AutoUpdater.NET#311]
![image](https://user-images.githubusercontent.com/54838682/64158030-618d0d80-ce6a-11e9-9710-7d710b8f8618.png)

**Comment by ravibpatel** [comment]
You can work around the problem by setting up a custom User-Agent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-user-agent-for-http-web-requests). I will see what I can do about it.

**Comment by ravibpatel** [comment]
Does workaround resolve your issue?
