### ISSUE TITLE
When I launch my app with amdin rights, autoupdate doesn't fire

### ISSUE THREAD

**Issue by alexeylobankov** [ravibpatel/AutoUpdater.NET#312]
I've faced a problem with administrator right. When I lanunch my app without admin rights, everything works fine, autoupdate works as it shoud work and update my app correctly. But the problem is that my app has to run with admin rights, and in this case autoupdate just does not work at all (no notification, no downloadin, just nothing). 
I know that my xml and versions stuff are fine, because I've tested the app and the updates in "regular" mode, and everything was perfect. Unfortunately when I laung the app with admin rights at the very beginning, autoupdater does not work. Am I doing something wrong?
It would be great if someone can help me with this issue

**Comment by ravibpatel** [comment]
@alexeylobankov Can you import the project and reference it directly? It will help in pointing out the issue.

**Comment by zaiplanet** [comment]
me too :(
if main app run normal without admin rights, everything works fine.
**if main app run as Admin right:**
- Check update and download complete.
- But when extract file is freeze at  _**Waiting for application to exit...**_
and main app can not exit
Please check this

![image](https://user-images.githubusercontent.com/58675403/145670496-8d2e389b-bed3-4af3-8145-8d533fd29b59.png)
