### ISSUE TITLE
Changed xml info and still downloads test zip

### ISSUE THREAD

**Issue by GeGeekTech** [ravibpatel/AutoUpdater.NET#313]
I've added the location of my xml file on the server, but when I click to update it downloads this file called AutoUpdaterTest.zip Both the test projects I've deleted yet it doesn't matter how many different times I remove the DLL and re add it to my project, I always get that there is an update and it downloads AutoUpdaterTest.zip instead of my update.

I went and added `AutoUpdater.OpenDownloadPage = true;` to see if it would show me the URL and all it did was load my own zip file which contains a text file and not the contents of the AutoUpdaterTest.zip

So I am at a lost on how to get this working. Any advice would be helpful thank you.

**Comment by ravibpatel** [comment]
Can you post your XML and C# code?
