### ISSUE TITLE
Maybe v1.5.6 has a bug for network check fail

### ISSUE THREAD

**Issue by xucongli1989** [ravibpatel/AutoUpdater.NET#314]
- When I upgrade to AutoUpdater.NET v1.5.6 in WinForm App and it doesn't working.
- My upgrade code one line only:  `AutoUpdater.Start("http://....com/update.xml")`
- I use fiddler check, and no http request to be send
- I change `ReportErrors=true`, and show message from `UpdateCheckFailedMessage` when I run App, but my network is normal.
- So I reinstall AutoUpdater.NET v1.5.4 and is OK again.

**Comment by ravibpatel** [comment]
You can work around the problem by setting up a custom User-Agent as shown here. I will see what I can do about it.

**Comment by ravibpatel** [comment]
If this workaround fixes your problem then please leave a comment so I can fix it and update the NuGet package.
