### ISSUE TITLE
Update for .NETCORE 3.0

### ISSUE THREAD

**Issue by Crytilis** [ravibpatel/AutoUpdater.NET#315]
Any possibility of getting this updated for .netcore3.0? Current version 1.5.7 is incompatible

**Comment by ravibpatel** [comment]
I'm currently porting it for the .NET standard you can check out v2.0 branch. It's a work in progress though.

**Comment by multinerd** [comment]
Any progress on the port?

**Comment by stebla27** [comment]
+1

**Comment by Crydsch** [comment]
+1

**Comment by rstm-sf** [comment]
Hello!

You can try using [this project](https://github.com/hvanbakel/CsprojToVs2017) for help

**Comment by ravibpatel** [comment]
New version support .NET Core 3.1 and .NET 5.0.
