### ISSUE TITLE
If the folder name has Chinese character，AutoUpdater shows disorder codes

### ISSUE THREAD

**Issue by LiuNet2** [ravibpatel/AutoUpdater.NET#316]
![图片](https://user-images.githubusercontent.com/48855867/64749151-287a2a80-d547-11e9-8d66-bf5561c12515.png)

If the folder name has Chinese character，AutoUpdater shows disorder codes.
As is shown in the  screen shot.

Maybe decompression in the AutoUpdater don‘t support Chinese character.

Please help me . Thanks.

当更新的文件夹含有中文字符的时候，本地下载更新后的文件夹名称有乱码。
可能是AutoUpdater 自带的解压功能不支持中文，谢谢

**Comment by ravibpatel** [comment]
You can use another tool to compress as mentioned in #280

**Comment by Necey** [comment]
老哥，进度条的问题你咋处理的呀？

**Comment by ZHHHHH** [comment]
I have some kind problem like u， are u  already resolve？

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1. It may fix your issue if you are using .net 4.5 or above.
