### ISSUE TITLE
Checksum Problem - administrator privileges

### ISSUE THREAD

**Issue by migueljfisel** [ravibpatel/AutoUpdater.NET#317]
When checksum is active on xml, during update "ZipExtractor" asks for administrator privileges even with AutoUpdater.RunUpdateAsAdmin = false;

Keep the great work. Thank you.

**Comment by ravibpatel** [comment]
That is weird behavior cause you can see from the following line that Checksum doesn't affect the code that is responsible for executing ZipExtractor as Admin.

https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L230
