### ISSUE TITLE
为什么在国外提示“无法连接远程服务器”？

### ISSUE THREAD

**Issue by yangpiena** [ravibpatel/AutoUpdater.NET#318]
在国内AutoUpdater.NET可以正常下载更新zip包，但是，在国外不能，为什么呢？
经过测试，在国外可以直接访问zip的URL地址访问，也能通过浏览器下载zip包。而AutoUpdater.NET就不能正常自动下载更新。

**Comment by ravibpatel** [comment]
Which version of AutoUpdater.NET are you using?

**Comment by yangpiena** [comment]
> Which version of AutoUpdater.NET are you using?

V1.5.3

**Comment by ravibpatel** [comment]
Can you try updating to the latest version?

**Comment by yangpiena** [comment]
Sure,I'm going to try,and tell you the result.Thank you for yor reply.

**Comment by yangpiena** [comment]
> Can you try updating to the latest version?

Hello,I tried v1.5.7, still unable to connect
![image](https://user-images.githubusercontent.com/19336724/65472542-8fcc9e80-dea6-11e9-8588-e66a2d2fed28.png)

**Comment by yangpiena** [comment]
I am already settling,The url in the XML file must be public address,Can't be localhost.
