### ISSUE TITLE
Allow other request authorization header field values

### ISSUE THREAD

**Issue by jay1891** [ravibpatel/AutoUpdater.NET#319]
Hi, 

First of all I have to say that AutoUpdater is a nice solution!

Could it be possible to allow a different authorization header than basic authentication? I would like to use Azure storage with a shared key authorization header. Azure storage doesn't use basic authentication. Is this possible to change the BasicAuthentication fields to an interface so also a different (ToString()) value than BasicAuthentocation can be applied to the authorization header field or do you accept pull requests?

Kind regards

**Comment by ravibpatel** [comment]
Hi,
It is possible by doing little modification to Basic Authentication class. You can provide another constructor accepting string directly. You can find the class on the following line.

https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L860

If you open the pull request then I will accept it.

**Comment by jay1891** [comment]
Hi Ravel,

Changing the BasicAuthentication class by injecting any string makes it no longer BasicAuthentication but all kinds of authentication. Could I make the proposal with the interface and a separate Azure storage authentication class? Normally this would be a no breaking change.

**Comment by jay1891** [comment]
Hi Ravi,

If you want I can make a CustomAuthenticalion Class next to the existing BasicAuthentication class which allows all kinds of strings to be injected, so not specific Azure storage naming is then needed?

**Comment by ravibpatel** [comment]
Thanks. I merged the pull request. You can test it out from [here](https://ci.appveyor.com/api/buildjobs/0xclr8gpu28ych03/artifacts/AutoUpdater.NET-1.5.7.zip). Tell me if you need NuGet release.

**Comment by jay1891** [comment]
Thanks Ravi for accepting it, and thanks for adjusting the naming issue! 🙂

I test it more.

________________________________

**Comment by jay1891** [comment]
Hi Ravi,

The security/integration for Azure storage was a little more complex than I initially thought. I made an update which allows to adjust the WebHeaderCollection before downloading the AutoUpdater.xml, changelog and actual file. 

Can I please create a pull request for this, and could you evaluate it to merge it? 

If you want I can also add the azure storage authentication class, because the custom authentication was not giving enough flexibility. This azure storage authentication class does more calculations and adjust the web request header fields for every specific file that needs to be download. This is required for Azure storage. Below you can find already this class.

`    public class AzureStorageAuthentication : IAuthentication
    {
        private string StorageKey { get; }
        private string StorageAccount { get; }
        private string Method { get; } = "GET";
        private string Now { get; } = DateTime.UtcNow.ToString("R");

        public AzureStorageAuthentication(string storageKey, string storageAccount)
        {
            this.StorageKey = storageKey;
            this.StorageAccount = storageAccount;
        }

        public void Adjust(Uri requestUri, WebHeaderCollection webHeaderCollection)
        {
            // Init
            string absolutePath = requestUri.AbsolutePath;
            string containerName = absolutePath.Split('/')[1];
            string blobName = absolutePath.Remove(0, $"/{containerName}/".Length);

            // Adjust WebHeaderCollection
            webHeaderCollection["x-ms-date"] = this.Now;
            webHeaderCollection[HttpRequestHeader.Authorization] =
                this.CreateAuthorizationHeader(
                    this.Method,
                    this.Now,
                    this.StorageAccount,
                    this.StorageKey,
                    containerName,
                    blobName);
        }

        private string CreateAuthorizationHeader(string method, string now, string storageAccount, string storageKey, string containerName, string blobName)
        {
            // Init
            string stringToSign = "GET\n\n\n\nx-ms-date:" + now + "\n/" + storageAccount + "/" + containerName + "/" + blobName;
            HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(storageKey));
            string signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(stringToSign)));

            // Create Authorization Header
            string authorizationHeader = string.Format("{0} {1}:{2}", "SharedKey", storageAccount, signature);

            return authorizationHeader;
        }
    }`
