### ISSUE TITLE
Issue with virtual directory

### ISSUE THREAD

**Issue by felixvandal** [ravibpatel/AutoUpdater.NET#32]
Hello!
I would like to start by thanking you for such a great piece to update software
I am more a website guy, but my boss asked me for a software...so i did a software
I have created a virtual directory on one of our server and put the xml needed for AutoUpdater.NET

```
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>2.0.0.0</version>
    <url>http://localhost:8080/setup.exe</url>
    <mandatory>true</mandatory>
</item>
```

and in my Window_Loaded event i put : 
`AutoUpdater.Start("http://catalogue.groupeep.com:8080/version.xml");`
my software is a WPF working in MVVM
(catalogue.groupeep.com is a redirection of a private site on our servers)

All work good until i try to update my soft.
When i open my soft, the popup telling me to update do show up.
When i click Update, nothing happen. Well something happen but the popup freeze at some point.
I tried to replace the setup.exe with the .msi that my installer give me.
I have created the installer with this:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2015InstallerProjects

can you help me?
did i missed something?
Thank you for your time

**Comment by ravibpatel** [comment]
If you are using http://localhost:8080/setup.exe as download URL then I don't think it will work. You need to define the URL in XML like this http://catalogue.groupeep.com:8080/setup.exe

**Comment by felixvandal** [comment]
well now it work
Thank you very much for your help
I tried this one :  http://localhost:8080/setup.exe because it was documented like that on Codeplex
Now i understand that the url tag is use to store a url that is return to the application calling the xml version file
could be nice to add to your documentation to prevent fool like me to do something like at did
anyway thank you for your help and have a nice day

**Comment by felixvandal** [comment]
Since i got you, is there a way to prevent the popup showing when there is no update available?

**Comment by ravibpatel** [comment]
@felixvandal There should be no dialog when there is no update. Are you seeing update dialog after updating the application to the latest version?

**Comment by felixvandal** [comment]
i have downloaded AutoUpdate.NET monday of this week
i have this showing up

![image](https://user-images.githubusercontent.com/30084866/29616425-71a8638c-87df-11e7-9f8a-88fa9f6f6ae6.png)

let me traduce
title: Update unavailable
message: There is no update available. Try again later

if i understand you right, this box is not supose to show up?

**Comment by felixvandal** [comment]
Forgot to add
My software is version 1.0.0.0
The xml version file is `<version>1.0.0.0</version>`

**Comment by ravibpatel** [comment]
@felixvandal version in the XML should be the latest version. The version you want your users to update to. So If your users have 1.0.0.0 and in the XML it is <version>1.1.0.0</version> then it will show the update dialog otherwise nothing. Since you have both the same it is showing there is no update. You only get this type of message if you set AutoUpdater.ReportErrors to true or you are handling update logic yourself as shown in the documentation. You only need one line AutoUpdater.Start("http://catalogue.groupeep.com:8080/version.xml"); to make it work. ReportErrors is false by default.

**Comment by felixvandal** [comment]
a ok!
i looked back at the description of ReportErrors and its written black on white that ReportErrors do this
i apologize for this
Thank you again for your quick support and have a nice day
