### ISSUE TITLE
/passive MSI install

### ISSUE THREAD

**Issue by AshotN** [ravibpatel/AutoUpdater.NET#322]
Mandatory mode is great, but I have a use case that requires no user interaction. Can a passive MSI install flag be added?

**Comment by ravibpatel** [comment]
You can use args tag in XML to pass command-line arguments as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file).

**Comment by AshotN** [comment]
Perfect, I must've misunderstood the functionality of the args field.

`<args>/passive</args>`  This is what worked for me!
