### ISSUE TITLE
Wrong filename when downloaded.

### ISSUE THREAD

**Issue by squalsoft** [ravibpatel/AutoUpdater.NET#33]
#I have url with my setup: https://downloader.disk.yandex.ru/disk/85704a961f8c50775a45e1f7dd2ec881b3d859c10d3c0e0b0d5a346c035b56a8/599dcfd3/736uxFAZ-OE2KC1qAjgYqnDKmSkHnnnDvneBtZXw-sz5qFRYJSlxvTwsZliYO9TgA3WHH9s1JsE0Mkm7UN7SKA%3D%3D?uid=168460779&filename=Setup_client_otb_1.2.88.0.msi&disposition=attachment&hash=&limit=0&content_type=application%2Fx-msi&fsize=18727064&hid=4e151e78d32e2bf5600bb218d061d5ff&media_type=settings&tknv=v2&etag=e3ee17cace5fc77a7f79c02fa88db60f

When file downloaded it have name 736uxFAZ-OE2KC1qAjgYqnDKmSkHnnnDvneBtZXw-sz5qFRYJSlxvTwsZliYO9TgA3WHH9s1JsE0Mkm7UN7SKA==
instead of Setup_client_otb_1.2.88.0.msi. So it cannot be installed.

**Comment by squalsoft** [comment]
I will try to fix it myself.

**Comment by ravibpatel** [comment]
Your link is not working anymore. Can you please update it so I can test the pull request?

**Comment by squalsoft** [comment]
By this link 
https://test.oxr-info.ru:47474/test/res.xml 
stored xml file which contains download link for file:
TestFile1.txt
