### ISSUE TITLE
Extracting to folder outside of update

### ISSUE THREAD

**Issue by thealphabetguy** [ravibpatel/AutoUpdater.NET#333]
If the updater is located in:

C:\abc\abc\ when the updater extracts the contents it extracts to the location C:\abc\abc\

However, if I want the contents to be extracted to C:\abc\ how do I do that?

Thank you.

**Comment by thealphabetguy** [comment]
Any help please?

**Comment by ravibpatel** [comment]
You can't do it. It only extracts the content of the zip file where the executable resides but you can accomplish this if you use an installer instead of a zip file.
