### ISSUE TITLE
UpdateCheckFailedMessage on Start()

### ISSUE THREAD

**Issue by lenkaiser** [ravibpatel/AutoUpdater.NET#334]
Title pretty much explains the problem. The only thing I do is run:
```
AutoUpdater.ReportErrors = true;
AutoUpdater.Start("https://.../update.xml");
```
I confirmed that the endpoint is reachable, ssl certificates are fine, by opening the link. Still the software thinks that it cannot reach this destination. By saying: "There is a problem reaching update server. Please check your internet connection and try again later.". I check the code but couldn't find a clear reason why this message is shown.

The xml contains:
```
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>1.0.0.4</version>
    <url>https://.../installer.msi</url>
    <changelog>https://.../changelog.html</changelog>
    <mandatory>false</mandatory>
</item>
```

**Comment by laithayoub71** [comment]
Me too! It's frustrating.. I can't get it to work

**Comment by ravibpatel** [comment]
Can you give me the URL of your XML file so I can troubleshoot?

**Comment by laithayoub71** [comment]
sure, but here’s the thing. when i upload it to GitHub or DropBox it
works fine but from my website it doesn’t. i’m guessing cuz it needs a
direct download link to work? GitHub works amazing but i’d rather use the
one from my website: https://sdie.ga/btd/update.xml

**Comment by ravibpatel** [comment]
@laithayoub71 I tried your XML file and it is fetching following data from the XML file.

``` html
<html>

<body>
    <script type="text/javascript" src="/aes.js"></script>
    <script>
        function toNumbers(d) {
            var e = [];
            d.replace(/(..)/g, function(d) {
                e.push(parseInt(d, 16))
            });
            return e
        }

        function toHex() {
            for (var d = [], d = 1 == arguments.length && arguments[0].constructor == Array ? arguments[0] : arguments, e = "", f = 0; f < d.length; f++) e += (16 > d[f] ? "0" : "") + d[f].toString(16);
            return e.toLowerCase()
        }
        var a = toNumbers("f655ba9d09a112d4968c63579db590b4"),
            b = toNumbers("98344c2eee86c3994890592585b49f80"),
            c = toNumbers("52ed1cbf76ff999c0aff617fc5cb01e9");
        document.cookie = "__test=" + toHex(slowAES.decrypt(c, 2, a, b)) + "; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
        location.href = "https://sdie.ga/btd/update.xml?i=1";
    </script>
    <noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>
</body>

</html>
```

That's why it can't parse the XML and give you an error.

**Comment by laithayoub71** [comment]
ohh, i guess it’s my hosting service. cuz when i uploaded it, it was a
normal XML file, i guess my hosting service tries to convert it to HTML.
now i know the problem, thanks!

**Comment by ravibpatel** [comment]
@laithayoub71 I updated the library so it will give clear errors like this from now on. You can test it from [here](https://ci.appveyor.com/api/buildjobs/4gj5e1ur7d35gfu1/artifacts/AutoUpdater.NET-1.6.0.zip).

**Comment by laithayoub71** [comment]
Thanks! It worked perfectly, it showed me what I did wrong. Amazing
developer, thanks for making it easier for me and the rest of us to
implement updates into our programs. Much appreciated <3

**Comment by Pulkitsoft** [comment]
@ravibpatel Can you please check what's going wrong, my link open perfectly in a web browser.

[https://www.pulkitsoft.com/wp-content/uploads/Download/PDFXPERT_Main.xml](https://www.pulkitsoft.com/wp-content/uploads/Download/PDFXPERT_Main.xml)

For testing purpose, XML contents are same as per yours.

Error showing: "There is a problem reaching update server. Please check your internet connection and try again later."
