### ISSUE TITLE
change ZipExtractor.exe UI but not work

### ISSUE THREAD

**Issue by ZHHHHH** [ravibpatel/AutoUpdater.NET#343]
Is possible to change ZipExtractor.exe UI? I want to custom UI and also I try it，but when I start Project and UI still be old version，How can I do this?

**Comment by ravibpatel** [comment]
You have to change the ZipExtractor.exe inside the resources folder of AutoUpdater.NET to make it work.

**Comment by ZHHHHH** [comment]
@ravibpatel 
In Url Tag,can I use “.exe” file？ I have read source code it seem to only suppot ".msi" file

**Comment by ravibpatel** [comment]
@ZHHHHH 
Yes, you can use the ".exe" file.
