### ISSUE TITLE
 Re-update

### ISSUE THREAD

**Issue by FoxTes** [ravibpatel/AutoUpdater.NET#348]
Hello. At the start of the offer, the update is successfully triggered, but if you click the "do not install" button, then the next time you start the application update window does not appear.
I don’t understand why this is happening.
Settings:
AutoUpdater.ReportErrors = true;
AutoUpdater.ShowRemindLaterButton = false;
AutoUpdater.RunUpdateAsAdmin = false;
AutoUpdater.Start("url");

**Comment by ravibpatel** [comment]
What do you mean by "Do not install" button? Are you referring to Remind Later or Skip option?

**Comment by FoxTes** [comment]
In the Russian version it sounds like "Do not install." This is definitely not a "remind later" button

**Comment by FoxTes** [comment]
There will be no answer to the solution of this problem?

**Comment by ravibpatel** [comment]
You mean button with this text "Не устанавливать" then it is a Skip button. If you press it then it will skip this version and never remind you again for this version. If you do not want to use the Remind Later and Skip option at all then you can turn Mandatory to true as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#ignore-previous-remind-later-or-skip-settings).

Do you propose a better translation for this term?

**Comment by FoxTes** [comment]
Now I understand the algorithm of work.
In my opinion, this button is not quite correctly named in the Russian version.
I advise you to name something "Skip the version", and not "Do not install."
The user thinks that in the future, when you re-open the application, the update window will appear again, but this does not happen.

**Comment by ravibpatel** [comment]
@FoxTes If you can provide better Russian translation then it will be great. Just open the pull request with update RU resource files and I'll merge your pull request.

**Comment by FoxTes** [comment]
And the last question.
If the <skip> button was pressed, can I reset this value?
Required to re-call the update.

**Comment by ravibpatel** [comment]
The only way to ignore skip value is by setting Mandatory to true. You can also set mandatory to true from XML and it will work. I usually do it like this. I provide 2 ways to update. I execute the AutoUpdater.Start on the Form_Load event and I also provide a way to check updates from the menu. I set the Mandatory to true when the user presses the menu option and call the start method to start looking for an update. This way even if the user ignored the update notification from the Form_Load event, they can still do update using the menu option.

**Comment by FoxTes** [comment]
Yes, I had this answer I wanted to hear. Thanks!
