### ISSUE TITLE
How to use proxy settings to download file from web when the web is blocked by company of user

### ISSUE THREAD

**Issue by sudoantang** [ravibpatel/AutoUpdater.NET#350]
Hi,

I  am using google drive to store my file and xml file. I get the link public so that anyone with the link can download file without the need of having username or password.

In some cases, the computer of my user blocks google drive so I cannot update file.

My approach is to use web proxy (for example: I use this web to have a proxy setting like IP and port, https://getproxylist.com/).

I have searched around your proxy settings but have no function having parameters like IP and Port above.

Would you mind give me some instructions.

Thank you.

**Comment by AAN3AC** [comment]
Have you considered using free Apache web server?


H

**Comment by sudoantang** [comment]
Thank you for your keyword. 

My major is not IT so I don't know so much about this. That is the reason I use google drive because it is the most simple one I can do ...

I will google according to your keyword.

**Comment by ravibpatel** [comment]
You can use the proxy server as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#proxy-server).

**Comment by sudoantang** [comment]
var proxy = new WebProxy("ProxyIP:ProxyPort", true) 
{
    Credentials = new NetworkCredential("ProxyUserName", "ProxyPassword")
};
AutoUpdater.Proxy = proxy

Your code in the example is above. But there is no function with the parameters for IP and Port.

Can you guide me more clearly.

Thank you.

**Comment by ravibpatel** [comment]
@sudoantang Just replace the ProxyIP in example with your IP and ProxyPort with your port. So if my IP is 10.0.0.1 and Port is 856 then the code should be as follows.

```csharp
var proxy = new WebProxy("10.0.0.1:856", true)
{
    Credentials = new NetworkCredential("ProxyUserName", "ProxyPassword")
};
AutoUpdater.Proxy = proxy
```

**Comment by sudoantang** [comment]
Thank you.
In my case, I dont have username and password. About the credentials, how can I declare.

Thank you a lot.

**Comment by sudoantang** [comment]
Thank you so much :D
