### ISSUE TITLE
Error Logging not working when ErrorReporting is enabled.

### ISSUE THREAD

**Issue by NeilMJohnson** [ravibpatel/AutoUpdater.NET#351]
Ravi, your package works great on all of my client machines except 1. 

This machine does not do automatic updates and does not pop-up any error boxes when ReportErrors is set to true.  Manually requesting an update also does nothing, even when a new version is available.  Do you have any suggestions on how to troubleshoot this?  The client machine is running Windows 10 professional and the user has local administrative privileges.  I can see the update directory from their machine and open the XML file.  Are there any other locations that I could check for some sort of error message?

Thanks, Neil

**Comment by ravibpatel** [comment]
I updated the code for better error reporting. Please try the new lib from [here](https://ci.appveyor.com/api/buildjobs/wpl200jgx1rufnxt/artifacts/AutoUpdater.NET-1.6.0.zip) and let me know what kind of error you are getting.

**Comment by NeilMJohnson** [comment]
Hi Ravi, I downloaded and  installed the update and when I tried to upgrade the users machine, the upgrade worked without my doing anything else.  The extra error reporting code will be useful in future. Thanks.
