### ISSUE TITLE
AutoUpdater.NET copys files into wrong directory

### ISSUE THREAD

**Issue by WeiderTools** [ravibpatel/AutoUpdater.NET#352]
Hi!
The tool works but it copies the downloaded files into a subfolder of the installation path.

I has set the DownloadPath to Environment.CurrentDirectory --> NOK
After that i has set the DownloadPath as below.
But both solutions doesn't work.

```
AutoUpdater.ReportErrors = true;
AutoUpdater.RunUpdateAsAdmin = true;
var tt = Environment.CurrentDirectory;
var ttt = tt.Substring(0, tt.LastIndexOf("\\"));
AutoUpdater.DownloadPath = ttt;
AutoUpdater.Start(@"E:\GIT\MyTestApp\UpdateFile\updateFile.xml");
```

After i clicked "Update", the tool download the zip, extract this and copied the files to:

C:\Program Files (x86)\HP Inc\Setup\Release\
--> Setup = Directory where the app istalled.
--> Release = Directory after update, with the updated files.

**Comment by ravibpatel** [comment]
Does your executable reside in the Release folder? It usually extracts the content into the folder where your executable resides.

**Comment by WeiderTools** [comment]
Yes it does.
In this testproject i have zipped the release directory. This is in the xml linked.

<?xml version="1.0" encoding="UTF-8"?>
<item>
  <version>1.0.37.0</version>
  <url>E:\GIT\MyTestApp\bin\Release.zip</url>
  <mandatory>false</mandatory>
</item>

How does the updater work after download the zip?

**Comment by ravibpatel** [comment]
It extracts the zip file in a folder where your executable resides. You can see it [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L69).

**Comment by WeiderTools** [comment]
OK!
That works. In this directory are the new files. But they aren't copied to the install folder...
(I run the app as admin)
i get no errors after update...

**Comment by ravibpatel** [comment]
Please download the latest lib from [here](https://ci.appveyor.com/api/buildjobs/3skxv1h83plutn4h/artifacts/AutoUpdater.NET-1.6.0.zip). I added the option to specify the installation path as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#specify-where-to-extract-zip-file-containing-updated-files).
