### ISSUE TITLE
Introduce the concept of "Minimum Version" instead of "Mandatory" update and allow a synchronous update check to be run

### ISSUE THREAD

**Issue by paulluscastro** [ravibpatel/AutoUpdater.NET#353]
### **The problem**

Currently a user can skip updates if one particular mandatory update is missed.

### **Explanation**

Currently the developer can set an update as mandatory by the use of the "Mandatory" property on the XML configuration file. If this property states that the update is mandatory then Autoupdater.NET does not allow the user to skip the update.

When calling the AutoUpdater.Start(string) method from the Program.cs file the CheckForUpdateEvent is triggered assynchronously by the BackgroundWorker, the main thread goes on and the user can just ignore the installation Wizard and proceed using the application. Creating a synchronous method that would give us the update information could prevent the application of going on before the first check.

But even creating a synchronous method that holds the main thread a user would still be able to skip a mandatory update by not using the application during the period that particular update is available. Lets say a developer releases version 1.1 as mandatory on the 1st of January, and by the 13th of January the developer releases a second update 1.2 that is not mandatory... the user that did not use the program before the 13th of January will miss the mandatory 1.1 version. The introduction of the "Minimum Version" concept in this scenario would prevent the user that enterede on the 15th of January from skipping/missing the mandatory update.

### **Code**
Changes made to files from the AutoUpdaterTest project.
https://gist.github.com/paulluscastro/f0a120c17d85a0ac4c8e2ad76dd2bc4f

### **Screen Capture Demonstrating the Error**

![UPDATE NOT MANDATORY](https://user-images.githubusercontent.com/2917025/73791727-cdb5c980-479a-11ea-83c8-65bc3269772f.gif)

**Comment by ravibpatel** [comment]
You shouldn't run AutoUpdater.NET before any forms of the application. It can't find UI thread if you do that and that's why it can't block the operations in your UI. Synchronous updates can solve the issue if you run it from Program.cs but It needs too much restructuring of the existing code so I don't think I can provide it now. Maybe in 2.0.

You got the point about the minimum version. I will see what I can do about it.

**Comment by paulluscastro** [comment]
I think I can provide a solution for both. Like I said before, this is the
first time ever that I am collaborating with an open source project, so I
didn't know how to do it.

I thought that instead of just developing the solution and making the pull
request it would be better to create an issue, see the acceptance and only
then develop it.

**Comment by ravibpatel** [comment]
I added way to do both. You can try new lib from [here](https://ci.appveyor.com/api/buildjobs/fayvvbjehkh9udbr/artifacts/AutoUpdater.NET-1.6.0.zip). Let me know if you run into any issues.

You can find the docs for it from [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) and [here](https://github.com/ravibpatel/AutoUpdater.NET#check-for-updates-synchronously).
