### ISSUE TITLE
System.NullReferenceException in AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerDoWork

### ISSUE THREAD

**Issue by arielbvargas** [ravibpatel/AutoUpdater.NET#354]
Hi,
On main form of my app I´ve the following code:

 AutoUpdater.ParseUpdateInfoEvent += AutoUpdaterOnParseUpdateInfoEvent;
AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;
AutoUpdater.ShowSkipButton = false;
AutoUpdater.ReportErrors = true;
AutoUpdater.DownloadPath = Environment.CurrentDirectory;
AutoUpdater.Mandatory = true;
AutoUpdater.UpdateMode = Mode.ForcedDownload;
AutoUpdater.HttpUserAgent = "iPV.OS AutoUpdater";
AutoUpdater.RunUpdateAsAdmin = false;
AutoUpdater.LetUserSelectRemindLater = false;

// Correct URL hidden
string updaterPath = "https://XXXXXX.updater.json";
 AutoUpdater.Start(updaterPath);

I always get the following error:

![image](https://user-images.githubusercontent.com/22923/74341333-4b269e80-4d86-11ea-84a3-d814268a9c2f.png)

How can I fix this issue?
Thanks!

**Comment by ravibpatel** [comment]
Are you using the NuGet package?

**Comment by arielbvargas** [comment]
Hi, I was using the package and since it wasn´t working I switched to the compiled DLL. Now (based on your question), I switched back to the package. I will get back to you as soon as I´ve feedback on how it goes. Thanks for your reply!

**Comment by ravibpatel** [comment]
If you use a package then make sure you follow docs from [here](https://github.com/ravibpatel/AutoUpdater.NET/tree/1dc25f2bea6ea522dbac1512b5563c4746d539c3). UpdateInfoEventArgs implementation has been changed in newer commits.

**Comment by arielbvargas** [comment]
Hi again! Unfortunately, using the Nuget package I get:

Message = Object reference not set to an instance of an object.
Data = System.Collections.ListDictionaryInternal
InnerException =
TargetSite = Void BackgroundWorkerDoWork(System.Object, System.ComponentModel.DoWorkEventArgs)
StackTrace =    at AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerDoWork(Object sender, DoWorkEventArgs e) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 545
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
HelpLink =
Source = AutoUpdater.NET
HResult = -2147467261

**Comment by ravibpatel** [comment]
Can you try updated lib from [here](https://ci.appveyor.com/api/buildjobs/q32h3th1c0jgkv2p/artifacts/AutoUpdater.NET-1.6.0.zip)?

**Comment by arielbvargas** [comment]
I´ve updated to the new lib, and realized that UpdateInfoEventArgs.Mandatory is now a Mandatory prop instead of a bool. I changed to args.Mandatory.Value to identify it´s value. Other change is DownloadUpdate that now accepts UpdateInfoEventArgs. Will compile and test the new lib. Get back in a couple of hours.

**Comment by arielbvargas** [comment]
Hi there. Same error, different line:

![image](https://user-images.githubusercontent.com/22923/74596314-53a00300-502c-11ea-8dcf-2e3b83adad00.png)

![image](https://user-images.githubusercontent.com/22923/74596321-716d6800-502c-11ea-8411-e6d89e3dea79.png)

**Comment by ravibpatel** [comment]
If you can provide AutoUpdaterOnParseUpdateInfoEvent and  AutoUpdaterOnCheckForUpdateEvent implementation it will help.
