### ISSUE TITLE
application not closing

### ISSUE THREAD

**Issue by rehman922** [ravibpatel/AutoUpdater.NET#356]
main application not closing , auto-updater hangs.
"waiting for application to exit. "

**Comment by ravibpatel** [comment]
Are you running the Start method from UI thread? You should also try handling application exit logic as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually).

**Comment by mosoftwareenterprises** [comment]
I had a similar issue. Turned out I have a FormClosed & FormClosing event that cancelled the event. So it never shutdown.
I solved it by unsubscribing from those events in the AutoUpdater.ApplicationExitEvent before calling Application.Exit().
