### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by andrik77782** [ravibpatel/AutoUpdater.NET#357]
Hi 
private void Form_Load(object sender, EventArgs e)
        {
            AutoUpdater.ReportErrors = true;
            AutoUpdater.DownloadPath = Environment.CurrentDirectory ;
            AutoUpdater.OpenDownloadPage = true;
            AutoUpdater.Start(xmlPath);
        }
get
![image](https://user-images.githubusercontent.com/36029456/75521765-10bd3280-5a11-11ea-9ef8-0cd84030823b.png)
AutoUpdater.NET.dll versin 1.6.0.0
Could you help?

**Comment by ravibpatel** [comment]
It seems It can't get the AssemblyTitle for your app. Please try passing the assembly with the Start method as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#current-version-detection).

**Comment by andrik77782** [comment]
Thsnk, it work
