### ISSUE TITLE
CheckForUpdateEvent how show standart dialog?

### ISSUE THREAD

**Issue by jenokizm** [ravibpatel/AutoUpdater.NET#358]
hi, i have code
```
private void AutoUpdater_CheckForUpdateEvent(UpdateInfoEventArgs args)
        {
            if (AutoUpdater.Mandatory)
            {
                //ручная проверка, показываем сообщение
                if (args == null)
                {
                    System.Windows.MessageBox.Show(Strings.Strings.CheckUpdateError,
                       Strings.Strings.Error, MessageBoxButton.OK, MessageBoxImage.Error);
                }
                else
                if (!args.IsUpdateAvailable)
                    System.Windows.MessageBox.Show(Strings.Strings.CheckUpdateNotFound,
                        Strings.Strings.TooltipHeader3, MessageBoxButton.OK, MessageBoxImage.Information);
                else
                    ShowStandartDialogWindow();
            }
        }
```
how do I, if successful, call the standard dialog provided by your library?

**Comment by ravibpatel** [comment]
If you are using the NuGet package then just call "AutoUpdater.ShowUpdateForm()".

**Comment by jenokizm** [comment]
> If you are using the NuGet package then just call "AutoUpdater.ShowUpdateForm()".

ok, but I have an old version. probably have to update

**Comment by jenokizm** [comment]
im updated AutoUpdater from 2017 ver to current. but now it does not work properly. when the Mandatory parameter (in xml) false when the program starts, the notification does not appear, and when it is true it appears every time it starts, while the user clicks to skip this update

**Comment by jenokizm** [comment]
+ controls of the user interface of the update dialog look like windows 98. since I have programming experience in assembly, I am aware that this style is the default style of programs if they are copied without a xp manifest

**Comment by ravibpatel** [comment]
Lot has changed since the 2017 version. Please read the docs from [here](https://github.com/ravibpatel/AutoUpdater.NET/tree/1dc25f2bea6ea522dbac1512b5563c4746d539c3) for the latest version and update your implementation accordingly. Also. I will fix the issue with a visual style. For now, you can use the following code before showing the dialog and it should fix the problem.

```csharp
Application.EnableVisualStyles();
```

**Comment by jenokizm** [comment]
yes to hell with them, with these styles. your logic is lame, I described a more important problem in the message above
