### ISSUE TITLE
Network share as the URL

### ISSUE THREAD

**Issue by WPFAdvocate** [ravibpatel/AutoUpdater.NET#359]
Hello I am getting error when trying to use a network share as the url in the xml file

![image](https://user-images.githubusercontent.com/60395331/76540238-3ce8a280-6458-11ea-8dae-185f07627c8a.png)

**Comment by ravibpatel** [comment]
Try to use file:// in front of the url.

**Comment by WPFAdvocate** [comment]
>  <url>file://cytgit\Applications\C#\EZDock\EZDock.zip</url>

![image](https://user-images.githubusercontent.com/60395331/76540758-f9daff00-6458-11ea-8815-9f4104060afd.png)

**Comment by ravibpatel** [comment]
It should be "file://cytgit/Applications/C#/EZDock/EZDock.zip".

**Comment by WPFAdvocate** [comment]
without the file it works that way, thank you!
