### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by snnshn96** [ravibpatel/AutoUpdater.NET#36]
Hello, 
   I was wondering if you guys can put all of the language folders under one folder. Also Is there a way to exclude any other language other than English so no other language folder shows up.
Thanks.

**Comment by ravibpatel** [comment]
@snnshn96 It is possible to do. But you need to edit your app.config file. You can add following code in to your app.config then you can move the Languages file to Languages folder.

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="Languages"/>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by snnshn96** [comment]
@ravibpatel Thanks for the answer. But whenever I build the application it generates the files outside of the languages folder.

**Comment by ravibpatel** [comment]
@snnshn96 You can move them into Languages folder in the release build. It will work.
