### ISSUE TITLE
Thread-safety?

### ISSUE THREAD

**Issue by jdahan91** [ravibpatel/AutoUpdater.NET#360]
It's kind of a pain in the ass that we must call from the ui thread. Sometimes I have other classes that want to invoke methods from a different thread which I have no control over.

**Comment by ravibpatel** [comment]
It will still work fine even if you use it from other threads. The only problem was apps had trouble exiting when exit was called from another thread. You can handle the application exit event if you encounter it.

**Comment by jdahan91** [comment]
> It will still work fine even if you use it from other threads. The only problem was apps had trouble exiting when exit was called from another thread. You can handle the application exit event if you encounter it.

Thank you so much for the reply, and yeah I just did notice this issue ;] So what i'm doing is calling .Exit() manually after the call to DownloadUpdate().

**Comment by jdahan91** [comment]
Too bad the CheckForUpdateEvent isn't defined as EventHandler<> because I needed information from object sender argument lol.
