### ISSUE TITLE
will this work in a console app?

### ISSUE THREAD

**Issue by rhousedorf-mla** [ravibpatel/AutoUpdater.NET#361]
Hi folks, I'm trying to add this to a .net c# console app, and I'm having some issues with it working.

Is this intended to work with console apps?
Or just winforms for now?
Also, what about using it to update a windows NT Service ?  ( not a web service, this is an actual Windows service, like SQL Server service .  but not SQL obviously.)

**Comment by ravibpatel** [comment]
It should work. What happens when you try to use it with a console app?

**Comment by rhousedorf-mla** [comment]
I have it working for the console, but not for the windows service.
