### ISSUE TITLE
System.net.exception occurs during automatic update with startup program

### ISSUE THREAD

**Issue by namilkimfree** [ravibpatel/AutoUpdater.NET#362]
HI, I'm using autoupdate but I have problem.
When I run my program the update works fine.  However, if it registers as a startup program, reboots the computer and runs automatically, it cannot be updated.

How to fix this issue? I need your help
Configuration: windows 10
Role: user
Exception: System.net.exception
Run as administrator : false
The environment is the same for both.

**Comment by TechnikEmpire** [comment]
You'll need to provide the actual exception data at minimum for anyone to be able to help you.

**Comment by ravibpatel** [comment]
You can try the dll from [here](https://ci.appveyor.com/api/buildjobs/5f5suuvyos1huxhy/artifacts/AutoUpdater.NET-1.6.0.zip) to see if it fixes your issue.
