### ISSUE TITLE
Using DLL from latest release doesn't work, using DLL from local build works

### ISSUE THREAD

**Issue by robinschiro** [ravibpatel/AutoUpdater.NET#364]
I just downloaded [this release](https://github.com/ravibpatel/AutoUpdater.NET/releases/tag/v1.5.8) and added the DLL as a reference in my project. After following the README and adding 'AutoUpdater.Start("url/to/manifest.xml");' to my client startup code, I get the following error:
![image](https://user-images.githubusercontent.com/5543503/78509497-283fb780-7743-11ea-8a11-302d79fdc0d8.png)

However, after cloning the repo and building a release DLL myself, everything works fine. 

For context, my project is running on the .NET 4.0 Client profile.

**Comment by ravibpatel** [comment]
Repo is updated drastically from the last released version but I didn't test it for all scenarios (Local file and FTP). That's why I didn't release it.

**Comment by ravibpatel** [comment]
Updated the NuGet package with latest version.
