### ISSUE TITLE
Update errors are not reported anymore in CheckForUpdateEvent event

### ISSUE THREAD

**Issue by zgabi** [ravibpatel/AutoUpdater.NET#365]
Before 2020.01.11 the `CheckForUpdateEvent `was called when there was an error with downloading the update xml with args==null.

In this commit it was changed: https://github.com/ravibpatel/AutoUpdater.NET/commit/32e01a7219e7bce2531a6f5d2d4870be771b637c

Now it is only called when Error is null and not possible to handle the error manually. The only options is just to show or not to show an error dialog.
We'd like to do different error handling without showing the error dialog.

The "Handling updates manually" section also shows an example for that:
```
AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;

private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
{
    if (args != null)
    {
        ...
    }
    else
    {
         this is not working anymore
    }
}
```

I agree not to call this event handler in case of error, but please add another error event. (Or restore the previous behavior.)

**Comment by ravibpatel** [comment]
How you intend to handle the case when args is null? How it can be useful?

**Comment by zgabi** [comment]
As it is in your example:
https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually

Earlier args was null when there was an error.

**Comment by ravibpatel** [comment]
Yes, I get that part but I removed it cause it wasn't giving any error info besides setting args to null. Can you tell me what you intend to do in the if (args != null) block of your event?

**Comment by zgabi** [comment]
It is almost the same as in your example:

```
                if (args.IsUpdateAvailable)
                {
                    if (args.Mandatory.Value)
                    {
                        if (AutoUpdater.DownloadUpdate(args))
                            Shutdown();
                        else
                            Messaging.ShowInfo(_message_FailedToDownloadUpdate);
                    }
                    else
                    {
                        var result = Messaging.ShowDialog(string.Format(_message_NewVersionAvalilableQuestion, AutoUpdater.AppTitle));

                        if (result == MessageBoxResult.Yes)
                        {
                            if (AutoUpdater.DownloadUpdate(args))
                                Shutdown();
                            else
                                Messaging.ShowInfo(_message_FailedToDownloadUpdate);
                        }
                    }
                }
```

The difference is in the args==null... i don't want to show any messagebox, just log the problem.

**Comment by zgabi** [comment]
> it wasn't giving any error info besides setting args to null

Yes, that it is true.. this is why I wrote: 

> I agree not to call this event handler in case of error, but please add another error event.

**Comment by ravibpatel** [comment]
@zgabi Thanks for the explanation. I understand you want to log the error. I'll see what I can do about it.
