### ISSUE TITLE
Progress bar window expands wrongly

### ISSUE THREAD

**Issue by aillanes-voovio** [ravibpatel/AutoUpdater.NET#366]
When we've some file paths too long, the (unexpected) behaviour of the update window is like the following one:

![test](https://user-images.githubusercontent.com/25003501/79341235-c4c83d80-7f2b-11ea-8c4d-be84d0243a47.gif)

The file path should be set to a maximum width finished with an ellipsis or let the progress bar also to grow with its parent window.

**Comment by ravibpatel** [comment]
Can you try the latest version of the lib from [here](https://ci.appveyor.com/api/buildjobs/ejcyej238y8c04ln/artifacts/AutoUpdater.NET-1.6.0.zip)? It should fix the issue.

**Comment by aillanes-voovio** [comment]
Now it fits the window. Could be possible to maintain the window's aspect instead of growing? I mean, using an ellipsis in the middle instead when more than (30 chars):
e.g. /usr/path/t.../file.jpg

![test](https://user-images.githubusercontent.com/25003501/79344717-78cbc780-7f30-11ea-9a77-712c748533cf.gif)

The current behavior is not too user-friendly.

**Comment by ravibpatel** [comment]
Yes, It is possible. I will try to do it and let you know.

**Comment by aillanes-voovio** [comment]
Ok. Thanks a lot in advance. As soon as you send me a new package I'll let you know if it works properly.

**Comment by ravibpatel** [comment]
I updated the lib you can try it from [here](https://ci.appveyor.com/api/buildjobs/nj0rsqemf54knjt7/artifacts/AutoUpdater.NET-1.6.0.zip). It shouldn't expand the window now while retaining the full path.

**Comment by aillanes-voovio** [comment]
Yep! It worked! Thanks you so much for your support.
