### ISSUE TITLE
Is there any XML attribute to handle machine bit (x64 or x86) and download updated installer based on machine bit version?

### ISSUE THREAD

**Issue by kernello** [ravibpatel/AutoUpdater.NET#367]
We hope there might have a way to detect machine bit versions and download based on bit versions. We need to handle by one XML and that XML has both bit version URL link. Autoupdator might have a way to detect and download the required bit version installer. 

Please let us know the way or should we do this by using two XML?. One for x64 and another for x86?.

**Comment by ravibpatel** [comment]
No, You have to use 2 separate XML files for x64 and x86 version.

**Comment by kernello** [comment]
Thanks for your response.
