### ISSUE TITLE
Updater can be closed with alt+f4 on mandatory settings

### ISSUE THREAD

**Issue by polgergo** [ravibpatel/AutoUpdater.NET#369]
I have the updater set up for mandatory update in my application, but i can close the updater app with alt+f4 and continue to use my own application. This shortcut should should be disabled when using mandatory setting.

**Comment by ravibpatel** [comment]
You are right. Let me see what I can do about it next update.

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1 with this feature.
