### ISSUE TITLE
can you add a exit  delegate?

### ISSUE THREAD

**Issue by shizenghua** [ravibpatel/AutoUpdater.NET#37]
@ravibpatel thank you for a good updater.

because when my program using the <exit>  function , it's crash. i don't know why.
so i changed your program for my logic exit.
i add a delegate <exit> function to resolve my problem.

 private static void Exit()
        {
            if (ExitEvent != null)
            {
                ExitEvent();
            }
            else{.........................................}
       }

thanks!!!

**Comment by ravibpatel** [comment]
I did it in [this](https://github.com/ravibpatel/AutoUpdater.NET/commit/14b8f687cb9ffb9724bb4ecb104fbbc9740ef964) commit but it causes the problem when AutoUpdater ran from an MTA thread.

**Comment by gmichaud** [comment]
Was this reverted? I just implemented something similar on my end to be able to properly close Microsoft Excel when my add-in calls the auto-updater. I need to marshal the event back to the main Excel thread, but it works fine for my use case: 

```
ExcelAsyncUtil.QueueAsMacro(() => Common.ExcelApplication.Quit());
```

**Comment by ravibpatel** [comment]
@gmichaud Recently I found a way to execute Exit code in caller thread. It was reverted before but I can add it again.

**Comment by gmichaud** [comment]
I think that having an event for AutoUpdater clients is a better approach - for my Microsoft add-in I really want to call Excel's Application.Quit() function. From the event the client can take care of marshalling it to the right thread. I think it's cleaner than to try to kill the process.

**Comment by ravibpatel** [comment]
Yeah, You are right I will add it back.

**Comment by gmichaud** [comment]
Thanks!
