### ISSUE TITLE
Cleanup files that are not contained within an update package

### ISSUE THREAD

**Issue by smohring** [ravibpatel/AutoUpdater.NET#376]
Hi,

Is there a way to auto-delete files that have been removed with an updated version?
Currently, the zip file is extracted to the target directiory and copied over the existing files, files that have been removed (not contained in the update zip) will stay in the program directory.

Thank you and kind regards!

**Comment by ravibpatel** [comment]
You have to use the installer file as an update file to do that. There is no way to do that if you use Zip as an update file.

**Comment by imckl** [comment]
> You have to use the installer file as an update file to do that. There is no way to do that if you use Zip as an update file.

Is there an example to explain how to use installer file?
Or by the means of "installer file", it is just a installer which prompt to user to react?

**Comment by ravibpatel** [comment]
You can use [NSIS ](https://nsis.sourceforge.io/Main_Page) to create the installer instead of Zip file and provide its URL as download URL in XML. You can try adding [this](https://stackoverflow.com/a/719851/1273550) in your NSIS script to uninstall the older version before installing a new one.

**Comment by smohring** [comment]
I solved the problem i had by using the ApplicationExitEvent (which is only executed on click to "Update").
Maybe not the best solution - but for me its working so far.

`
private static void AutoUpdater_ApplicationExitEvent()
        {
            // Cleanup leftovers from old installation
            try
            {
                Directory.Delete(Path.Combine(Directory.GetCurrentDirectory(), "DirectoryToDelete"), true);
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
            }

            Application.Current.Shutdown();
        }
`

**Comment by zaiplanet** [comment]
> I solved the problem now by using the ApplicationExitEvent (which is only executed on click to "Update"). Maybe not the best solution - but for me its working so far.
> 
> ```
> private static void AutoUpdater_ApplicationExitEvent()
> {
>     // Cleanup leftovers from old installation
>     try
>     {
>         Directory.Delete(Path.Combine(Directory.GetCurrentDirectory(), "DirectoryToDelete"), true);
>     }
>     catch (Exception ex)
>     {
>         _log.Error(ex.Message, ex);
>     }
>     
>     Application.Current.Shutdown();
> }
> ```
> 
> `
> 
> `
This void you add it into ButtonUpdateClick ?

**Comment by zaiplanet** [comment]
> 

i put AutoUpdater.ApplicationExitEvent += AutoUpdater_ApplicationExitEvent below InitializeComponent()
but event don't run while form close
