### ISSUE TITLE
Problems with URL hosted in infinityfree

### ISSUE THREAD

**Issue by CarmeloViavattene** [ravibpatel/AutoUpdater.NET#383]
I created an account on
infinityfree.net, and in the appropriate folder I copied the 2 files, which can be downloaded via the browser (Chrome)
XML file can be downloaded from "http://carmeloviavattene.epizy.com/AutoUpdater.xml"
ZIP from "http://carmeloviavattene.epizy.com/Prova/AutoUpdaterTest.zip"

To check version:
This not work:
AutoUpdater.Start("http://carmeloviavattene.epizy.com/AutoUpdater.xml");
The same file in FTP mode work:
AutoUpdater.Start("ftp://ftpupload.net/htdocs/Prova/AutoUpdater.xml", new NetworkCredential("epiz_25736932", "password")); // i cannot publish password

after the Update check start, if i click ok to update, after the UAC control, appear a dialog "System.IO.InvalidDataException" "Rilevati dati non validi durante la decodifica"

If in XML I change the URL to FTP link, it work perfectly

---------
If ZIP and XML are hosted on github,, it work.
XML is obviously different and you can see it at:
"https://github.com/CarmeloViavattene/califfo/releases/download/Califfo/AutoUpdater.xml"
the same ZIP is at:
https://github.com/CarmeloViavattene/califfo/releases/download/Califfo/AutoUpdater.zip

I use:
AutoUpdater.Start("https://github.com/CarmeloViavattene/califfo/releases/download/Califfo/AutoUpdater.xml");
and after the update check start, if i click ok to update, after the UAC control, all is OK
------------
My problem is:
1) I would like to avoid using github for another program with non-public domain sources, and therefore I wanted to host them in a URL other than github, as I thought infinityfree.net could be for testing
2) if I publish at this moment my open source, i publish also my account and password

Can You help me?

**Comment by robertnisipeanu** [comment]
It's probably your hosting company that may be trying to stop bots from accessing your website by requiring browsers to have JS enabled.
I downloaded your .xml file and started a local xampp server, this is the response I get on localhost server:
![image](https://user-images.githubusercontent.com/16354517/82767185-42863f80-9e2e-11ea-8586-b9f5e76ed45e.png)

And this is the response I got on your server:
![image](https://user-images.githubusercontent.com/16354517/82767192-55007900-9e2e-11ea-88ef-23e5af7bbf5c.png)

**Comment by CarmeloViavattene** [comment]
AutoUpdater.NET can simulate a browser with JS enabled ?

**Comment by robertnisipeanu** [comment]
It can't, as AutoUpdater.NET is not using a browser to do the requests or download the file, it's using http requests. I don't a browser would ever be added to it as it is not worth it (it can introduce a lot of bugs, it's gonna add some hundreds MB to the package and even more runtime dependencies that can crash anytime or that may face errors while running on the user's PC). It is indeed your hosting company blocking the requests: https://forum.infinityfree.net/t/this-site-requires-javascript-to-work/6035/2
So I suggest just changing your hosting plan or provider.

**Comment by CarmeloViavattene** [comment]
I thank You, The fast.io is a perfect solution
