### ISSUE TITLE
use S3 as file location?

### ISSUE THREAD

**Issue by fake-fur** [ravibpatel/AutoUpdater.NET#387]
hi and thanks for the library

is there any way to use S3 as the file locations? i looked through the docs and code briefly but could not see anything obvious - is there perhaps a way to override the "get xml file" and "get update file" functions anywhere?

thanks again :)

**Comment by ravibpatel** [comment]
Hi,
There is no direct support for this. There are two events for parsing the received file and handling updates but there is no event for changing the logic of web requests.

**Comment by morrikan** [comment]
I'm doing this myself and have no problems.  Upload the installer to a public S3 bucket, and AutoUpdate.NET is able to read it just fine.

**Comment by fake-fur** [comment]
thanks but i decided to write my own as i also needed beta and release channels 
glad it does work from S3 tho
good to know
