### ISSUE TITLE
Please add ability to override the method which determines current version

### ISSUE THREAD

**Issue by ttodua** [ravibpatel/AutoUpdater.NET#393]
By default, the program takes assembly version to determine current version.
however, please give us an override ability, so we would tell the program that current version is XYZ (we are making versions by some non-standard ways).

**Comment by ravibpatel** [comment]
I added the feature in the latest commit. You can try it from here. You should be able to assign the installed version manually as shown below.

```csharp
AutoUpdater.InstalledVersion = new Version("1.2");
AutoUpdater.Start("Your XML file URL");
```

**Comment by ttodua** [comment]
Thank you ravibpatel !
