### ISSUE TITLE
Video tutorial for total noobs please.

### ISSUE THREAD

**Issue by anuragdmon** [ravibpatel/AutoUpdater.NET#394]
any videos on how to work with Autoupdater.NET.Official from the nuget packages ?

**Comment by ravibpatel** [comment]
There is no video available but it is very simple. Just create an XML file as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) and upload it on your server. Now in your application provide its URL to the AutoUpdater Start method. You can do that on form load or on button click event.

```csharp
AutoUpdater.Start("Your XML file URL");
```

Now, whenever you update your application. You just have to update the version in the XML file on your server and all the users currently using old version of the application will get the message. If you put it on form load then they will get message when they open the app.
