### ISSUE TITLE
How to use custom version number instead of assembly ?

### ISSUE THREAD

**Issue by Summer006** [ravibpatel/AutoUpdater.NET#395]
Hi :

My app has 2-3 exe or dll files, I want it autoupdate when any one of them has new version on server.

one way is customize version number, calculate all exe and dll files version to one version number.

xml file on server can modify manually, but on app side, I did't found how to customize version number.

function **AutoUpdater.Start** has second parameter "Assembly", but also need a special assembly file.

so I think what I need is: 

`AutoUpdater.Start(string url, Version customVersion)`

is there any way to do it? 

thank you

**Comment by ravibpatel** [comment]
No, currently there is no way to do it but I am planning to add it as soon as I get some free time.

**Comment by ravibpatel** [comment]
I added the feature in the latest commit. You can try it from [here](https://ci.appveyor.com/api/buildjobs/8dl1v6cvtbh4wlvv/artifacts/AutoUpdater.NET-1.6.1.zip). You should be able to assign the installed version manually as shown below.

```csharp
AutoUpdater.InstalledVersion = new Version("1.2");
AutoUpdater.Start("Your XML file URL");
```

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1 with this feature.

**Comment by Summer006** [comment]
Thanks, it's working
