### ISSUE TITLE
Application.Exit functionality in UpdateForm_FormClosed 

### ISSUE THREAD

**Issue by DeathGOD7** [ravibpatel/AutoUpdater.NET#396]
Can you add an option that the user can enable and disable whether to close the application fully or not if UpdateForm is closed? 

Or bool that provides if the update form is closed or not.

**Comment by ravibpatel** [comment]
If you want to force the user to update then you can try setting the following option before calling the 
Start method.

[https://github.com/ravibpatel/AutoUpdater.NET#forced-updates](https://github.com/ravibpatel/AutoUpdater.NET#forced-updates)

**Comment by moebigit** [comment]
I think the OP means that it would be nice to know whether the user decided to execute the update, postpone it or simply closed it. I would like to execute some logic if the user decides to not perform the update (clicking on the close button top right).
