### ISSUE TITLE
Application doesn't exit completely before downloaded file gets executed

### ISSUE THREAD

**Issue by moebigit** [ravibpatel/AutoUpdater.NET#398]
I am running into the issue that my application doesn't exit completely before the downloaded file gets executed.
I am trying to figure out what is taking so much time but I am basically having some threads running that communicate with Arduinos using the cmdMessenger library and it requires a shutdown of these process and libraries (dlls) to properly terminate the app. This might be taking some time.

Well, in other words, I am downloading a self-executable zip file (WinRar) and whenever I do the update it complains that it cannot overwrite the dlls that are still in use of the not completely shut down running application.

I believe the problem is, that the "Exit()" is called after "DownloadUpdate(args)" where the latter already contains the start of the process.

So I wonder why there are not more people complaining about this.

In my opinion it would be helpful to have a callback method that is executed BEFORE the zip/exe/msi process is started. This might help to have the application prepare for a very fast shutdown.
At the same time I believe it is a fundamental problem to have the updater process be a process within the application it is trying to update. Even if the shutdown of the application is very quick, there is no guarantee that dlls are unloaded properly before the updater process tries to unzip and overwrite the files.

I hope I am explaining my self clearly. Feel free to follow up with questions in case I am not clearly describing the issue.

**Comment by moebigit** [comment]
This seems to be a follow up on this issue https://github.com/ravibpatel/AutoUpdater.NET/issues/11

**Comment by ravibpatel** [comment]
I will implement the callback which will be called before exiting the application.

**Comment by ravibpatel** [comment]
I added the retry behavior in the latest version of the library. It should remedy this issue.
