### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by xamrex** [ravibpatel/AutoUpdater.NET#399]
Hey
Long time ago i develop application. (in polish)
I d like to implemented Autoupdater.NET.
Almost everything is working, but for some reason, when I call `AutoUpdater.Start("http://rbsoft.org/updates/AutoUpdaterTest.xml");`
it shows window in English language. How can i force autoupdater to be in 'polish' ?

For my test i have just created another new app, and when i implementing Autoupdater.NET. it shows window in polish, what i right,

So i have to few years ago did something wrong, and now I have Autoupder.Net in English..
How can i correct it? How can i force Autoupdater to be in polsih ?
Thanks for help

**Comment by xamrex** [comment]
I know where is the issue, but i have no idea how to fix it.
So i have added to my app a .dll file, and i wanted to be .dll file combined into .exe
so i have added:
` AppDomain.CurrentDomain.AssemblyResolve += new `ResolveEventHandler(CurrentDomain_AssemblyResolve);``
` static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("Proj.DocX.dll"))
            {
                byte[] assemblyData = new byte[stream.Length];
                stream.Read(assemblyData, 0, assemblyData.Length);
                return Assembly.Load(assemblyData);
            }
        }`

And with that code AutoUpdater.net is not in polish ;-(

**Comment by xamrex** [comment]
closed by mistake

**Comment by ravibpatel** [comment]
You can embed the dll with something like [Costura.Fody](https://github.com/Fody/Costura).
