### ISSUE TITLE
Changelog example

### ISSUE THREAD

**Issue by patrikmichnac** [ravibpatel/AutoUpdater.NET#400]
I would like to ask you, if there an example for release log page. Just because it is rendered inside autoupdate form, I want to know how it has to looks like. Some demo page for release log.
<changelog>https://github.com/ravibpatel/AutoUpdater.NET/releases</changelog>
Or is there an example how to write change log directly to tag <changelog> and do not use url link?

**Comment by ravibpatel** [comment]
You can have any type of page you like as a changelog. It should work on IE cause web browser control uses IE to render the page. Currently, there is no way to write a changelog directly. YOu have to provide a URL.
