### ISSUE TITLE
项目用vs2019 16.7.2版本打不开

### ISSUE THREAD

**Issue by 593172440** [ravibpatel/AutoUpdater.NET#401]
项目用vs2019 16.7.2打开,提示:AutoUpdater.NET 针对 是".NETFramework,Version=v2.0",但是这个2.0官网已经不提供下载了.将目标更改为.net Framework 4.6.1后,提示加载失败.

**Comment by ravibpatel** [comment]
Replace [this line](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.NET.csproj#L6) with the following code.

```xml
<TargetFramework>net461</TargetFramework>
```

Do the same for ZipExtractor.csproj.
