### ISSUE TITLE
How to generate  the Resources's "ZipExtractor.exe" contains ZipStorer.dll

### ISSUE THREAD

**Issue by LuGuangguang** [ravibpatel/AutoUpdater.NET#402]
Hello,When I Use the AutoUpdater.NET to decompression some contains Japanese name Files Zip,It's Garbled.
![图片](https://user-images.githubusercontent.com/34500722/90873506-db4a3e00-e3d0-11ea-83ae-64b5cf9957d5.png)
So,I changed the "ZipExtractor" some codes.When I replace the  AutoUpdater.NET's Resources\ZipExtractor.exe,It's tell me that needs ZipStorer.dll.
I use winRAR packed the dll,but Can't run with paras.
So I want to know how you did it。
![图片](https://user-images.githubusercontent.com/34500722/90874246-0b461100-e3d2-11ea-8e73-cb89f3f51170.png)
 
Thank you.

**Comment by LuGuangguang** [comment]
> 
> 
> AutoUpdater.NET->属性->资源->将字符串选择为文件就可以看见ZipExtractor.exe;你可以将ZipExtractor项目生成的ZipStorer.dll放进去试试.如果不是乱码的话.请告知一下怎么修改的.因为它中文也是乱码

你的方法我已经试过了，不可以的。
我上面放的图， ravibpatel已经把DLL打进exe了，你把DLL放到外面这种会报上面的错误的

**Comment by ravibpatel** [comment]
Updated the NuGet package to v1.6.1 with this feature. It may fix your issue if you are using .net 4.5 or above. It uses native .net class to decompress zip file for .net 4.5 or above. Please let me know how it goes.

**Comment by LuGuangguang** [comment]
> 
> 
> Updated the NuGet package to v1.6.1 with this feature. It may fix your issue if you are using .net 4.5 or above. It uses native .net class to decompress zip file for .net 4.5 or above. Please let me know how it goes .

I do but no working. So I want to use "SharpZipLib.dll" to replace ZipStorer.
I see your V1.6.2's 4.5 by using "ZipFile",I updated and  it can also fix this issue,but only 4.5 can do it.

**So I'd kinda like to know you  how  to pack the dll to ZipExtractor.exe,I want modify by using "SharpZipLib.dll"**
Thank you!

**Comment by ravibpatel** [comment]
Currently, If you build the ZipExtractor in release mode it will output the dll as AutoUpdater.NET resource so you can just use SharpZipLib to replace ZipExtractor and build the project. After that just build the AutoUpdater.NET in release mode and you will have ZipExtractor with SharpZipLib.

**Comment by ravibpatel** [comment]
You will have to remove the reference to ZipStorer from the project too. Just remove the reference and remove the ZipStorer NuGet package from the project.

**Comment by LuGuangguang** [comment]
> 
> 
> You will have to remove the reference to ZipStorer from the project too. Just remove the reference and remove the ZipStorer NuGet package from the project.

I found when I change Release Model,the Output Path turned the "AutoUpdater.NET\Resources\",the file size also turned 104K.
Thank you a lot.
