### ISSUE TITLE
Does this work with private repos (specifically BitBucket)

### ISSUE THREAD

**Issue by V972** [ravibpatel/AutoUpdater.NET#403]
I have a project and I use a BitBucket as a repo because its repos are pricate by default which is what I need.
But I'm not sure if AutoUpdater will be able to reach XML (and if needed, later the update itself) if it's in such private repo.
Will it?

**Comment by ravibpatel** [comment]
No, It won't work with private repo.

**Comment by ravibpatel** [comment]
You must provide an XML file URL that can be accessible by anyone for it to work.
