### ISSUE TITLE
更新到1.6.1.0又出现新问题了

### ISSUE THREAD

**Issue by 593172440** [ravibpatel/AutoUpdater.NET#404]
提示找不到路径,但是明明有呀
![image](https://user-images.githubusercontent.com/11573521/91545572-cc750580-e953-11ea-8cc4-c31d755a9ead.png)

**Comment by ravibpatel** [comment]
Which .NET Framework you are using and does the update adds a new folder with file?

**Comment by 593172440** [comment]
.net Framework 4.8 Configs里面包含许多文件

**Comment by ravibpatel** [comment]
Please try new version from [here](https://ci.appveyor.com/api/buildjobs/wm5qy6fay5gu5etq/artifacts/AutoUpdater.NET-1.6.2.zip). Use "AutoUpdater.NET.dll" from "net45" folder. Let me know how it goes.

**Comment by 593172440** [comment]
用了这个1.6.2版本，以上的未能找到路径问题解决了。感谢大佬

**Comment by ravibpatel** [comment]
I updated the NuGet package with the fix. It will be available soon.
