### ISSUE TITLE
Is this a way to change the download design ?

### ISSUE THREAD

**Issue by Haswell19** [ravibpatel/AutoUpdater.NET#406]
Hello,

I want to know if it's possible to change the download window like the the update checker ?
Something like this but for the download event : `AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;`

Thanks in advance. Greate work fot this framework.

**Comment by ravibpatel** [comment]
Sorry, currently there is now way to do this.

**Comment by rishit-epari** [comment]
Any plans on when this feature can be available?

**Comment by ravibpatel** [comment]
Currently, There are no plans to implement it. You can fork the project and modify it as you wish.
