### ISSUE TITLE
An exception occured during a webclient request

### ISSUE THREAD

**Issue by boengkak** [ravibpatel/AutoUpdater.NET#41]
error downloading for bigger files around 40Mb, is there any workaround for this? thank you

![new picture 9](https://user-images.githubusercontent.com/5528689/30840510-ead2d35a-a2a1-11e7-8e3c-b5cc52038e35.jpg)

**Comment by ravibpatel** [comment]
@boengkak Can you provide the XML file URL so I can test at my end?

**Comment by boengkak** [comment]
this is the xml file tester, i've change to 1.7Mb file, but still error in the middle of download prosess
http://9wali-boengkak.rhcloud.com/update/AutoUpdaterTest.xml

**Comment by ravibpatel** [comment]
@boengkak It is downloading fine on my machine.

**Comment by boengkak** [comment]
thx for the response, yes, it seems my OS got problems, i'm trying with another client, and it's okay
