### ISSUE TITLE
handling internet connection errors

### ISSUE THREAD

**Issue by seltix5** [ravibpatel/AutoUpdater.NET#410]
hello,

after analising the code to try to handle the internet connections errors myself, I think it is not possible?
from what I understand, here :
https://github.com/ravibpatel/AutoUpdater.NET/blob/974a8761ea1f199b72615b143effc5d1040869b1/AutoUpdater.NET/AutoUpdater.cs#L288
if the CheckUpdate() throws a exception it will never call StartUpdate() and there is no other way to manually handle the error other than the ReportErrors variable to show the message.

Maybe the StartUpdate() should be in a separate try catch ? that way this code example could work :
https://github.com/ravibpatel/AutoUpdater.NET/blob/f07d5dabe5ad942d49df22e62fb66ba2e3a613d6/AutoUpdaterTest/FormMain.cs#L217

or throw the exception if ReportErrors is false ?

thanks!

**Comment by Summer006** [comment]
I agree.
my app is check update at start (force update if available, no cancel, no next time),  after that enter main app ui.
but if user network not working, whole app is stuck at update checking. 
no failed message, no exception thrown, no event fired.
to fixed that , I had to check that url is reachable or not, before call update check.

I suggest that, add a 'FailedReason' enum type in event parameter, it can tell what error type of this failure. 
like network issue / domain issue / host connection issue / http response error/ xml parse error / no error

**Comment by seltix5** [comment]
Closed with no reply? :/

**Comment by ravibpatel** [comment]
New commit added the ability check errors in check for update event. You can check it out.

**Comment by seltix5** [comment]
> New commit added the ability check errors in check for update event. You can check it out.

in my project is use the NuGet version ( https://www.nuget.org/packages/Autoupdater.NET.Official/1.6.3?_src=template ), how does it work for updates? since apparently there is no new update there.
Thanks!

**Comment by ravibpatel** [comment]
I haven't released the NuGet package but you can try it from [here](https://ci.appveyor.com/api/buildjobs/vsg35kfwlr5xn0r2/artifacts/AutoUpdater.NET-1.6.3.zip).
