### ISSUE TITLE
No error message when detecting SHA512 Differences?

### ISSUE THREAD

**Issue by SpecterFXXK** [ravibpatel/AutoUpdater.NET#413]
So i did a test with AutoUpdater.NET in my project and changed some files against the original package.zip
1 test all original, updated with success no errors
test 2, no updating, because of differences in SHA512 Values, no error message popped up?
is there such a feature to tell the user that the package has been modified?

**Comment by ravibpatel** [comment]
Check out the [checksum option](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) of XML file.
