### ISSUE TITLE
Can it be used for Windows Services?

### ISSUE THREAD

**Issue by shrinidhi111** [ravibpatel/AutoUpdater.NET#416]

**Comment by ravibpatel** [comment]
Please refer to answer in #405.

**Comment by devinstasafe** [comment]
@ravibpatel  Hi! 

I went through the linked issue and other Windows Service related issues.. But my question is this. How will the update logic work without the service running? 

Like, it will find an update, download and install. But before install the current service has to be stopped. But if the service is stopped won't the update part also stop?

**Comment by ravibpatel** [comment]
Not if you create a separate win forms project for updating the service as suggested in the issue.
