### ISSUE TITLE
Temporary disable previous remind later and skip selections

### ISSUE THREAD

**Issue by erikf-iccms** [ravibpatel/AutoUpdater.NET#417]
Is there a way to temporary disable the previous Remind me later and Skip selections that a user may have done for a specific update check?

In our program we check for updates when the program starts and then we give the user an option to remind me later or skip this update.

We also have a menu option to manually check for updates. We want this manual check to always check if there is an update even if the user previously has selected to remind me later or skip this update.

I can call on AutoUpdater.ShowUpdateForm but that will show the update form even if there is no new version of the software so that does work for us.
I can also set AutoUpdater.Mandatory = True but that will remove the buttons Remind me later and Skip buttons and we do not want to do that. We still want to show the Remind me later and Skip buttons.

**Comment by ravibpatel** [comment]
Setting AutoUpdater.Mandatory = True to is only way to do it right now.
