### ISSUE TITLE
UpdateInfoEventArgs in NuGet package doesn't contain an Error field

### ISSUE THREAD

**Issue by i74n** [ravibpatel/AutoUpdater.NET#418]
![image](https://user-images.githubusercontent.com/45488861/95561981-2cb39880-0a24-11eb-9bc2-8bb51873cc15.png)

As I can see, you updated the repository 9 days ago and changed [this](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) example, but NuGet package wasn't updated. 
How can I handle updates manually now?

**Comment by ravibpatel** [comment]
I still didn't update the NuGet package. You can remove the if statement containing the error field to make it work with current NuGet package.
