### ISSUE TITLE
Not installing the latest version

### ISSUE THREAD

**Issue by benjam60** [ravibpatel/AutoUpdater.NET#420]
This is our code (Our app is compiled with .Net Framework 4.0):
`AutoUpdater.InstalledVersion = new Version("2.3.0.0");
  AutoUpdater.DownloadPath = Environment.CurrentDirectory;
   AutoUpdater.Start('xml url is here');`

This is our xml:
`<item>
<version>2.5.0.0</version>
<url>https://cpmsexecutableserver.azurewebsites.net/api/file/cpmsRelease.zip</url>
<mandatory>false</mandatory>
</item>`
(That url should not work for you by the way)

Our app prompts with an update that there is a new version. We click update. We saw the downloaded zip and we know for sure that the downloaded executable in the zip file is the newer version of the app. However, it keeps reinstalling the original, older version. So it uninstalls the original version, ignores the updated setup file and then reinstalls the original version. We have spent days on this and can't figure out the issue. :/

**Comment by ravibpatel** [comment]
Please take a look at the issue #213. Your issue looks similar.

**Comment by benjam60** [comment]
Unfortunately, I combed through it carefully, and hasn't solved it. I also have the same application name.

`Thursday, October 15, 2020 2:59:47 PM

ZipExtractor started with following command line arguments.
[0] C:\Users\benja\AppData\Local\Apps\2.0\D8J8EV1N.Q0D\W2MQDPD1.L05\cpms..tion_0000000000000000_0001.0001_1ad9969ce18f9261\ZipExtractor.exe
[1] C:\Users\benja\AppData\Local\Apps\2.0\D8J8EV1N.Q0D\W2MQDPD1.L05\cpms..tion_0000000000000000_0001.0001_1ad9969ce18f9261\cpmsRelease.zip
[2] C:\Users\benja\AppData\Local\Apps\2.0\D8J8EV1N.Q0D\W2MQDPD1.L05\cpms..tion_0000000000000000_0001.0001_1ad9969ce18f9261
[3] C:\Users\benja\AppData\Local\Apps\2.0\D8J8EV1N.Q0D\W2MQDPD1.L05\cpms..tion_0000000000000000_0001.0001_1ad9969ce18f9261\CPMS.Net.exe

BackgroundWorker started successfully.
Found total of 71 files and folders inside the zip file.
Extracting setup.exe [1%]
Extracting Application Files/CPMS.Net_1_1_0_15/AutoUpdater.NET.dll.deploy [2%]
Extracting Application Files/CPMS.Net_1_1_0_15/CPMS.Net.application [4%]
Extracting Application Files/CPMS.Net_1_1_0_15/CPMS.Net.exe.config.deploy [5%]
Extracting Application Files/CPMS.Net_1_1_0_15/CPMS.Net.exe.deploy [7%]
Extracting Application Files/CPMS.Net_1_1_0_15/CPMS.Net.exe.manifest [8%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.CrystalReports.Design.dll.deploy [9%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.CrystalReports.Engine.dll.deploy [11%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.Data.AdoDotNetInterop.dll.deploy [12%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.ReportAppServer.DataSetConversion.dll.deploy [14%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.ReportSource.dll.deploy [15%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.Shared.dll.deploy [16%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.VSDesigner.dll.deploy [18%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.Web.dll.deploy [19%]
Extracting Application Files/CPMS.Net_1_1_0_15/CrystalDecisions.Windows.Forms.dll.deploy [21%]
Extracting Application Files/CPMS.Net_1_1_0_15/EnvDTE.dll.deploy [22%]
Extracting Application Files/CPMS.Net_1_1_0_15/EnvDTE80.dll.deploy [23%]
Extracting Application Files/CPMS.Net_1_1_0_15/log4net.dll.deploy [25%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.BatchParser.dll.deploy [26%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.BatchParserClient.dll.deploy [28%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.ConnectionInfo.dll.deploy [29%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.ConnectionInfoExtended.dll.deploy [30%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Diagnostics.Strace.dll.deploy [32%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Dmf.Common.dll.deploy [33%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Dmf.dll.deploy [35%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.Collector.dll.deploy [36%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.CollectorEnum.dll.deploy [38%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.Common.dll.deploy [39%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.RegisteredServers.dll.deploy [40%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.Sdk.Sfc.dll.deploy [42%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.SmoMetadataProvider.dll.deploy [43%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.Utility.dll.deploy [45%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.UtilityEnum.dll.deploy [46%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.XEvent.dll.deploy [47%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.XEventDbScoped.dll.deploy [49%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.XEventDbScopedEnum.dll.deploy [50%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Management.XEventEnum.dll.deploy [52%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.PolicyEnum.dll.deploy [53%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.RegSvrEnum.dll.deploy [54%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.ServiceBrokerEnum.dll.deploy [56%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Smo.dll.deploy [57%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SmoExtended.dll.deploy [59%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SqlClrProvider.dll.deploy [60%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SqlEnum.dll.deploy [61%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SqlTDiagm.dll.deploy [63%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SqlWmiManagement.dll.deploy [64%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.SString.dll.deploy [66%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.Types.dll.deploy [67%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.WmiEnum.dll.deploy [69%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.XE.Core.dll.deploy [70%]
Extracting Application Files/CPMS.Net_1_1_0_15/Microsoft.SqlServer.XEvent.Linq.dll.deploy [71%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl00_FileInfo.sql.deploy [73%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl01_Selected.sql.deploy [74%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl06_TIP_Conformity.sql.deploy [76%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_CBD_Districts.sql.deploy [77%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_District_CBD.sql.deploy [78%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_District_ILH.sql.deploy [80%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_District_ILS.sql.deploy [81%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_District_USC.sql.deploy [83%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_GIS.sql.deploy [84%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_IFD_Districts.sql.deploy [85%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_ILH_Districts.sql.deploy [87%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_ILS_Districts.sql.deploy [88%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_MFT.sql.deploy [90%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_Municipality.sql.deploy [91%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl07_USC_Districts.sql.deploy [92%]
Extracting Application Files/CPMS.Net_1_1_0_15/Resources/dbo.tbl08_Comments.sql.deploy [94%]
Extracting Application Files/CPMS.Net_1_1_0_15/Seal_of_Lake_County,_Illinois.ico.deploy [95%]
Extracting Application Files/CPMS.Net_1_1_0_15/VSLangProj.dll.deploy [97%]
Extracting Application Files/CPMS.Net_1_1_0_15/VsWebSite.Interop.dll.deploy [98%]
Extracting CPMS.Net.application [100%]
Successfully launched the updated application.


`

**Comment by benjam60** [comment]
There is my zipextractor log. I zip everything correctly..

**Comment by benjam60** [comment]
Any ideas?

**Comment by ravibpatel** [comment]
Sorry for late reply. I don't see CPMS.Net.exe extracted in the log. Do you have it in zip file?
