### ISSUE TITLE
sometimes  it did'nt work when the server.xml is on https server

### ISSUE THREAD

**Issue by zhouqing-inovance** [ravibpatel/AutoUpdater.NET#421]
hi,
I use 'anywhere'(a simple http sever) to create a web server and I find it works on 'http' but sometime it didn't work on 'https'.
I use version:1.6.3.0

here is my code
//work
AutoUpdater.Start("http://127.0.0.1:8000/server.xml");
// not work
AutoUpdater.Start("https://127.0.0.1:8001/server.xml")

**Comment by ravibpatel** [comment]
Are you using self-signed certificate?

**Comment by zhouqing-inovance** [comment]
> signed

a no signed certificate url

**Comment by ravibpatel** [comment]
You need a valid SSL certificate for it to work properly with HTTPS.

**Comment by zhouqing-inovance** [comment]
> 
> 
> You need a valid SSL certificate for it to work properly with HTTPS.

OK  thank  u
