### ISSUE TITLE
How to reset this setting after using the skip button

### ISSUE THREAD

**Issue by howzew** [ravibpatel/AutoUpdater.NET#424]
Hello
Where is this information stored when I use the skip button? 
How do I restore this version of the update?
After clicking the skip button, I found that there was no place to restore this setting. I found that someone had mentioned this problem before. The solution seems to be to set the mandatory to true. 
But since I am debugging the function in the test environment, I need to restore this setting so that I can test normally.
Thank you!

**Comment by ravibpatel** [comment]
It is stored in the registry in the current user tree. You can see it the location from [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L348-L350).

**Comment by ravibpatel** [comment]
You can remove the registry entry to reset the settings.
