### ISSUE TITLE
Unzip setup executable and run #84

### ISSUE THREAD

**Issue by EricFang2020** [ravibpatel/AutoUpdater.NET#425]
Dear Sir,

Would it be possible to implement the ability to download a zipped setup executable and have it unzip and execute the setup file?

https://github.com/ravibpatel/AutoUpdater.NET/issues/84

I have the same problem but after reading your message, I still have no idea how to do it.
I have already included AutoUpdater.NET V1.6.3.0 in my VS C# project.

Do you mean that I have to download the ZipExtractor code and modify it?
I have downloaded the project, but there are so many compile error. In addition, where should I insert your lines?

Besides, does that mean I need to compile a new DLL and replace V1.6.3.0 DLL? How to create a DLL and replace it?

Really appreciate your help!

Have a nice day.

Eric Fang

**Comment by ravibpatel** [comment]
Which Visual Studio version are you using? You can add the following lines after [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/fc443c8b10681bf4b81edc0ce127da659b509e16/ZipExtractor/FormMain.cs#L137) line to run the setup.

```csharp
if(Path.GetExtension(filePath) == ".exe") {
   Process.Start(filePath);
   eventArgs.Cancel = true;
   return;
} 
```

**Comment by EricFang2020** [comment]
Hello, Ravi,

I use:
Microsoft Visual Studio Community 2019
Version 16.4.4

I know where to insert your lines now, but I have compile errors:
![Compile_Error](https://user-images.githubusercontent.com/73827450/98210970-ac5c5680-1f41-11eb-9b20-c59bc3ed933d.PNG)
How can I fix these errors?

And how do I generate a new .dll and replace the original AutoUpdater.NET.dll ?
![Original_DLL](https://user-images.githubusercontent.com/73827450/98212227-918ae180-1f43-11eb-99e9-6018934532ab.PNG)

Really appreciate your help!

Have a nice day.

Eric Fang

**Comment by ravibpatel** [comment]
It seems like you didn't restore the NuGet packages so you should do that first. Just go to NuGet package manager and it will ask you to restore the packages.

You also have to go to project properties of AutoUpdater.NET and ZipExtractor project and turn off signing. You will be able to build the project after that.
 
Just right-click on your Project and click on Add Reference to add AutoUpdater.NET.dll you just built.

**Comment by EricFang2020** [comment]
Hello, Ravi,

I fix all the errors and want to test my new .dll now. Really appreciate your help!!

Have a nice day : )

Eric Fang

**Comment by ravibpatel** [comment]
You have to do the release build and reference the resulting AutoUpdater.NET.dll in your project to test it out.

**Comment by EricFang2020** [comment]
Hello, Ravi,

I have no problem when compiling in debug mode. But I have errors when I compile in release mode.
Please refer to the follwing:
![Release_Compile_Error](https://user-images.githubusercontent.com/73827450/98220184-37dbe480-1f4e-11eb-9de1-f69ad9370dc5.PNG)
How can fix these errors? Really appreciate your help!

Eric Fang

**Comment by EricFang2020** [comment]
Hello, Ravi,

I select frame work net45 then compile again. I still have following error:

![Release_Compile_Error_2](https://user-images.githubusercontent.com/73827450/98220649-e54ef800-1f4e-11eb-96ff-ceb0d6f8daee.PNG)

How can fix these errors? Really appreciate your help!

Eric Fang

**Comment by EricFang2020** [comment]
Hello, Ravi,

I download code V1.6.4 and test again. Please refer to the following:

Debug mode OK
![Debug_OK_V1 6 4](https://user-images.githubusercontent.com/73827450/98224377-b2f3c980-1f53-11eb-9274-b81307062918.PNG)

Release mode NG
![Release_Compile_Error_2](https://user-images.githubusercontent.com/73827450/98224424-bf782200-1f53-11eb-9dd9-8e84f781e1ef.PNG)

How can fix these errors? Really appreciate your help!

Eric Fang

**Comment by EricFang2020** [comment]
Hello, Ravi,

I download code V1.6.4 and test again. Please refer to the following:

Debug mode OK
![Debug_OK_V1 6 4](https://user-images.githubusercontent.com/73827450/98224706-17af2400-1f54-11eb-8f55-8c5e7860e44f.PNG)

Release mode NG
![Release_NG_V1 6 4](https://user-images.githubusercontent.com/73827450/98224736-21388c00-1f54-11eb-800f-2f48a4d3669d.PNG)

How can fix these errors? Really appreciate your help!

Eric Fang

**Comment by ravibpatel** [comment]
You can try changing the output path of the ZipExtractor.exe for release mode. It is currently output it in Resources directory of AutoUpdater.NET as you can see [here](https://github.com/ravibpatel/AutoUpdater.NET/tree/master/AutoUpdater.NET/Resources). You can manually copy the ZipExtractor.exe after building it separately and then you can build the AutoUpdater.NET.

**Comment by EricFang2020** [comment]
Hello, Ravi,

I copy the ZipExtractor.exe and build a release. I still have following errors:
![Release_NG_V1 6 4_2](https://user-images.githubusercontent.com/73827450/98228856-74f9a400-1f59-11eb-8099-7f9086a56c4c.PNG)

But anyway, I can see new .dll created under path \AutoUpdater.NET\build\lib\net45
So I just use this .dll, and this .dll works!
AutoUpdater will unzip my installer and run it.

Are these release mode compile error OK? Thanks for your help!

Eric Fang

**Comment by ravibpatel** [comment]
The process can't access the file errors can happen if those DLL or EXE file is in use. Sometimes antivirus software can cause it too because they acquire lock on file when they scan them.
