### ISSUE TITLE
Does this work for updating a Windows Service?

### ISSUE THREAD

**Issue by cholojuanito** [ravibpatel/AutoUpdater.NET#426]
Just want to check and see if this would work with auto updating a Windows service on Windows 7.

**Comment by ravibpatel** [comment]
You have to implement the AutoUpdater.NET in a separate winforms project which will be responsible for handling the updates of the service. It is not possible to directly use it with a service.

**Comment by jeremy-russell-accesso** [comment]
@ravibpatel How do you get the separate project to analyze the binaries of the service to confirm that it needs to be updated?

**Comment by ravibpatel** [comment]
@jeremy-russell-accesso Create a new winforms project. Add NuGet package for this library into the new project. On winforms load event you can determine your service file version either by using [this method](https://stackoverflow.com/a/1755514/1273550) or any other method you prefer and assign it to InstalledVersion as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#provide-installed-version-manually). After that you can call the Start method of autoupdater to check for updates. This win forms executable should reside in the same folder as service files. You can stop the service by handling exit logic manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually).

**Comment by jeremy-russell-accesso** [comment]
@ravibpatel Awesome! I'll give that a shot. Thanks for the rapid response, much appreciated!

**Comment by cholojuanito** [comment]
Okay, thanks for responding. I'm only running a service so just being able to spin up a thread that checks every so often is what I need. Thanks!
