### ISSUE TITLE
Support for .NET 5

### ISSUE THREAD

**Issue by AlexBrunnerACAG** [ravibpatel/AutoUpdater.NET#430]
Hi my friends,

do you see a chance to implement support for .NET 5 in the near future?

We are currently in a transition process and migrate some projects to .NET 5.

I would greatly appreciate to hear from you.
Thank you very much.

Best regards,
Alex

**Comment by notpaimon** [comment]
So I guess it doesn't take off with .NET 5 at the moment, right?

**Comment by ravibpatel** [comment]
I am working on .NET 5.0 version on a separate branch. You can try it out from [here](https://ci.appveyor.com/api/buildjobs/y4a7kbb3vshn8108/artifacts/AutoUpdater.NET-1.6.5.zip). Let me know how it goes.

**Comment by ravibpatel** [comment]
Update NuGet pacakge to support .NET 5.0.
