### ISSUE TITLE
More than one item in xml file

### ISSUE THREAD

**Issue by stebla27** [ravibpatel/AutoUpdater.NET#433]
This issue is a question or a feature request:
Can I specify more than one item in the XML file?
My software is splitted into the main software and some Plugins. Can I describe this in my XML file and can I make independent updates for main software and PlugIns?
Note: A Plugin is not always a C# component. So there is no possibility to check the Assembly Version. In my case it could be also a ZIP file with some files which should be overwritten on update in the program directory.
Is this possible with the current version?

**Comment by CyberBitz** [comment]
Can you update your main app and drop the pluggins from the resources or embedded files?
