### ISSUE TITLE
Error in xml document (1,17)

### ISSUE THREAD

**Issue by NicoBellic44** [ravibpatel/AutoUpdater.NET#436]
Hello,

First of all sorry for my bad english (im french :) )

I've got an error in my app when i launch the autoupdater.start => Error in xml document (1,17)

The xml file is correct because it is working when i try to use it on a local ressource using IIS.

But it is not working when the file is on a dropbox url.

Any help would be great, thanks in advance :)

And Happy New Year !

**Comment by ravibpatel** [comment]
Can you provide XML file url?

**Comment by NicoBellic44** [comment]
https://www.dropbox.com/s/d1zezt04vwoxk55/version.xml?dl=0

**Comment by ravibpatel** [comment]
You won't be able to use the Dropbox URL like this as an XML file cause it shows XML preview in the HTML page. You need direct link to the XML file for it work.

**Comment by NicoBellic44** [comment]
Thanks a lot Ravi, just have to change the "www" with "dl" ans it works like a charm now.
