### ISSUE TITLE
Force update (download and install) current version manually.

### ISSUE THREAD

**Issue by patrikmichnac** [ravibpatel/AutoUpdater.NET#438]
Is there any options how to force download and install current version again and again even if version number is not changed? I just want to call 
    ```
    AutoUpdater.DownloadUpdate(args) 
    ```
and download and install current version again and again. For example I am just testing with one customer new version and adding some very small changes, I do not want to increase version number every time. I just want to allow user to reinstall current version.
I do not know how to set args parameters. I do not want to read XML from server, I just want to reinstall current verison.

**Comment by ravibpatel** [comment]
No, It is not possible. You must update the version in the XML file in order to trigger the update.
