### ISSUE TITLE
Extract zip with two files and run one of them

### ISSUE THREAD

**Issue by franukis** [ravibpatel/AutoUpdater.NET#439]
I've seen the replies about extracting and running a single file, but I am having some problems:

- When I open the solution, it prompts me to go .NET Framework 4.6.1, as I do not have 4.6.2... but I have 4.8 --> is it okay to target 4.8?

- I want to pack a setup.exe and setup.msi in a zip, and extract both, but run only the .exe. Is it possible? How should I modify the zipextractor?

-If I modify the provided solution and build it in my system... hiw should I handle it wit Nuget? I initially downloaded the nuget package in my own solution with the command provided in github, but I am not familiar with it, and don't know how to generate a package locally after building the solution

Thanks in advance!!

**Comment by ravibpatel** [comment]
You can target 4.8. It shouldn't be a problem. Your issue looks similar to #425. After you build the DLL file you can directly reference it without adding the NuGet package by right-clicking the project.

**Comment by ravibpatel** [comment]
In your case you can store filePath of exe file in executablePath  variable.

Inside the loop before [this line](https://github.com/ravibpatel/AutoUpdater.NET/blob/fc443c8b10681bf4b81edc0ce127da659b509e16/ZipExtractor/FormMain.cs#L138) add the following code.

```csharp
if (Path.GetExtension(filePath) == ".exe") {
   excutablePath = filePath;
} 
```
It should now execute the installer after the extraction finishes.

**Comment by franukis** [comment]
Thanks!! I solved the targeting issue already :)

However I tried your code chunk, and looks like it downloads the zip but does not launch the installer... so I have two doubts:

- after setting the executablePath, shouldn't we trigger some process start?

- as I see, the path does not include a filename after extracting, does it? Is it a problem if the zip filename does not match the name of the files contained?

Thank you!!!

**Comment by ravibpatel** [comment]
It extracts the file provided as executablePath [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L231). You need to move the new ZipExtractor.exe in [Resources](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/Resources/ZipExtractor.exe) folder and compile the AutoUpdater.NET again to make it work. I already set the release build path to that location, but you may have a different path so check it out.

**Comment by ravibpatel** [comment]
Yes, ZipExtractor makes log file when it extracts the contents of zip file. You can find it in your temp folder.

**Comment by franukis** [comment]
Ok, I have seen it... but all the logs I see (ZipExtractor.log) are from some days ago... and I have just run it. So it looks like it is not being properly launched, then?

**Comment by franukis** [comment]
BTW, after the download, I see a Windows dialog asking for permission to run Zipextractor, so it looks like it is being called, although that is the last thing I see

**Comment by ravibpatel** [comment]
You can try the DLL from [here](http://rbsoft.org/downloads/AutoUpdater.NET.zip). I have done the changes myself and tested it with the installer in zip.

**Comment by franukis** [comment]
Thanks, Ravi... your DLL works perfectly!

Now, I don't know where did I make the mistake...

**Comment by ravibpatel** [comment]
I added the same code I told you about earlier.  I also changed csproj file to target only one .NET framework. Currently, they are targeting multiple frameworks for making NuGet package.

**Comment by franukis** [comment]
It is weird... I have tried using the Nuget, or directly referencing the DLL, but it seems either I am not building zipextractor properly, or the proper version is not being imported in Autoupdater.NET Resources folder... and it seems related to this error with the file being in use

**Comment by ravibpatel** [comment]
If you target only one .NET Framework in AutoUpdater.NET.csproj and ZipExtractor.csproj then you won't get the file being in use error. You have to just change the TargetFrameworks tag to TargetFramework and keep only 1 framework in it. I changed it to the following.

```xml
<TargetFramework>net45</TargetFramework>
```

**Comment by franukis** [comment]
That was it, thank you very much!!!

Targeting only one version allowed to properly build zipextractor :)
