### ISSUE TITLE
Update an Windows Service

### ISSUE THREAD

**Issue by boonkerz** [ravibpatel/AutoUpdater.NET#44]
is it possible to update an windows service?

**Comment by ravibpatel** [comment]
@boonkerz I don't have experience with windows service. But I think it should work if you [handle the update logic manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). You may need to change the part where you exit the application. So for Windows service if AutoUpdater.DownloadUpdate() returns true then you need to stop the service so it will be no longer in use then it can start upgrading the files.
