### ISSUE TITLE
Mandatory mode set to 1 + Atl-F4 freezes update app

### ISSUE THREAD

**Issue by jimmycr** [ravibpatel/AutoUpdater.NET#440]
When **"\<mandatory mode="1"\>true\</mandatory\>"** is set, so there's only "Update button" visible, try close update app pressing Alt-F4 (update app shouldn't close because of mandatory mode set) and then click "Update" button. App will freeze showing
![obrazek](https://user-images.githubusercontent.com/15044491/105555635-1ea33280-5d0a-11eb-971b-31333bb83045.png)
and cannot be closed (must be closed using Task Manager)

**Comment by ravibpatel** [comment]
Can you try the new build from [here](https://ci.appveyor.com/api/buildjobs/pn83ji0s2jaajtj4/artifacts/AutoUpdater.NET-1.6.4.zip)? It should fix the issue.

**Comment by jimmycr** [comment]
seems OK! thanks
