### ISSUE TITLE
Disable message box "unavailable update"

### ISSUE THREAD

**Issue by NicoBellic44** [ravibpatel/AutoUpdater.NET#441]
Hi Ravi,

Is it possible to disable the message box "Update unavailable" if the versions match ?

**Comment by ravibpatel** [comment]
You can set the [ReportErrors](https://github.com/ravibpatel/AutoUpdater.NET#enable-error-reporting) too false to stop the message box.

**Comment by NicoBellic44** [comment]
Ok thanks but if i do so i won't be able to catch the real update errors, it would be interesting to dissociate real update errors from the unavailable update.

**Comment by ravibpatel** [comment]
If you're starting the update on application start then it is not a good idea to show any of the errors because it will be a background check but when users presses a button or menu item for checking updates it should show all types of error. The ReportErrors flag is based on this logic. You can [handle the update manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) using the event if you want more control over it.

**Comment by sremelis** [comment]
Hello Ravib!

Great tool man, thank you!

I have a little problem though:
I am using mandatory update on VB code (Windows Forms .NET 4.7.2) and the "update unavailable" popup keeps showing, even when I set `AutoUpdater.ReportErrors` to `false`. The app is updating when necessary, but all subsequent executions end up with this same message box.
The exact same code (with same `AutoUpdater` params, of course) runs on another .NET 4.7.2 app of mine without the above issue. This one also updates normally and never shows above message, even when `ReportErrors` is set to `true`.
Both apps start through Main() method and the only difference between them is that the second is written in C#.

Any ideas?

Thanks in advance!

**Comment by ravibpatel** [comment]
@sremelis If you see [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L474-L479). It only throws that error if ReportErrors is set to true. Are you setting the ReportErrors after calling the Start method?

**Comment by sremelis** [comment]
Thanks for your prompt response!
I get your point, however I am calling Strat() at the end, as you can see:

```
    AutoUpdater.Synchronous = True
    AutoUpdater.ReportErrors = False
    AutoUpdater.RunUpdateAsAdmin = False
    AutoUpdater.AppCastURL = My.Settings.UpdateURL
    AutoUpdater.Mandatory = True
    AutoUpdater.UpdateMode = Mode.ForcedDownload
    AutoUpdater.Start()
```

As I mentioned previously, the same code (except in C#) runs smoothly on another app of mine.
It really doesn't make any sense

**Comment by ravibpatel** [comment]
@sremelis Can you share your sample project where I can reproduce this?

**Comment by sremelis** [comment]
No need man, but thanks anyways!
Just recreated a new VB project and it runs as expected... Can't explain
it, don't care...

Thanks!

Στις Σάβ, 17 Ιουλ 2021, 08:21 ο χρήστης Ravi Patel ***@***.***>
έγραψε:
