### ISSUE TITLE
User closes the update window on a mandatory update cannot be handled properly

### ISSUE THREAD

**Issue by AlexBrunnerACAG** [ravibpatel/AutoUpdater.NET#442]
When an update is configured as mandatory and the user just closes the update window, the application continues to run and might crash.

Is there a way to check whether the user skipped the mandatory update with closing the form by clicking on [x] in the upper right corner of the update form?

Best regards,
Alex

**Comment by AlexBrunnerACAG** [comment]
There should be a property after a synchronous update called MandatoryUpdateCancelled in this situation.
Do you think you would be able to collect the information to get this property filled correctly?

**Comment by ravibpatel** [comment]
Why not just use "Forced" update mode, so the user can't cancel the update?

**Comment by AlexBrunnerACAG** [comment]
How can I set forced in xml? I just set mandatory to true in the xml file.

**Comment by ravibpatel** [comment]
It is in the docs [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file).

"Mode (Attribute, Optional): You can provide mode attribute on mandatory element to change the behavior of the mandatory flag. If you provide "1" as the value of mode attribute then it will also hide the Close button on update dialog. If you provide "2" as the value of mode attribute then it will skip the update dialog and start downloading and updating the application automatically."

```xml
<mandatory mode="2">true</mandatory>
```

**Comment by AlexBrunnerACAG** [comment]
The mode attribute did the trick.
Thanks for your quick response.
Best regards,
Alex
