### ISSUE TITLE
AutoUpdater.Start unable to fetch XML

### ISSUE THREAD

**Issue by Pulkitsoft** [ravibpatel/AutoUpdater.NET#443]
@ravibpatel  Can you please check what's going wrong, my link open perfectly in a web browser.

Error showing: "**There is a problem reaching update server. Please check your internet connection and try again later.**"

[https://www.pulkitsoft.com/wp-content/uploads/Download/PDFXPERT_Main.xml](https://www.pulkitsoft.com/wp-content/uploads/Download/PDFXPERT_Main.xml)

For testing purpose, XML contents are same as per yours.

**Comment by ravibpatel** [comment]
@Pulkitsoft Your server is returning "403 Forbidden" status code when you don't provide user agent. You should add the following line before calling AutoUpdater.Start method.

```csharp
AutoUpdater.HttpUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36";
```

**Comment by Pulkitsoft** [comment]
@ravibpatel thanks, working now.
