### ISSUE TITLE
System.IO.InvalidDataException

### ISSUE THREAD

**Issue by jhannesreimann** [ravibpatel/AutoUpdater.NET#444]
hey @ravibpatel 
I get this "System.IO.InvalidDataException" error, after clicking on "Update".

![Screenshot_8](https://user-images.githubusercontent.com/75742343/106387003-01402980-63d8-11eb-8885-5be72bfc2331.png)

it says:
"The end of the dataset in the central directory was not found."

is there maybe a way you could help me?

**Comment by ravibpatel** [comment]
It can be due to bad zip file.  Are your issue resolved?
