### ISSUE TITLE
Need silent update?

### ISSUE THREAD

**Issue by Pulkitsoft** [ravibpatel/AutoUpdater.NET#446]
Hi @ravibpatel,

Congratulation and thanks, your library working great.

Is it possible to **perform a silent update, without any user interaction**? I don't want installation process next, next, finish, Is any method in the library? I am using the AutoUpdater.NET-1.6.4 version.

Thanks in advance.

**Comment by ravibpatel** [comment]
You can call the start method at application startup and use [ForcedDownload](https://github.com/ravibpatel/AutoUpdater.NET#forced-updates) mode to update the app. It will show only download dialog and there will be no other user interaction require except maybe UAC prompt.

**Comment by Pulkitsoft** [comment]
Dear @ravibpatel 

I tried, its hide only standard update dialog box and start downloading and installing, but my MSI installer user interface shows me and wait for my instruction (Next, Next, Finish), Is any way to hide MSI installer user interface as well?

**Comment by ravibpatel** [comment]
You can try the suggestion from [here](https://stackoverflow.com/a/8560308/1273550). Just provide command line arguments using args tag in XML file.

```csharp
<args>/quiet /qn</args>
```

**Comment by AAN3AC** [comment]
You can try what I do:
      
      <?xml version="1.0" encoding="UTF-8"?>
      <item>
          <version>2021.1.6.0</version>
         
<url>http://www.yourwebsite.com/Apps/YourAppInstaller.exe</url>
          <args>/VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL
      /CLOSEAPPLICATIONS /FORCECLOSEAPPLICATIONS</args>
          <mandatory mode="2">true</mandatory>
      </item>
      
      Let me know if it works well for  you.
      
      Regards,
      Howard
      
      On 2/6/2021 15:20, Ravi Patel wrote:
    
    
      
      You can try the suggestion from here. Just provide
        command line arguments using args tag in XML file.
      
        <args>/quiet /qn</args>
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ravibpatel/AutoUpdater.NET/issues/446#issuecomment-774537955",
"url": "https://github.com/ravibpatel/AutoUpdater.NET/issues/446#issuecomment-774537955",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Pulkitsoft** [comment]
@ravibpatel - Many thanks,**` <args>/quiet /qn</args>`** its working for me.

@AAN3AC - Thanks you as well, unfortunately `<args>/VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL /CLOSEAPPLICATIONS /FORCECLOSEAPPLICATIONS</args>` not working for me.
