### ISSUE TITLE
Call two times in sequence and in async mode

### ISSUE THREAD

**Issue by johnnyontheweb** [ravibpatel/AutoUpdater.NET#447]
Hello,
I noticed that the code won't work if I call AutoUpdaterDotNET.AutoUpdater.Start for 2 times in not syncronous mode. The variable Running is true hence the second time (in which I need to check updates for another ring, with different base uri) the uri in the first call is used.
In other words, I need to wait until AutoUpdater ends execution for the 1st instance, then I can call the second time - it seems not possible using thread.sleep, it works only in syncronous mode.
Can you help on that? I'm trying to find out what's going on - I think this happens since Running is static.
thanks

EDIT:
this is not an elegant solution, but I solved by putting Running as public. In such a away, before to call the 2nd time, I used:
```vb
Do While AutoUpdaterDotNET.AutoUpdater.Running
            Application.DoEvents()
Loop
```
Any other ideas?

**Comment by ravibpatel** [comment]
You can use BackgroundWorker with synchronous mode to make it possible, or you can create an asynchronous method inside your app and do it inside it.
