### ISSUE TITLE
After download finished Application will close and nothing happens

### ISSUE THREAD

**Issue by KushFace** [ravibpatel/AutoUpdater.NET#45]
As the title says. The Message "oh theres a new update" is working and by clicking "Update" it will download the Update. After the Update is finished, the Application will close itself and thats it. In the folder where I started the Application, there is still the old Application. AutoUpdater.NET doesn't replace the old app with the new downloaded. And it also doesn't restart it after downloading.

I also tried to start my app with Admin Rights but got the same issue.

**Comment by ravibpatel** [comment]
You need to provide Zip or Installer file URL in the XML file. If you provide application executable itself it won't work. Even if you want to update only 1 file in the application directory you need to Zip it or Create an installer for it.
