### ISSUE TITLE
Systen.IO.IOException - The process cannot access the file

### ISSUE THREAD

**Issue by viningd45** [ravibpatel/AutoUpdater.NET#450]
Auto update always fails due to IO exception saying that a file to be updated is being used by another process. 

It is not caused by one specific file, sometimes the updater fails early in the update process and other times it fails near the end; but the reason is always the same IO error. 

I have checked all running processes and nothing is using the locked files, so I believe it is an issue on the updater's side. Has anyone else experienced this and found a workaround?

![image](https://user-images.githubusercontent.com/41274342/109517734-31c6c200-7a6f-11eb-8f61-cd984ea52635.png)

**Comment by ravibpatel** [comment]
Are you using the latest version of the library?

**Comment by ravibpatel** [comment]
Can you try removing the if statement from [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L145-L189) and compiling the DLL again? Just remove the if and else and move the code inside if block out of the if block to see if it shows which process is locking the file.

**Comment by viningd45** [comment]
Okay, now I am getting the following:

![image](https://user-images.githubusercontent.com/41274342/109527823-b585ac00-7a79-11eb-873d-5130ea316e5c.png)

**Comment by ravibpatel** [comment]
Before compiling both AutoUpdater.NET and ZipExtractor make sure you change [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.NET.csproj#L6) and [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/ZipExtractor.csproj#L6) line to following.

```xml
<TargetFramework>net45</TargetFramework>
```
