### ISSUE TITLE
ZipExtractor.exe is flagged on VirusTotal

### ISSUE THREAD

**Issue by qayyumabro** [ravibpatel/AutoUpdater.NET#452]
Hi, ZipExtractor.exe from the resources folder here is flagged on VirusTotal, please check.

https://www.virustotal.com/gui/file/b25e91015e84b2fab6cc860ebcb32de27eb540f7a49bf0d207706ae5177a4712/detection

**Comment by gHashFlyer** [comment]
Obviously a false positive: 2 rather obscure vendors flag it as malicious while 66 others do not.
