### ISSUE TITLE
Download update window hide or replace with other message box (window)

### ISSUE THREAD

**Issue by dardanshabani** [ravibpatel/AutoUpdater.NET#455]
Hi,

Is there any way to hide or do it in silent way downloading while not showing the progress of download and download window itself?

Thnx,

**Comment by ravibpatel** [comment]
There is no built-in way to do this, but You can do it by handling download yourself after subscribing to [CheckForUpdateEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) event. You can remove the UI related code from the [DownloadUpdateDialog.cs](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs) and use it inside the event.

**Comment by dardanshabani** [comment]
Yes, that's what I already did. Thank you.

**Comment by tekken387** [comment]
@dardanshabani hi, could you please what did u do to hide the download window? thanks
