### ISSUE TITLE
Use AutoUpdater for offline updates ? 

### ISSUE THREAD

**Issue by simchevr83** [ravibpatel/AutoUpdater.NET#456]
Hello 

Sorry if this question has already been answered, I could not find anything relevant using the search tool.

I would like to use AutoUpdater to do the "automatic" online updates (using the Zip file mode)

But some of my users will be on computers with no  internet at all, so I would like to know if there is a possibility to use the same tool but with a downloaded update  zip ? 

Ideally they would browse the update zip file in my software , and then I would trigger the update manually using  that zip ( but how could be managed the version comparison ? ) 

Thanks in advance

**Comment by ravibpatel** [comment]
It won't be possible to notify users about the update without internet. For using zip to update file part you can use the code from [this file](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs).

**Comment by simchevr83** [comment]
Thanks for the infos ,  I'll take a look  at it

**Comment by simchevr83** [comment]
Hi 

I managed to do it like you suggested, thanks.

But I could not access the ZipExtractor Resource in the assembly directly , (I tried several combinations like System.Reflection.Assembly.LoadFrom("AutoUpdater.NET.dll").GetManifestResourceStream("AutoUpdaterDotNET.Properties.Resources.ZipExtractor"); unsuccessfully)

So I copied a copy of ZipExtractor in my app Flde
