### ISSUE TITLE
Whether to consider upgrading to .NET 5.0/6.0?

### ISSUE THREAD

**Issue by wangpaishi** [ravibpatel/AutoUpdater.NET#457]
Whether to consider upgrading to .NET 5.0/6.0?

**Comment by ravibpatel** [comment]
You can try the .net 5.0 version from [here](https://ci.appveyor.com/api/buildjobs/y4a7kbb3vshn8108/artifacts/AutoUpdater.NET-1.6.5.zip).

**Comment by ThomasBoettcherHolschen** [comment]
@ravibpatel: First let me thank for your work on this.
But to be honest why is this not released to public ?
If I have to guess most of us use Nuget in these days, so a file-dependency is always not very good to maintain.

Is threre anything that I can do to get this up an running on .Net 5 ?

**Comment by ravibpatel** [comment]
@ThomasBoettcherHolschen I haven't tested it fully on .net 5. That is one of the reason I didn't release it. Waiting for someone to test it out because I am working on other projects using different language, so I rarely work on C# now.

**Comment by ThomasBoettcherHolschen** [comment]
Ok, I can spend some Time on it. What Tests are you expecting?

**Comment by ThomasBoettcherHolschen** [comment]
I've pulled your Net5 Branch and created 2 Projects. These Projects are just duplicates of your TestProjects, but with .Net 5 as Framework.
The WPF works fine. But I've got a problem on the Forms Project.

I'll get an unhandled Exception. Here is the Debug-Output. Any Idea what I'm doing wrong?


Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IO.FileLoadException: Could not load file or assembly 'AutoUpdater.NET, Version=1.6.5.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'AutoUpdater.NET, Version=1.6.5.0, Culture=neutral, PublicKeyToken=null'
   at AutoUpdaterTestNet5.Form1.FormMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Private.CoreLib.dll.
----------------------------------------
AutoUpdaterTestNet5
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Dev/Github/AutoUpdater.NET/AutoUpdaterTestNet5/bin/Debug/net5.0-windows/AutoUpdaterTestNet5.dll.
----------------------------------------
System.Runtime
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Runtime.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 5.0.5.0.
    Win32-Version: 5.0.521.16701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/System.Windows.Forms.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 5.0.5.0.
    Win32-Version: 5.0.521.16701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Collections.Specialized.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 5.0.0.2.
    Win32-Version: 5.0.421.11614.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/System.Drawing.Common.dll.
----------------------------------------
System.Threading
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Collections.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Threading.Thread.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.521.16701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/Accessibility.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Runtime.Extensions.dll.
----------------------------------------
System.Memory
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Memory.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.ComponentModel.TypeConverter.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.ComponentModel.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Collections.NonGeneric.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Private.Uri.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 5.0.5.0.
    Win32-Version: 5.0.521.16701.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.5/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Reflection.Metadata.dll.
----------------------------------------
System.IO.FileSystem
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.IO.FileSystem.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Collections.Immutable.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.521.16609.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.5/System.Text.Encoding.Extensions.dll.
----------------------------------------

************** JIT-Debuggen **************

**Comment by ravibpatel** [comment]
@ThomasBoettcherHolschen I want to check if all the configuration option still works correctly, and It can exit the application when download finishes. For WPF it can cause problems because it doesn't compile when I include [this lines](https://github.com/ravibpatel/AutoUpdater.NET/blob/net50/AutoUpdater.NET/AutoUpdater.cs#L564-L568) which are responsible for gracefully exiting the WPF application. Without that it will use Enviorment.Exit and it is not a good idea to use that method to exist unless it is absolutely required.

Try doing Clean Solution in Visual Studio and try rebuilding the project again. It should fix the issue.

**Comment by ravibpatel** [comment]
@ThomasBoettcherHolschen If you still encounter same issues then try removing the bin and obj folder from project directory.

**Comment by ThomasBoettcherHolschen** [comment]
Cleaning Solution has no effect. Deleting /bin and /obj folder no effect, too. Trying to get my Head arround what is happening here...

Using Rider for Develpment but there is no differnce for VS. Same Error here.

> For WPF it can cause problems because it doesn't compile when I include this lines which are responsible for gracefully exiting the WPF application. Without that it will use Enviorment.Exit and it is not a good idea to use that method to exist unless it is absolutely required.

![grafik](https://user-images.githubusercontent.com/2284286/115294887-74487900-a159-11eb-8859-6c425c517a7a.png)

![grafik](https://user-images.githubusercontent.com/2284286/115294924-7c081d80-a159-11eb-8a3d-93b2d4db661e.png)

References from WPF Project :
![grafik](https://user-images.githubusercontent.com/2284286/115295216-ca1d2100-a159-11eb-8ab0-50bc9fe14f9c.png)

References from AutoUpdater.NET Project
![grafik](https://user-images.githubusercontent.com/2284286/115295267-d99c6a00-a159-11eb-839a-604fa70beb97.png)

Maybe because there is no Reference to PresentationFramwork.dll in AutoUpdater.dll- Project ?
At this Point of my unterstanding of this Project I don't feel able to fix this... maybe when I unterstand the Code a litte bit better...

**Comment by ravibpatel** [comment]
Try changing [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/net50/AutoUpdater.NET/AutoUpdater.NET.csproj#L6) with the following code.

```xml
<TargetFramework>net5.0-windows</TargetFramework>
```

Do the same for ZipExtractor and it should work. Also make sure you are only targeting net5.0-windows in your WPF and WinForms project.

**Comment by ravibpatel** [comment]
I added the reference to it by adding UseWpf in csproj file as you can see [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/net50/AutoUpdater.NET/AutoUpdater.NET.csproj#L8). It seems like in .NET 5.0 you have to use UseWindowsForms to reference WinForms related dependencies and UseWpf if you want to reference WPF related dependencies in class library project.

**Comment by Dunge** [comment]
The linked appveyor page and blobs are down. Was this goal abandoned?

**Comment by ravibpatel** [comment]
@Dunge You can try the latest on from [here](https://ci.appveyor.com/api/buildjobs/5r0j4g160aejsjvd/artifacts/AutoUpdater.NET-1.7.0.zip). It is stable with some tests, I will be able to release it soon.

**Comment by ravibpatel** [comment]
Updated Nuget package with support for .NET Core 3.1 and .NET 5.0.
