### ISSUE TITLE
System.IO.InvalidDataException

### ISSUE THREAD

**Issue by musicianx2** [ravibpatel/AutoUpdater.NET#458]
Hello,
I get this "System.IO.InvalidDataException" error, after clicking on "Update".

![image](https://user-images.githubusercontent.com/34031699/114567587-0ba25d80-9c7c-11eb-9d28-c7510c4c7fce.png)
![image](https://user-images.githubusercontent.com/34031699/114567615-152bc580-9c7c-11eb-9ea2-eac60af4877b.png)

"The end of the dataset in the central directory was not found."
same with issue #444

and im sure zip file is not corrupted. Zip file is working fine.
What could be the problem?

Thanks.

**Comment by ravibpatel** [comment]
Can you try different program or compression method to create the zip file?

**Comment by musicianx2** [comment]
Thanks. I tried different program and it didnt give any errors but when extracting setup file its just dissappers and opens unupdated application. Because of unupdated application it asks for update again but never updates application. My setup file is msi setup file. AutoUpdater can't install app because it didnt uninstall first ? Does AutoUpdater should uninstall first?  How should i proceed.
Thanks for help.

**Comment by ravibpatel** [comment]
You shouldn't zip the msi file. Provide MSI file link directly as download URL in xml file.

**Comment by musicianx2** [comment]
Thanks for response. I thought i tried that before but I tried like you said anyway and it worked i guess i was wrong. Appreciated for help.
