### ISSUE TITLE
Index out of Range after Download

### ISSUE THREAD

**Issue by HelloKitty** [ravibpatel/AutoUpdater.NET#467]
After downloading a zip file from AzureBlob SAS URL it seems to fail with a non-descript Index out of Range. With no stack trace and I don't see a way to catch the exception to get more information related to it.

**Comment by HelloKitty** [comment]
Update: Setting ContentDisposition to "inline" on the Azure blob mitigates this issue. But why is explicit setting of the ContentDisposition required?

**Comment by ravibpatel** [comment]
You can test it by downloading the latest build from [here](https://ci.appveyor.com/api/buildjobs/5r0j4g160aejsjvd/artifacts/AutoUpdater.NET-1.7.0.zip).

**Comment by HelloKitty** [comment]
@ravibpatel This appears to resolve the issue. Either #468 or some other change in-between 1.6.4 to 1.7.x seems to fix the issue related to an empty ContentDisposition.
