### ISSUE TITLE
New Configuration to block message when there is no Update

### ISSUE THREAD

**Issue by KushFace** [ravibpatel/AutoUpdater.NET#47]
I included the `AutoUpdater.Start()` in my Window_Load Event. So it runs if the application starts.
But its not cool to get the Message "No Update there" everytime because the program starts.

Would be nice to have a Configuration like `AutoUpdater.MessageForNoUpdate = false;` which is true for default.

To prevent getting MessageBox of "No Update there, you have the newest version".

**Comment by ravibpatel** [comment]
Make sure you don't set AutoUpdater.ReportErrors to true otherwise it will throw errors like this.
