### ISSUE TITLE
Changelog from file

### ISSUE THREAD

**Issue by BElluu** [ravibpatel/AutoUpdater.NET#470]
Hi, is it possible to get changelog from file?
For example I have on my webserver changelog.txt and AutoUpdater will read it.
My repo is private, so I can not set url to Github Releases.

**Comment by NabaviFard-Mahdi** [comment]
UP

**Comment by ravibpatel** [comment]
Can't you just use the URL of the changelog.txt as changelog URL. Does it trigger the Download?

**Comment by ravibpatel** [comment]
Similar to #496.
