### ISSUE TITLE
So many directories with lang

### ISSUE THREAD

**Issue by BElluu** [ravibpatel/AutoUpdater.NET#471]
Hello.

1. Can I delete directories with langs which I do not use? If not, can I move them all to new directory?
2. If no and no, please refactor it and scale them into one place (directory).
![image](https://user-images.githubusercontent.com/11333925/125206294-dad7c180-e286-11eb-8266-15df1aa118eb.png)

**Comment by ravibpatel** [comment]
You can remove them. They are not required.

**Comment by BElluu** [comment]
Hi,
I added AutoUpdater.NET using NuGet and then Pulished to directory. Maybe I did something wrong and that's why I have that directories :)
Sorry, newbie here :D

**Comment by ravibpatel** [comment]
You can remove all the language directories. They are not necessary.

**Comment by BElluu** [comment]
Perfect! Thank you so much and have a nice day!

**Comment by BElluu** [comment]
Hi @ravibpatel I allowed myself to repopen this issue. Every new version which I compile, this directories with langs are created. Could it be that these folders weren't created during compilation?

**Comment by ravibpatel** [comment]
You can add msbuild task like [this](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/blob/master/ILRepack.Lib.MSBuild.Task/ILRepack.Lib.MSBuild.Task.targets#L40) that can remove the folders when you compile it.

**Comment by hawkeye-stan** [comment]
Finally found another answer in my project. You can add the following element in PropertyGroup in csproj file and the language folders will not be there when build or publish:

```
<PropertyGroup>
        ......
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
</PropertyGroup>
```

**Comment by jansohn** [comment]
> SatelliteResourceLanguages

@ravibpatel could you add this to the README please? Or consider switching to localized satellite packages instead: https://learn.microsoft.com/en-us/nuget/create-packages/creating-localized-packages#localized-satellite-packages

Then users can explicitly add those languages they actually need.
