### ISSUE TITLE
How update process work on .zip files?

### ISSUE THREAD

**Issue by dim0147** [ravibpatel/AutoUpdater.NET#472]
- Hi, I have a question, let's say my current app is version `1.0` like this:
![image](https://user-images.githubusercontent.com/44487221/126283147-2a5f1217-ba87-4d6a-ba34-627304bdb90a.png)
- Now I have added some features and build, ready release version '2.0' and version `2.0` will be like this:
![image](https://user-images.githubusercontent.com/44487221/126283356-4de62111-4412-4432-b1cc-8715dc66e51f.png)
- To implement the update, I will zip the release version `2.0` into `2.0.zip` :
![image](https://user-images.githubusercontent.com/44487221/126284360-2e09d51c-f612-4bf3-b183-4275339b3840.png)
- Upload zip file to the server, update the XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>2.0</version>
    <url>http://myserver.com/downloads/2.0.zip</url>
</item> 
```
- Now when the user hits update, the application will download `2.0.zip` and extract it to `current directory` right? Will it override the `app.exe` which is currently running or it will close `app.exe` and then start extracting the `2.0.zip`? Thank you

**Comment by ravibpatel** [comment]
It will close the app.exe and start extracting 2.0.zip. After extraction finishes, it will start the application again.

**Comment by dim0147** [comment]
Oh thank you, I didn't know this, can I ask you this, how do we know which files/folders needs to be updated when we release a new version? Let said `app.exe version 1.0`  have this code:
![image](https://user-images.githubusercontent.com/44487221/126285263-d7dda6cf-332c-466f-b530-74ae75dad938.png)
- In `app.exe version 2.0` the code will use some libraries and add some code:
![image](https://user-images.githubusercontent.com/44487221/126285457-7288d447-0c99-4b37-8ecd-439745589a72.png)
- In this case, the update `.zip` will contain `app.exe` for new codes and `new_lib_for_v2.dll` for new libraries only or we have to include all files and folders of `version 2.0` to replace completely `version  1.0`? Thank you so much

**Comment by ravibpatel** [comment]
Yes, You have to include all files needed to run the app in the update zip file. It will extract everything into the app directory and overwrites anything that already exists.

**Comment by dim0147** [comment]
Ok Thank you for your big help, now I am clear.
