### ISSUE TITLE
Hello world sample

### ISSUE THREAD

**Issue by sanchit1591** [ravibpatel/AutoUpdater.NET#473]
I am new to this package and so I am struggling to set it up. In the AutoUpdater.Start method, my program throws a file not found exception. I have created both my xml file and the .zip package on a public github repo and in my code I provide the raw github links to access the file. Please guide me as I don't understand where I am going wrong. My code can be found on https://github.com/sanchit1591/autoupdateTrial

**Comment by ravibpatel** [comment]
You are using it in console application. You have to add the following code after [this line](https://github.com/sanchit1591/autoupdateTrial/blob/master/autoupdateTrial.csproj#L9).

```csharp
<FrameworkReference Include="Microsoft.WindowsDesktop.App" />
```

You also have to use synchronous mode as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#check-for-updates-synchronously). I see you didn't add assembly version too. It won't be able to detect the update without it.

**Comment by sanchit1591** [comment]
I have updated my repository to include all your suggestions. Now I am able to detect a new version and download update but before finishing it throws an error saying "End of Central Directory record could not be found". I saw other issues on this repo with the same error (#444) but changing the zip method also didn't work. Can you take a look at my files and let me know what is possibly going wrong?

**Comment by ravibpatel** [comment]
I tried your project, but it works fine for me. It doesn't throw any errors.

**Comment by ravibpatel** [comment]
This can happen if your download is getting corrupted. You can include the checksum of the zip file in the XML file as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) to avoid this.

**Comment by sanchit1591** [comment]
Yeah before you tried it out, I figured out the error and now I don't receive any "End of Central Directory record could not be found" error. Instead now when I try to run my application, the update dialogue is shown. However when I click updates the package updates but before the update finishes the update dialogue box pops again and I go in an infinite loop where no files are updated but the dialogue box is shown again and again

**Comment by ravibpatel** [comment]
It can happen if the executable file in the zip file have the same assembly version as the executing file. You updated the version in XML file, but your executable file in zip still have version 1.5.0.0 which is same as old version, so it detects that 1.9.0.0 update is available when it executes. It uses Assembly version to check if there is new update is available or not.

**Comment by sanchit1591** [comment]
What all files should be packaged inside the .zip file? Should it be the entire project or just the files in the bin folder? Also do we need to publish the project for the library to work? Because I did what you suggested in the last comment and I made a new project and all but still I go in an infinite loop

**Comment by ravibpatel** [comment]
You should zip the files inside bin/Release or bin/Release/publish. I see your executable name is "autoupdateTrial.exe" but in the zip file it is "autoUpdateDemo.exe". It executes the executable file after the update, so you must have an executable with same name in zip file. It extracts the "autoUpdateDemo.exe" in the folder but executes the "autoupdateTrial.exe" which is still old so it asks for update again.
