### ISSUE TITLE
Q: How does it handle the app.config file?

### ISSUE THREAD

**Issue by JendolaRajda** [ravibpatel/AutoUpdater.NET#474]
Hello,
I am considering incorporating this into some of my projects, seems like a wonderful addition. However, I would like to know if there are any options in regards to updating/not updating the app.config file, since different users may have different values in the config file and I don't want them to be overwritten when an update happens.

**Comment by ravibpatel** [comment]
It just extracts the zip file to current application directory. You can avoid adding app.config in update zip or for finer control over the processs you should use installer instead of zip file.

**Comment by JendolaRajda** [comment]
So just leaving the config out when posting a zip with a new version is enough, sounds simple enough. Thank you very much for a swift reply!
