### ISSUE TITLE
Many language folders when publish

### ISSUE THREAD

**Issue by dim0147** [ravibpatel/AutoUpdater.NET#475]
Hi, when I publish the project I found many language folders in my build, is there any way for excluding those folders? My app
using English  only
![image](https://user-images.githubusercontent.com/44487221/126744581-1d8d192e-6a55-4e33-9552-223b97d9de28.png)

**Comment by ravibpatel** [comment]
You can remove those. They are not required.

**Comment by dim0147** [comment]
Is there any way automatically excluding those folders when publishing?

**Comment by ravibpatel** [comment]
You can publish a single file application if you are using .NET Core or .NET 5.0 or above as shown [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#publish-a-single-file-app---sample-project-file).
