### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by tensign1444** [ravibpatel/AutoUpdater.NET#476]
I made a windows form which uses this autoupdate feature. It is downloaded by an installer using the [Microsoft Visual Studio Installer](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects). Once I try to test updating it, the new installer downloads then says "Access to path is denied." I had also tried to zip the dll files and new exe, but still kept getting an error. I am installing it on another pc for testing which is where I am getting these errors. I installed it to program files(x84). Below is my code.
` AutoUpdater.DownloadPath = Environment.CurrentDirectory;
            AutoUpdater.Mandatory = true;
            AutoUpdater.UpdateMode = Mode.Forced;
            AutoUpdater.RunUpdateAsAdmin = true;
            AutoUpdater.Start("https://www.dropbox.com/s/8ywv9zvi2zt3l9q/ImmortalUpdateXML.xml?dl=1");
            `

**Comment by ravibpatel** [comment]
Are you getting this error when downloading, or after it downloads and start extracting?

**Comment by tensign1444** [comment]
I get this error after the download and it starts to extract to the path.

**Comment by ravibpatel** [comment]
If you get this at extraction stage, then you have to make the path accessible by the updater. If it was happening at download stage then you have the option to change download folder but at extraction change it is not possible.

**Comment by DasFragezeichen** [comment]
I had a similar problem. Could you check if it helps, to replace Environment.CurrentDirectory; with Application.StartupPath;?
See https://github.com/ravibpatel/AutoUpdater.NET/issues/481
