### ISSUE TITLE
[question] what is the better way only to check if a new version exist?

### ISSUE THREAD

**Issue by sanslash332** [ravibpatel/AutoUpdater.NET#478]
Exist a easy method to check if your program have a new available version?

I want implement on the UI a simple button to manually check updates.
If the answer is true, the classic update dialog of this library popups, like at the start of the program. In the case that not, simply do a small reaction.
Send a message through the active screen reader (for blind users) or the button blinks on red. something similar.

Exist a easy way to do that? A directly checkUpdate method? or the only way is override the method and do a complete manual update process.

¡thanks!

**Comment by ravibpatel** [comment]
The only way to do this is using event, as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).

**Comment by sanslash332** [comment]
@ravibpatel 
OK, thanks for the tip!

Maybe a checkUpdate method that simply returns a boolean will be a good option to be implemented. Somebody can concider it as usable :3

And thanks for the library. Convine this library will github actions to generate the XML and new releases of your program... Uf is a charm for your users the update process. You're a awesome.
