### ISSUE TITLE
Add simple option to check if update is available

### ISSUE THREAD

**Issue by DasFragezeichen** [ravibpatel/AutoUpdater.NET#479]
Could you please add an simple option to check if an update is available?
I think on something like

`bool AutoUpdater.UpdateAvailable`

So it's possible to create an easy way to check. For example:

```
if (AutoUpdater.UpdateAvailable == true)
{
    // Do something
}
else
{
    // Do something other
}
```

**Comment by ravibpatel** [comment]
You can do it using event as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).
