### ISSUE TITLE
Pass Parameter from old version to new version

### ISSUE THREAD

**Issue by KushFace** [ravibpatel/AutoUpdater.NET#48]
I saved my connectionString to a MySQL Database in app.config.
Settings.Default.Upgrade() only upgrades the UserSettings but not the connectionString.

So I think giving the connectionString as Parameter when Update from old to new version would be fine.
But as I can see, there is noo function to pass Parameters to new version. 

I guess it will be a good improvement.

**Comment by ravibpatel** [comment]
You can exclude app.config from Update file ( Installer or Zip ) so it won't overwrite the OLD file.

**Comment by KushFace** [comment]
Ou thanks.
