### ISSUE TITLE
Environment.CurrentDirectory should be replace with Application.StartupPath

### ISSUE THREAD

**Issue by DasFragezeichen** [ravibpatel/AutoUpdater.NET#481]
I have an information for you.

I installed my application with Innosetup and set it to start with Windows. AutoUpdater.NET wants to extract the update.zip to C:\Windows\SysWOW64. By starting the application normal that doesen't happen.
https://jrsoftware.org/isfaq.php#startup

I asked for help in a german C#-Board and the soluition was to repleace "Environment.CurrentDirectory" with "Application.StartupPath".
https://mycsharp.de/forum/threads/124122/autoupdater-net-gibt-fehler-wenn-programm-aus-autostart-gestartet-wird?page=1
https://mycsharp.de/forum/threads/124122/autoupdater-net-gibt-fehler-wenn-programm-aus-autostart-gestartet-wird?page=1#forumpost-3832224

So perhaps it's usful to modify the Dokumentation.
https://github.com/ravibpatel/AutoUpdater.NET#specify-where-to-extract-zip-file-containing-updated-files

**Comment by ravibpatel** [comment]
Thanks for reporting. I will do it asap.

**Comment by ravibpatel** [comment]
Updated in README.md.
