### ISSUE TITLE
No application is associated with the specified file for this operation.

### ISSUE THREAD

**Issue by DiaryOfAstra** [ravibpatel/AutoUpdater.NET#484]
I uploaded the rar file here in a github repo and the xml file too, everything worked well until the update started
![Capture](https://user-images.githubusercontent.com/90661172/133176962-8a8c5039-c496-4f0a-a404-b3e2f163fd33.PNG)
the file's size is 1KB, don't know from where did that 300+ KB come from.. and after it finishes, it gives me that message.

Any solutions?

**Comment by ravibpatel** [comment]
It only works with zip files.
