### ISSUE TITLE
Replace XML with an Interface to get needed info

### ISSUE THREAD

**Issue by integral-llc** [ravibpatel/AutoUpdater.NET#49]
Using XML is good, but what if I have already a REST service that gives me JSON instead, even in a different format. Why not use an interface to be implemented by the application developer to query his server in the way he wants? That would create more flexibility.
In my case, I have control over the WinForms app, but not on the REST service, and there is no way the service to be changed. As such I cannot use the library.
Any ideas?
Thx

**Comment by integral-llc** [comment]
I have made the needed changes, but cannot push my branch to create a pull-request. Would you please allow me?
Thx

**Comment by ravibpatel** [comment]
Just open a Fork the project to your account then you can open the pull request.
