### ISSUE TITLE
text being cut in the notification window

### ISSUE THREAD

**Issue by marcelomera** [ravibpatel/AutoUpdater.NET#497]
text being cut in the notification window, follows the print where the text that was partially cut is marked in red

![image](https://user-images.githubusercontent.com/57372471/143159210-8c250be3-c6d1-4b19-88e8-a716e9ce3a09.png)

**Comment by ravibpatel** [comment]
Which language are you using?

**Comment by marcelomera** [comment]
pt-BR

**Comment by ravibpatel** [comment]
Which version are you using? For me, it works fine. I even tried a longer application name, and it wrapped to the next line perfectly.

**Comment by xiaoff1234** [comment]
text cut,there is indeed this problem.
It's not a language problem, but the system resolution is too small or the zoom ratio is too large
![7](https://user-images.githubusercontent.com/97714598/149440705-4f429da2-e7ea-43db-9259-f476932fb046.png)

**Comment by SeanWickstrom** [comment]
I think the issue is caused by line 102 in UpdateForm.cs
  var labelSize = new Size(Width - 110, 0);

I think it should be
  var labelSize = new Size(Width - labelUpdate.Left, 0);

**Comment by ravibpatel** [comment]
I applied the fix @SeanWickstrom suggested. Can you test if it works or not? You can download the latest lib from [here](https://ci.appveyor.com/api/buildjobs/52adn1hy8bd07uto/artifacts/AutoUpdater.NET-1.7.1.zip).

**Comment by SeanWickstrom** [comment]
@ravibpatel that did the trick.  thanks for the quick response.

**Comment by ravibpatel** [comment]
@SeanWickstrom Do you get this issue on DownloadUpdateDialog as shown in screenshot posted by @xiaoff1234. I can't reproduce it for DownloadUpdateDialog.

**Comment by SeanWickstrom** [comment]
@ravibpatel I am not able to reproduce that issue either.
