### ISSUE TITLE
Can not run extract when main app run on Admin right

### ISSUE THREAD

**Issue by zaiplanet** [ravibpatel/AutoUpdater.NET#499]
File app.manifest in main app is set as below:
`<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`

if main app run normal without admin rights, everything works fine.
**if main app run as Admin right:**
- Check update and download complete.
- But when extract file is freeze at  _**Waiting for application to exit...**_
and main app still running and main app do not exit
Please check this

![image](https://user-images.githubusercontent.com/58675403/145670496-8d2e389b-bed3-4af3-8145-8d533fd29b59.png)

**Comment by mosoftwareenterprises** [comment]
I had a similar issue. Turned out I have a FormClosed & FormClosing event that cancelled the event. So it never shutdown.
I solved it by unsubscribing from those events in the AutoUpdater.ApplicationExitEvent before calling Application.Exit().

**Comment by ravibpatel** [comment]
This can only happen if the app is unable to exit for some reason. You have to handle ApplicationExitEvent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually) and make sure it exists properly.
