### ISSUE TITLE
AutoUpdater.NET.pfx files is missing from solution.

### ISSUE THREAD

**Issue by Talagozis** [ravibpatel/AutoUpdater.NET#5]
AutoUpdater.NET.pfx files is missing from ZipExtractor project. Should that file be there? or an other .pfx files is needed to be created?

**Comment by ravibpatel** [comment]
I didn't notice it until now. I used the same pfx file as used with AutoUpdater.NET. You can sign them with your own .pfx files for now and use it in your project. I will provide signed version of the dll with the final release of AutoUpdater.NET 1.4.
