### ISSUE TITLE
Application won't get closed

### ISSUE THREAD

**Issue by Danny-P** [ravibpatel/AutoUpdater.NET#501]
Hi,
I am using this great package inside a simple application that runs as long as the user is logged in. 
On Application start it checks for updates and forces to install them. But the application hangs on "Waiting application to close". 

But the Application isn't closed, so the update never finishes. 

Can you help me on this?

**Comment by ravibpatel** [comment]
You can handle the application manually using the following code.

https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually

**Comment by Danny-P** [comment]
Thank you! I used it and with a small piece of logic it's working fine.
