### ISSUE TITLE
UseLatestIE exception when used from unmanaged process

### ISSUE THREAD

**Issue by gmichaud** [ravibpatel/AutoUpdater.NET#51]
I am using AutoUpdater.NET from a Microsoft Excel add-in and the UseLatestIE function is throwing an exception because Assembly.GetEntryAssembly() is returning NULL. This behaviour is described on MSDN: https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getentryassembly

P.S. overriding this registry key by default might not be a good idea; it could interfere with applications that are already setting this to force a specific version.

**Comment by gmichaud** [comment]
Sample fix https://github.com/gmichaud/AutoUpdater.NET/commit/3f37a9c0d210a3925b1e32f48bef6741573984f0

**Comment by ravibpatel** [comment]
@gmichaud Are you providing the assembly in Start method?

**Comment by gmichaud** [comment]
I am passing ``System.Reflection.Assembly.GetExecutingAssembly()`` to the Start method -- that would be the path to the Excel add-in, and not an actual .exe file. Changing UseLatestIE to use the assembly passed to Start would fix the crash, but system would still create a (useless in this case) registry entry.

**Comment by ravibpatel** [comment]
Can you open a pull request with this change?

**Comment by gmichaud** [comment]
Yes I will
