### ISSUE TITLE
Silent update

### ISSUE THREAD

**Issue by muccix** [ravibpatel/AutoUpdater.NET#52]
Is it possible to perform a silent update, without the need for user interaction?

Typically that is feasible using a batch file with the following command:

msiexec /i file.msi /q

Many thanks

**Comment by ravibpatel** [comment]
@muccix You need to edit the source code DownloadUpdateDialog.cs to make this possible. Just change the processStartInfo variable at line 68 as shown in the following link.

[https://stackoverflow.com/questions/25738066/how-to-run-msi-installer-in-cmd-as-admin-using-c-sharp](how-to-run-msi-installer-in-cmd-as-admin-using-c-sharp)

**Comment by muccix** [comment]
Ok, thanks,

One question: from a practical point of view, putting in the zip files all the files changed from the previous version is equivalent to install a new version via a .msi file?

Many thanks

**Comment by ravibpatel** [comment]
@muccix Yes, It is the same thing unless your new version installer requires registry changes or some special thing that can only be done using an installer.

**Comment by AshotN** [comment]
Can you please add the ability to pass command line arguments like /quiet or /passive
