### ISSUE TITLE
Generate Nuget Package

### ISSUE THREAD

**Issue by FlameadoDeMoe** [ravibpatel/AutoUpdater.NET#522]
Hi, I'm trying to build the Nuget package for this project. I want to build for the 3 platforms net45, netcore-3.0 and net5.0, but when I'm trying to use the package, the download of the update it's fine but the zipExtractor does not executing.

If I build it only for net45 like says @ravibpatel in #450, it's working. But I need it for the 3 platforms (or at least netcore-3.0 and net5.0).

How can I do it? Thanks in advance.

**Comment by ravibpatel** [comment]
You have to build the ZipExtractor first in Release configuration and after that try to build the AutoUpdater.NET.

**Comment by FlameadoDeMoe** [comment]
> You have to build the ZipExtractor first in Release configuration and after that try to build the AutoUpdater.NET.

Yes, I'm building first ZipExtractor in Release configuration, then AutoUpdater.NET in Release configuration too. Both with the 3 TargetFrameworks (net45;netcoreapp3.1;net5.0-windows). Until this point, all fine.

Then, I generate the NuGetPackage(.nupkg) using: `nuget pack Autoupdater.NET.Official.nuspec` inside the AutoUpdater.NET build folder. 

Once the package is generated, I add it to my project, all fine. But when I execute my code and a new version is available, the download is fine but the zipextractor does not executing.

I don't know if I'm generating the NuGet Pack right. 

My project is running in NET 5.0.

Thank you for your help.

**Comment by ravibpatel** [comment]
ZipExtractor TargetFramework should match the AutoUpdater.NET TargetFramework or you will have a compatibility issues. If you see the [appveyor.yml](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/appveyor.yml) you will see I first compile the ZipExtractor in specific TargetFramework then it compiles AutoUpdater.NET using same TargetFramework.

**Comment by FlameadoDeMoe** [comment]
Thanks, it's working fine now.
