### ISSUE TITLE
Downloads but doesn't install

### ISSUE THREAD

**Issue by methc** [ravibpatel/AutoUpdater.NET#53]
Hi Guys,

I have an issue where it detects the new update, downloads and closes the main app/program but after the download the old app just reopens again. The new version never gets installed.

**Comment by methc** [comment]
Additional info:

I did some more digging. In the %temp% folder I can see the update.zip file and ZipExtractor. 

I tried running ZipExtractor by double clicking it. It runs and get's stuck at the extracting... screen. Progress bar is empty. Nothing happens after this. Upon trying to close ZipExtractor by clicking the X button at the top of the window I get;

"Unhandled exception has occurred in your application. If you click continue the application will ignore this error and attempt to continue If you click quit the application will close immediately. Object reference not set to an instance of an object."

**Comment by ravibpatel** [comment]
@methc You can't run the ZipExtractor directly from temporary it requires arguments to work properly. Can you provide me with the URL of your XML file?

**Comment by methc** [comment]
I'm using a UNC as the URL to the update.zip file. 

The unc I'm using is:-
"\\server01\software\autoupdate\update.zip"

Thanks for the reply.

**Comment by ravibpatel** [comment]
@methc You said your update.zip was in temp folder after download completed that means it can access and download the file but maybe it was corrupted or incompatible. Try using a different application to zip files. I use 7Zip to zip them.

**Comment by methc** [comment]
Well I thought it was perhaps corrupt but I ruled that out by going into temp and opening the zip manually and double clicking the file the setup file, which extracted file and started the installation. Installation went through fine. 

As for incompatibility, it's possible... I used winrar with the zip option to create the archive. I'll try your suggestion and try 7zip.

**Comment by ravibpatel** [comment]
@methc Are you zipping the installer file?

**Comment by methc** [comment]
Yes, I zipped up the two setup files.

**Comment by ravibpatel** [comment]
@methc No, You can't do that. You need to provide update.zip with all the updated files of the application or provide a setup file URL directly in the XML file.

**Comment by methc** [comment]
Ahhhh. I see. I read all the documentation, don't think I came across that bit. Thanks for clarifying for me. 

Question: if I zip up the actual software files. After the update, will add/remove control panel update the version number of the app? I'm pretty sure it wouldn't. 

Anyway, heading to work now. Will try your solution in a bit.

**Comment by ravibpatel** [comment]
No, It won't show new version number in the control panel. That's why I prefer to use Installer instead of zip file.

**Comment by methc** [comment]
It's all sorted now, thanks to you for helping me see where I was erring. 

Only problem I have no (which is totally unrelated to your autoupdate CL) is the installer just gave me two options - 1) repair installation 2) remove. 
I chose remove, all the installer did was remove the software. It didn't try to reinstall. 

Like I said... totally unrelated to your project. 

Great work on the auto-updater! I must say, really good support too!

**Comment by roscofil** [comment]
Hello there,
Am in the same situation as methc described...Didn't realize that zipextractor doesn't work with msi and setup.exe files.
Pardon my ignorance, being somewhat a newbie in this autoupdate process, but I do have a question:
my project contains many subdirectories with html help files and such...
Does this mean that I have to create one <item> tag for each file that gets modified?
If yes, does this mean that my server repository must mimic my real local install?

Thanks for clarifying it and a really great thumsbs up for this huge help!

Best regards from Paris, France

Philippe

**Comment by methc** [comment]
@roscofil - The ZipExtractor extracts your programs files and places it in the target directory (original location where your software is installed). I haven't yet tested this method as I much prefer to do the installer method. 

> Pardon my ignorance, being somewhat a newbie in this autoupdate process, but I do have a question:
my project contains many subdirectories with html help files and such...
> 
There are two approach to this. 
1) You can actually use VB .NET or some other 3rd party setup/install maker to create an installer (msi or exe)
2) You can use 7zip or another archiving utility to create a zip file that will contain the entire bin directory of your project (exe's, dll's, help file's etc)

In the case of option 1 all you need to do is set the path to the .msi or .exe installer in the XML file. AutoUpdater will launch the installer and get the process started. 

In the case of option 2 you'll need to create a zip of your software files, set the XML path tag to point to the zip file. AutoUpdater/ZipExtractor will unzip files to your target directory. 

> Does this mean that I have to create one item tag for each file that gets modified?
> 
You do not need to create multiple path tags. Just one path tag will do in either option I detailed above.

I just started using this class library so I don't know everything there is to know about it but I hope this helped in some way. 

PS - next time create a new post in the forum instead of posting to an existing post, so folks can better assist you.

**Comment by roscofil** [comment]
@methc : Thanks for your fast comment and sorry to post in a post but I figured that, since it was almost exactly the same issue it was useless to create a duplicate.

This said, I must say that my project is written in VB.NET and that I use the VS2017 installer stuff( .msi and setup.exe)
I first tried to zip these 2 files and add the zipfile to the xml update file (option 1). This did exactly what you described in your post.

I then tried as a test to add just one item with my main exe, but then I ran into an Avast web agent issue which detected a false positive and blocked the connection.

With option 1 (which is what I'd really prefer by far), the thing is you can't just use a link to the zipped msi as you never know if the client pc will have the appropriate .net platform, so setup.exe is required.

If I'm right, the question then becomes: how to unzip and run setup.exe?

Thx

Philippe

**Comment by methc** [comment]
@roscofil 

> If I'm right, the question then becomes: how to unzip and run setup.exe?
> 
You don't need to zip the installer. Just update the path tag to reflect the location of the installer (.exe)

**Comment by ravibpatel** [comment]
@roscofil Between URL tag of the XML file you need to provide the URL of your installer file (.exe or .msi).

**Comment by roscofil** [comment]
OK...Thanks to both of you!
I got it to download and extract ok creating a single file installer combining both the msi and setup.exe with WinRar SFX.
This way, I just indicated the single exe name in the xml tag and it works.
Again, thanks to ravibpatel for bringing this great tool!

Cheers

Philippe

**Comment by methc** [comment]
Glad you got it working, it's a great tool instead. Many thanks to @ravibpatel
