### ISSUE TITLE
How to not restart after upgrade?

### ISSUE THREAD

**Issue by rmcrackan** [ravibpatel/AutoUpdater.NET#531]
When I run the below code example, it does the software download then waiting for application to exit. I exit the application. Update completes, app restarts. How can I configure AutoUpdater so that final restart does not occur. I assume that when the user exits the program, they don't want it to open again.

    string repoUrl => "https://github.com/rmcrackan/UpdaterExample/releases/latest";
    // in production: get these from github api
    string downloadUrl => "https://github.com/rmcrackan/UpdaterExample/releases/download/v7.6.3/UpdaterExample.7.6.3.zip";
    string latestVersionOnServer => "7.6.3.2";

    private void Form1_Load(object sender, EventArgs e)
    {
        AutoUpdater.ParseUpdateInfoEvent += args =>
            args.UpdateInfo = new()
            {
                CurrentVersion = latestVersionOnServer,
                DownloadURL = downloadUrl,
                ChangelogURL = repoUrl
            };
        AutoUpdater.CheckForUpdateEvent += args =>
        {
            if (args is not null && args.IsUpdateAvailable)
                AutoUpdater.DownloadUpdate(args);
        };
        AutoUpdater.Start(repoUrl);
    }

**Comment by ravibpatel** [comment]
Currently, there is no way to do this. You have to use the installer as the update file and configure it in installer, or you have to modify the ZipExtractor by downloading the source code. This [line](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L242) restarts the process. You can comment it out and compile AutoUpdater.NET to produce the desired behaviour.
