### ISSUE TITLE
Changelog Doesn't Display in Other Languages Properly

### ISSUE THREAD

**Issue by squiey** [ravibpatel/AutoUpdater.NET#540]
I want to use **changelog.txt** file to keep my change logs to display in the update dialog. But in the update dialog if the words not in English, shows as random char like " **MÃœÅžTERÄ° Ä°ÅžLEMLERÄ°** ". How can I fix this issue? Thanks in.
![Screenshot_79](https://user-images.githubusercontent.com/106429978/174300484-946f6f95-3e39-4b8d-a3fa-ff4e003ade88.png)

**Comment by squiey** [comment]
I cannot provide the URL but I'll attach the files that is causing the issue
[changelog.txt](https://github.com/ravibpatel/AutoUpdater.NET/files/8940841/changelog.txt)
 
![Screenshot_84](https://user-images.githubusercontent.com/106429978/174609393-e45f94f8-55d0-475d-9283-7a45eafa8310.png)

**Comment by ravibpatel** [comment]
I am able to reproduce this issue, but changing the text file encoding to "UTF-8-BOM" fixed the issue. You can see the modified file below.

[changelog.txt](https://github.com/ravibpatel/AutoUpdater.NET/files/9542319/changelog.txt)
