### ISSUE TITLE
Just open 7Zip when updating

### ISSUE THREAD

**Issue by Feneck91** [ravibpatel/AutoUpdater.NET#541]
Really strange.
When a new version is updated, I can see the dialog that explain to me that the application must be updated.
I clic on update and then 7Zip open the updated zip file and application is quit.
Nothing is done.

My code is a WPF application
Code (simplified) is:
```
public partial class DataManagerApp : Application
{
        private void AutoUpdater_ApplicationExitEvent()
        {
            Application.Current.Shutdown();
        }

        protected override void OnStartup(System.Windows.StartupEventArgs _eStartupEvent)
        {
                   ....... some code ......
                    AutoUpdater.Synchronous = true;
                    AutoUpdater.RunUpdateAsAdmin = false;
                    AutoUpdater.OpenDownloadPage = true;
                    AutoUpdater.ReportErrors = true;
                    AutoUpdater.ApplicationExitEvent += AutoUpdater_ApplicationExitEvent;
                    AutoUpdater.Start(@"file://Y:/Tools/some other directories/AutoUpdaterXX.xml");
                   ....... some code (skipped if exit event is called) ......
    }
}
```
So it doesn't work for me...

**Comment by ravibpatel** [comment]
You must use a zip file as your update file for it to work, and your zip file structure must match your application file structure.

**Comment by Feneck91** [comment]
The update file is a zip file with no root folder (like where the program is running). May be I must put the program zip file structure with root folder? Same name as the folder where the program is running?

**Comment by Feneck91** [comment]
I found the problem in UpdateForm.cs:
`        private void ButtonUpdateClick(object sender, EventArgs e)
        {
            if (AutoUpdater.OpenDownloadPage)
            {
                var processStartInfo = new ProcessStartInfo(_args.DownloadURL);

                Process.Start(processStartInfo);

                DialogResult = DialogResult.OK;
            }
            else
            {
                if (AutoUpdater.DownloadUpdate(_args))
                {
                    DialogResult = DialogResult.OK;
                }
            }
        }`
The url is file://Y:/Tools/Geomaps/DataManager/AutoUpdater_DataManager_4.6.8.3152.zip
My xml is:
`<?xml version="1.0" encoding="UTF-8"?>
<item>
  <version>4.6.8.3152</version>
  <url>file://Y:/Tools/Geomaps/DataManager/AutoUpdater_DataManager_4.6.8.3152.zip</url>
  <urlR>file://D:/Dev/Geomaps/AutoUpdater_DataManager_4.6.8.3152.zip</urlR>
  <changelogT>file://Y:/Tools/Geomaps/DataManager/changelog/AutoUpdater_DataManager_4.6.8.3152.txt</changelogT>
  <mandatory minVersion="4.6.8.3152">true</mandatory>
</item>`

The Process.Start(processStartInfo); just open the Zip file.

**Comment by ravibpatel** [comment]
You have to remove line "AutoUpdater.OpenDownloadPage = true". As its name suggests, it will open the URL you provide in the browser. Zip won't be handled by the library if you set this true.

**Comment by Feneck91** [comment]
I don't know if it is a bug, but when the version is mandatory, you cannot pass, only update button is available (it's a normal behaviour).
But you can close the dialog by cricking on upper right cross (or ALT + F4) => the update window is closed without doing the update!

I add the code;
```
                                    AutoUpdater.ShowUpdateForm(_args);
                                    if (_args.Mandatory.Value && _args.InstalledVersion < new Version(_args.Mandatory.MinimumVersion))
                                    {   // If the version is mandatory always close the app, continue to run it is forbidden
                                        s_bRunning = false;
                                        Application.Current.Shutdown();
                                    }
```

**Comment by ravibpatel** [comment]
It is expected behavior. When you set the Mandatory to true, Remind Later and Skip is ignored, and that functionality will be unavailable. If you want to exit the app when you close the update form, then you can use [forced updates](https://github.com/ravibpatel/AutoUpdater.NET#forced-updates).
