### ISSUE TITLE
Check if there is anything to update?

### ISSUE THREAD

**Issue by khoshbin** [ravibpatel/AutoUpdater.NET#542]
Hi 
  I've an application launcher that checks for updates and then runs the main application and exit.
At first I run:
AutoUpdater.Start("url");

But I don't have any clue if there is anything to update or not. I want to wait for AutoUpdater if there is any updates otherwise run the main application and exit the launcher.

Thanks

**Comment by ravibpatel** [comment]
You can [handle update manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) to accomplish this.

**Comment by ravibpatel** [comment]
You can still use the original update form that comes with the library using the below code. You don't have to write any extra code. The event is provided, so you can adjust the flow. Event is working like a callback here. You are getting everything it fetched about the latest update in the event args. You won't have to implement any logic that the library is already doing.

```charp
AutoUpdater.ShowUpdateForm(args);
```

**Comment by khoshbin** [comment]
Thank you so much
