### ISSUE TITLE
Add CheckForUpdateDoneEvent

### ISSUE THREAD

**Issue by Feneck91** [ravibpatel/AutoUpdater.NET#543]
Is it possible to add a notification (like CheckForUpdateEvent) when the check for update is done (with parameter that indicate it will update or not?

I would like to add a splash screen that indicate to the user that the update is checking but I have no way to close the splash screen before the update dialog is show to the user, so the dialog appears under the splash, it's not really beautiful.
So for the moment: no way to add it. The goal is to let all update like it is actually working.

When checking is done, if an event could be called I can take decision to close the splash screen.
Thanks.

**Comment by ravibpatel** [comment]
CheckForUpdateEvent is triggered after the checking is done. You can call Start method than show splash screen and in CheckForUpdateEvent you can hide the splash screen.

**Comment by ravibpatel** [comment]
You don't need to do it. You can just call ShowUpdateForm(args); and it will work. If there is update, show the update form, otherwise launch the application. I attached sample code you can use.

```csharp
AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;

private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
{
    if (args.Error == null)
    {
        if (args.IsUpdateAvailable)
        {
            AutoUpdater.ShowUpdateForm(args);
        }
        else
        {
            // Launch your app.
        }
    }
    else
    {
        if (args.Error is WebException)
        {
            MessageBox.Show(
                @"There is a problem reaching update server. Please check your internet connection and try again later.",
                @"Update Check Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
        else
        {
            MessageBox.Show(args.Error.Message,
                args.Error.GetType().ToString(), MessageBoxButtons.OK,
                MessageBoxIcon.Error);
        }
    }
}
```

**Comment by ravibpatel** [comment]
It depends on your use case. If you want to use Mandatory flag, then feel free to use it. DownloadUpdate method is also public, so you can directly use it too. You won't need to do SetTimer for remind later, because it will be done for you even if you use this event.
