### ISSUE TITLE
Can I see the Class Diagram of the autoupdater?

### ISSUE THREAD

**Issue by DarkBrain-LP** [ravibpatel/AutoUpdater.NET#544]

**Comment by DarkBrain-LP** [comment]
I'm working on an autoupdater that could updater many applications. I'm having problems in class diagram design. Can I look at yours please ?

**Comment by ravibpatel** [comment]
You can download the source code and generate the Class Diagram using the Visual Studio. Feel free to use any code you want in your updater.
