### ISSUE TITLE
Startup arguments don't appear to be working?

### ISSUE THREAD

**Issue by arpIdeas** [ravibpatel/AutoUpdater.NET#546]
I'm trying to get my .NET Core WPF app to "know" when it's being ran after an update. It seems like a simple argument should suffice, so I've added `<args>update</args>` to the update XML file (currently testing things offline using `file://` paths).

At the moment my app will just display a message when ANY argument is provided, which I've verified to be working (`MyApp.exe something` will make it display the message). However when the app's started after an update this message isn't displayed.

Note - I'm using zipped updates.

Am I doing something wrong or is this possibly a bug? I'm currently using version 1.7.3 of Autoupdater.

EDIT: I'm looking at the code for Autoupdater and apparently this is a bug or is poorly documented. If the update is using ZIP it's not using the installer arguments parsed from the XML file. `DownloadUpdateDialog.cs` creates a `processStartInfo` based on the provided `installeerArgs` (if any), but if the extension is ZIP it'll override this object with a new one that uses `Environment.GetCommandLineArgs()`. This last bit is probably a mistake.

**Comment by ravibpatel** [comment]
installerArgs is used for installer (.exe or .msi). When you use zip, it passes the arguments this current instance was started with, and it runs the updated exe with that argument. You can see it [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L47). In your case, it should work without passing args in XML if your app started with some command line arguments and updated.

**Comment by andrewalter1** [comment]
I have the same issue, since v 1.7.1. the app always restarts with empty commandline args if AutoUpdater.ClearAppDirectory is false. the problem is that you append "-c" before the app commandLineArgs in DownloadUpdateDialog.cs line 159.
so if AutoUpdater.ClearAppDirectory is set to false, there are only 4 arguments passed to ZipExtractor. commandLineArgs are always empty then in FormMain.cs line 47.

**Comment by ravibpatel** [comment]
@andrewalter1 Thanks for the suggesting. It was exactly the issue you mentioned. I fixed it in the latest commit. You can try it out from [here](https://ci.appveyor.com/api/buildjobs/qsmuen4fnb2ibvs3/artifacts/AutoUpdater.NET-1.7.4.zip).
