### ISSUE TITLE
How to get rid of language resources.

### ISSUE THREAD

**Issue by patrikmichnac** [ravibpatel/AutoUpdater.NET#548]
Hi there, I want to use Autoupdate only with English language. How to prevent Autoupdate create all those language folders with diferent language resources dll.
I do not want to have my application folder full of unecessary folders. Or is therea nother way how to move it somewhere else to one dir or ...

ar\
cs\
da\
de\
dll\
es\
fr\
it\
ja-JP\
ko\
lv\
nl\
pl\
pt\
pt-BR\
ru\
sk\
sv\
th\
tr\
zh\

**Comment by ravibpatel** [comment]
It looks related to #471. You can use the solution suggested by @hawkeye-stan in the issue.
