### ISSUE TITLE
Why this warning - This call site is reachable on all platforms. 'AutoUpdater.RunUpdateAsAdmin' is only supported on: 'Windows' 7.0 and later.

### ISSUE THREAD

**Issue by atulshelar** [ravibpatel/AutoUpdater.NET#551]
![Untitled](https://user-images.githubusercontent.com/57441786/178461161-547c13ff-e5f8-491c-9206-dbc9ea394b42.png)

**Comment by ravibpatel** [comment]
It may be happening cause AutoUpdater.NET is compiled with "net5.0-windows" target framework. You can see more about it [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416).
