### ISSUE TITLE
Can I choose whether to use WebView2

### ISSUE THREAD

**Issue by howzew** [ravibpatel/AutoUpdater.NET#552]
After updating to 1.7.3, I found that webview2 was used by default. 
After compiling my program, I found that there was an "runtimes" folder in the debug directory, which contained "webview2loader.dll" files of different platforms. At the same time, there were "microsoft.web.webview2.core.dll", "microsoft.web.webview2.winforms.dll" and "microsoft.web.webview2.wpf.dll" files in the debug directory, This brings some trouble to my software release, because I used to pack it into a single file, so I have to pack the "webview2loader.dll" file in the "runtimes" folder at the same time, resulting in a larger file size. Can I choose to still use the past WebBrowser method?

**Comment by ravibpatel** [comment]
It is not possible even if I provide a flag to use old one, it will still reference those DLLs. You have to use older version (1.7.0) if you want to use old webbrowser control without those DLLs or you can fork the project and remove WebView2 altogether.

**Comment by howzew** [comment]
> It is not possible even if I provide a flag to use old one, it will still reference those DLLs. You have to use older version (1.7.0) if you want to use old webbrowser control without those DLLs or you can fork the project and remove WebView2 altogether.

Thank you
