### ISSUE TITLE
Hide all windows (download, extractor etc) during update process

### ISSUE THREAD

**Issue by alextrxtrx** [ravibpatel/AutoUpdater.NET#553]
Hello! I need absolutely silent update process without any windows. I used CheckForUpdateEvent and remove main update dialog window, but other windows (download, extractor, wait for close etc) are still there. How I can hide this windows?

**Comment by ravibpatel** [comment]
It is not possible to do so right now.

**Comment by alextrxtrx** [comment]
Thanks for the reply! I forked the project and fixed it for myself.

**Comment by Kanomiz** [comment]
Hey there @alextrxtrx !

Saw your fix for a silent install in AutoUpdater.NET. I'm a junior dev in C# WPF, working on something where this would be super handy. Any chance you could share how you did it or your fork? Would really appreciate the help!

**Comment by DotanVG** [comment]
Hey there @alextrxtrx !

Saw your fix for a silent install in AutoUpdater.NET. I'm a junior dev in C# WPF, working on something where this would be super handy. Any chance you could share how you did it or your fork? Would really appreciate the help!
