### ISSUE TITLE
Work with Avalonia UI?

### ISSUE THREAD

**Issue by rmcrackan** [ravibpatel/AutoUpdater.NET#556]
Is AutoUpdater.NET compatible with Avalonia UI?

**Comment by ravibpatel** [comment]
It should work, but it will show WinForms update form, although you can handle "CheckForUpdateEvent" and provide your own UI for that, but it is not possible to change Download and Extractor forms which shows download progress and update progress.

**Comment by rmcrackan** [comment]
Thanks. Those WinForms components won't work for us because we're developing a cross-platform application.
