### ISSUE TITLE
Failed to build AutoUpdater.NET

### ISSUE THREAD

**Issue by squiey** [ravibpatel/AutoUpdater.NET#557]
I would like to commit some changes in AutoUpdater.NET and I've downloaded the master but I can't build the solution. .NET 4.5/5/6/ is **already installed** on the machine by the way.

![Screenshot_140](https://user-images.githubusercontent.com/106429978/183071105-ccc82e58-b808-48f5-959a-1c19c836d3a1.png)

**Comment by ravibpatel** [comment]
Disable signing from project properties of both AutoUpdater.NET and ZipExtractor. Also, edit both .csproj file of [AutoUpdater.NET](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.NET.csproj#L6) and [ZipExtractor](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/ZipExtractor.csproj) and change following line. Use .NET version you prefer.

`<TargetFrameworks>net45;netcoreapp3.1;net5.0-windows</TargetFrameworks>`

For .NET 5.0 change it to following.

`<TargetFramework>net5.0-windows</TargetFramework>`

VS2022 doesn't allow building .NET 4.5 by default, so you can just change it to core only for editing, or you have to follow steps from [here](https://stackoverflow.com/a/70109092/1273550) to us 4.5. After that, you have to build the ZipExtractor project in release configuration, so it can find the ZipExtractor.exe in resources. You should be able to build it now without any issues.

**Comment by alphadon** [comment]
You can also generate your own key, run VS as an admin and let the signing happen on build: 
https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair

https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name
