### ISSUE TITLE
not use quotes in startargs after update?

### ISSUE THREAD

**Issue by dsan0815** [ravibpatel/AutoUpdater.NET#562]
I have an App with AutoUpdater.Net 1.7.0 and find an "issue".
I start my app with follow arguments:  app.exe --timeout=300 --outputdir="c:\temp\abc def"
This Start is OK, but after an Update (with AutoUpdater.Net), the new StartArguments are --timeout=300 --outputdir=c:\temp\abc def
(without quotes)
-> then not correct parse an string with spaces :(
Is there an issue or have i an error in my autoupdater.net-config?

Config:
            AutoUpdater.RunUpdateAsAdmin = false;
            AutoUpdater.DownloadPath = Path.Combine(Application.StartupPath, "update");
            AutoUpdater.ShowRemindLaterButton = false;
            AutoUpdater.ShowSkipButton = true;
            AutoUpdater.Synchronous = true;
            AutoUpdater.AppTitle = "abc...";

**Comment by ravibpatel** [comment]
I pushed commit, that should resolve the issue. Can you test it out by manually referencing the DLL from [here](https://ci.appveyor.com/api/buildjobs/3mn7pnjas2xoqsp8/artifacts/AutoUpdater.NET-1.7.5.zip)?
