### ISSUE TITLE
Does not load current culture

### ISSUE THREAD

**Issue by p-p-p-p-p-p** [ravibpatel/AutoUpdater.NET#567]
- Windows Form (.NET6.0)
- Autoupdater.NET.Official 1.7.5 (nuget)

I would like to change the UI display language to Japanese.

I set up Culture based on the following Issue https://github.com/ravibpatel/AutoUpdater.NET/issues/97
The following code is written in the Load event of MainForm.

```cs
private void Main_Load(object sender, EventArgs e)
{
    AutoUpdater.Mandatory = true;
    AutoUpdater.UpdateMode = Mode.Forced;
    Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("ja-JP");
    
    AutoUpdater.Start(xmlUrl);
}
```

When I push an update to the server, a UI appears in English announcing the release of the latest version.

Any other information needed will be provided immediately.

**Comment by ravibpatel** [comment]
What kind of application are you developing (WinForms, WPF etc..)?

**Comment by p-p-p-p-p-p** [comment]
WinForms (.NET6.0)

**Comment by ravibpatel** [comment]
I tried creating a simple example project using .NET 6.0, and it works fine for me.

**Comment by ravibpatel** [comment]
Instead of doing it in Load event, try to do it from the Form constructor. Paste this just after InitializeComponent();

```csharp
Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("ja-JP");
```

**Comment by p-p-p-p-p-p** [comment]
This worked ideally in the example project, but the existing project kept displaying the English message.

The following code was causing the problem.
```xml
<PropertyGroup>
    <SatelliteResourceLanguages>ja-JP</SatelliteResourceLanguages>
</PropertyGroup>
```

After making the following changes, the Japanese message is now displayed.
```xml
<PropertyGroup>
    <SatelliteResourceLanguages>ja-JP</SatelliteResourceLanguages>
</PropertyGroup>
```

Thank you for your support.
