### ISSUE TITLE
Method not found Exception in InitializeBrowserControl

### ISSUE THREAD

**Issue by tznind** [ravibpatel/AutoUpdater.NET#569]
I am getting the following error when trying to launch the update browser window.  This has manifest at some point since 27th of June as it occurs when updating from 7.0.17 of my tool (developed between 27th of June and 1st of August).

I have released the following versions of my tool

- 7.0.14 (Released on 27th of June - shipped with AutoUpdater 1.7.3) 
- 7.0.17 (1st August - shipped with AutoUpdater 1.7.4) 
- 7.0.18 (31st August)

I am able to update from 7.0.14=>7.0.18 but not from 7.0.17=>7.0.18.  I think this means that the issue manifest after 27th of June

Based on these dates I think the package that isn't working is Autoupdater.NET.Official 1.7.4? 

Based on [the diff between 1.7.3 and 1.7.4](https://github.com/ravibpatel/AutoUpdater.NET/compare/v1.7.3...v1.7.4) I can see that there was a change in f6797c4aebad6e455432ec57c754072d68f59bc1 to remove anchor on specific version of WebView2 but there is still a specific version (admittedly unbounded) in the .nuspec (` version="[1.0.1210.39,2)"`.  
```
-<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1210.39" />
+<PackageReference Include="Microsoft.Web.WebView2" Version="1.*" />
```

Do you think this is the issue? The nuspec is resulting in a different dependency being drawn down at build time of my application than was used to compile the AutoUpdater.NET dll?

**Exception**

```
Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_CoreWebView2InitializationCompleted(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs>)'.

at AutoUpdaterDotNET.UpdateForm.InitializeBrowserControl()
   at AutoUpdaterDotNET.UpdateForm..ctor(UpdateInfoEventArgs args)
   at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm(UpdateInfoEventArgs args)
   at AutoUpdaterDotNET.AutoUpdater.StartUpdate(Object result)
   at AutoUpdaterDotNET.AutoUpdater.<>c.<Start>b__43_1(Object _, RunWorkerCompletedEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
```

**Comment by ravibpatel** [comment]
In latest version, I fixed the version, so it should work now. See #554.
