### ISSUE TITLE
Check update on Startup

### ISSUE THREAD

**Issue by leluc42** [ravibpatel/AutoUpdater.NET#57]
Hi,
i try to use this updater on startup.
But it doesn't work. The parent applicatio is starting and the downloadwindow ist closing.
Am i able to use this updater on startup of my application!?

**Comment by methc** [comment]
I call the AutoUpdater from a button but yea, I dont see any reason why you can't call it on form load. 

Did you follow the guide on the mainpage? 

Perhaps you can tell us what you did in details so we can have more info in order to assist you.
