### ISSUE TITLE
issue in nuget-pack?

### ISSUE THREAD

**Issue by dsan0815** [ravibpatel/AutoUpdater.NET#571]
No Problem if I use manually download and reference to dll.
-> autoupdater.dll, webview*.dll and runtimes subfolder in Zip and I add all to project.

But, if I install AutoUpdater with nuget:
Only Autoupdater.dll and webview*.dll are in build-folder, no runtimes-subfolder.
Issue: AppStart throw an exception -> can't find webview2loader.dll -> screenshot in attachment.

Is this normal or an error in webview/autoupdater?

![Capture](https://user-images.githubusercontent.com/97553908/188200545-a1056d04-2c00-49df-9499-4191eeda562e.PNG)

**Comment by ravibpatel** [comment]
Are you using the latest version of AutoUpdater.NET?

**Comment by dsan0815** [comment]
Yes, both as dll and/or nuget-pack

**Comment by ravibpatel** [comment]
I tried it out in a new WinForms .NET 6.0 project, and it works fine for me using latest NuGet package.

**Comment by dsan0815** [comment]
Oh sorry, i use NetFramework 4.8

**Comment by ravibpatel** [comment]
I tried a new project with .NET Framework 4.8 and still can't reproduce the issue. Make sure "Copy Local" is set to true for all WebView2 references under "References" in solution explorer.

**Comment by dsan0815** [comment]
:( why, can you explain?
I mean ... I install the nuget for autoupdater.net, this has a dependency on Microsoft.Web.WebView2 which is also installed. But it is missing the local DLL webview2loader.
Consequently, I always have to use the nuget package AND a local copy of the webview2loader.dll (from the zip)? This is quite unusual for a nuget-pack.

**Comment by ravibpatel** [comment]
It does copy runtimes folder to bin\Debug automatically for me.

**Comment by dsan0815** [comment]
ok, i have check this:

When I install only nuget-pack for autoupdater.net (automatic install dependencies packs = transitive packs), after build i have no runtimes-subfolder in debug.
solution-explorer:
![image](https://user-images.githubusercontent.com/97553908/188261929-b6193945-b974-4f21-8540-e96dcc5486f9.png)
debug-folder:
![image](https://user-images.githubusercontent.com/97553908/188261992-ae983559-6dba-4d89-995a-2f47b5ef96e0.png)

When i install nuget-packs for autoupdater.net and microsoft.web.webview2, after build i have the runtimes-subfolder.
solution-explorer:
![image](https://user-images.githubusercontent.com/97553908/188261969-b28887d6-34ae-4440-929d-a5419769409f.png)
debug-folder:
![image](https://user-images.githubusercontent.com/97553908/188261981-bfd0acd3-3909-4dbc-8fe4-475df1a75ecb.png)

i mean ... is an little bit crazy, but you can close this issue-ticket :)
