### ISSUE TITLE
Changelog does not load

### ISSUE THREAD

**Issue by TheMatrixAgent** [ravibpatel/AutoUpdater.NET#572]
Hello.
I have tried a normal txt file, and lastly a html file. I use Windows 11, so I don't have IE to test it out (I remember reading that the changelog box uses IE to render), but the code runs on Chrome, Edge and Firefox. I can download updates from my server, so I don't think connection is the problem. When the dialog loads, the box appears, and stays white (I suppose that means the file was found).
Here is the code (and yes, the URL is set correctly, I quadruple-checked):
```
<!DOCTYPE html>
<html>
	<body>
		<h1>Version 1.0.2:</h1>
		<p>Test</p>
		<h1>Version 1.0.1:</h1>
		<p>Test</p>
		<h1>Version 1.0.0:</h1>
		<p>Test</p>
	</body>
</html>
```
Either I'm doing something really wrong, or it isn't working.

**Comment by ravibpatel** [comment]
It uses WebView2 now, so it is using Edge. Can you provide URL of the changelog?

**Comment by TheMatrixAgent** [comment]
Hello. Thanks a lot for the quick reply. "ftp://192.168.178.21/App/changelog.html"
Since I only need to update devices within my household, I use "Xlight FTP Server" to make an FTP server.

**Comment by TheMatrixAgent** [comment]
Quick update: For the first time, I got a promt to open Google Chrome, when the WebView loaded. Maybe this helps.

**Comment by ravibpatel** [comment]
FTP URL won't work in WebView2, I think. You have to provide web URL. If changelog is not important, then you can also omit the changelog URL.

**Comment by TheMatrixAgent** [comment]
Oh ok! I though it would first download the file, then try to display it! Maybe this would be a useful feature!
IP URLs will work though, right? I guess I'll just leave it without a changelog!
Thanks a lot!

**Comment by ravibpatel** [comment]
IP URL should work without issue.
