### ISSUE TITLE
Datetime value not parse

### ISSUE THREAD

**Issue by zalktisgithub** [ravibpatel/AutoUpdater.NET#575]
![2](https://user-images.githubusercontent.com/61417705/188723225-b4b93517-c2e2-4591-83c1-92dbb5bc78de.jpeg)
Attach error meeage.

Somertime some user message with this error message !
Me not idea to do.

**Comment by ravibpatel** [comment]
Which version are you using?

**Comment by zalktisgithub** [comment]
Hello !
I use version of 2019 year version.



Ar cieņu,

Ainārs Osmanis

________________________________
No: Ravi Patel ***@***.***>
Nosūtīts: ceturtdiena, 2022. gada 8. septembris 09:17
Kam: ravibpatel/AutoUpdater.NET ***@***.***>
Kopija: Ainārs Osmanis ***@***.***>; Author ***@***.***>
Tēma: Re: [ravibpatel/AutoUpdater.NET] Datetime value not parse (Issue #575)


Which version are you using?

**Comment by zalktisgithub** [comment]
Version 1.5.6.



Ar cieņu,

Ainārs Osmanis


________________________________
No: Ravi Patel ***@***.***>
Nosūtīts: ceturtdiena, 2022. gada 8. septembris 13:55
Kam: ravibpatel/AutoUpdater.NET ***@***.***>
Kopija: Ainārs Osmanis ***@***.***>; Author ***@***.***>
Tēma: Re: [ravibpatel/AutoUpdater.NET] Datetime value not parse (Issue #575)


Can tell me exactly which version?

**Comment by ravibpatel** [comment]
You can set Mandatory to true in XML as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file) and your users won't get this error.

**Comment by ravibpatel** [comment]
I handled the exception in latest [commit](https://github.com/ravibpatel/AutoUpdater.NET/commit/223d4af11a8cbcadfdf97ae2f58546846d0ad9f8), so it shouldn't be a problem when 1.7.6 is released, but to prevent this error for current users you can just set mandatory to true in XML.

**Comment by zalktisgithub** [comment]
Hello!

My product use on 4000 users computers.
Accounting software for Small business.
I cannot individual set mandatory to True for current computer.

Now we am update my software component Updater.NET to version 1.7.5.
Only later I can know, is this update is helping fot current user.

Thanks You!


Ar cieņu,

Ainārs Osmanis

SIA "Zalktis Programmas"


________________________________
No: Ravi Patel ***@***.***>
Nosūtīts: svētdiena, 2022. gada 25. septembris 08:37
Kam: ravibpatel/AutoUpdater.NET ***@***.***>
Kopija: Ainārs Osmanis ***@***.***>; Author ***@***.***>
Tēma: Re: [ravibpatel/AutoUpdater.NET] Datetime value not parse (Issue #575)


I handled the exception in latest commit<https://github.com/ravibpatel/AutoUpdater.NET/commit/223d4af11a8cbcadfdf97ae2f58546846d0ad9f8>, so it shouldn't be a problem when 1.7.6 is released, but to prevent this error for current users you can just set mandatory to true in XML.

**Comment by ravibpatel** [comment]
You don't have to set Mandatory to true in code. You can just set it in the XML, and it should work.

This should only happen when the user used the "Remind Later" option in the past. It saves it to fixed date format, so it shouldn't happen in the first place, unless the saved date is corrupted somehow. Setting Mandatory element in XML prevents the date from being read, preventing the exception.

**Comment by zalktisgithub** [comment]
In Latvia  use Latvian date format dd-MM-yyyy.
I can see date formats? In Windows register?.
In my and this customer computers.


Ar cieņu,
Ainārs Osmanis
SIA Zalktis Programmas


________________________________

**Comment by zalktisgithub** [comment]
On my computer I see :   1/26/2022  1:45:45 PM




Ar cieņu,

Ainārs Osmanis
SIA "Zalktis Programmas"


________________________________
No: Ravi Patel ***@***.***>
Nosūtīts: svētdiena, 2022. gada 25. septembris 17:21
Kam: ravibpatel/AutoUpdater.NET ***@***.***>
Kopija: Ainārs Osmanis ***@***.***>; Author ***@***.***>
Tēma: Re: [ravibpatel/AutoUpdater.NET] Datetime value not parse (Issue #575)


It specifies to store it in English format and also specify English when retrieving it, as you can see here<https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/RegistryPersistenceProvider.cs#L65>. You can see it in Windows registry. Can you tell me what kind of format you see?
