### ISSUE TITLE
Multiple urls

### ISSUE THREAD

**Issue by vitalerter** [ravibpatel/AutoUpdater.NET#576]
Is it possible to application select from where to download the update.

For example i need to store same application on two servers(China and Eu).
Then after first download to keep updated from the server from where it was download.

**Comment by vitalerter** [comment]
But then in the code i need to build for multiple configurations of the url. Maybe there is a **cache or cookies**

**Comment by ravibpatel** [comment]
You still have to implement a way to know from where the app was downloaded. You can create a registry entry on installation or if it is a portable app you can include a json file indicating where it was downloaded. Then in the app, you can just read that file or registry entry to determine which update XML file you want to use.

**Comment by vitalerter** [comment]
Maybe select the server during update? Show a prompt with all available servers for update
