### ISSUE TITLE
Suggestion: parameter SetFormTopMost to set default update form as TopMost

### ISSUE THREAD

**Issue by hahyes** [ravibpatel/AutoUpdater.NET#584]
Hi there, 
another one from me.

I suggest to add something like this:
```csharp
AutoUpdater.SetFormTopMost = true;
```

I currently have problem with using default update form. Because of workers changing windows a lot of times, there is a big change they will not find out there is update window somewhere as it is hidden somewhere. I want to keep default form on screen no matter what are they doing. Maybe little strict, but I need this to implement it in my software. 
Or maybe there is a way to set this without any changes in source code?

I tried to pick `ActiveForm` in `CheckForUpdateEvent`, but this is internal class (`UpdateForm`) so I can't modify it.

Best regards.

**Comment by ravibpatel** [comment]
It is possible to set your Form or Window as owner to ensure correct focus in new version. You can try it out from [here](https://ci.appveyor.com/api/buildjobs/nr729ere083g2iym/artifacts/AutoUpdater.NET-1.8.2.zip). You can set owner as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-the-owner-form--window).
