### ISSUE TITLE
cannot get the updater to read the xml off an http url

### ISSUE THREAD

**Issue by c4artisan** [ravibpatel/AutoUpdater.NET#585]
my website (http://trolleybus.ga in case it's needed for further assistance) is brand new and i have not requested an ssl for it. i found this package and i've been trying to get it to read the version xml off this website. it doesn't work, however, the default url, which, is https, does work.
any clue on what's happening? i really need to get this to work

**Comment by ravibpatel** [comment]
Can you provide me your XML URL?

**Comment by c4artisan** [comment]
> Can you provide me your XML URL?

http://trolleybus.ga/file.xml

**Comment by ravibpatel** [comment]
There is something wrong from server side. AutoUpdater.NET is receiving following content when calling that URL.

```html
<html><body><script>document.cookie="_test=0d49ecc731607f1228722a8789d3da95 ; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/" ;document.location.href="http://trolleybus.ga/file.xml?i=1";</script></body></html>
```

From its content it looks like it is redirecting to URL "http://trolleybus.ga/file.xml?i=1" but when I tried, it returned the same response but this time the redirect URL changed to "http://trolleybus.ga/file.xml?i=2".

I also tried customizing User agent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-user-agent-for-http-web-requests), so it mimics the browser, but it didn't solve the issue.

**Comment by c4artisan** [comment]
> There is something wrong from server side. AutoUpdater.NET is receiving following content when calling that URL.
> 
> ```
> <html><body><script>document.cookie="_test=0d49ecc731607f1228722a8789d3da95 ; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/" ;document.location.href="http://trolleybus.ga/file.xml?i=1";</script></body></html>
> ```
> 
> From its content it looks like it is redirecting to URL "http://trolleybus.ga/file.xml?i=1" but when I tried, it returned the same response but this time the redirect URL changed to "http://trolleybus.ga/file.xml?i=2".
> 
> I also tried customizing User agent as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#set-user-agent-for-http-web-requests), so it mimics the browser, but it didn't solve the issue.

that's probably an infinityfree flaw then
i don't really mean to be a nuisance but, any free hosting service that you'd recommend to me? because i know infinityfree's definitely not going to allow me to change that behavior, nor do i know any other services

**Comment by c4artisan** [comment]
i forgot about the existence of 000webhost lol
i'm gonna give it a try. i hope it solves this

**Comment by ravibpatel** [comment]
You can use GitHub itself if you only want to serve the XML for updates.
