### ISSUE TITLE
File exist exception(System.IO.IOException) after download.

### ISSUE THREAD

**Issue by brallow** [ravibpatel/AutoUpdater.NET#589]
If  AutoUpdater.XML's URL set without a filename suffix, Like 'http://10.10.10.10/'  and it redirect to a valid URL which contains the ZIP file.  The update dialog will shown and the exception will be shown after downloading.

The problem may at DownloadUpdateDialog.cs Line 110~124(ver 1.7.6)

Line 110: variable 'fileName' assigned with EMPTY string.  Then,  Line 124: File.Move(_tempFile,tempPath).  parameter1 _tempFile is a full path filename.  Parameter 2 tempPath link to the same path without any filename.  It moves a file to its current path!
![Uploading Xnip2022-12-06_13-06-52.png…]()

**Comment by ravibpatel** [comment]
If the URL has no filename suffix, then it should provide the valid content-disposition header with filename so AutoUpdater.NET can determine the file extension from the name. It is necessary cause it works with different file extensions and update behavior change according to it.
