### ISSUE TITLE
Space in Windows username breaks zipextractor

### ISSUE THREAD

**Issue by rmcrackan** [ravibpatel/AutoUpdater.NET#595]
My issue appears to be the same as #323 . At the time. this was closed without a bug fix. One of my users [documented the same issue](https://github.com/rmcrackan/Libation/issues/423). Is there a work-around for this?

**Comment by ravibpatel** [comment]
This should not happen. It is already using double quotes around the path, as you can see [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L157). Following is the log I am getting when I tried with path with spaces.

ZipExtractor started with following command line arguments.
[0] d:\test autoupdater\zipextractor.exe
[1] --input
[2] d:\test autoupdater\autoupdatertest.zip
[3] --output
[4] d:\test autoupdater\space space space
[5] --executable
[6] d:\test autoupdater\space space space\autoupdatertest.exe

**Comment by ravibpatel** [comment]
Can you give me URL of XML file you are using?

**Comment by rmcrackan** [comment]
My apologies. You're correct. In our Winforms solution, we use your library directly. Since you don't support AvaloniaUI, we used code *like yours* and we forgot to escape it.

https://github.com/rmcrackan/Libation/blob/3f6689d0324276e757027ab4e46330136f50a0bc/Source/LibationAvalonia/Views/MainWindow.axaml.cs#L156

Thank you so much for your quick reply
