### ISSUE TITLE
发行说明无法加载

### ISSUE THREAD

**Issue by codehub2881** [ravibpatel/AutoUpdater.NET#596]
发行说明显示未找到文件，如何增加发行说明呢？

**Comment by AndersChen123** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<item>
  <version>2.0.0.0</version>
  <url>https://rbsoft.org/downloads/AutoUpdaterTest.zip</url>
  **<changelog>https://github.com/ravibpatel/AutoUpdater.NET/releases</changelog>**
  <mandatory>false</mandatory>
</item>

无法加载是路径设置的不对吧。

**Comment by AndersChen123** [comment]
这个应该是路径设置的不对吧。

**Comment by ravibpatel** [comment]
You have to provide the change log URL in your XML file.

**Comment by codehub2881** [comment]
> 

怎么设置路径呀？

**Comment by ravibpatel** [comment]
You have to provide changelog URL as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#xml-file).

**Comment by codehub2881** [comment]
感谢，已解决。
