### ISSUE TITLE
Ability for update from zip to delete files

### ISSUE THREAD

**Issue by BTPDarren** [ravibpatel/AutoUpdater.NET#598]
There is on occasion the need to delete some supporting DLL's

The DevExpress DLL's change name each major and minor version

E.G.DevExpress.XtraTreeList.v22.1.dll has changed to DevExpress.XtraTreeList.v22.2.dll

and when deploying an update I will deploy the new DLL BUT the old DLL's need to be removed

I was thinking I could supply a batch file to execute after the update, maybe as an option from the XML update file

Thoughts?

**Comment by ravibpatel** [comment]
You can clear app directory before extracting new files.

https://github.com/ravibpatel/AutoUpdater.NET#clear-application-directory-before-extracting-update-file

**Comment by BTPDarren** [comment]
Hi,  yes I know but not all files need to be , or will be updated

In our case the app has over 350+ files, the DevExpress ones in this case amount to only 118

So an update would be these files + the main EXE and a couple of other files not the entire app. 

It would be easier to just build a new installer

Also I noticed when you clear the directory and update ALL files , the launch of the app triggers a repair and these old files come back.

Not sure if this is a setup feature so will look into this.

**Comment by GlodenBoy** [comment]
Is it possible to add a simple configuration that fills in the files that need to be deleted, so that it should be easier to implement

**Comment by BTPDarren** [comment]
FYI
I added my own take to deal with this to allow the execution of a .BAT file pre and post update
the pre update performs the delete DevExpress*.* then the update is performed

Not using Post for now but ultimately its working perfectly

**Comment by ravibpatel** [comment]
Now it is possible to provide different execution path to execute any post update logic.
