### ISSUE TITLE
Can not use ZipExtractor

### ISSUE THREAD

**Issue by LuciaVeldera** [ravibpatel/AutoUpdater.NET#6]
Do you have any suggestion on how I can start use this feature?

**Comment by ravibpatel** [comment]
ZipExtractor is embedded in AutoUpdater.NET.dll file. So if you provide zip file URL between url tag of the XML file, AutoUpdater.NET will use the ZipExtractor to extract the contents of ZIP file to the current working directory. This feature is intended for those developers who are not familiar with the development of installer technologies. Those developers can now just zip the contents of the new version of the application, upload it to the server and provide its URL in the XML file.

**Comment by LuciaVeldera** [comment]
![image](https://cloud.githubusercontent.com/assets/9936548/25372336/31e10156-29bf-11e7-8ff3-c65fdbdbdaad.png)
When I click on update button,it run winrar program. Is it suppose to be like this? I thought it will show progress bar and replace files with the new ones.

**Comment by ravibpatel** [comment]
Did you compile the latest version of DLL by downloading the project and using it in your project?

**Comment by LuciaVeldera** [comment]
PM> Install-Package Autoupdater.NET.Official
I only run the above line. Did I do it correctly? If it's not, Where can I get the latest version of the project?
I downloaded a master version of the project ,but I can't use it because there are some kind of error and some files missing from the project.

**Comment by ravibpatel** [comment]
You did it correctly, but Nuget package wasn't updated then. I have done it now. So you can try again and this time it should work.

**Comment by LuciaVeldera** [comment]
Thank you for your help ravibpatel. A zip extractor is now already worked, but the application still didn't get an updated version. I think the extractor already extract the file, but what I don't know is where the files are extract to. I place my application in D:\MyApplication .

**Comment by ravibpatel** [comment]
Can you tell me the URL of XML you are using? You need to match your application structure with zip file. For example if your executable resides in D:\MyApplication\AutoUpdaterTest.exe then it should be In the root of your zip file. If you download the project now and check it you will see I updated the example project to demonstrate this functionality.

**Comment by LuciaVeldera** [comment]
I'm sorry ravibpatel. It's my mistake and now the auto updater are working perfectly. I really appreciate your help.
