### ISSUE TITLE
Turn off ZipExtractor.exe UAC dialog after downloading

### ISSUE THREAD

**Issue by phuocminh6464** [ravibpatel/AutoUpdater.NET#600]
I want to use AutoUpdater to silent update (no need user interact) and open app again after updating for kiosk machine.  I used the following code in my project:
```            
AutoUpdater.Mandatory = true;
AutoUpdater.UpdateMode = Mode.ForcedDownload;
AutoUpdater.RunUpdateAsAdmin = true;
```
But AutoUpdater always shows ZipExtractor.exe UAC dialog for permission after downloading. How could I do to turn off this dialog because I want updating work is entirely silent since there are so many kiosk in different places.

**Comment by ravibpatel** [comment]
Setting AutoUpdater.RunUpdateAsAdmin to false should suppress UAC dialog. Do you require admin privileges for update?

**Comment by phuocminh6464** [comment]
> Setting AutoUpdater.RunUpdateAsAdmin to false should suppress UAC dialog. Do you require admin privileges for update?

@ravibpatel Thank you so much. I don't need admin privileges for update
