### ISSUE TITLE
ZipExtractor fails with System.UnauthorizedAccessException if the Files it is trying to replace are hidden

### ISSUE THREAD

**Issue by PeterStrick** [ravibpatel/AutoUpdater.NET#601]
ZipExtractor fails with System.UnauthorizedAccessException if the Files it is trying to replace are marked as hidden.

This was re-produced on a Fresh Installation of Windows 11 21H2, no Antivirus or any other 3rd Party Software is installed.

The Application that was using AutoUpdater.Net is stored on a FAT32 USB-Stick, so this isn't a Permission issue.

Downloading the ZIP File, Getting the XML File and displaying the Changelog worked flawlessly without problems.

ZipExtractor extracts the ZIP File without problems if the Hidden attribute has been removed from all Files it is trying to replace.

<img width="856" alt="Screenshot 2023-02-08 100102" src="https://user-images.githubusercontent.com/60312421/217484102-39b8fd34-5da7-49c7-96bf-e14312835cca.png">

![image](https://user-images.githubusercontent.com/60312421/217484146-56f989de-b3e1-42ae-9d78-15faad5e19e4.png)

**Comment by ravibpatel** [comment]
This should be fixed in latest commit. Can you try it out from [here](https://ci.appveyor.com/api/buildjobs/e2tx8dm8ui7gtjhi/artifacts/AutoUpdater.NET-1.7.7.zip)?

**Comment by ravibpatel** [comment]
Which application are you using to create the zip file?

**Comment by PeterStrick** [comment]
> Which application are you using to create the zip file?

Just Windows Explorer. Creating it with the Send To Shortcut

**Comment by ravibpatel** [comment]
I made some changes. Can you please try it again from [here?](https://ci.appveyor.com/api/buildjobs/tihou50ns0xeb0b1/artifacts/AutoUpdater.NET-1.7.7.zip)

**Comment by PeterStrick** [comment]
> After using the new DLL the Error Message went away and it extracted successfully.
> 
> Just to make sure I modified the Appx.zip file on my local system by adding files to it and ran an Update (Just changed the Versions in Visual Studio to an older Version)
> 
> The Zip File and main EXE were replaced by the Versions within the Update Zip File, while even leaving the Hidden Attributes intact so I would say everything works with this Version now

Is this change in the normal AutoUpdater.Net Version?

**Comment by ravibpatel** [comment]
I tagged the latest commit, so it will be available on NuGet soon.
