### ISSUE TITLE
Not allow to close app while updating new version

### ISSUE THREAD

**Issue by phuocminh6464** [ravibpatel/AutoUpdater.NET#602]
Hi all, my WPF app always works except in case of crash. It will run on multiple kiosks so user want it can auto update if new version exists. My app has a maintenance screen, it will show when nobody use kiosk after every 30 minutes or when update new version. However, when **AutoUpdater.NET** update new version it will force closing app and maintenance screen can't show. So how could I do to show maintenance screen as well as update app.
Any comment is appreciated.

**Comment by ravibpatel** [comment]
You can try to show the maintenance screen in [ApplicationExitEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually). Just create another app with only maintenance screen and launch the process.

**Comment by phuocminh6464** [comment]
> You can try to show the maintenance screen in [ApplicationExitEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually). Just create another app with only maintenance screen and launch the process.

@ravibpatel Thank you so much. I will tried it

**Comment by ravibpatel** [comment]
To show maintenance screen before the closing the app, you can [handle update logic manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). You are running it in a kiosk, so I guess there should be no prompt if user wants to update or not. If there is an update, it should download it. So you can start the download as soon as there is a new update, and you can show the maintenance screen before you call AutoUpdater.DownloadUpdate(args) as shown in the example.

To close the maintenance app after app restart, you can have current version of app in plain text file in app directory and in your maintenance app you can read this file every second or your preferred polling time. When the app updates it should also increase the version in this file and when it does, you can close the maintenance app.

**Comment by phuocminh6464** [comment]
@ravibpatel, I will tried it and tell you the result later.
