### ISSUE TITLE
UnauthorizedAccessException

### ISSUE THREAD

**Issue by BlyZeYT** [ravibpatel/AutoUpdater.NET#604]
![image](https://user-images.githubusercontent.com/95288041/220468170-0cfca670-3d88-4cda-bbab-70e289003a04.png)

Happens not on my computer but on the computer of my friend trying to install the update.
On my computer it worked fine.
He had to reinstall because the update won't work.
Previous update worked thought.

Does anyone know whats the problem?

**Comment by ravibpatel** [comment]
It seems it encountered UnauthorizedAccessException while overwriting the file. Do you use admin privileges for update?

**Comment by ravibpatel** [comment]
Does the file in question can be overwritten by admin? This can happen if there is an ownership issue. For example, if you created a file and then reformat PC while keeping data on that drive and do the fresh installation of the system. That file still owned by old user of the previous installation. You have to switch ownership to new user to avoid this issue.

**Comment by BlyZeYT** [comment]
> Does the file in question can be overwritten by admin? This can happen if there is an ownership issue. For example, if you created a file and then reformat PC while keeping data on that drive and do the fresh installation of the system. That file still owned by old user of the previous installation. You have to switch ownership to new user to avoid this issue.

So thats Not a Problem I can fix in my code right?

**Comment by ravibpatel** [comment]
Yeah, It's mostly likely coming from the system and not the issue with code.
