### ISSUE TITLE
CoreWebView2Environment.GetAvailableBrowserVersionString() throw ArgumentException "The path is not of a legal form"

### ISSUE THREAD

**Issue by BoGnY** [ravibpatel/AutoUpdater.NET#605]
In [UpdateForm.cs#L53](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/UpdateForm.cs#L53) every time there is a new update **WITH URL CHANGELOG** specified, the result is a `System.ArgumentException "The path is not of a legal form"`.

Changing the try/catch to catch general `Exception` instead only `WebView2RuntimeNotFoundException` show UpdateForm without any problems.

**Comment by ravibpatel** [comment]
Thanks for reporting. Fixed in latest commit.

**Comment by BoGnY** [comment]
> Thanks for reporting. Fixed in latest commit.

@ravibpatel is it normal that version 1.7.7 isn't be pushed on release/nuget yet??

**Comment by ravibpatel** [comment]
I tagged the latest commit so it will available on NuGet soon.
