### ISSUE TITLE
Show Update Form

### ISSUE THREAD

**Issue by DwainSnickles** [ravibpatel/AutoUpdater.NET#606]
I read the readme.md that said
` // Uncomment the following line if you want to show standard update dialog instead.
 // AutoUpdater.ShowUpdateForm(args);`

There is no method for ShowUpdate, I a added the method sent the args the showUI worked but the args sent wern't dipslayed in the form. 

One last question I assume the release is a directory so I need to add that dir with a index.html.

Any help I'm probably missing something here

**Comment by ravibpatel** [comment]
You just have to create the XML and upload it to your server and provide its URL as argument for start function as shown below.

```csharp
AutoUpdater.Start("http://example.com/example.xml");
```

You don't need to [handle the update manually](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) if you don't want to add any custom logic for update.
