### ISSUE TITLE
V1.7.7 has a high probability of being falsely reported as a Trojan horse by Windows antivirus

### ISSUE THREAD

**Issue by shushu789** [ravibpatel/AutoUpdater.NET#612]
I updated the latest version v1.7.7 through the NuGet package today, and then when I generate my winform (whether using debug or release), my winform exe execution file will be falsely reported as a Trojan horse by the antivirus software that comes with Windows10, In the beginning, it was the code problem of my program, but my code has never been falsely reported as a virus. I have been using v1.7.0 before, and I will be falsely reported as a virus when I use V1.7.7.When I rolled back the version to v1.7.6, there were no more false positives, so I guess it may be a problem with v1.7.7

My development environment:
.net framework 4.72
visual studio 2022
Windows 10 22H2

**Comment by ravibpatel** [comment]
Can you try changing your ProjectGuid in application project file to see if it removes the detection?
