### ISSUE TITLE
File Downloads goes to the the proper directory but doesn't start

### ISSUE THREAD

**Issue by DwainSnickles** [ravibpatel/AutoUpdater.NET#613]
Am I missing something here the update runs, downloads the file, puts it in the propr directory eg\\myProj\... \ytd.exe
I can run it from that directory manually. I turned on zip errors as I seen that was corrected. no erros tried msi then converted it to exe both do the same. I am running windows dotnet 4.5 vs2019 I edited out the actual site.
my code just in case.
` private void btnUpdates_Click(object sender, EventArgs e)
        {
            XmlDocument xDoc = new XmlDocument();
            xDoc.Load("https://somesite.com/YouTubeDownloads/ytdupdate.xml");
            XmlNodeList TheVersion = xDoc.GetElementsByTagName("version");
            String XMLVersion = "version xml: " + TheVersion[0].InnerText + Environment.NewLine + "Actual Ver " + TheVersion;
            //MessageBox.Show(XMLVersion);
            Version APPVersion = new Version(Application.ProductVersion);
            //MessageBox.Show(APPVersion.ToString());
            if (TheVersion[0].InnerText == APPVersion.ToString())
            {
                MessageBox.Show("Youtube Downloader Platinum is up to date.");
            }
            else
            {
                Cursor = Cursors.WaitCursor;
                AutoUpdater.ReportErrors = true;
                AutoUpdater.Mandatory = true;
                //AutoUpdater.ShowSkipButton = true;
                //AutoUpdater.ShowRemindLaterButton = true;
                AutoUpdater.Start("https://somesite.com/YouTubeDownloads/ytdupdate.xml");
                //MessageBox.Show("Update Avaiable");
                Cursor = Cursors.Default;
            }
        }`

**Comment by DwainSnickles** [comment]
Didnt see anywhere in the doccumentation that I needed to do this but this is how I got it to work
Added application exit method as shown in sample and
`private void AutoUpdater_ApplicationExitEvent()
        {
            if (File.Exists(FolderPaths + "ytd21.exe"))
            {
                Process.Start(FolderPaths + "ytd21.exe");
            }
        }`

**Comment by ravibpatel** [comment]
@DwainSnickles "ytd21.exe" is the name of the installer file?
