### ISSUE TITLE
AutoUpdater.Start method can be bool?

### ISSUE THREAD

**Issue by foxi69** [ravibpatel/AutoUpdater.NET#618]
Is AutoUpdater.Start method can be bool?

If an update available it will leave true, otherwise false.
Is it possible?

(or any chance to get bool without create a custom update form)

**Comment by ravibpatel** [comment]
You can handle the update with the inbuilt dialog as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). Just call the AutoUpdater.ShowUpdateForm(args); in the event.
