### ISSUE TITLE
Code Error?

### ISSUE THREAD

**Issue by Grisu74** [ravibpatel/AutoUpdater.NET#62]
Hello.

I have an Error in AutoUpdater.cs.

`if (runWorkerCompletedEventArgs.Result is DateTime remindLaterTime)
                {
                    SetTimer(remindLaterTime);
                }
                else`

Visual Studio makes a Error. Required ) or {

Please Help for the Problem.

Thanks

**Comment by ravibpatel** [comment]
@Grisu74 Which Visual Studio version you are using?

**Comment by Grisu74** [comment]
Visual Studio 2015

**Comment by ravibpatel** [comment]
@Grisu74 You need Visual Studio 2017 to make it work. You can also replace it with the following and it should work on Visual Studio 2015.

```csharp
if (runWorkerCompletedEventArgs.Result is DateTime)
{
SetTimer(runWorkerCompletedEventArgs.Result as DateTime); 
}
```
