### ISSUE TITLE
Auto update with latest version not working

### ISSUE THREAD

**Issue by VigneswaranMuruganandan** [ravibpatel/AutoUpdater.NET#620]
I'm using the auto update latest package is not working.
Can you please help us

**Comment by imflammable** [comment]
Details here : I am using AutoUpdater.Start() to update one of my applications which i have developed. But its not working for some reason. Can u please help me with it ? PFA the popup i am getting but when i click on "Update" button of this pop up nothing works and my application is also not updated.

<img width="576" alt="Issue" src="https://github.com/ravibpatel/AutoUpdater.NET/assets/23197882/b66e61b3-b284-464f-838a-95fa36c4a2fa">

**Comment by ravibpatel** [comment]
Can you give the URL of the XML you are using?

**Comment by imflammable** [comment]
There are two urls i am using 

1. Internal url which when excecuted as GET request gives json response as

{ "version": "*latest version available on server*", "file": "*filePath to the latest app file*" }

- this is given as appCast url to  AutoUpdater.Start() method. Another param i am giving to this method is the assembly version details installed on my machine.

3. Internal url which when appended with the filePath obtained above, downloads a zip file containing the latest .exe files - this is set as DownloadURL property of the UpdateInfoEventArgs class.

**Comment by ravibpatel** [comment]
Can you post the code you are using for AutoUpdater? Are you passing the file path to Start method?

**Comment by imflammable** [comment]
I am passing a url to the start method which xml file but as a response UpdateInfoEventArgs is coming null.

Is the url i am giving, when hit as a get request on postman or on browser, should download an xml file ?

With my url its giving a reponse in xml format but NOT a xml file .PFA the ss below

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/23197882/228f06b2-85ce-40b6-a70e-6cce43673740)

**Comment by ravibpatel** [comment]
If you can't provide the XML file, then providing a similar dummy file will help me pinpoint the issue. You can also debug it yourself by adding the AutoUpdater.NET project to your solution by following the guide [here](https://github.com/ravibpatel/AutoUpdater.NET#steps-to-build-it-for-further-development).

**Comment by imflammable** [comment]
And why 50% and 100% any idea ?

**Comment by imflammable** [comment]
https://github.com/ravibpatel/AutoUpdater.NET#handling-parsing-logic-manually

following this method i have written the code

**Comment by imflammable** [comment]
The issue is resolved ....Zip folder which i was downloading was of two levels so thats why it was not getting extracted. Please close this ticket
