### ISSUE TITLE
Cleaning does not work

### ISSUE THREAD

**Issue by peterjanto** [ravibpatel/AutoUpdater.NET#623]
Hi, my settings:

```
AutoUpdater.UpdateMode = Mode.Forced;
AutoUpdater.Synchronous = true;
AutoUpdater.ClearAppDirectory = true;
```

No cleanup was performed
log:

```
ZipExtractor started with following command line arguments.
[0] c:\update\zipextractor.exe
[1] --input
[2] c:\update\autoupdate.zip
[3] --output
[4] c:**
[5] --current-exe
[6] c:**
[7]  --clear

Waiting for application process to exit...
BackgroundWorker started successfully.
Found total of 40 files and folders inside the zip file.
Extracting cs/ [2%]
.....
```

As you can see it's not even in the logs

BUT if i run zipextractor manually with parameters:

`zipextractor.exe --input C:\update\autoupdate.zip --output c:\* --current-exe c:\* --clear`

```
ZipExtractor started with following command line arguments.
[0] zipextractor.exe
[1] --input
[2] C:\update\autoupdate.zip
[3] --output
[4] c:\*
[5] --current-exe
[6] c:\*
[7] --clear

BackgroundWorker started successfully.
Removing all files and folders from "c:\*
.....
```

**Comment by peterjanto** [comment]
Lol. I just noticed it now. There is a white space in the first log before --clear.

**Comment by ravibpatel** [comment]
Thanks for reporting this. I removed the space from the argument. Can you try it from [here](https://ci.appveyor.com/api/buildjobs/hocujkuosd4nfv8q/artifacts/AutoUpdater.NET-1.8.3.zip)?

**Comment by peterjanto** [comment]
It works. Thx.

**Comment by ravibpatel** [comment]
I tagged it, so it will be available on NuGet soon.
