### ISSUE TITLE
Auto update infinite loop

### ISSUE THREAD

**Issue by wandersonareis** [ravibpatel/AutoUpdater.NET#624]
I have a problem with infinite loop if the local app name is different from server.
Example:
local: myapp[Central.net.br].exe
server: myapp.exe

The myapp.exe is downloaded to the directory, but myapp[Central.net.br].exe is always restarting and downloading myapp.exe.
To solve this, I have to close myapp[Centrals.net.br].exe and open myapp.exe.

If the name is the same, there is no problem.

**Comment by ravibpatel** [comment]
You should specify a new executable name in the XML as shown below and it should work.

```xml
<executable>myapp.exe</executable>
```

**Comment by wandersonareis** [comment]
I'm using json. Wouldn't it be possible to use the runtime name of the app?

**Comment by ravibpatel** [comment]
The executable element is used to notify the AutoUpdater that the executable name has changed from the previous version. You can also add it to your JSON and parse it back.

```csharp
private void AutoUpdaterOnParseUpdateInfoEvent(ParseUpdateInfoEventArgs args)
{
    dynamic json = JsonConvert.DeserializeObject(args.RemoteData);
    args.UpdateInfo = new UpdateInfoEventArgs
    {
        CurrentVersion = json.version,
        ChangelogURL = json.changelog,
        DownloadURL = json.url,
        ExecutablePath = json.executable,
        Mandatory = new Mandatory
        {
            Value = json.mandatory.value,
            UpdateMode = json.mandatory.mode,
            MinimumVersion = json.mandatory.minVersion
        },
        CheckSum = new CheckSum
        {
            Value = json.checksum.value,
            HashingAlgorithm = json.checksum.hashingAlgorithm
        }
    };
}
```
