### ISSUE TITLE
ability to kill processes opened by other users

### ISSUE THREAD

**Issue by brux88** [ravibpatel/AutoUpdater.NET#626]
thanks for your contribution, very beautiful and functional, a function that would make it perfect (although difficult for security reasons I think) is that if more users have opened the program, there is the possibility of closing all the processes in order to continue the update.

**Comment by ravibpatel** [comment]
You can use the [ApplicationExitEvent](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually) to handle the killing of all instances.

**Comment by brux88** [comment]
yes but, i'm in a windows server environment, and i can't kill the processes if i don't have administrator rights. and my software starts without administration rights, is it possible in the ApplicationExitEvent event to ask for administrator rights to be able to kill the processes of other users?

**Comment by ravibpatel** [comment]
You can create a separate EXE that resides with your application and kill all running processes. You can launch another process from ApplicationExitEvent that executes this EXE to do so.
