### ISSUE TITLE
AutoUpdater unable to detect assembly version .Net Core

### ISSUE THREAD

**Issue by Esgok** [ravibpatel/AutoUpdater.NET#628]
Hello,
I upgraded my WinForms .Net Framework app to .Net Core. In .Net Framework everything was fine. But in .Net Core AutoUpdater unable to detect assembly version. It always shows "0.0.0.0". Here is my project's version definitions. Help please. 

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/87549621/da067485-3a04-402a-a2d7-1866dc1bb486)

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/87549621/a5b36e3a-a52a-4964-a65b-285cb40a0065)

**Comment by ravibpatel** [comment]
It assembly version shown [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L422). Can you check what it is returning for you?

You can also set InstalledVersion manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#provide-installed-version-manually).
