### ISSUE TITLE
Caching problem

### ISSUE THREAD

**Issue by serdam55** [ravibpatel/AutoUpdater.NET#63]
I just saw a strange bug, in particular when I do this:

     AutoUpdater.Start("some url");

the application doesn't detect the update version, yesterday all was working good. So I just tried to add:

     AutoUpdater.Start("some url?" + Guid.NewGuid());

and the update is now available again, so I guess this is a cache issue, not?

**Comment by ravibpatel** [comment]
@serdam55  I set HttpRequestCachePolicy to NoCacheNoStore, So I think it is not a caching issue. Can you try to disable caching for XML file in your .htaccess file?

**Comment by serdam55** [comment]
@ravibpatel hi, thanks for the answer, unfortunately I'm not expert on .htaccess, which content should I write inside this file? Thanks.

**Comment by serdam55** [comment]
@ravibpatel  Ok I found the bug, essentially in the property of my application the current versioni is: 0.0.0.1 and the .xml on the server have this version: 0.0.0.2, in this situation the updater doesn't working.
If instead I change the version of my application to 1.0.0.0 and set the .xml to 2.0.0.0 this working.
Any fix?

**Comment by ravibpatel** [comment]
@serdam55 I will test it on my end and let you know.

**Comment by serdam55** [comment]
@ravibpatel  thanks, I don't know if this is correlated but I fix the situation by changing the assembly version manually in the assemblyinfo.cs file, no idea why now working

**Comment by serdam55** [comment]
@ravibpatel I found the same problem on the changelog, so I guess there is some cache issue, could you please try to generate a GUID in the url?

**Comment by ravibpatel** [comment]
@serdam55 You can add code from [here](https://stackoverflow.com/a/11724596/1273550) to your .htaccess file to prevent caching.
