### ISSUE TITLE
args.RemoteData encoding problem

### ISSUE THREAD

**Issue by yomnxkcs** [ravibpatel/AutoUpdater.NET#632]
Sorry for my bad English.

I'm using AutoUpdater.NET in a .net framework 4.5 winform project. When I run the sample code of "Handling parsing logic manually", args.RemoteData gives me an unreadable string. I find out args.RemoteData use WebClient.DownloadString() under the hood. So I will use WebClient below to illustrate the encoding problem.

Let's say I have an UTF-8 encoded json file.
```json
{
	"desc": "中文字1"
}
```

WebClient use Encoding.Default, which is CodePage936 in my machine, to decode bytes. If I run the following codes:
```csharp
var file = "test.json";
var wc = new WebClient();
var text = wc.DownloadString(file);
MessageBox.Show(text);
```

I will get:
```json
{
	"desc": "涓枃瀛?"
}
```

Here is a temporary but not perfect solution:
```csharp
var file = "test.json";
var wc = new WebClient();
var text = wc.DownloadString(file);
var bytes = Encoding.Default.GetBytes(text);
var str = Encoding.UTF8.GetString(bytes);
MessageBox.Show(str);
```

The result will be:
```json
{
	"desc": "中文�?"  //still have some unreadable chars
}
```

I suggest add a new property, args.RemoteBytes maybe, which will return a byte array from WebClient.DownloadData(). Let the user handle encoding problem, incase HTTP Content-Encoding header maybe wrong.

**Comment by ravibpatel** [comment]
Can you provide me a link to the JSON file you are having issue with, so I can reproduce it on my end?

**Comment by yomnxkcs** [comment]
You can test this [URL](https://raw.githubusercontent.com/yomnxkcs/utf8json/main/test.json) with the following code:
```c#
        // Autoupdater.NET.Official v1.8.3
        // .net framework 4.5 winform
        // windows 10 simple chinese
        private void Form1_Shown(object sender, EventArgs e)
        {
            var url = @"https://raw.githubusercontent.com/yomnxkcs/utf8json/main/test.json";
            // url = "c:/dotnet/test.json"; // reproducable on local file too.
            AutoUpdater.ParseUpdateInfoEvent += AutoUpdaterOnParseUpdateInfoEvent;
            AutoUpdater.Start(url);
        }

        private void AutoUpdaterOnParseUpdateInfoEvent(ParseUpdateInfoEventArgs args)
        {
            MessageBox.Show(args.RemoteData);
        }
```
And here is what I get:
![utf8json.png](https://github.com/yomnxkcs/utf8json/blob/main/utf8json.png?raw=true)
