### ISSUE TITLE
AutoUpdater.NET.XmlSerializers.dll not found

### ISSUE THREAD

**Issue by GamerClassN7** [ravibpatel/AutoUpdater.NET#636]
Hello,
 i am getting to debug console this error AutoUpdater.NET.XmlSerializers.dll 

`
File name: 'AutoUpdater.NET.XmlSerializers, Version=1.8.3.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc, processorArchitecture=MSIL'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
[08.08.2023-22:06:02][3][HA]System.IO.FileNotFoundException: 
File name: 'C:\Users\JonatanRek\Downloads\HA_Self_Contained (2)\AutoUpdater.NET.XmlSerializers.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)`

Can anybody help me resolve the issue ? 

Thank you in advance for any answer :)

**Comment by ravibpatel** [comment]
Which .NET version are you using? Are you creating a self-contained executable?

**Comment by GamerClassN7** [comment]
Yes i am using self-contained also since i use UWM Notification "toats" i am stuck to this version "net6.0-windows10.0.17763.0"

**Comment by GamerClassN7** [comment]
any update how to fix the issue since everything's woks normaul it just spam the log

**Comment by ravibpatel** [comment]
Can you try turning on "Just my code" in your project as shown [here](https://stackoverflow.com/a/22682018/1273550)?

**Comment by AlessandroMenchiniTmaxLab** [comment]
[https://stackoverflow.com/questions/1127431/xmlserializer-giving-filenotfoundexception-at-constructor](url)

**Comment by Kurpanik** [comment]
The important part from the Stackoverflow link above:

> [..] this is normal behavior. The constructor of the XmlSerializer first tries to find an assembly named [YourAssembly].XmlSerializers.dll which should contain the generated class for serialization of your type. Since such a DLL has not been generated yet (they are not by default), a FileNotFoundException is thrown. When that happenes, XmlSerializer's constructor catches that exception, and the DLL is generated automatically at runtime by the XmlSerializer's constructor (this is done by generating C# source files in the %temp% directory of your computer, then compiling them using the C# compiler). Additional constructions of an XmlSerializer for the same type will just use the already generated DLL.

> The exception is handled by XmlSerializer's constructor. There is no need to do anything yourself, you can just click 'Continue' (F5) to continue executing your program and everything will be fine. If you're bothered by the exceptions stopping the execution of your program and popping up an exception helper, you either have 'Just My Code' turned off, or you have the FileNotFoundException set to break execution when thrown, instead of when 'User-unhandled'
