### ISSUE TITLE
AutoUpdater doesn't start after HTTPS -> HTTP

### ISSUE THREAD

**Issue by OssieFromDK** [ravibpatel/AutoUpdater.NET#638]
Hi,

I have changed from a HTTPS domain, to a new domain which is currently only HTTP. I'm hosting my .zip & the .xml file on the new HTTP domain, but after changing, it simply wont autoupdate. I have tried changing version and stuff, but nothing. I'm not sure why this happens.

Anyone else with the same problem?

**Comment by OssieFromDK** [comment]
I can access the XML on the domain just fine myself also

**Comment by ravibpatel** [comment]
Can you give me URL of your XML file?

**Comment by OssieFromDK** [comment]
> Can you give me URL of your XML file?

New: http://173.249.48.177/burger/au.xml

Old: https://burger.ossie.dk/AU/au.xml

**Comment by ravibpatel** [comment]
Upon debugging, I can see that it is returning the following error, "System.Net.WebException: The remote server returned an error: (555)." for HTTPS URL, but it works fine for me with HTTP URL.

**Comment by OssieFromDK** [comment]
> Upon debugging, I can see that it is returning the following error, "System.Net.WebException: The remote server returned an error: (555)." for HTTPS URL, but it works fine for me with HTTP URL.

It is only meant to run for http. But can you get it to do an autoupdate vis the HTTP url?

**Comment by OssieFromDK** [comment]
I seem to have got it working
