### ISSUE TITLE
UAC exception management

### ISSUE THREAD

**Issue by datelligence** [ravibpatel/AutoUpdater.NET#64]
Hi @ravibpatel,  is there a way to manage exception when windows UAC prompts for elevated privileges but user cancels,  say no password entered?

Thanks.

**Comment by ravibpatel** [comment]
@datelligence As you can see [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L84-L92). I wrapped Process.Start call in try catch block. So there shouldn't be a problem if user press No.

**Comment by datelligence** [comment]
Thanks Ravi,  actually my app stalls when UAC is prompted and user clicks No,  instead of inserting elevated password.

**Comment by ravibpatel** [comment]
@datelligence Does it raises any exception?

**Comment by datelligence** [comment]
@ravibpatel not it does not,  this is the scenario: a new update is available,  user accepts,  exe is downloaded,  opnened,  then UAC prompts,  if the user,  being a standar user with no admin privileges,  click No on UAC prompt,  the screen goes black and nothing happnes,  so the device must be restarted.

**Comment by ravibpatel** [comment]
@datelligence If user press Yes it works fine?

**Comment by LaurenceXu** [comment]
@ravibpatel I test this issues.when UAC show message box "ZipExtractor.exe Is unknown source", If user press yes it works fine, otherwise autoupdater do nothing.
OS:windows 10
AutoUpdater.RunUpdateAsAdmin = true;

**Comment by ravibpatel** [comment]
@LaurenceXu If your app doesn't need admin privileges to install then you can set AutoUpdater.RunUpdateAsAdmin to false. If you keep it true then it won't update application if the user doesn't press Yes on UAC dialog.

**Comment by LaurenceXu** [comment]
@ravibpatel Your suggestion is right, it works.thk
