### ISSUE TITLE
Zip extractor needs .net framework installed, but main application may use a self contained distribution

### ISSUE THREAD

**Issue by bob-dawson** [ravibpatel/AutoUpdater.NET#641]
Zip extractor needs .net framework installed, but main application may use a .net self-contained distribution.  So, the main application can run on a machine without .net framework installed.  Should provide an Api to specify application's own zip extractor instead of the embedded zip extractor.  Or the zip extractor replaced with some program which has no other dependency.

**Comment by ravibpatel** [comment]
Currently, You can compile a self-contained ZipExtractor to resolve this issue. Doing this increases the size of the DLL significantly, that's why it is not compiled as self-contained EXE.

**Comment by prj** [comment]
Compiling ZipExtractor for anything except .net framework 4.5 is completely broken at the moment.
The resulting exe is not usable because it depends on .dll and .json files.

**Comment by ravibpatel** [comment]
Now I am embedding ZipExtractor compiled using .NET Framework 4.5. Can you try DLL from [here](https://ci.appveyor.com/api/buildjobs/9xv8ws4x6sfd93ha/artifacts/AutoUpdater.NET-1.9.1.zip)? It should work fine on Windows 8 or above without installing anything, even with self-contained apps.
