### ISSUE TITLE
ZipExtractor.EXE

### ISSUE THREAD

**Issue by johnwanzhi** [ravibpatel/AutoUpdater.NET#646]
When I made the installation package, I included ZipExtractor.exe in the installation package and set a code digital signature for it.
After executing the update program and updating the file (the updated zip file does not contain ZipExtractor.exe), ZipExtractor.exe has been tampered with, the code digital signature is missing, and the modification date has also been changed. Why is this?

**Comment by prj** [comment]
Because the tool bundles ZipExtractor.exe as a resource in AutoUpdater.NET.dll
You need to re-build the DLL and inject your ZipExtractor.exe into it.

**Comment by johnwanzhi** [comment]
We are now encountering a problem. We now use the net6.0-windows framework for the AutoUpdater.NET project and the ZipExtractor project. We use release mode to build the project. There are ZipExtractor.deps.json, ZipExtractor.dll, ZipExtractor.exe, and ZipExtractor.runtimeconfig.json files in the net6.0-windows directory.

Then I added the ZipExtractor.exe resource in Resources.resx of the AutoUpdater.NET project.

I run the AutoUpdaterTest project and can download the zip file normally, but cannot decompress it.

Because nothing happens when running ZipExtractor.exe alone

**Comment by johnwanzhi** [comment]
Thank you for your reply. If it is a .Net Framework framework, it is no problem to follow your construction method.

However, the net6.0-windows framework will generate a series of files, which is different from the .Net Framework framework. Because it only has one ZipExtractor.exe file

I've read the examples and instructions you provided at least five times, but none of them solved my problem. I don't know if I'm stupid.

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/90312135/321e188f-f2b8-4bf8-90a0-b5765a69b04a)

**Comment by ravibpatel** [comment]
As stated in the docs, "While compiling it for .NET Core 3.1 or above, you have to use publish command instead of build as shown [here](https://learn.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio?pivots=dotnet-7-0) and copy the resulting executable to "AutoUpdater.NET/Resources" folder."

You can see in this line that it uses PublishSingleFile option csproj so if you publish it will create a single EXE file. You can also use the command to do it. I used it in appveyor.yml [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/appveyor.yml#L21). Just replace the paths with the correct path and it should work for you too.

**Comment by johnwanzhi** [comment]
> 如文档中所述，“在为 .NET Core 3.1 或更高版本编译时，您必须使用发布命令而不是如图所示的构建，[并将](https://learn.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio?pivots=dotnet-7-0)生成的可执行文件复制到“AutoUpdater.NET/Resources” “文件夹。”
> 
> 您可以在该行中看到它使用 csproj 中的 PublishSingleFile 选项，因此如果您发布它，将会创建一个 EXE 文件。您也可以使用该命令来执行此操作。我在[这里的](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/appveyor.yml#L21)appveyor.yml 中使用了它。只需将路径替换为正确的路径，它也应该适合您。

very good! Following your tips I successfully published. More people should see this description

**Comment by johnwanzhi** [comment]
> As stated in the docs, "While compiling it for .NET Core 3.1 or above, you have to use publish command instead of build as shown [here](https://learn.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio?pivots=dotnet-7-0) and copy the resulting executable to "AutoUpdater.NET/Resources" folder."
> 
> You can see in this line that it uses PublishSingleFile option in csproj so if you publish it then it will create a single EXE file. You can also use the command to do it. I used it in appveyor.yml [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/appveyor.yml#L21). Just replace the paths with the correct path and it should work for you too.

very good! Following your tips I successfully published. More people should see this description
