### ISSUE TITLE
Is there a way to selectively target only vX.Y.Z (or a range) to autoupdate to latest?

### ISSUE THREAD

**Issue by arithex** [ravibpatel/AutoUpdater.NET#647]
I see the `<mandatory minversion="X.Y.Z">` feature .. but that sounds like the opposite of what I need.

In my case, my app has undergone several breaking changes over the years.. (eg. we no longer support 32-bit OS).  I don't want to force (or even offer) users below a certain version to autoupdate to the latest, which is x64 only.

But, I would like to use AutoUpdate to push some high-priority bug fixes, for users of the current generation app.

Unfortunately I'm not passing any current-assembly-version info in my request, to do this targeting on the backend.  We shipped the app with a hardcoded url 

```cs
// Same line of code in v1 and v2 of our app..
AutoUpdater.Start(@"https://blahblah.com/AutoUpdate.xml", System.Reflection.Assembly.GetExecutingAssembly());
```

Is it possible to "push autoupdate to only users of vX.Y.Z or later"?

**Comment by ravibpatel** [comment]
Did you set UserAgent in any of the version? It can help you decide on server side which XML to serve if you set different User Agent for each version.

**Comment by arithex** [comment]
No, we were not that forward-thinking.  Going forward, we'll do that, or maybe put the version in the url path.   Just wanted to check I wasn't missing something obvious, already in the library..

Thanks for making this -- the way you've made it usable across dotnet core and framework is quite innovative.

**Comment by ravibpatel** [comment]
Thanks. You can set UserAgent to your application name and version for future. I also suggest serving the XML dynamically if that's possible by using PHP, ASP.NET etc... That way you can check the UserAgent header and decide which XML to serve.
