### ISSUE TITLE
 Can a.exe, a.dll, and b.dll use the same XML file ?

### ISSUE THREAD

**Issue by jzdcf** [ravibpatel/AutoUpdater.NET#649]
Including a.exe, a.dll, and b.dll  in my project.
Q1: When using "items" to accommodate multiple "item" in an XML file, it seems that it is not recognized.
Q2: Sometimes only b.dll needs to be updated,and sometimes only a.exe needs to be updated in the XML file.Can an XML file be used to upgrade a specific section separately

**Comment by ravibpatel** [comment]
1. Yes, only the first item will be used for the check.
2. You can just make the zip file with the files you want to update, and it should work, but most of the time it is a good idea to include all files. Imagine a scenario where your app update to 1.1 only contains updated DLL and 1.2 only contains updated EXE. If your 1.2 update file contains only EXE, then updating from 1.0 will only update the EXE, even if both DLL and EXE are required for update from 1.0→1.2.
