### ISSUE TITLE
How to force the update window after a skip

### ISSUE THREAD

**Issue by jenokizm** [ravibpatel/AutoUpdater.NET#65]
For example, if the user first pressed to skip, and then still changed his mind and clicked again in the menu to call the update window, how to make it appear?

**Comment by ravibpatel** [comment]
You can add the Mandatory tag in XML and set it to true. It will ignore skip settings.

**Comment by jenokizm** [comment]
No, this is not the right decision. Read again the situation I described above. It's about choosing a user, if he presses again to check the update, then at will it will not be shown. You need to provide this in the code!

**Comment by ravibpatel** [comment]
If you are using the button then it is not a good idea to show skip button. Skip and Remind Later options only makes sense when you are checking for an update at application start. Why user click the button to update the application and then press Skip or Remind Later? If you are checking for an update at application start and in the button event then I think I can make mandatory public that way you can set mandatory to true for button event.

**Comment by jenokizm** [comment]
My English is bad to understand everything. But I check for updates every time I start. Sometimes the user can click to skip over the stupidity and then want to call the update on the help button - spoil the update but nothing happens!

**Comment by ravibpatel** [comment]
@jenokizm I can expose the Mandatory property that way you can set it true for help button and it will ignore the skip option.

**Comment by jenokizm** [comment]
ok, come on

**Comment by ravibpatel** [comment]
Exposed Mandatory in latest commit.

**Comment by jenokizm** [comment]
hello I was on vacation. Today I tested the new version and I did not succeed
`AutoUpdater.Mandatory = true;
            AutoUpdater.Start("https://gri-software.com/AutoUpdaterTest.xml");`

error 

> Error CS0117 "AutoUpdater" does not contain a definition for "Mandatory".

**Comment by ravibpatel** [comment]
I still didn't provide NuGet release with that feature. You can download AutoUpdater.NET with this feature from [here](https://www.dropbox.com/s/xg2543cmlcff04a/AutoUpdater.NET.zip?dl=0).

**Comment by jenokizm** [comment]
Thanks, it really works. I'm glad that you made this useful function. I will wait for the appearance in nuget

**Comment by ravibpatel** [comment]
@jenokizm Updated NuGet package with this change.
