### ISSUE TITLE
Win 11 中解压文件后是以文件夹的方式在运行目录下

### ISSUE THREAD

**Issue by lio-xing** [ravibpatel/AutoUpdater.NET#650]
Win 10 中解压文件后，文件下的dll等文件提取到了程序运行目录下，而win11解压后是以文件夹方式存放在运行目录下，文件夹里的一些dll等文件并没有提取到运行目录下

**Comment by ravibpatel** [comment]
Can you provide me an example of the zip file you are using?

**Comment by lio-xing** [comment]
你好，我已经解决了。我把指定压缩包解压的目录改成程序运行目录，并且将服务器上的压缩包改成程序运行目录一样的名字，可以解决这个问题。不过程序运行目录就只能和服务器中压缩包名字一样了。
