### ISSUE TITLE
怎样在手动更新时，如果本地软件已是最新，如何获得反馈报告？

### ISSUE THREAD

**Issue by kingxi82** [ravibpatel/AutoUpdater.NET#651]
如题。
如果目前没有这个机制，能否在`AutoUpdater.Start("https://rbsoft.org/updates/AutoUpdaterTest.xml")`方法给出返回值来判断，或者有其他更好的解决方法？

**Comment by ravibpatel** [comment]
You can handle update flow using the event as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually).
