### ISSUE TITLE
Messagebox blocks process from being terminated

### ISSUE THREAD

**Issue by Jungleonly1740** [ravibpatel/AutoUpdater.NET#657]
Hey,

i have a problem with AutoUpdater.

a Messagebox seems to block the intended use of AutoUpdater - My Code looks something like this:

//Autoupdater
//AutoUpdater Settings
AutoUpdater.ShowSkipButton = false;
AutoUpdater.Mandatory = true;
AutoUpdater.TopMost = true;
AutoUpdater.RunUpdateAsAdmin = false;
AutoUpdater.UpdateMode = Mode.ForcedDownload;
AutoUpdater.Synchronous = true;

 AutoUpdater.Start("somethingsomething.xml", new NetworkCredential("something","something"));

MessageBox.Show("something");

**Expected Outcome:**
Update available -> Autoupdater starts, downloads update, terminates source process, installs update, relaunches updated process

**Actual Outcome:**
Update available -> Autoupdater starts, downloads update, **MESSAGEBOX POPS UP, Autoupdater gets STUCK and you need to click away the MSGBOX in order for it to terminate the process**

i cant find any way around this? Any hints on how to solve the issue?

Can i check with Autoupdater IF an update is available so i can close down the application manually? Something along the likes of this:

AutoUpdater.Start("somethingsomething.xml", new NetworkCredential("something","something"));

**if(AutoUpdater.UpdateAvailable=true) {
Application.Exit();
}**

MessageBox.Show("Something");

**Comment by ravibpatel** [comment]
You can handle the update manually as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) to achieve this.
