### ISSUE TITLE
How to skip the installation wizard

### ISSUE THREAD

**Issue by vince0823** [ravibpatel/AutoUpdater.NET#658]
I want to skip the installation wizard and allow users to directly install the latest program without clicking.This is my code, but currently I can only skip the update wizard.Do you have any good solutions?
                AutoUpdater.Mandatory = true;
                AutoUpdater.UpdateMode = Mode.ForcedDownload;
                AutoUpdater.RunUpdateAsAdmin = false;
                AutoUpdater.ReportErrors = false;
                AutoUpdater.DownloadPath = Application.StartupPath; // 获取下载后的安装程序路径
                AutoUpdater.TopMost = true;
                AutoUpdater.Start(serverPath, Assembly.GetExecutingAssembly());

**Comment by ravibpatel** [comment]
You can add use the ZIp file as an update file or supply command line arguments for your installer in XML so it does the silent update.

**Comment by vince0823** [comment]
This is my XML update file. How should I modify it

<?xml version = "1.0" encoding = "UTF-8"?>
<item>
    <version>1.1.0.3</version>
    <url>http://121.41.12.236:4567/AutoUpdate/BanBanTongSetup.msi</url>
    <changelog>版本说明</changelog>
    <mandatory >true</mandatory>
</item>

**Comment by vince0823** [comment]
This is my XML update file. How should I modify it？
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/51349340/f48bb2ae-c45e-45e8-b4e9-af0c17daec7a)

**Comment by vince0823** [comment]
I successfully used zip file. Thank you
