### ISSUE TITLE
Windows10 Do not display update button

### ISSUE THREAD

**Issue by 0755SIR** [ravibpatel/AutoUpdater.NET#66]
Windows10 do not display update button.

**Comment by ravibpatel** [comment]
I also use Windows 10 and it works fine for me. Can you tell me your resolution and screen scale settings?

**Comment by 0755SIR** [comment]
1366 x 768, and I use a notebook computer.

**Comment by ravibpatel** [comment]
@0755SIR Are you using this library for WinForms project or WPF project?

**Comment by Ninjin89** [comment]
Some of my user's got the same problem so they don't have an Update button mostly this is coming from portuguese users and using it for WinForms project.

**Comment by ravibpatel** [comment]
I updated the library to solve this issue in [latest commit](https://github.com/ravibpatel/AutoUpdater.NET/commit/f46eb2576acb05005d5d725d9c8245711580041e).

**Comment by ravibpatel** [comment]
@0755SIR @Ninjin89 Did latest commit fixed problems you had?

**Comment by Ninjin89** [comment]
@ravibpatel yep seems like its fixed :)

**Comment by ravibpatel** [comment]
Update NuGet package with this change
