### ISSUE TITLE
Autoupdater.NET.Official v1.8.4 does not allow to use several command line arguments

### ISSUE THREAD

**Issue by pavel-mitchenko** [ravibpatel/AutoUpdater.NET#664]
I only can specify one command like argument using <args> section

If I specify several arguments  like  `<args>/qb+! TARGETDIR=C:\installfolder</args>` (quiet mode + installation path), then I get the syntax error, because the final command will be `msiexec /i Setup.msi "/qb+! TARGETDIR=C:\installfolder"`. The from args are put to quotes which is wrong.  It would work if we have `msiexec /i Setup.msi /qb+! TARGETDIR=C:\installfolder`

Look like the breaking commit is https://github.com/ravibpatel/AutoUpdater.NET/commit/7796d0bee6dd092fb1c3a3d15c77e5a5f7e68e44  line 237 processStartInfo.Arguments = Utils.BuildArguments(arguments);    

 PasteArguments.AppendArgument put everything to quotas if it has white-space or quota   

```
if (argument.Length != 0 && ContainsNoWhitespaceOrQuotes(argument))
        {
            // Simple case - no quoting or changes needed.
            stringBuilder.Append(argument);
        }
        else
        {
            stringBuilder.Append(Quote);
```

**Comment by ravibpatel** [comment]
I reverted that change as it was unnecessary. Thanks for reporting it.
