### ISSUE TITLE
CheckForUpdateEvent

### ISSUE THREAD

**Issue by JiaoZaiShiJie** [ravibpatel/AutoUpdater.NET#669]
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/76502889/a5a39bcf-237e-4a8b-996e-0e0194ddbe1d)

I've done a manual update in checkfouupdateEvent, and I've drawn my own interface, but how can I customize the above interface?

hank you for your busy reply Thank you

**Comment by JiaoZaiShiJie** [comment]
Of course you can customize the download write, so if you do so and what is the difference between not using the framework, I'm puzzled, but this is still a great product if the custom interface program is a little more advanced

**Comment by JiaoZaiShiJie** [comment]
I've already downloaded the source code and compiled it myself, but if you can give me the corresponding events, I think it would be good to open them up.

**Comment by ravibpatel** [comment]
Currently, there is no way to do this. You can just have to copy the download logic from the library and use it in the CheckForUpdateEvent.

**Comment by JiaoZaiShiJie** [comment]
Thanks for your great work, I have compiled it myself, but it would be nice if you could open the interface later!
