### ISSUE TITLE
Auto-Updater Does Not OverWrite File

### ISSUE THREAD

**Issue by jo15765** [ravibpatel/AutoUpdater.NET#67]
From within Visual Studio I ran the command Install-Package Autoupdater.NET.Official and have added a reference to AutoUpdate.Net.dll

When I run my win form by using the command AutoUpdater.Start("http://testhelptest/AutoUpdater.xml"); i get a pop-up display informing me there is a new version.  I click Update and the new version begins to download, is succesfully downloaded and the current version closes.

However, this new version never updates the current version.  I remain on the old version - the over write never occurs.

What is going on with this?

**Comment by jo15765** [comment]
Please disregard.  This was user error, as I was uploading a .exe and not a .zip

If I uploaded a .zip file the syntax would auto-extract and over write just as it is supposed to.

**Comment by chenpengli** [comment]
mute the thread
