### ISSUE TITLE
.NET 8 Self Contained App prompts with .NET Framework must be downloaded

### ISSUE THREAD

**Issue by atran913** [ravibpatel/AutoUpdater.NET#673]
I have a .NET 8 application that is self contained. When it tries to use ZipExtractor, I get prompted with .NET framework needs to be downloaded. What are my steps to fix this?

**Comment by ravibpatel** [comment]
You have to compile and use the self-contained ZipExtractor by following steps from [here](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#steps-to-build-it-for-further-development). Older version of AutoUpdater (<1.8.5) used ZipExtractor compiled in older .NET Framework so it can work on most Windows OS without need for the same .NET version as host app. You can try that out too.
