### ISSUE TITLE
Polish translation issue

### ISSUE THREAD

**Issue by Wismat** [ravibpatel/AutoUpdater.NET#68]
Great library, works perfect, but I noticed that the translation for Polish language has three little mistakes. User can already understand the sense of sentences but it seems odd (as if some translatator has done it) and not natural. As these prompt is usually displayed just a moment after opening an application, it would be great if you could correct it!

In a file UpdateForm.pl.resx:
line 121 -> `Nowa wersja {0} jest dostępna!` should be `Nowa wersja programu {0} jest dostępna!`
line 124 -> `{0} {1} jest już dostępny. Masz wersję {2} zainstalowany. Chcesz go ściągnąć?` should be `Program {0} {1} jest już dostępny. Masz zainstalowaną wersję {2}. Chcesz ją ściągnąć?`
line 136 -> `{0} {1} jest dostępna!` should be `Aktualizacja programu {0} {1} jest dostępna!`

Best regards!

**Comment by ravibpatel** [comment]
@Wismat I will do it asap. Thanks for the correct translation.
