### ISSUE TITLE
An error occurred trying to start process

### ISSUE THREAD

**Issue by howzew** [ravibpatel/AutoUpdater.NET#681]
The program can receive the update prompt normally, but after clicking update, the following prompt appears (the picture is from another issue, but the problem is the same):

![148583553-8ceb7699-b386-430e-a404-1dd54c8cb825](https://github.com/ravibpatel/AutoUpdater.NET/assets/71800965/1666074d-e019-456e-b5f0-0fc644d373fd)

After my testing, I found that if I add this code 'AutoUpdater.OpenDownloadPage = true;', it will have this problem. If I comment out this code, it can download normally, but I have used this code before without any problems.

win 10
.net 8
AutoUpdater 1.8.5

thank you

**Comment by ravibpatel** [comment]
It is fixed in latest commit. You can try it from [here](https://ci.appveyor.com/api/buildjobs/72s4j2c02v2dajgm/artifacts/AutoUpdater.NET-1.8.5.zip).

**Comment by ravibpatel** [comment]
@howzew I pushed the release so it should be available soon.
