### ISSUE TITLE
请问一下，AutoUpdater.NET 支持.7z格式的文件么

### ISSUE THREAD

**Issue by jilu080712** [ravibpatel/AutoUpdater.NET#683]
我在更新的时候能够读取到服务器上的文件，但是下载完了以后提示  “没有应用程序与此操作的指定文件有关联”![1](https://github.com/ravibpatel/AutoUpdater.NET/assets/169521512/a7abc48a-f2b9-4421-b4fd-80f94e0d049b)

**Comment by jilu080712** [comment]
改成ZIP格式  会提示这个问题  我该怎么修改呢
![2](https://github.com/ravibpatel/AutoUpdater.NET/assets/169521512/8813dd47-5578-415b-a572-ea7f4b7e4118)

**Comment by ravibpatel** [comment]
Can you tell me what it says in the dialog?

**Comment by jilu080712** [comment]
What I want to ask is whether AutoUpdater.NET supports.7z format files, and if not, is there any implementation of this feature in the future

**Comment by ravibpatel** [comment]
Currently, it don't support 7z format. There are no plans for 7z support, but it can be done in future when I have more time to work on it.

**Comment by jilu080712** [comment]
OK，Thank you。
