### ISSUE TITLE
.NET 8.0 , Zipextractor forcing install of x86

### ISSUE THREAD

**Issue by shubhammane77** [ravibpatel/AutoUpdater.NET#684]
Autoupdater Version : 1.8.5
PC: x64

While autoupdating, zipextractor is not detecting x64 .NET 8.0 installed on user's PC and forcing x86 download.

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/42941701/ac41afc8-a285-48b0-a916-b9486522f500)

**Comment by ravibpatel** [comment]
It can be happening due to usage of only win-x86 runtime identifier [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/ZipExtractor.csproj#L25). I can add win-x64 along with it. Can you help me test it out?

**Comment by shubhammane77** [comment]
Thanks for the reply. Yes, it is possible to test.

**Comment by shubhammane77** [comment]
Thank Ravi. The given dll works for the given scenario. Kindly help to release a new version on Nuget.

**Comment by ravibpatel** [comment]
I pushed the latest NuGet package. It should be available soon.

**Comment by shubhammane77** [comment]
Thank you Ravi for your prompt response.
