### ISSUE TITLE
When will the support for Lanzouyun parsing be updated?

### ISSUE THREAD

**Issue by tobaba** [ravibpatel/AutoUpdater.NET#685]
When will the support for Lanzouyun parsing be updated?

**Comment by ravibpatel** [comment]
Can you tell me what you mean by Lanzouyun parsing?

**Comment by tobaba** [comment]
http://lanzou.com/
https://github.com/Entity-Now/LanzouCloudSolve
> Can you tell me what you mean by Lanzouyun parsing?

**Comment by ravibpatel** [comment]
Currently, there are no plans to do it. Feel free to fork the project if you want to implement it.

**Comment by tobaba** [comment]
> Currently, there are no plans to do it. Feel free to fork the project if you want to implement it.

Could you please tell me which file needs to be modified? I will make the necessary changes. Due to the update service, the server is unable to handle a very large request load, so I would like to use this method to solve the issue indirectly.

**Comment by ravibpatel** [comment]
XML parsing is handled [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/AutoUpdater.cs#L411-L427). Download of the update file handled [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L47-L68).

**Comment by tobaba** [comment]
The zip file was downloaded successfully, but it wasn't extracted and updated. What could be the reason?
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/33279660/26a1c6de-33d5-420d-9cce-b82c14ac10a1)

**Comment by tobaba** [comment]
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/33279660/c20a0ec9-4dd5-4374-9928-eb63fdab2483)
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/33279660/f7af57b9-d2a2-4c70-b19c-a6b9b7e089fe)

**Comment by tobaba** [comment]
Thank you so much! With your guidance, I was able to get it done. Fantastic!

**Comment by ravibpatel** [comment]
Glad to help. If you are not modifying the XML fetching logic, then [this event](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#handling-parsing-logic-manually) may help you too.
