### ISSUE TITLE
update via msi mode silent install with vb.net

### ISSUE THREAD

**Issue by furiousfifou17** [ravibpatel/AutoUpdater.NET#686]
Hello 
I have an app write in vb.net to visualstudio 2022 with autoupdater.net. It work fine but i wan't to add the option /qn to my package msi but i don't find this option to the xml update file

What is the method for a silent update with the msi package
Thanks

**Comment by ravibpatel** [comment]
You can use args element inside your XML to specify command line arguments you want to use with the installer.

```xml
<args>/qn</args>
```

**Comment by furiousfifou17** [comment]
Yes i just see it It's work perfectly. Thanks
