### ISSUE TITLE
Not able to update new version

### ISSUE THREAD

**Issue by phuocminh6464** [ravibpatel/AutoUpdater.NET#688]
Hi everyone, I have a .NET 7 WPF App and using Setup project to build .msi installer for first setup. Then I create .zip file for automatic update system. I tried to use AutoUpdater.NET but get this error:
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/26184798/f6aca7a6-cbf3-4cef-b376-2d8ccb54305d)

Another machine show another error message but I try to close app `Application.Current.Shutdown();` in CheckForUpdateEvent
![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/26184798/50f97a0c-1c1f-4023-9986-4f0cdcbee104)

Anyone can advise me?

**Comment by ravibpatel** [comment]
You should use msi file directly without zipping it. Zip file should only be used if you are zipping application files directly and not the setup file.

**Comment by phuocminh6464** [comment]
> You should use msi file directly without zipping it. 

I only use .msi file to install app into Disk C. When need to update, I will publish app to a folder and zipping all files there then update the path to xml file.

**Update status:**
With the message app is still opening, Auto update works if I close app and dialogs of AutoUpdater.Net then allow to run again

**Comment by ravibpatel** [comment]
Process is exited must be happening due to unhandled exception. I fixed it in latest commit. Can you try it from [here](https://ci.appveyor.com/api/buildjobs/ok3alfx75vu2ht9n/artifacts/AutoUpdater.NET-1.9.0.zip) by manually referencing the DLL?

**Comment by phuocminh6464** [comment]
Thanks @ravibpatel. I will try it and post the result here.
But sometimes I get the message "App is still opening" again, at that time I check the task manger so carefully and I'm definitely that there is no process of current app is running. Maybe AutoUpdater.NET run while the app hasn't shut down completely yet? Is there any log of AutoUpdater.NET to check issues when the current app closed?

**Comment by ravibpatel** [comment]
ZipExtractor creates log, but AutoUpdater.NET doesn't create any logs. You will still get more info in ZipExtractor logs. It must be in the temp folder where it is extracted to update the app.

**Comment by ravibpatel** [comment]
If you are not handling [exit event](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#handling-application-exit-logic-manually), then you should also try to do that to cleanly exit the application. When you handle this event, AutoUpdater.NET will use the code inside it to close the app.

**Comment by phuocminh6464** [comment]
> If you are not handling [exit event](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#handling-application-exit-logic-manually), then you should also try to do that to cleanly exit the application. 

Thanks @ravibpatel , let me try it

**Comment by phuocminh6464** [comment]
Hi @ravibpatel, the 

> Can you try it from [here](https://ci.appveyor.com/api/buildjobs/ok3alfx75vu2ht9n/artifacts/AutoUpdater.NET-1.9.0.zip) by manually referencing the DLL?

Hi @ravibpatel , the DLL you give me works now. Can you update this version on Nuget?

**Comment by ravibpatel** [comment]
I already pushed it to NuGet. You can download latest version v1.9.0.
