### ISSUE TITLE
.Net 6.0 ZipExtractor.exe need to install .Net Desktop runtime

### ISSUE THREAD

**Issue by FLCYR** [ravibpatel/AutoUpdater.NET#691]
where update file and extract files
![11](https://github.com/ravibpatel/AutoUpdater.NET/assets/40991365/080d6171-0b10-4612-ad0e-7822ef929de0)

**Comment by ravibpatel** [comment]
Can you tell me which .NET version are you targeting on your main application? Does it ask for it even if it is installed?

**Comment by FLCYR** [comment]
I use .Net 6.0 to write Winform program and packaged applications for x64 system

**Comment by FLCYR** [comment]
> Can you tell me which .NET version are you targeting on your main application? Does it ask for it even if it is installed?
I use .Net 6.0 to write Winform program and packaged applications for x64 system

**Comment by FLCYR** [comment]
I had packaged .Net runtime for my program  So I have the .Net Desktop runtime environment

**Comment by ravibpatel** [comment]
Are you using self-contained app you mean? This looks similar to #641.

**Comment by FLCYR** [comment]
I had publish my ZipExtractor.exe ,but AutoUpdater how to use my ZipExtractor.exe not the default(by Autoupdater.Net.dll)
![2222](https://github.com/ravibpatel/AutoUpdater.NET/assets/40991365/9547e74e-5dd5-4595-979b-67f5ebc59959)

**Comment by ravibpatel** [comment]
You have to follow the guide [here](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#steps-to-build-it-for-further-development) to build DLL with self-contained ZipExtractor. I think you can revert it to previous behavior where ZipExtractor used .NET Framework, which is already installed on most newer OSes.

**Comment by FLCYR** [comment]
I want to know how the AutoUpdater.Net.dll can use my self-contained ZipExtractor.exe

**Comment by FLCYR** [comment]
Ok. I already know how to handle it。But this is not a good method。The dll is large。
Why can't we use the same  runtime dlls.

**Comment by ravibpatel** [comment]
It is cause ZipExtractor is embedded as resource. As I suggested earlier, instead of compiling the ZipExtractor for the same .NET version. You can compile it using .NET Framework 4.6. It should work with Windows 10 and 11 without installing the .NET Framework, because it is present on those OSes by default.

**Comment by ravibpatel** [comment]
You can also use installer instead of zip file. You can use something like [NSIS](https://nsis.sourceforge.io/Download) to convert your update zip to EXE. It won't use ZipExtactor if you use installer as your update file.

**Comment by ravibpatel** [comment]
Now I am embedding ZipExtractor compiled using .NET Framework 4.5. Can you try DLL from [here](https://ci.appveyor.com/api/buildjobs/9xv8ws4x6sfd93ha/artifacts/AutoUpdater.NET-1.9.1.zip)? It should work fine on Windows 8 or above without installing anything, even with self-contained apps.

**Comment by FLCYR** [comment]
Thanks your help. I have slove my problem.
