### ISSUE TITLE
.NET 8.0 ZipExtractor requires .NET 8.0 drivers after compiling as self-contained.

### ISSUE THREAD

**Issue by J0nathan550** [ravibpatel/AutoUpdater.NET#693]
Yesterday, I was testing auto updating for my WPF application. I tried to test with my friend together to update the application. For me everything went smoothly because I am a developer and have all required drivers.

For him, he had to install .net 8 drivers in order to autoupdate the application.

What to do?

Everything is latest from NuGet.

**Comment by ravibpatel** [comment]
This is similar to #691. You have to compile ZipExtractor with self-contained and compile AutoUpdater.NET with it so it can use self-contained ZipExtractor. You can also use installer as an update file instead of zip file and that may solve this issue too. You can do that by downloading [NSIS](https://nsis.sourceforge.io/Download) and converting your zip to installer.

**Comment by ravibpatel** [comment]
Can you tell me which OS are you targeting? I plan to revert to previous behavior where ZipExtractor was compiled using .NET Framework 4.5. It can run without installing anything on Windows 8 and above.

**Comment by J0nathan550** [comment]
> Can you tell me which OS are you targeting? I plan to revert to previous behavior where ZipExtractor was compiled using .NET Framework 4.5. It can run without installing anything on Windows 8 and above while keeping the DLL size low.

Targeting all Windows versions that WPF supports. 

I believe it's, Windows 7 SP1 and above.

**Comment by J0nathan550** [comment]
> This is similar to #691. You have to compile ZipExtractor with self-contained and compile AutoUpdater.NET with it so it can use self-contained ZipExtractor. You can also use installer as an update file instead of zip file and that may solve this issue too. You can do that by downloading [NSIS](https://nsis.sourceforge.io/Download) and converting your zip to installer.

I would say this is too much fuss, when you expect library to work flawlessly without any 3rd party interaction, like literally compiling library your own, and do other stuff.

I believe there was a version that didn't had this issue? I don't remember which one it was, can you remind?

**Comment by ravibpatel** [comment]
It was v1.8.4. That version used ZipExtractor compiled using .NET Framework. Although that was unintentional. I never received a complaint about this issue with that version. I am thinking of reverting that change and bundling the ZipExtactor compiled using .NET Framework 4.5 in next version. That should fix this issue and make it compatible with Windows 8 or above without installing anything.

**Comment by ravibpatel** [comment]
I went ahead and did the change. Can you try DLL from [here](https://ci.appveyor.com/api/buildjobs/9xv8ws4x6sfd93ha/artifacts/AutoUpdater.NET-1.9.1.zip)?

**Comment by J0nathan550** [comment]
> I went ahead and did the change. Can you try DLL from [here](https://ci.appveyor.com/api/buildjobs/9xv8ws4x6sfd93ha/artifacts/AutoUpdater.NET-1.9.1.zip)?

Sure, let me try.

**Comment by J0nathan550** [comment]
Works, no issues.

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/88881607/36c1fccc-33e7-41fb-88fa-8329b53b2450)
![image1](https://github.com/ravibpatel/AutoUpdater.NET/assets/88881607/2dc0786f-7b6e-4ed1-b6f3-04e7ea45e05f)

**Comment by ravibpatel** [comment]
I went ahead and pushed the new release to NuGet. It should be available soon.
