### ISSUE TITLE
ZipExtractor Extraction window textBoxInformation is not read only

### ISSUE THREAD

**Issue by BTPDarren** [ravibpatel/AutoUpdater.NET#695]
Minor issue

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/77784319/d825c316-7b78-491d-9a6b-8528f3288718)

With a large downloaded update, this window is shown for the zip extraction. I have discovered that the textBoxInformation is a text box (unsure why, should it be a label?) and can be edited 

Not a big deal but thought it worth noting for any future update.

**Comment by ravibpatel** [comment]
TextBox allows scrolling text with a mouse horizontally unlike label, so it is useful in case of a long text, but it should have been read-only. I fixed it in latest commit. Thanks for reporting it.
