### ISSUE TITLE
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

### ISSUE THREAD

**Issue by eposlink** [ravibpatel/AutoUpdater.NET#696]
I'm getting the following when trying to use this...
System.IO.FileLoadException
  HResult=0x8013141A
  Message=Could not load file or assembly 'AutoUpdater.NET, Version=1.9.1.0, Culture=neutral, PublicKeyToken=501435c91b35f4bc' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by ravibpatel** [comment]
Are you using a NuGet package? Is it possible to provide a sample project that can replicate this?

**Comment by Aeon512** [comment]
If you check on the command-line wit
`sn.exe -v AutoUpdater.NET.dll`
you receive the error message that the assembly does not have a valid strong name.

The strange thing is, that the assembly is signed, but somehow it's not a valid signature.

**Comment by ravibpatel** [comment]
That is indeed weird. I checked the NuGet package using the NuGet Package Explorer, and it shows that it has the strong name. I also use this on projects where the main app has a strong name, but I don't get this issue.

![2024-07-31_12h42_35](https://github.com/user-attachments/assets/d1eed265-b145-42e2-8da8-7be4787b336f)

**Comment by ravibpatel** [comment]
Yes, you are right. It shows valid for 1.8.6 but invalid for 1.9.1. I also noticed that it is missing the satellite assemblies too. Build is created by appveyor.yml. I will investigate it further.

**Comment by ravibpatel** [comment]
Issue with satellite assemblies and signature failure was connected. I accidentally allowed Resource.Embedder package to embed satellite assemblies in .NET Core assemblies too, and it messed up the signature. Can you try the new NuGet package from [here](https://ci.appveyor.com/api/buildjobs/1uuat77xos4bjqky/artifacts/Autoupdater.NET.Official.1.9.2.nupkg)?
