### ISSUE TITLE
Error The given path's format is not supported.

### ISSUE THREAD

**Issue by ashek1412** [ravibpatel/AutoUpdater.NET#697]
following error is shown before start before downloading update ,

![image](https://github.com/ravibpatel/AutoUpdater.NET/assets/18645594/f4acfcd1-e1a3-44ea-b00f-db13d12eb1b6)

please help !!

**Comment by ravibpatel** [comment]
Are you modifying the downloadPath as shown [here](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#specify-where-to-download-the-update-file)?

**Comment by ashek1412** [comment]
No
