### ISSUE TITLE
Has the custom download progress and page been removed from the current version?

### ISSUE THREAD

**Issue by Xncodet** [ravibpatel/AutoUpdater.NET#699]
Hello everyone, 
has the custom download progress method been removed in version 1.9.1? 
What do I need to do to implement a custom download schedule and install a restart?

**Comment by ravibpatel** [comment]
Can you tell me in detail what you want to achieve? There is nothing removed in latest version.

**Comment by Xncodet** [comment]
> Can you tell me in detail what you want to achieve? There is nothing removed in latest version.

I'm sorry, let me put it another way. I want to implement a custom download progress page how do I do it?

**Comment by ravibpatel** [comment]
You have to modify the DownloadUpdateDialog for that and recompile the library as per instructions [here](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#steps-to-build-it-for-further-development).

**Comment by Xncodet** [comment]
> You have to modify the DownloadUpdateDialog for that and recompile the library as per instructions [here](https://github.com/ravibpatel/AutoUpdater.NET?tab=readme-ov-file#steps-to-build-it-for-further-development).

I need to change Winform to WPF and use HandyControl UI, there seem to be quite a few areas that need to be modified
