### ISSUE TITLE
Custom Arguments for MSI Installation

### ISSUE THREAD

**Issue by letherman255** [ravibpatel/AutoUpdater.NET#701]
I'm using AutoUpdater.NET to install an MSI packaged application. I've noticed that AutoUpdater.NET can restart applications installed as a ZIP after an update, but it doesn't seem to handle MSI or EXE installations the same way. To address this, I added a parameter to the MSI that governs whether the application should be started after installation. This parameter can be set programmatically using `msiexec`.

However, I'm facing an issue where AutoUpdater.NET runs the installer directly as `installFile.msi + args`, rather than using `msiexec /i installFile.msi + args`, which is necessary to pass custom parameters to the MSI installer.

**Current Configuration:**
- AutoUpdater.NET is configured to download and run an MSI installer.
- The version.xml file includes an `<args>` tag to pass custom arguments to the installer.

**Problem:**
AutoUpdater.NET does not use `msiexec` to execute the MSI installer with the provided arguments. Instead, it runs the installer directly, which prevents custom parameters from being applied correctly.

**Example:**
Desired command: 
```sh
msiexec /i "installFile.msi" /qn REBOOT=ReallySuppress ADDLOCAL=ALL STARTAPPLICATION=1
```
AutoUpdater.NET currently executes:
Desired command: 
```sh
installFile.msi /qn REBOOT=ReallySuppress ADDLOCAL=ALL STARTAPPLICATION=1
```
**Request:**
Is there a way to configure AutoUpdater.NET to use msiexec for installing MSI packages and pass custom arguments as needed? If this feature is not currently supported, could it be considered for future updates?

Thank you

**Comment by ravibpatel** [comment]
It looks like a bug with current functionality. It does use msiexec, but it's maybe not passing the command line arguments correctly. You can see [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L234-L237). I will investigate it further and let you know.

**Comment by letherman255** [comment]
@ravibpatel, thank you for the quick reply.

It seems the issue might be related to my MSI package, which I generated using the WiX toolset. I had stopped troubleshooting under the assumption that msiexec was not supported. With this new information, I will resume troubleshooting on my end to see if the problem lies within my MSI package.

Please allow me some time to investigate further. I will reach out with my findings to avoid taking up your time unnecessarily if the issue is on my side.

Thanks again for your support.

**Comment by letherman255** [comment]
I can confirm that my msi was responsible for the issue. Sorry for the trouble.
