### ISSUE TITLE
A way to prevent certain files from being overwritten (feature request, maybe)

### ISSUE THREAD

**Issue by BoEsse** [ravibpatel/AutoUpdater.NET#705]
I'm using this package for a while now and it is a fantastic one! Thx!
I am suggesting this feature, but if it is already possible, please excuse my research fail :-)

We supply a few default config files (json) and the user can open the files and apply custom configuration.
Now everytime we update, the customized files get overwritten by the defaults in the zip.
Creating the json from code isn't really feasable and I was wondering, if this could help others too:

### Being able to supply a list of files, that should not be overwritten if present.

* The list could be in the XML directly or in the zip file.
* maybe even wildcard usage
* providing a subfolder and only extract if not present to the whole folder

Really curious what others think about that.

All the best and thanks for the time and effort.

**Comment by BoEsse** [comment]
I just had a look at the code and basically something like a check in
https://github.com/ravibpatel/AutoUpdater.NET/blob/7fef4e11bcdf3b8163be791d6c8cd61588e87a41/ZipExtractor/FormMain.cs#L153

We could compare against a list from the XML.
If the file exists, `continue; ` 🤔

**Comment by hannes2706** [comment]
Hey @BoEsse I did the same feature request #680 . He told me to use a NSIS installer. 

I did not try it yet, but I will try it in the future.

**Comment by BoEsse** [comment]
@hannes2706 `NSIS installer`  ahhh, good times. damals. 😃 
I still consider it (NSIS) a little heavy for an installer, but since 1GB "Installer-Installation-Manager-Agents" became a thing, I guess I'm just behind the times 🤓 
Was considering using my own fork, just doing a little LINQ on a json file or something 🤔 
For my use-case, even just one directory would be enough. And the user could have like a "vault" and those file are never gonna be over-written — pinky-swear 🤣
