### ISSUE TITLE
跨版本更新

### ISSUE THREAD

**Issue by RaiseWwb** [ravibpatel/AutoUpdater.NET#706]
如果用户的版本是1.0.0  当前程序发布版本到1.3.0   中间有1.1.0 和 1.2.0，要是用户更新  是直接更新1.3.0 还是 逐级更新（先更新1.1.0 再更新1.2.0,最后更新1.3.0 ）？

**Comment by ravibpatel** [comment]
Update should work directly. No matter which version, user is updating from.
