### ISSUE TITLE
Spanish translation need more space for Remind Later

### ISSUE THREAD

**Issue by Zarpyk** [ravibpatel/AutoUpdater.NET#708]
Spanish translation "Remind Later" need bigger button for it and "Update" text starts with a lowercase letter.
![imagen](https://github.com/user-attachments/assets/aa154bc6-766a-401e-934d-0bfb2ec5a2a7)

**Comment by ravibpatel** [comment]
I fixed it in latest commit. Can you try it out from [here](https://ci.appveyor.com/api/buildjobs/5ut9505q18pys6mn/artifacts/AutoUpdater.NET-1.9.3.zip)?

**Comment by Zarpyk** [comment]
Yes, it is fixed.
