### ISSUE TITLE
dont update 

### ISSUE THREAD

**Issue by erfan132** [ravibpatel/AutoUpdater.NET#71]
while i genrate update for my users 
but isnt update 
i change xml version but not work

**Comment by ravibpatel** [comment]
@erfan132 Are your application Assembly version is lower than version mentioned in XML?

**Comment by erfan132** [comment]
no

**Comment by erfan132** [comment]
where is problem my host is ok but updater dosent respond

**Comment by erfan132** [comment]
and my xml is
http://cheatbanned.ml/Updates/AutoUpdater.xml

**Comment by ravibpatel** [comment]
@erfan132 I tried your XML file with version 1.1.0.0 and it works fine for me. The application you are testing from must have a version less than 1.1.0.0 to make it work. Also, make sure your application is allowed internet access. Try turning off the firewall.

**Comment by erfan132** [comment]
my firewall is off and my assembly version fine 
but dosent work for all users

**Comment by erfan132** [comment]
maybe for catch??
im use 1.4.4 autoupdate.net

**Comment by ravibpatel** [comment]
@erfan132 Sorry for a late response. I can't reproduce the issue on my end. Technically, If XML URL you provided works in my application then it should work in your application too. If some of the users have this problem then it means the application has trouble getting to the XML file from the internet.
