### ISSUE TITLE
Using ftp plus compressed package update program, the compressed package downloaded to the target path, not updated error

### ISSUE THREAD

**Issue by 2099521591** [ravibpatel/AutoUpdater.NET#710]
The error looks like this  
An error occurred trying to start process'D:\PDF书\自动更新程序7z' with working directory'C:\Users\tan\source\repos\自动更新程序\bin\Debug\net6.0-windows10.0.19041.0'.没有应用程序与此操作的指定文件有关联。

Here's the code

 AutoUpdater.Start("ftp://192.168.1.8/111//XMLFile1.xml");//检测的地址，检查xml文档中的序号与当前是否相同 
 AutoUpdater.DownloadPath = @"D:\PDF书"; //下载地址
 var currentDirectory = new DirectoryInfo(AutoUpdater.DownloadPath);
 if (currentDirectory.Parent != null)
 {
     AutoUpdater.InstallationPath = currentDirectory.Parent.FullName;//设置安装路径
 }
 AutoUpdater.ExecutablePath = @"bin/AutoUpdaterTest.exe";//可执行文件路径

**Comment by ravibpatel** [comment]
It only supports zip files or installer executables for update. Are you using 7z file?

**Comment by 2099521591** [comment]
Thank you very much for solving my problem because I used 7z instead of zip
