### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by hypers1** [ravibpatel/AutoUpdater.NET#713]
Hello,

I am using AutoUpdater.NET in a WinForms application (4.6.2). My operating system is in German (I am from Germany). In the development environment, all input dialogs of the AutoUpdater are correctly displayed in German. The culture of my application is explicitly set to German:

            CultureInfo.CurrentCulture = new CultureInfo("de-DE", false);
            CultureInfo.CurrentUICulture = CultureInfo.CurrentCulture;
            Thread.CurrentThread.CurrentCulture = CultureInfo.CurrentCulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.CurrentCulture;

As soon as I run the EXE (no matter on which PC), the input dialogs of the AutoUpdater are shown in English again. What could be the reason for this?

**Comment by ravibpatel** [comment]
I tried this in test project [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdaterTest/MainWindow.xaml.cs#L19-L21), and it shows up in German for me. Can you tell me where you are calling this code? Can you tell me exact steps to reproduce this behavior?

**Comment by ravibpatel** [comment]
Do you have satellite assemblies for all languages in the folder where your executable resides?
