### ISSUE TITLE
Could it be possible to remove the "No new update. Retry later" type messagebox for a silent check

### ISSUE THREAD

**Issue by roscofil** [ravibpatel/AutoUpdater.NET#718]
I am successfully using the forced install so that new versions get installed ok.
Only thing that bothers me a bit is to see the "No new updates available" messagebox when starting the application.
Could there be a way to optionally disable displaying this messagebox?
Looks like it's located in lines 542+ in AutoUpdater.cs...So, for now, should I just comment these lines out?
Thx

**Comment by roscofil** [comment]
Looks like it's locaated in lines 542+ in AutoUpdater.cs...Should I just comment these lines out?
Thx

**Comment by ravibpatel** [comment]
Set ReportErrors to false and it should be silent.

**Comment by roscofil** [comment]
Thank you!
