### ISSUE TITLE
Can not update WPF app when upgrade .NET7 to .NET8

### ISSUE THREAD

**Issue by phuocminh6464** [ravibpatel/AutoUpdater.NET#724]
Hi @ravibpatel,

I'm using .NET7 for my WPF app and Autoupdater.NET v1.9.0. I publish app with self-contained and compress all files to a .zip file for auto update. Everything runs smoothly but now I want to upgrade my app to .NET8. I try to do in local with these steps:

1. Install app v1 (.NET7)
2. Upgrade to .NET8 then auto update v2 => updated new version and all features can run
3. Do auto update v3 (.NET8) => can not update new version, please see the below image 

Could you help me this issue?

Note: currently PC is installed windows desktop runtime 7(x64)
![Screenshot 2024-11-22 132149](https://github.com/user-attachments/assets/70a7a0e8-f6a0-45eb-8fda-3a54b2ba3685)

**Comment by ravibpatel** [comment]
Please update the AutoUpdater.NET to latest version. It should fix the issue. It compiles the ZipExtractor in .NET Framework 4.5 so it can natively run on Windows 8 and above without installing anything. Before this, it was using the same .NET version as the host app.

**Comment by phuocminh6464** [comment]
> Please update the AutoUpdater.NET to latest version. It should fix the issue. It compiles the ZipExtractor in .NET Framework 4.5 so it can natively run on Windows 8 and above without installing anything. Before this, it was using the same .NET version as the host app.

Thanks @ravibpatel for your quickly reply. I will try the latest version.
