### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hoffarthaustin** [ravibpatel/AutoUpdater.NET#76]
I followed your steps, it all worked good the first time with your example xml link on the button click. But now i click the button the second time and nothing happens not even an error.

**Comment by ravibpatel** [comment]
@hoffarthaustin Did you used Remind Later or Skip options?

**Comment by hoffarthaustin** [comment]
No i just clicked download, it prompted to rightclickenhancer.zip, i stopped debugger tried to run it again and nothing. happens

**Comment by ravibpatel** [comment]
Set ReportErrors to true and check what error you get.

**Comment by MinecraftGodTier** [comment]
@hoffarthaustin what happened to your repo, thought it was a good idea

**Comment by MinecraftGodTier** [comment]
@hoffarthaustin did you see my repo i think we should work together on it and i have a lot of time on my hands if you want me to do more of the work so let me know if you are going to join join my discord https://discord.gg/ZETAr3

**Comment by MinecraftGodTier** [comment]
@hoffarthaustin if you dont wanna work with me can you atleast upload your source code i would like to use it
