### ISSUE TITLE
Download is triggered twice

### ISSUE THREAD

**Issue by vjenne** [ravibpatel/AutoUpdater.NET#77]
When autoupdater downloads the update file (zip file). The download is triggered twice. I made a php file which serves the zip file, and also tracks the download count. 
The issue is that because the download is triggered twice, the tracker counts 2 downloads instead of 1.

**Comment by ravibpatel** [comment]
@vjenne Can you provide me a link to your XML file?

**Comment by vjenne** [comment]
<?php
require_once("../alg.php");


$piwikTracker = getTracker();
$piwikTracker->doTrackPageView("AutoUpdaterCheckVersion");

$piwikTracker->setUrl('https://www.xxxxx.com/xxxx/download/autoupdater.php');


header('Content-type: text/xml');


//require("sql.php");

//connectMYSQL();



//$sql = "UPDATE counter SET number=number+1 WHERE name='versionXML'";
//$conn->query($sql) OR die("Error:");
//$conn->close();

$versionString = file_get_contents("version.txt");

 $str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<item>
    <version>".$versionString."</version>
    <url>https://www.xxxx.com/xxxxx/download.php</url>
    <changelog>https://www.xxxxx.com/xxxxx/download/changelog.txt</changelog>
    <mandatory>true</mandatory>
</item>"; 



        $xml=new SimpleXMLElement($str);
      echo $xml->asXML();
      
?>

**Comment by ravibpatel** [comment]
@vjenne I can't troubleshoot using dummy URL. You need to provide the URL that you have trouble with. If you are uncomfortable providing it here then you can provide it [here](http://rbsoft.uservoice.com).

**Comment by vjenne** [comment]
I'm sorry about that, I sent you the link. I hope you can track it down.
Thank you in advance

**Comment by ravibpatel** [comment]
@vjenne I found the problem. It happens because there are 2 requests. One is for getting the name of the file from headers and other is for downloading the file itself. You are providing PHP script to download the file so it is necessary to get the name of the file using headers. You can fix this problem by hardcoding the file name in AutoUpdater.NET. Just change [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs#L40) line in DownloadUpdateDialog.cs with following.

````csharp
_tempPath = Path.Combine(Path.GetTempPath(), "Rad2Share.zip");
````

**Comment by vjenne** [comment]
Thank you for the explanation. I was hoping I could leave autoupdater as original as possible(also still dont know how github actually works, forks etc). So I tried hooking into the "CheckForUpdateEvent" event. But visual studio doesn't see this event. Only "CheckForUpdateEventHandler" exists.

**Comment by ravibpatel** [comment]
@vjenne Fixed this issue in latest commit. You can download it [here](https://ci.appveyor.com/api/buildjobs/ak1b9gphr2biw0yc/artifacts/AutoUpdater.NET-1.4.7.9.zip).
