### ISSUE TITLE
Update Installation Routine Fails

### ISSUE THREAD

**Issue by vizyul** [ravibpatel/AutoUpdater.NET#79]
I'm using VS2015 and InstallSheild LE 2015.  I get the following error when I tried to update the application using AutoUpdater.NET.  I'm not sure whether the error is due to AutoUpdater.NET or InstallShield LE.  Please see the attached screenshot
[Update Error.pdf](https://github.com/ravibpatel/AutoUpdater.NET/files/1630588/Update.Error.pdf)

**Comment by ravibpatel** [comment]
@vizyul This error happens because of InstallShield LE.
