### ISSUE TITLE
Does this work for Visual Studio for Mac?

### ISSUE THREAD

**Issue by TonyValenti** [ravibpatel/AutoUpdater.NET#8]

**Comment by TonyValenti** [comment]
Specifically, I'm building an AppKit app and it can't be updated through the AppStore.

**Comment by ravibpatel** [comment]
I don't have cross platform development experience. Maybe core code (AutoUpdater.cs) that gets the XML file from the server and fill the properties is portable. But it uses WinForms to notify users about the update.
