### ISSUE TITLE
Error while handling JSON format

### ISSUE THREAD

**Issue by rokshill** [ravibpatel/AutoUpdater.NET#80]
Hi, 

for JSON config example as below, AutoUpdater is not working properly (because of missing args.InstallerArgs):

`{
  "version": "1.0.1.2",
  "url": "http://localhost/appUpdate/1.0.1.2/appName.msi"
}`

BTW Good tool, good job.

**Comment by ravibpatel** [comment]
You can just add args to json and read it using following code.

````csharp
args.InstallerArgs = json.args
````

**Comment by rokshill** [comment]
Thank you for your tip. I eventually used the XML format. However I think that it's still a bug if we have to pass `args` because they are optional. As the documentation inform that only the `Url` and `Version` are required. Another thing is that in above scenario with JSON format, library's user doesn't get any errors and AutoUpdater just doesn't work.

Best regards

**Comment by ravibpatel** [comment]
@rokshill Yeah. You are right it was a bug. I fixed it in lates commit. You can download it [here](https://ci.appveyor.com/project/ravibpatel/autoupdater-net/build/artifacts).

**Comment by rokshill** [comment]
Cool. Thanks & good luck !

Pozdrawiam
-=-=-=-=-=-=-=-=-=-=-=-=-=-
Jan Mucha
*T* 697 912 864
*E* rokshill@gmail.com
