### ISSUE TITLE
Feature Request: Ability to specify where to store ZipExtractor.exe

### ISSUE THREAD

**Issue by mashles** [ravibpatel/AutoUpdater.NET#81]
Right now it seems ZipExtractor.exe is always saved to the temp folder, but I have run into environments where this gets blocked by policies. Can you add the option of specifying a specific location where ZipExtractor.exe is saved (e.g. I want to use Environment.CurrentDirectory).

**Comment by ravibpatel** [comment]
@mashles I was thinking of the ability to define the path where the download is saved. That can be also used for ZipExtractor.

**Comment by ravibpatel** [comment]
@mashles Added this feature in latest commit. You can download it [here](https://ci.appveyor.com/api/buildjobs/ak1b9gphr2biw0yc/artifacts/AutoUpdater.NET-1.4.7.9.zip).
