### ISSUE TITLE
i get eror

### ISSUE THREAD

**Issue by edisudarma** [ravibpatel/AutoUpdater.NET#82]
![screenshot_1](https://user-images.githubusercontent.com/35764561/35328191-1dbd143e-012e-11e8-9e21-5d9b8c4ea872.png)

**Comment by ravibpatel** [comment]
@ Are you using NuGet package?

**Comment by edisudarma** [comment]
yes, use nuget package

**Comment by edisudarma** [comment]
![image](https://user-images.githubusercontent.com/35764561/35331639-a05a9f04-013a-11e8-8cca-e1d540f30c40.png)

**Comment by edisudarma** [comment]
yes i use nuget package
[image: Inline image 1]

**Comment by ravibpatel** [comment]
Which .NET Framework version your project is using?

**Comment by edisudarma** [comment]
i use 4.5.2

**Comment by edisudarma** [comment]
i make video for this error
http://jmp.sh/agfPtBB

**Comment by ravibpatel** [comment]
Can you share me compiled executable?

**Comment by edisudarma** [comment]
this link download
http://jmp.sh/cxrzeEu

**Comment by ravibpatel** [comment]
You are using AutoUpdater.NET wrong way. AutoUpdater.NET needs installer or zip file URL between url tag of the XML file. You are providing only updated executable. Just zip the updated executable and upload it to your server then provide that zip file URL in the XML file. It will download the zip file when your press Update button and extract it into your application directory.

**Comment by edisudarma** [comment]
oke thanks

**Comment by edisudarma** [comment]
sir, i try make installer, and nothing error
but after download, update file not running

**Comment by ravibpatel** [comment]
Can you give URL of your XML file?

**Comment by edisudarma** [comment]
<?xml version="1.0" encoding="utf-8"?>
<item>
<version>1.2.4.0</version>
<url>http://threesignal.net/autoupdate.exe</url>
<changelog>http://threesignal.net/releasenotes.html</changelog>
<mandatory>false</mandatory>
<checksum algorithm="MD5">Update file Checksum</checksum>
</item>

**Comment by edisudarma** [comment]
http://threesignal.net/cekautoupdate.xml

**Comment by ravibpatel** [comment]
@edisudarma Use following XML and it should work. You are providing an invalid checksum for the file.

```xml
<item>
<version>1.2.4.0</version>
<url>http://threesignal.net/autoupdate.exe</url>
<changelog>http://threesignal.net/releasenotes.html</changelog>
</item>
```

**Comment by edisudarma** [comment]
same sir, no update running

**Comment by ravibpatel** [comment]
@edisudarma I tested it and it works fine. Try renaming the XML file on the server. It may be a caching issue.

**Comment by edisudarma** [comment]
oke youre right, thanks very much

**Comment by edisudarma** [comment]
best regards
