### ISSUE TITLE
Lot of "garbage" in output directory

### ISSUE THREAD

**Issue by m4rcelpl** [ravibpatel/AutoUpdater.NET#83]
Hi,
I really like this library but does it have to generate so many files/catalogs? (Catalog for each language and .pdb files.)
Please consider the idea of combining this into one (or two) file :)

**AutoUpdater.NET.dll
AutoUpdater.NET.xml**

**Comment by ravibpatel** [comment]
You can remove language files you don't need from packages folder.

**Comment by Gerardo-Sista** [comment]
I agree, great library but
you could embed resources into the main assembly leaving only **AutoUpdater.NET.dll** in output folder.

**Comment by ravibpatel** [comment]
@Gerardo-Sista I will use do it in next version.

**Comment by Gerardo-Sista** [comment]
Please tell me how I can contribute to change Italian translation: it's really bad (I'm italian).

**Comment by ravibpatel** [comment]
@Gerardo-Sista You can open a pull request with the fix and I will accept it. To open the pull request you need to fork the repo first.
