### ISSUE TITLE
Unzip setup executable and run

### ISSUE THREAD

**Issue by nayr006** [ravibpatel/AutoUpdater.NET#84]
Would it be possible to implement the ability to download a zipped setup executable and have it unzip and execute the setup file?

**Comment by ravibpatel** [comment]
@You need to modify ZipExtractor for that. After [this](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/ZipExtractor/FormMain.cs#L68) line, you can execute installer using following lines.

```csharp
string filePath = Path.Combine(path, entry.FilenameInZip);
if(Path.GetExtension(filePath) == ".exe") {
	Process.Start(filePath);
	return;
} 
```

**Comment by EricFang2020** [comment]
Dear Sir, 

I have the same problem but after reading your message, I still have no idea how to do it.
I have already included AutoUpdater.NET V1.6.3.0 in my VS C# project.

Do you mean that I have to download the ZipExtractor code and modify it?
Where can I download the project? Where should I insert your lines?
Does that mean I need to compile a new DLL and replace V1.6.3.0 DLL? How should I do that?

Really appreciate your help!

Have a nice day.

Eric Fang
