### ISSUE TITLE
Update UI takes a dependency on screen resolution height; won't show Update button if it's below a certain threshold

### ISSUE THREAD

**Issue by SaviorXTanren** [ravibpatel/AutoUpdater.NET#86]
Hey, so I have been trying to diagnose an issue some of the users of my app were seeing when attempting to use your pre-made Update UI. If their screen resolution was small enough, your UI would appear and look "fine" for the most part, but there would be no "Update" button at the bottom. I saw this myself when setting my resolution to something like 1366 x 768.

**Comment by ravibpatel** [comment]
@SaviorXTanren Which version you are using?

**Comment by SaviorXTanren** [comment]
1.4.5

**Comment by ravibpatel** [comment]
@SaviorXTanren Upgrade to the latest version. This issue was fixed in version 1.4.6
