### ISSUE TITLE
Feature request - add new 'ForceUpdateCheck' option.

### ISSUE THREAD

**Issue by straypointer** [ravibpatel/AutoUpdater.NET#90]
I want to add a new option that will force an update check, ignoring (but not removing) any existing remind-later or skip options, but also not forcing the user to update (e.g. mandatory=true.) This can be useful in a Help->Check-For-Update menu option. (If 'remind later' was clicked earlier, an update check will not happen without a feature such as this.)

**Comment by ravibpatel** [comment]
@straypointer Mandatory field works same as ForceUpdateCheck so there is no need to introduce new option. Currently, the Mandatory field doesn't stop the running timer. I will do that and it will work as intended.

**Comment by alexalok** [comment]
As far as I understand, **mandatory** forces the update, meaning user won't be able to cancel it. 

On the other hand, if user postpones or skips an update, he has no way to check it again - even if `AutoUpdater.Start` is called, for instance, via a "Check for updates" button, it will detect previously set postpone/skip and cancel. 

From what I understand, **ForceUpdateCheck** basically suppresses postpone and skip but doesn't force an update installation, meaning user can still cancel/postpone/skip it again. 

I've implemented a similar mechanism myself, but it definitely would be much nicer to see it in an original repository.

**Comment by ravibpatel** [comment]
@alexalok No, You can postpone Mandatory update too. It doesn't force you to do it. You can close the update dialog. Mandatory does not work if there is running remind later timer which I will fix soon.

**Comment by alexalok** [comment]
Okay, thanks for clarifying, @ravibpatel

**Comment by straypointer** [comment]
Thanks for the response and information. I will try playing with the Mandatory option to see if it meets our needs- the word mandatory implied to me that there are no choices to skip updating. 

I am also concerned that our user base, which is largely computer novices, may be confused if the only option is to close the update dialog with the 'X'. (Rather than a remind-later or close button.)

**Comment by ravibpatel** [comment]
@straypointer, In that case, you can just show message box showing that there is an update. As shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually). You will have more control on UI this way.

**Comment by ravibpatel** [comment]
Fixed this issue in commit https://github.com/ravibpatel/AutoUpdater.NET/commit/aaf192ceeb639e4837d3c2dd023571ec18783065.
