### ISSUE TITLE
Updater closes installer if its name is the same as program's

### ISSUE THREAD

**Issue by alexalok** [ravibpatel/AutoUpdater.NET#93]
https://github.com/ravibpatel/AutoUpdater.NET/blob/7989cad1f42ce9a5a6c970b8ab604673512c8056/AutoUpdater.NET/AutoUpdater.cs#L499

Instead of relying just on process' name, we should consider checking path of each process we're about to close and make sure that it's equal to the current process' one.

**Comment by ravibpatel** [comment]
@alexalok Great find. I will change it asap. Thanks for reporting. If you like to contribute this change you can open a pull request. I will accept it.

**Comment by alexalok** [comment]
Hi, @ravibpatel,
there are 2 ways of checking another processe's image path in pure C# that are known to me:
`process.MainModule.FileName;`, and using WMI. The first one is much faster and is OS-independent, but if autoupdater is compiled as 32-bit, it won't be able to get paths of 64-bit processes. The WMI way, on the other hand, is more reliable, but would only work on Windows. I've implemented a WMI way as I don't need cross-platform support. If you're okay with that as well, I can open a pull request.

**Comment by ravibpatel** [comment]
AutoUpdater is compiled for Any CPU so there should be no problems with 32 bit and 64-bit processes.

**Comment by alexalok** [comment]
`AnyCPU` on all modern VS versions has a **prefer 32-bit** flag, which tells CLR to run assemblies in 32-bit mode even on 64-bit OSes.

**Comment by ravibpatel** [comment]
@alexalok That code takes care of killing other instances of application. If host application is compiled with 64-bit then AutoUpdater.NET also runs in 64-bit. It means it can see other instances of current application.

**Comment by alexalok** [comment]
Yeah, @ravibpatel, that's actually a good point. 

Right now I see the algorithm like this:
1. If we cannot get target process' path bc of an arhitecture mismatch, it's safe to say we don't need to close it.
2. If we can get the path (i.e. arch is the same), we check the path and compare it to the one of our assembly. If they're not equal, we don't close the process.

**Comment by ravibpatel** [comment]
@alexalok Yeah. You can open a pull request now.
