### ISSUE TITLE
restart application after upgrade with same command line arguments

### ISSUE THREAD

**Issue by k2s** [ravibpatel/AutoUpdater.NET#96]
starting my app with: `app.exe --keep`
upgrading with AutoUpdater.NET will restart my app without the `--keep` parameter

could you, please, keep the command line parameters ?

**Comment by ravibpatel** [comment]
@k2s You can specify command line parameters using args element in XML.

<args>--keep</args>

**Comment by k2s** [comment]
yes, I am using ZIP file 
the command line options are based on users settings, so they are known only at runtime

**Comment by KoruNL** [comment]
@ravibpatel I think, line 93 of FormMain.cs of ZipExtractor should have been changed to 'Process.Start(processStartInfo)'

**Comment by ravibpatel** [comment]
@KoruNL Missed that. I will fix it tomorrow.

**Comment by mfansari82** [comment]
I also need restart application after update done.
I am also using Zip file for update the application so, please help me how you solved this.

**Comment by ravibpatel** [comment]
@mfansari82 It should restart the app automatically. You don't need to do anything. Make sure exe name isn't changed in the update otherwise it won't be able to start the updated app.

**Comment by mfansari82** [comment]
@ravibpatel My application restart but it is not visible in front but it is running in background.
