### ISSUE TITLE
AutoUpdater does not read current culture

### ISSUE THREAD

**Issue by serdam55** [ravibpatel/AutoUpdater.NET#97]
I set the current culture for the whole program as:

     CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("en");

the autoupdater isn't full translate the string "update" is "aggiorna" which is italian language, for get the full updater translation I have used the:

    Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("en");

inside the method that call the AutoUpdater.Start(), is this a bug or I did something wrong?

**Comment by ravibpatel** [comment]
@serdam55 AutoUpdater.NET uses current thread's culture so setting Thread.CurrentThread.CurrentCulture to something else will change the language of AutoUpdater.NET. CultureInfo.CurrentCulture is read only if you are using .NET Framework 4.5.2 or below, So setting it won't work.
