### ISSUE TITLE
waiting for application exit stuck application

### ISSUE THREAD

**Issue by serdam55** [ravibpatel/AutoUpdater.NET#99]
I found similar issue on this repo, but I guess this bug isn't fixed at all. In particular if I call 

     AutoUpdater.Start("some link");

from the MainWindow all working good, but I do this in that way:
inside the MainWindow I have this line of code:

    UpdaterHelper.CheckUpdate();
     
where UpdaterHelper is a static class which have this content:

    public class UpdaterHelper
    {
        private static async void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
        {
            var dict = Globals.SfVm.SettingsController.GetCurrentLangDict;

            if (CultureInfo.CurrentCulture.Name == "it")
            {
                Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("it");
            }
            else
            {
                Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("en");
            }
            if (args != null)
            {
                if (args.IsUpdateAvailable)
                {
                    try
                    {
                        var result = await Globals.App
                            .ShowMessageAsync(
                            Lang.Line("ok", dict),
                            Lang.Line("newUpdateVersion", dict) + " " + args.CurrentVersion + " " +
                            Lang.Line("isAvailable", dict) + " " + 
                            Lang.Line("yourVersion", dict) + " " + args.InstalledVersion + ". " + 
                            Lang.Line("updateConfirm", dict),
                            MessageDialogStyle.AffirmativeAndNegative, Globals.DialogSettings);

                        if(result == MessageDialogResult.Affirmative)
                        {
                            AutoUpdater.DownloadUpdate();
                        }
                        else
                        {
                            Globals.SfVm.IsUpdateAvailable = true;
                        }
                    }
                    catch (Exception e)
                    {
                        await Globals.App.ShowMessageAsync(Lang.Line("attention", dict),
                            Lang.Line("updateFailed", dict) + " " + e.Message, MessageDialogStyle.Affirmative);
                    }
                }
                else
                {
                    await Globals.App.ShowMessageAsync(Lang.Line("about", dict),
                            Lang.Line("noUpdate", dict), MessageDialogStyle.Affirmative);
                }
            }
            else
            {
                await Globals.App.ShowMessageAsync(Lang.Line("attention", dict),
                            Lang.Line("noUpdate", dict), MessageDialogStyle.Affirmative);
            }
        }

        public static void CheckUpdate()
        {
            AutoUpdater.ReportErrors = true;
            AutoUpdater.ShowSkipButton = false;
            AutoUpdater.LetUserSelectRemindLater = true;
            AutoUpdater.RemindLaterTimeSpan = RemindLaterFormat.Minutes;
            AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;     
           AutoUpdater.Start("some link");
        }`

why happen this? I did something wrong in the implementation?

**Comment by ravibpatel** [comment]
@serdam55 Why are you using async? To close the application successfully you need to be on the main thread. AutoUpdater.DownloadUpdate(); should be called on the main thread (UI thread).

**Comment by serdam55** [comment]
@ravibpatel thanks for reply, I need to use async because I'm using ShowMessageDialog provided by mahapp, which require to be async.

How can I manage this? I tried:

                            Application.Current.Dispatcher.Invoke(new Action(() =>
                            {
                                AutoUpdater.DownloadUpdate();
                            }));

but not seems to working. Also: 
1. is possible set a window owner to updater? 
2. how can I display a custom update window with changelog?

**Comment by ravibpatel** [comment]
@serdam55 You can try implementing application exit logic by yourself as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-application-exit-logic-manually). You can provide your custom update window using CheckForUpdateEvent.

**Comment by serdam55** [comment]
I tried the exit event and isn't firing, why?
